automation:

# device_id airco Amilya = 61864d1ab32c5af91d5f13faf697c27e

- alias: temperatuur kamer Amilya boven 22 graden en meer
  id: '40315ffe-dd48-4cc5-80dd-ff93d3798ed3'
  description: ''
  trigger:
  - platform: numeric_state
    entity_id: sensor.kamer_amilya_temperature
    above: 22
  - platform: numeric_state
    entity_id: sensor.kamer_amilya_temperature
    above: 23
  - platform: numeric_state
    entity_id: sensor.kamer_amilya_temperature
    above: 24
  - platform: numeric_state
    entity_id: sensor.kamer_amilya_temperature
    above: 25
  - platform: numeric_state
    entity_id: sensor.kamer_amilya_temperature
    above: 26
  - platform: numeric_state
    entity_id: sensor.kamer_amilya_temperature
    above: 27
  - platform: numeric_state
    entity_id: sensor.kamer_amilya_temperature
    above: 28
  - platform: numeric_state
    entity_id: sensor.kamer_amilya_temperature
    above: 29
  - platform: numeric_state
    entity_id: sensor.kamer_amilya_temperature
    above: 30                              
  condition: []
  action:
  - service: notify.bart_phone
    data:
      title: Temperatuur kamer Amilya
      message: Temperatuur in kamer Amilya is nu {{ states('sensor.kamer_amilya_temperature') | round(1) }} °C.
  mode: single

- alias: temperatuur kamer Amilya boven 22 graden = koelen met airco
  id: 'c4f0b414-0f34-4f22-9b89-34445c863ebf'
  description: ''
  trigger:
  - platform: numeric_state
    entity_id: sensor.kamer_amilya_temperature
    above: 22
  - platform: numeric_state
    entity_id: sensor.kamer_amilya_temperature
    above: 23
  condition:
  - condition: state
    entity_id: input_boolean.cooling_season
    state: "on"
  - condition: state
    entity_id: person.amilya
    state: home    
  # - condition: state
  #   entity_id: binary_sensor.kamer_amilya_temp_rising
  #   state: 'on'
  - condition: state
    entity_id: binary_sensor.kamer_amilya_raam
    state: 'off'    
  action:
  - service: script.amilya_airco_cooling_start
  - service: notify.bart_phone
    data:
      title: Airco koelt nu in kamer Amilya
      message: Temperatuur in kamer Amilya is nu {{ states('sensor.kamer_amilya_temperature') | round(1) }} °C.
  mode: single  