automation:

# device_id airco Alunya = 3c12e341dfd1d1fe2327ec66f3613321

##################
# Aan
##################

# Aircoverwarming gaat AAN bij de trigger:
# - het schema gaat op "aan" 
# - Alunya komt in de kamer (of thuis)
# - kamertemperatuur is lager dan normale temperatuur
# Met de voorwaarden:
# - het schema staat op "aan"
# - Alunya is in de kamer (of thuis)
# - kamertemperatuur is lager dan normale temperatuur

- alias: "♨️ airco heating // Alunya // aan volgens schema/te koud/aankomst"
  id: '97872037-539d-496f-807e-26248fb4cae2'
  description: ""
  trigger:
    - platform: state
      entity_id: schedule.kamer_alunya_normal_temperature_schema
      to: "on"
    # - platform: state
    #   entity_id: person.alunya
    #   to: home
    - platform: template
      value_template: >
        {{ states('sensor.kamer_alunya_temperature') | float <
        states('input_number.kamer_alunya_normal_temperature') | float }}
  condition:
    - condition: state
      entity_id: input_select.heating_mode
      state: airco  
    - condition: template # only between September and April
      value_template: "{{ now().month < 5 and now().month > 8 }}"
    - condition: state
      entity_id: schedule.kamer_alunya_normal_temperature_schema
      state: "on"
    - condition: state
      entity_id: person.alunya
      state: home
    - condition: numeric_state
      entity_id: sensor.kamer_alunya_temperature
      below: 17
    - condition: state
      entity_id: binary_sensor.kamer_alunya_raam
      state: "off"
  action:
  - service: input_number.set_value
    data:
      value: >
        {{ states('input_number.kamer_alunya_normal_temperature') | float }}
    target:
      entity_id: input_number.alunya_airco_target_temperature          
  - service: input_number.set_value
    data:
      value: 30
    target:
      entity_id: input_number.alunya_airco_timer_minutes
  - wait_template: ''
    timeout: "00:00:02"
  - service: script.alunya_airco_start_heating
  mode: restart

- alias: "♨️ airco heating // Alunya // verwarm van 21u45 tot 22u15" 
  id: '616e5f62-43b2-4737-80b9-376214057555'
  description: ''
  trigger:
  - platform: time
    at: '21:45:00'
  condition:
    - condition: state
      entity_id: input_select.heating_mode
      state: airco  
  action:
    - if:
        - condition: state
          entity_id: person.alunya
          state: home
        - condition: state
          entity_id: group.kamer_alunya_ramen
          state: 'off'
        - condition: numeric_state
          entity_id: sensor.kamer_alunya_temperature
          below: 16
      then:
        - service: input_number.set_value
          data:
            value: 21
          target:
            entity_id: input_number.alunya_airco_target_temperature          
        - service: input_number.set_value
          data:
            value: 30
          target:
            entity_id: input_number.alunya_airco_timer_minutes
        - delay:
            seconds: 2
        - service: script.alunya_airco_start_heating
          data: {}   


##################
# Uit
##################

# Aircoverwarming gaat UIT bij de trigger:
# - het schema gaat op "uit" 
# - Alunya verlaat het huis
# - op einduur van de timer
# - wanneer het raam opengaat

- alias: "♨️ airco heating // Alunya // uit volgens volgens schema/verlaten huis/timer stop"
  id: '1428f07e-3f83-4afe-a24e-fcb00f88ae7e'
  description: ""
  trigger:
    - platform: state
      entity_id: schedule.kamer_alunya_normal_temperature_schema
      to: "off"
    - platform: state
      entity_id: person.alunya
      to: not_home
    - platform: state
      entity_id: binary_sensor.kamer_alunya_raam
      to: "on"
      for:
        minutes: 1
    - platform: time
      at: input_datetime.alunya_airco_timer_stop      
  condition: []
  action:
    - service: climate.turn_off
      data: {}
      target:
        device_id: 3c12e341dfd1d1fe2327ec66f3613321  
    - service: climate.set_temperature
      data:
        temperature: 14
      target:
        device_id: 3c12e341dfd1d1fe2327ec66f3613321
    - service: input_number.set_value
      data:
        value: 14
      target:
        entity_id: input_number.alunya_airco_target_temperature        
    - service: timer.finish
      data: {}
      target:
        entity_id: timer.alunya_airco_timer
  mode: single


- alias: "♨️ airco heating // Alunya // 's nachts niet meer dan 18 graden"
  id: '5c6555ab-8472-4c68-8c14-459d96d9e4f8'
  description: ''
  trigger:
  - platform: numeric_state
    entity_id: input_number.alunya_airco_target_temperature
    above: 18
  condition:
  - condition: time
    after: '23:00:00'
    before: 06:30:00
  - condition: template
    value_template: "{{trigger.to_state.context.user_id == '7e508a5d2a5c42029f3d9238f0cc4648'}}"
  action:
  - service: notify.alunya_phone
    data:
      title: De temperatuur wordt 's nachts beperkt.
      message: "{{ states('input_number.alunya_airco_target_temperature') }} graden is niet mogelijk."
  - service: notify.bart_phone
    data:
      title: De temperatuur wordt 's nachts beperkt.
      message: >
        Alunya probeerde temperatuur op {{ states('input_number.alunya_airco_target_temperature') }} graden in te stellen.
        De kamertemperatuur was {{ states('sensor.kamer_alunya_temperature') }} graden.
  - service: input_number.set_value
    data:
      value: 14
    target:
      entity_id: input_number.alunya_airco_target_temperature
  mode: single


########################
# Handmatige aanpassing
########################

- alias: '♨️ airco heating // Alunya // aan gedurende 30 minuten bij hogere gewenste temperatuur'
  id: 'da19679e-5318-4bd2-85f3-1b5153f0ab08'
  description: ''
  trigger:
  - platform: template
    value_template: >
      {{ states('sensor.kamer_alunya_temperature') | float < states('input_number.alunya_airco_target_temperature') | float }}
  condition:
  - condition: state
    entity_id: person.alunya
    state: home
  action:
  - service: input_number.set_value
    data:
      value: 30
    target:
      entity_id: input_number.alunya_airco_timer_minutes
  - service: script.alunya_airco_start_heating
    data: {}            
  mode: restart


- alias: '♨️ airco heating // Alunya // uit als huidige temperatuur hoger is dan gewenste temperatuur'
  id: 'ce181e9e-3206-404a-8588-46583be2e248'
  description: ''
  trigger:
  - platform: template
    value_template: >
      {{ states('sensor.kamer_alunya_temperature') | float > states('input_number.alunya_airco_target_temperature') | float }}
  condition: []
  action:  
  - service: climate.turn_off
    data: {}
    target:
      device_id: 3c12e341dfd1d1fe2327ec66f3613321  
  - service: climate.set_temperature
    data:
      temperature: 14
    target:
      device_id: 3c12e341dfd1d1fe2327ec66f3613321
  - service: input_number.set_value
    data:
      value: 14
    target:
      entity_id: input_number.alunya_airco_target_temperature
  - service: timer.finish
    data: {}
    target:
      entity_id: timer.alunya_airco_timer
  mode: single

- alias: '♨️ airco heating // Alunya // uit als verwarming 10 min aan staat buiten de normale uren'
  id: 'ec418031-ba50-4aca-b396-d6c864ddbe59'
  description: ''
  trigger:
  - platform: template
    value_template: >
      {{ states('climate.alunya_airco') == "verwamen" }}
    for:
      hours: 0
      minutes: 10
      seconds: 0
  condition:
    - condition: state
      entity_id: schedule.kamer_alunya_normal_temperature_schema
      state: "off"
  action:
  - service: climate.turn_off
    data: {}
    target:
      device_id: 3c12e341dfd1d1fe2327ec66f3613321 
  - service: climate.set_temperature
    data:
      temperature: 14
    target:
      device_id: 3c12e341dfd1d1fe2327ec66f3613321
  - service: input_number.set_value
    data:
      value: 14
    target:
      entity_id: input_number.alunya_airco_target_temperature
  mode: single