automation:

# device_id airco living = 1c560bbc7917f45d737e87d3e2bd0d89

- alias: temperatuur living boven 23 graden
  id: 'f9348f08-a5db-4172-8410-2593768dd9c9'
  description: ''
  trigger:
  - platform: numeric_state
    entity_id: sensor.living_temperature
    above: 23
  condition: []
  action:
  - service: notify.bart_phone
    data:
      title: Temperatuur living
      message: Temperatuur in living is nu {{ states('sensor.living_temperature') }} graden.
  mode: single

- alias: temperatuur living boven 22 graden en zonneopwek 2000 W = koelen met airco
  id: 'a8f80e84-1935-4cb4-8109-99c5ee6d2dc2'
  description: ''
  trigger:
  - platform: numeric_state
    entity_id: sensor.living_temperature
    above: 22
  - platform: numeric_state
    entity_id: sensor.living_temperature
    above: 23
  condition:
  - condition: state
    entity_id: input_boolean.cooling_season
    state: "on"
  - condition: numeric_state
    entity_id: sensor.solar_power
    above: 1500
  action:
  - service: script.living_airco_cooling_start
  - service: notify.bart_phone
    data:
      title: Airco koelt nu in living
      message: Temperatuur in living is nu {{ states('sensor.living_temperature') | round(1) }} °C.
  mode: single   