automation:

# device_id airco living = 1c560bbc7917f45d737e87d3e2bd0d89

- alias: "♨️ airco heating // living // aan volgens schema normale temp of aankomst"
  id: 'ddf200ed-b5d7-4bab-aee4-8c1a37bb7d56'
  description: ""
  trigger:
    - platform: state
      entity_id: schedule.living_normal_temperature_schema
      to: "on"
    - platform: state
      entity_id: group.gezin
      to: home
    - platform: template
      value_template: >
        {{ states('sensor.living_temperature') | float <
        states('input_number.living_normal_temperature') | float }}
  condition:
    - condition: state
      entity_id: input_select.heating_mode
      state: airco      
    - condition: state
      entity_id: schedule.living_normal_temperature_schema
      state: "on"
    - condition: state
      entity_id: group.gezin
      state: home
    - condition: template
      value_template: >
        {{ states('sensor.living_temperature') | float <
        states('input_number.living_normal_temperature') | float }}
    - condition: state
      entity_id: group.living_ramen
      state: "off"
  action:
    - service: climate.set_temperature
      data:
        hvac_mode: heat
        temperature: >
          {% set target = states('input_number.living_normal_temperature') | float %}
          {% set temp = states('sensor.living_temperature') | float %}
          {% set adj = target - temp %}
          {{ (state_attr('climate.living_airco', 'current_temperature') + adj ) | round(1, 'half', 0) }}
      target:
        device_id: 1c560bbc7917f45d737e87d3e2bd0d89
    - service: climate.set_preset_mode
      data:
        preset_mode: eco
      target:
        device_id: 1c560bbc7917f45d737e87d3e2bd0d89
    - service: climate.set_swing_mode
      data:
        swing_mode: 3D
      target:
        device_id: 1c560bbc7917f45d737e87d3e2bd0d89
    - service: input_number.set_value
      target:
        entity_id: input_number.living_airco_target_temperature
      data:
        value: "{{ states('input_number.living_normal_temperature') | float() }}"
  mode: single


- alias: '♨️ airco heating // living // aan volgens schema comfort temperatuur'
  id: '9bb6cb31-9f9f-42c2-a4ac-f551cc970eb7'
  description: ''
  trigger:
    - platform: state
      entity_id: schedule.living_comfort_temperature_schema
      to: "on"
    - platform: state
      entity_id: group.bart_madouce
      to: home
    - platform: template
      value_template: >
        temperature: >
          {{ states('sensor.living_temperature') | float <
          states('input_number.living_comfort_temperature') | float }}
  condition:
    - condition: state
      entity_id: input_select.heating_mode
      state: airco   
    - condition: state
      entity_id: schedule.living_comfort_temperature_schema
      state: "on"
    - condition: state
      entity_id: group.gezin
      state: home
    - condition: template
      value_template: >
        {{ states('sensor.living_temperature') | float <
        states('input_number.living_comfort_temperature') | float }} 
  action:
    - service: climate.set_temperature
      data:
        hvac_mode: heat
        temperature: >-
          {% set adj = (states('input_number.living_comfort_temperature') | float) - (states('sensor.living_temperature') | float) %}
          {{ (state_attr('climate.living_airco', 'current_temperature') + adj) | round(1, 'half', 0) }} 
      target:
        device_id: 1c560bbc7917f45d737e87d3e2bd0d89
    - service: climate.set_preset_mode
      data:
        preset_mode: eco
      target:
        device_id: 1c560bbc7917f45d737e87d3e2bd0d89
    - service: climate.set_swing_mode
      data:
        swing_mode: 3D
      target:
        device_id: 1c560bbc7917f45d737e87d3e2bd0d89
    - service: input_number.set_value
      target:
        entity_id: input_number.living_airco_target_temperature
      data:
        value: "{{ states('input_number.living_comfort_temperature') | float() }}"
  mode: single

- alias: "♨️ airco heating // living // uit volgens schema/verlaten huis/timer stop"
  id: '075c660b-6d9b-4190-b6fb-3acb07a7f7ce'
  description: ""
  trigger:
    - platform: state
      entity_id:
        - schedule.living_normal_temperature_schema
        - schedule.living_comfort_temperature_schema
      to: "off"
    - platform: state
      entity_id: group.gezin
      to: not_home
    - platform: state
      entity_id: group.living_ramen
      to: "on"
    - platform: time
      at: input_datetime.living_airco_timer_stop
  condition: []
  action:
    - service: climate.turn_off
      data: {}
      target:
        device_id: 1c560bbc7917f45d737e87d3e2bd0d89
    - service: climate.set_temperature
      data:
        temperature: 14
      target:
        device_id: 1c560bbc7917f45d737e87d3e2bd0d89
    - service: input_number.set_value
      data:
        value: 14
      target:
        entity_id: input_number.living_airco_target_temperature
    - service: timer.finish
      data: {}
      target:
        entity_id: timer.living_airco_timer
  mode: single


########################
# Handmatige aanpassing
########################

- alias: '♨️ airco heating // living // aan gedurende 30 minuten bij hogere gewenste temperatuur'
  id: 'f747ffe1-4135-4e72-af50-fd6052de540b'
  description: ''
  trigger:
  - platform: template
    value_template: >
      {{ states('sensor.living_temperature') | float < states('input_number.living_airco_target_temperature') | float }}
  condition:
  - condition: state
    entity_id: group.gezin
    state: home
  action:
  - service: input_number.set_value
    data:
      value: 30
    target:
      entity_id: input_number.living_airco_timer_minutes
  - service: script.living_airco_start_heating
    data: {}
  mode: restart


## NEW #####################

- alias: "♨️ airco heating // living // aan als temperatuur living 0,75 graad lager is dan doeltemperatuur"
  id: '58254156-db9d-4c65-b655-502839dfafe5'
  description: ''
  trigger:
  - platform: template
    value_template: >
      {{ ( states('input_number.living_airco_target_temperature') | float ) - ( states('sensor.living_temperature') | float ) >= 0.75 }}
  condition:
  - condition: or
    conditions:
      - condition: state
        entity_id: schedule.living_comfort_temperature_schema
        state: "on"
      - condition: state
        entity_id: schedule.living_normal_temperature_schema
        state: "on"
  - condition: state
    entity_id: group.gezin
    state: home
  action:
    - service: climate.turn_on
      data: {}
      target:
        device_id: 1c560bbc7917f45d737e87d3e2bd0d89
    - service: climate.set_temperature
      data:
        hvac_mode: heat
        temperature: >
          {% set adj = (states('input_number.living_airco_target_temperature') | float) - (states('sensor.living_temperature') | float) %}
          {{ (state_attr('climate.living_airco', 'current_temperature') + adj) | round(1, 'half', 0) }} 
      target:
        entity_id: climate.living_airco
    # - service: climate.set_temperature
    #   data:
    #     hvac_mode: heat
    #     temperature: 24.5
    #   target:
    #     entity_id: climate.living_airco
    - service: climate.set_preset_mode
      data:
        preset_mode: eco
      target:
        device_id: 1c560bbc7917f45d737e87d3e2bd0d89
    - service: climate.set_swing_mode
      data:
        swing_mode: 3D
      target:
        device_id: 1c560bbc7917f45d737e87d3e2bd0d89
    - service: notify.bart_phone
      data:
        title: Verwarming living aan
        message: >
          Airco living wordt opnieuw ingeschakeld om gewenste temperatuur {{ states('input_number.living_airco_target_temperature') }} te bereiken.
          Huidige temperatuur: {{ states('sensor.living_temperature') }}
  mode: single


- alias: "♨️ airco heating // living // uit als doeltemperatuur (ongeveer) bereikt is"
  id: '99579020-6dc1-4869-a91e-0631e04698f1'
  description: ''
  trigger:
  - platform: template
    value_template: >
  - platform: template
    value_template: >
      {{ ( states('input_number.living_airco_target_temperature') | float ) - ( states('sensor.living_temperature') | float ) <= 0.0 }}
  condition: []
  action:
    - service: climate.turn_off
      data: {}
      target:
        device_id: 1c560bbc7917f45d737e87d3e2bd0d89
    - service: notify.bart_phone
      data:
        title: Verwarming living uit
        message: >
          Airco living heeft doeltemperatuur {{ states('input_number.living_airco_target_temperature') }} bereikt. Wordt tijdelijk uitgeschakeld.
          Huidige temperatuur: {{ states('sensor.living_temperature') }}
  mode: single

- alias: "♨️ airco heating // living // ventilator living aan-uit volgens airco"
  id: '6c2a7de2-e755-4d05-a380-7109c46e313b'
  description: ''
  trigger:
  - platform: state
    entity_id: climate.living_airco
    to: "heat"
    for: "00:03:00"
    id: airco-aan
  - platform: state
    entity_id: climate.living_airco
    to: "off"
    for: "00:03:00"
    id: airco-uit
  condition: []
  action:
  - choose:
      - conditions:
          - condition: trigger
            id: airco-aan
        sequence:
          - service: fan.turn_on
            data:
              percentage: 35
            target:
              entity_id: fan.living_ventilator
      - conditions:
          - condition: trigger
            id: airco-uit
        sequence:
          - service: fan.turn_off
            data: {}
            target:
              entity_id: fan.living_ventilator
  mode: single
  