automation:

#############################################################
# Airco living
#############################################################

- alias: 'zonne-energie verwarmen // injectie meer dan 1000 W gem. 15 min. = living verwarming modus op airco'
  id: '68d14511-ef1e-468e-bc78-4a41113f1f24'
  description: ''
  trigger:
  - platform: time_pattern
    minutes: /15
  condition:
    - condition: template
      value_template: >
        {% set net = states('sensor.net_power_avg_15min') | float() %}
        {% set charger = states('sensor.charger_current_power_avg_15min') | float() %}
        {{ (net - charger) | int() < - ( states('input_number.living_airco_injection') | float() ) }}
    - condition: state
      entity_id: input_select.heating_mode_living
      state: centrale verwarming
    - condition: state
      entity_id: input_select.load_priority_1
      state: 'living airco'
    # - condition: numeric_state
    #   entity_id: climate.living
    #   below: input_number.living_target_temperature
    #   attribute: current_temperature
    - condition: state
      entity_id: group.bart_madouce
      state: home
  action:
  - service: notify.bart_phone
    metadata: {}
    data:
      title: Verwarming living ingesteld op airco
      message: >
        {% set c = states('sensor.charger_current_power_avg_15min') | float() %}
        {% set n = states('sensor.net_power_avg_15min') | float() %}
        Meer dan 1000 W injectie laatste 15 min.: Er is {{ - ( n - c) | int() }} W beschikbaar.
  - service: input_select.select_option
    target:
      entity_id: input_select.heating_mode_living
    data:
      option: airco
  - service: tado.set_climate_timer
    target:
      entity_id: climate.living
    data:
      requested_overlay: MANUAL
      temperature: 14
  mode: single

- alias: 'zonne-energie verwarmen // Netverbruik meer dan 200 W + airco living aan = living verwarming modus op centrale verwarming'
  id: 'bf9c4241-ded8-4dbf-8a41-7e4a494a4c59'
  description: ''
  trigger:
  - platform: time_pattern
    minutes: /15
  condition:
    - condition: template
      value_template: >
        {% set net = states('sensor.net_power_avg_15min') | float() %}
        {% set charger = states('sensor.charger_current_power_avg_15min') | float() %}
        {{ (net - charger) | int() > 200 }}
    - condition: state
      entity_id: input_select.heating_mode_living
      state: airco        
  action:
  - service: notify.bart_phone
    metadata: {}
    data:
      title: Verwarming living ingesteld op centrale verwarming
      message: De laatste 15 min. was er geen 1000 W injectie beschikbaar. ({{ states('sensor.net_power_avg_15min') | int() }} W)
  - service: input_select.select_option
    target:
      entity_id: input_select.heating_mode_living
    data:
      option: centrale verwarming
  mode: single

- alias: 'heating modus living op airco = airco starten'
  id: '2e6c96cd-6754-45f9-82ec-3dadbc9f79a1'
  description: ''
  trigger:
  - platform: state
    entity_id: input_select.heating_mode_living
    to: airco
  condition:
    - condition: state
      entity_id: input_boolean.heating_season
      state: "on"
    - condition: state
      entity_id: group.bart_madouce
      state: home  
  action:
    - service: climate.set_temperature
      data:
        hvac_mode: heat
        temperature: 22
      target:
        device_id: 1c560bbc7917f45d737e87d3e2bd0d89
    - service: climate.set_preset_mode
      data:
        preset_mode: eco
      target:
        device_id: 1c560bbc7917f45d737e87d3e2bd0d89
    - service: climate.set_swing_mode
      data:
        swing_mode: 3D
      target:
        device_id: 1c560bbc7917f45d737e87d3e2bd0d89
    - service: climate.set_fan_mode
      data:
        fan_mode: auto
      target:
        device_id: 1c560bbc7917f45d737e87d3e2bd0d89  
  mode: single

- alias: 'heating modus living op centrale verwarming = centrale verwarming op auto en airco stoppen'
  id: '7a0d56b7-9cd2-418f-bf86-f768851f4f65'
  description: ''
  trigger:
  - platform: state
    entity_id: input_select.heating_mode_living
    to: centrale verwarming
  condition:
    - condition: state
      entity_id: input_boolean.heating_season
      state: "on"
  action:
  - service: climate.set_hvac_mode
    data:
      hvac_mode: auto
    target:
      entity_id: climate.living
  - service: script.living_airco_stop
  mode: single  


#############################################################
# Airco Alunya
#############################################################

- alias: 'zonne-energie verwarmen // injectie meer dan 1000 W gem. 15 min. = Alunya verwarming modus op airco'
  id: 'd8e36ddc-9731-471d-bac6-9bb52c540264'
  description: ''
  trigger:
  - platform: time_pattern
    minutes: /15
  condition:
    - condition: template
      value_template: >
        {% set net = states('sensor.net_power_avg_15min') | float() %}
        {% set charger = states('sensor.charger_current_power_avg_15min') | float() %}
        {{ (net - charger) | int() < - ( states('input_number.alunya_airco_injection') | float() ) }}
    - condition: state
      entity_id: input_select.heating_mode_kamer_alunya
      state: centrale verwarming
    - condition: state
      entity_id: input_select.load_priority_1
      state: 'Alunya airco'
    - condition: state
      entity_id: group.bart_madouce
      state: home
  action:
  - service: notify.bart_phone
    metadata: {}
    data:
      title: Verwarming kamer Alunya ingesteld op airco
      message: >
        {% set c = states('sensor.charger_current_power_avg_15min') | float() %}
        {% set n = states('sensor.net_power_avg_15min') | float() %}
        Meer dan 1000 W injectie laatste 15 min.: Er is {{ - ( n - c) | int() }} W beschikbaar.
  - service: input_select.select_option
    target:
      entity_id: input_select.heating_mode_kamer_alunya
    data:
      option: airco
  - service: tado.set_climate_timer
    target:
      entity_id: climate.kamer_alunya
    data:
      requested_overlay: MANUAL
      temperature: 14
  mode: single

- alias: 'heating modus kamer Alunya op airco = airco starten'
  id: 'f923db2f-2bfc-4d08-a261-5412ddb06a4b'
  description: ''
  trigger:
  - platform: state
    entity_id: input_select.heating_mode_kamer_alunya
    to: airco
  condition:
    - condition: state
      entity_id: input_boolean.heating_season
      state: "on"
    - condition: state
      entity_id: group.bart_madouce
      state: home  
  action:
    - service: climate.set_temperature
      data:
        hvac_mode: heat
        temperature: 22
      target:
        device_id: 3c12e341dfd1d1fe2327ec66f3613321
    - service: climate.set_preset_mode
      data:
        preset_mode: eco
      target:
        device_id: 3c12e341dfd1d1fe2327ec66f3613321
    - service: climate.set_swing_mode
      data:
        swing_mode: 3D
      target:
        device_id: 3c12e341dfd1d1fe2327ec66f3613321
    - service: climate.set_fan_mode
      data:
        fan_mode: auto
      target:
        device_id: 3c12e341dfd1d1fe2327ec66f3613321  
  mode: single

- alias: 'zonne-energie verwarmen // Netverbruik meer dan 200 W + airco Alunya aan = kamer Alunya verwarming modus op centrale verwarming'
  id: 'ad149aa8-0aab-4a0a-a27b-deef5188c27a'
  description: ''
  trigger:
  - platform: time_pattern
    minutes: /15
  condition:
    - condition: template
      value_template: >
        {% set net = states('sensor.net_power_avg_15min') | float() %}
        {% set charger = states('sensor.charger_current_power_avg_15min') | float() %}
        {{ (net - charger) | int() > 200 }}
    - condition: state
      entity_id: input_select.heating_mode_kamer_alunya
      state: airco        
  action:
  - service: notify.bart_phone
    metadata: {}
    data:
      title: Verwarming kamer Alunya ingesteld op centrale verwarming
      message: De laatste 15 min. was er geen 1000 W injectie beschikbaar. ({{ states('sensor.net_power_avg_15min') | int() }} W)
  - service: input_select.select_option
    target:
      entity_id: input_select.heating_mode_kamer_Alunya
    data:
      option: centrale verwarming
  mode: single


- alias: 'heating modus kamer Alunya op centrale verwarming = centrale verwarming op auto en airco stoppen'
  id: '56524a74-e7a1-43db-bf3d-482fc6f8a101'
  description: ''
  trigger:
  - platform: state
    entity_id: input_select.heating_mode_kamer_alunya
    to: centrale verwarming
  condition:
    - condition: state
      entity_id: input_boolean.heating_season
      state: "on"
  action:
  - service: climate.set_hvac_mode
    data:
      hvac_mode: auto
    target:
      entity_id: climate.kamer_alunya
  - service: script.alunya_airco_stop
  mode: single  