automation:

- alias: 'injectie meer dan 1000 W = living verwarming modus op airco'
  id: '68d14511-ef1e-468e-bc78-4a41113f1f24'
  description: ''
  trigger:
  - platform: time_pattern
    minutes: /15
  condition:
    - condition: numeric_state
      entity_id: sensor.net_power_avg_15min
      below: -1000  
  action:
  - if:
      - condition: state
        entity_id: input_select.heating_mode_living
        state: centrale verwarming
    then: 
      - service: notify.bart_phone
        metadata: {}
        data:
          title: Verwarming living ingesteld op airco
          message: Meer dan 1000 W injectie laatste 15 min. ( {{ states('sensor.net_power_avg_15min') }})
  - service: input_select.select_option
    target:
      entity_id: input_select.heating_mode_living
    data:
      option: airco
  - service: tado.set_climate_timer
    target:
      entity_id: climate.living
    data:
      requested_overlay: MANUAL
      temperature: 14
  mode: single

- alias: 'injectie minder dan 1000 W = living verwarming modus op centrale verwarming'
  id: 'bf9c4241-ded8-4dbf-8a41-7e4a494a4c59'
  description: ''
  trigger:
  - platform: time_pattern
    minutes: /15
  condition:
    - condition: numeric_state
      entity_id: sensor.net_power_avg_15min
      above: -1000    
  action:
  - if:
      - condition: state
        entity_id: input_select.heating_mode_living
        state: airco
    then: 
      - service: notify.bart_phone
        metadata: {}
        data:
          title: Verwarming living ingesteld op centrale verwarming
          message: Minder dan 1000 W injectie laatste 15 min. ( {{ states('sensor.net_power_avg_15min') }})
  - service: input_select.select_option
    target:
      entity_id: input_select.heating_mode_living
    data:
      option: centrale verwarming
  mode: single

- alias: 'heating modus living op airco = airco starten'
  id: '2e6c96cd-6754-45f9-82ec-3dadbc9f79a1'
  description: ''
  trigger:
  - platform: state
    entity_id: input_select.heating_mode_living
    to: airco
  condition:
    - condition: state
      entity_id: input_boolean.heating_season
      state: "on"
    - condition: state
      entity_id: group.bart_madouce
      state: home  
  action:
    - service: climate.set_temperature
      data:
        hvac_mode: heat
        temperature: 23
      target:
        device_id: 1c560bbc7917f45d737e87d3e2bd0d89
    - service: climate.set_preset_mode
      data:
        preset_mode: eco
      target:
        device_id: 1c560bbc7917f45d737e87d3e2bd0d89
    - service: climate.set_swing_mode
      data:
        swing_mode: 3D
      target:
        device_id: 1c560bbc7917f45d737e87d3e2bd0d89
    - service: climate.set_fan_mode
      data:
        fan_mode: auto
      target:
        device_id: 1c560bbc7917f45d737e87d3e2bd0d89  
  mode: single

- alias: 'heating modus living op centrale verwarming = centrale verwarming op auto en airco stoppen'
  id: 'clsgo4ymd00005osnf85z770u'
  description: ''
  trigger:
  - platform: state
    entity_id: input_select.heating_mode_living
    to: centrale verwarming
  condition:
    - condition: state
      entity_id: input_boolean.heating_season
      state: "on"
  action:
  - service: climate.set_hvac_mode
    data:
      hvac_mode: auto
    target:
      entity_id: climate.living
  - service: script.living_airco_stop
  mode: single  
