automation:

##############################
# verluchting kamers
##############################


- alias: 💨 air // 🪟 raam Amilya // openen op warmste moment van de dag
  id: '63cf0cbd-bc53-422d-9095-90cffa3eea3e'
  description: ''
  trigger:
  - platform: time
    at: input_datetime.max_dagtemperatuur_uur
  condition:
  - condition: template
    value_template: "{{ states('sensor.amilya_raam_open_vandaag') | round() == 0}}"
  - condition: template
    value_template: "{{ ('sensor.kamer_amilya_heating') | float(default=0) == 0 }}"
  action:
  - service: input_boolean.turn_on
    target:
      entity_id: input_boolean.kamer_amilya_raam_moet_open    
  - service: script.notify_bart_windows_open
    data:
      title: Zet raam Amilya nu even open. Warmste moment van de dag.
      reason: >
        Raam is vandaag nog niet open geweest.      
      message: >
        Vocht kamer Amilya: {{states('sensor.gram_water_kamer_amilya')}} g/m³. Buiten: {{states('sensor.gram_water_outside')}} g/m³.<br><br>Vocht kamer Amilya: {{states('sensor.kamer_amilya_humidity') | round() }}%. Buiten: {{states('sensor.eikenbos_humidity')}}%<br>Temp kamer Amilya: {{states('sensor.kamer_amilya_temperature')}} °C. Buiten: {{states('sensor.eikenbos_temperature')}} °C.
      tag: window_kamer_amilya  
  - service: script.notify_madouce_windows_open
    data:
      title: Zet raam Amilya nu even open. Warmste moment van de dag.
      reason: >
        Raam is vandaag nog niet open geweest.       
      message: >
        Vocht kamer Amilya: {{states('sensor.gram_water_kamer_amilya')}} g/m³. Buiten: {{states('sensor.gram_water_outside')}} g/m³.<br><br>Vocht kamer Amilya: {{states('sensor.kamer_amilya_humidity') | round() }}%. Buiten: {{states('sensor.eikenbos_humidity')}}%<br>Temp kamer Amilya: {{states('sensor.kamer_amilya_temperature')}} °C. Buiten: {{states('sensor.eikenbos_temperature')}} °C.
      tag: window_kamer_amilya
  mode: single

- alias: 💨 air // 🪟 raam Alunya // openen op warmste moment van de dag
  id: 'f2d84987-861d-460a-9ff0-79535903143a'
  description: ''
  trigger:
  - platform: time
    at: input_datetime.max_dagtemperatuur_uur
  condition:
  - condition: template
    value_template: "{{ states('sensor.alunya_raam_open_vandaag') | round() == 0}}"
  - condition: template
    value_template: "{{ ('sensor.kamer_alunya_heating') | float(default=0) == 0 }}"
  action:
  - service: input_boolean.turn_on
    target:
      entity_id: input_boolean.kamer_alunya_raam_moet_open
  - service: script.notify_bart_windows_open
    data:
      title: Zet raam Alunya nu even open. Warmste moment van de dag.
      reason: >
        Raam is vandaag nog niet open geweest.      
      message: >
        Vocht kamer Alunya: {{states('sensor.gram_water_kamer_alunya')}} g/m³. Buiten: {{states('sensor.gram_water_outside')}} g/m³.<br>Vocht kamer Alunya: {{states('sensor.kamer_alunya_humidity') | round() }}%. Buiten: {{states('sensor.eikenbos_humidity')}}%<br>Temp kamer Alunya: {{states('sensor.kamer_alunya_temperature')}} °C. Buiten: {{states('sensor.eikenbos_temperature')}} °C.
      tag: window_kamer_alunya
  - service: script.notify_madouce_windows_open
    data:
      title: Zet raam Alunya nu even open. Warmste moment van de dag.
      reason: >
        Raam is vandaag nog niet open geweest.      
      message: >
        Vocht kamer Alunya: {{states('sensor.gram_water_kamer_alunya')}} g/m³. Buiten: {{states('sensor.gram_water_outside')}} g/m³.<br>Vocht kamer Alunya: {{states('sensor.kamer_alunya_humidity') | round() }}%. Buiten: {{states('sensor.eikenbos_humidity')}}%<br>Temp kamer Alunya: {{states('sensor.kamer_alunya_temperature')}} °C. Buiten: {{states('sensor.eikenbos_temperature')}} °C.
      tag: window_kamer_alunya      
  mode: single

- alias: 💨 air // 🪟 raam keuken // openen op warmste moment van dag
  id: 615fc634-795d-489e-9c25-4f36d912b7ca
  description: als het raam nog niet geopend geweest is vandaag = melding sturen op warmste moment van de dag
  trigger:
  - platform: time
    at: input_datetime.max_dagtemperatuur_uur
  condition:
  - condition: template
    value_template: "{{ states('sensor.keuken_raam_open_vandaag') | round() == 0}}"
  - condition: template
    value_template: "{{ ('sensor.living_heating') | float(default=0) == 0 }}"
  action:
  - service: input_boolean.turn_on
    target:
      entity_id: input_boolean.living_raam_moet_open  
  - service: script.notify_bart_windows_open
    data:
      title: "Zet keukenraam nu even open. Warmste moment van de dag."
      reason: >
        Raam is vandaag nog niet open geweest.
      message: >
        Temp buiten: {{states('sensor.eikenbos_temperature')}} °C. Vocht living: {{states('sensor.living_humidity') | round() }}%.
      tag: "window_living"
  - service: script.notify_madouce_windows_open
    data:
      title: "Zet keukenraam nu even open. Warmste moment van de dag."
      reason: >
        Raam is vandaag nog niet open geweest.      
      message: >
        Temp buiten: {{states('sensor.eikenbos_temperature')}} °C. Vocht living: {{states('sensor.living_humidity') | round() }}%.<br>
        Raam is vandaag nog niet open geweest.
      tag: "window_living"
  mode: single




##############################
# ventilatie toilet
##############################
  
- alias: 💨 air // ventilator // 1,5 min. licht in toilet = ventilator aan gedurende 3 minuten
  id: 'b5f5d558-a745-409f-8989-f0749a5992b4'
  description: ''
  trigger:
  - platform: state
    entity_id: light.toilet
    to: 'on'
    for: '00:01:30'
  condition:
  - condition: time
    after: '07:00'
    before: '23:30'
  action:
  - service: switch.turn_on
    target:
      entity_id:
      - switch.toilet_douche_ventilatie
  - delay:
      hours: 0
      minutes: 3
      seconds: 0
      milliseconds: 0
  - service: switch.turn_off
    target:
      entity_id: switch.toilet_douche_ventilatie
  mode: single

- alias: 💨 air // ventilator // licht in toilet, voormiddag, Bart thuis = ventilator aan gedurende 5 minuten
  id: 'cf2d5d42-332e-40ba-8cbb-e5035d18e61e'
  description: ''
  trigger:
  - platform: state
    entity_id: light.toilet
    to: 'on'
    for: '00:00:30'    
  condition:
  - condition: time
    after: '09:00'
    before: '12:00'
  - condition: state
    entity_id: person.bart
    state: home
  action:
  - service: switch.turn_on
    target:
      entity_id:
      - switch.toilet_douche_ventilatie
  - delay:
      hours: 0
      minutes: 5
      seconds: 0
      milliseconds: 0
  - service: switch.turn_off
    target:
      entity_id: switch.toilet_douche_ventilatie
  mode: single


##############################
# ventilatie badkamer
##############################

- alias: 💨 air // ventilator // badkamer raam wijd open = ventilator uit
  id: '09185cc1-4293-4cc0-9f89-831f0be7a74e'
  description: ''
  trigger:
  - platform: state
    entity_id: binary_sensor.badkamer_raam_wijd
    to: 'on'
    for:
      hours: 0
      minutes: 0
      seconds: 30
      milliseconds: 0
  - platform: state
    entity_id: binary_sensor.badkamer_raam_kantel
    to: 'on'
    for:
      hours: 0
      minutes: 0
      seconds: 30
      milliseconds: 0    
  condition: []
  action:
  - service: switch.turn_off
    target:
      entity_id: switch.toilet_douche_ventilatie
  mode: restart  

- alias: 💨 air // ventilator // licht in douche = ventilator aan zolang licht brandt + 10 minuten
  id: 'c4f8b201-16f1-41db-a285-7fb33b277343'
  description: ''
  trigger:
  - platform: state
    entity_id: light.badkamer_douche
    to: 'on'
    for: '00:00:30'
  condition:
  - condition: time
    after: '06:30'
    before: '23:30:00'
  action:
  - repeat:
      while:
      - condition: state
        entity_id: light.badkamer_douche
        state: 'on'
      sequence:
      - service: switch.turn_on
        target:
          entity_id:
          - switch.toilet_douche_ventilatie      
  - delay:
      hours: 0
      minutes: 10
      seconds: 0
      milliseconds: 0
  - service: switch.turn_off
    target:
      entity_id: switch.toilet_douche_ventilatie
  mode: single


##############################
# ventilator (algemeen)
##############################

- alias: 💨 air // ventilator // al 10 min aan = ventilator uit
  id: 'b1f343ba-5201-43ee-9502-f1d96abe99f9'
  trigger:
  - platform: event
    event_type: mobile_app_notification_action
    event_data:
      action: toilet_douche_ventilator_10_min_aan
  action:
  - service: switch.turn_on
    target:
      entity_id:
      - switch.toilet_douche_ventilatie
  - delay:
      hours: 0
      minutes: 10
      seconds: 0
      milliseconds: 0
  - service: switch.turn_off
    target:
      entity_id:
      - switch.toilet_douche_ventilatie
  mode: single


- alias: 💨 air // ventilator // al 20 minuten aan = ventilator uit
  id: '6754188c-c368-4013-89cc-1acc82b30ad3'
  description: ''
  trigger:
  - platform: state
    entity_id: switch.toilet_douche_ventilatie
    to: 'on'
    for:
      hours: 0
      minutes: 20
      seconds: 0
  condition: []
  action:
  - service: switch.turn_off
    target:
      entity_id:
      - switch.toilet_douche_ventilatie
  mode: single


##############################
# CO2 meter
##############################

- alias: 💨 air // check om 20u C02-niveau in master bedroom
  id: '2708d0cb-ef37-4efe-b6e6-1159df5d82bb'
  description: ""
  trigger:
    - platform: time
      at: "20:00:00"
  condition:
    - condition: numeric_state
      entity_id: sensor.kooldioxide_detector_carbon_dioxide
      above: 1000
  action:
    - service: notify.bart_phone
      data:
        title: Verlucht master bedroom.
        message: >
          CO2 waarde is {{ states('sensor.kooldioxide_detector_carbon_dioxide') | int() }} PPM.<br>
          De luchtvochtigheid is {{states('sensor.master_bedroom_humidity') | round() }}%. Buiten: {{states('sensor.eikenbos_humidity')}}%
        data:
          color: red          
  mode: single