automation:

##############################
# luchtzuivering living
##############################

- alias: 💨 air // purifier // Air Quality Index > 8 = aan
  id: '7e3043d1-8299-4121-ad8b-08da26340065'
  description: ''
  trigger:
  - platform: template
    value_template: >
      {{ states('sensor.zhimi_mb3_83f2_pm25') |float(default=0) > 8 }}
  condition:
  - condition: state
    entity_id: group.gezin
    state: 'home'
  - condition: time
    after: '07:00'
    before: '23:30'
  action:
  - service: fan.set_preset_mode
    data:
      entity_id: fan.air_purifier
      preset_mode: auto
  mode: single

- alias: 💨 air // purifier // Air Quality Index < 8 = uit
  id: '991a6848-2b77-4573-a2c4-76d603eeb899'
  description: ''
  trigger:
  - platform: template  
    value_template: >
      {{ states('sensor.zhimi_mb3_83f2_pm25') |float(default=0) <= 8 }}
  condition:
  - condition: state
    entity_id: input_boolean.busy_cooking
    state: 'off'    
  action:
  - service: fan.turn_off
    target:
      entity_id: fan.air_purifier
  mode: single

- alias: 💨 air // purifier // niet thuis = uit
  id: '0c3adcca-2586-4ee3-a3bc-a78f38f65937'
  description: ''
  trigger:
  - platform: state
    entity_id: group.gezin
    to: 'not_home'
    for: 00:05:00
  condition: []
  action:
  - service: fan.turn_off
    target:
      entity_id: fan.air_purifier
  mode: single

- alias: 💨 air // purifier // 23u00 = uit
  id: 'c046f93d-d49a-4db3-8dbf-4e3231374926'
  description: ''
  trigger:
  - platform: time
    at: '23:00:00'
  condition: []
  action:
  - service: fan.turn_off
    target:
      entity_id: fan.air_purifier
  mode: single

- alias: 💨 air // purifier // aan het koken = aan
  id: 'ef2b8563-60f8-4962-a357-6ac1589b08cd'
  description: ''
  trigger:
  - platform: state
    entity_id: input_boolean.busy_cooking
    to: 'on'
  - device_id: dd2e7860b0b3eade0fbecf9965c6106a
    domain: zha
    platform: device
    type: remote_button_short_press
    subtype: remote_button_short_press
  condition: []
  action:
  - service: input_boolean.turn_on
    target:
      entity_id: input_boolean.busy_cooking
  - service: fan.turn_on
    target:
      entity_id: fan.air_purifier
    data: {}
  - service: notify.bart_phone
    data:
      message: Lekker aan het koken? De lucht wordt gezuiverd.
      data:
        tag: lucht-zuivering
  - service: media_player.volume_set
    data:
      entity_id: media_player.living_speaker
      volume_level: 0.5      
  - service: tts.edge_tts_say
    data:
      entity_id: media_player.living_speaker
      message: >
        {{ ("Laat het dadelijk smaken! Ik zorg voor de zuivere lucht.",
        "Zullen we deze week ook nog eens frietjes eten?", 
        "Moet ik helpen met koken?",
        "Wie heeft het eten klaargemaakt?",
        "Laten we genieten van dit heerlijke maal en elkaars gezelschap!",
        "Laten we deze avond onthouden door te lachen met echt goede moppen en heerlijk te eten!",
        "Voor mij een steak met frietjes graag.",
        "Wanneer eten we nog eens spaghetti?",
        "Vergeet de groentjes niet voor de vitaminen!")
        |random }}
  - delay: '00:00:10'
  - service: media_player.volume_set
    data:
      entity_id: media_player.living_speaker
      volume_level: 0.4
  - delay: '01:00:00'
  - service: input_boolean.turn_off
    target:
      entity_id: input_boolean.busy_cooking
  - service: notify.bart_phone
    data:
      message: clear_notification
      data:
        tag: lucht-zuivering      
  mode: restart
  
- alias: 💨 air // purifier // koken gedaan = uit
  id: 'dd3f89f5-e628-408a-a5aa-9aa9afbbd6d6'
  description: ''
  trigger:
  - platform: state
    entity_id: input_boolean.busy_cooking
    to: 'off'
  condition: []
  action:
  - service: fan.turn_off
    data: {}
    target:
      entity_id: fan.air_purifier
  - service: tts.edge_tts_say
    data:
      entity_id: media_player.living_speaker
      message: >
        {{ ("De kooksessie is gedaan. Hopelijk heeft het gesmaakt.",
        "De lucht is weer gezuiverd. Jullie kunnen nu weer ademhalen.",
        "De lucht is hier zo zuiver als aan de zee.",
        "Haal eens diep adem. Voel je de zuivere lucht?",
        "Voel je de frisheid? De lucht is weer zuiver.",
        "De luchtreiniging is voltooid. Adem diep in en geniet.",
        "De luchtkwaliteit is weer top. Ontspan en geniet."
        )
        |random }}
  - service: notify.bart_phone
    data:
      message: clear_notification
      data:
        tag: lucht-zuivering        
  mode: restart
