############################ Table of Contents ############################ 
# 
#   Automations
#     🏡 Bart komt thuis = melding auto % + open garage/voordeur
#     🏡 Madouce komt thuis = melding auto % + open garage/voordeur
#     🏡 Alunya komt thuis = welkom & melding garage/deur
#     Open garage
#     Open voordeur
#
############################ Automations ################################## 

automation:

- alias: 🏡 Bart komt thuis met auto 1 = melding auto % + open garage/voordeur
  id: '99d307b5-f692-4996-8d0e-7eb92a735b57'
  description: ''
  # HACS integration sun2 is required to get the sensor.sun_phase sensor 
  trigger:
  - platform: zone
    entity_id: device_tracker.bart_s23plus
    zone: zone.home
    event: enter
  condition:
  - condition: state
    entity_id: binary_sensor.bart_phone_connected_to_car_1
    state: 'on'
  action:
  - service: notify.bart_phone
    data:
      message: TTS
      data:
        tts_text: >-
          {% if now().hour < 3 %}{% set t = now().date() %}{% set d = 'vandaag' %}
          {% else %}{% set t = now().date() + timedelta(days=1) %}{% set d = 'morgen' %}
          {% endif %}
          {% set target_soc = 'input_number.car_1_min_target_soc_day_' ~ t.isoweekday() %}
          {% set current_soc = states('sensor.car_1_soc') | round(default=0) %}
          {% set use = 'input_select.car_1_use_day_' ~ t.isoweekday() %}
          {% set v = states('sensor.solar_sim_energy_today_adj') | int %}
          {% set m = states('sensor.solar_sim_energy_tomorrow_adj') | int %}
          {% set nu = states('sensor.sma_today') | float %}
          {% set restzon = (v - nu )| int %}
          {% set resturen = (((states('sensor.sun_next_setting') | as_timestamp) - (now() | as_timestamp)) / 3600 ) %}
          {% set restperuur = (restzon / resturen) | round(1) %}
          Welkom thuis Bart!
          {% if states('sensor.car_1_soc') | float(default=0) <  states(target_soc) | float(default=0) %}Vergeet niet de laadkabel in te steken.
            {% if current_soc == unavailable %}Er moet geladen worden tot {{ states(target_soc) | round(default=0) }}%
            {% else %}Er moet geladen worden van {{ current_soc }}% naar {{ states(target_soc) | round(default=0) }}%.
            {% endif %}
            {% if restperuur > 1 and states('sensor.sun_phase') =="Day" %}Je kan met zon laden. Er wordt vandaag nog {{ restzon }} kilowattuur zon verwacht.
            {% endif %}
          {% else %}De auto heeft {{states('sensor.car_1_soc') | round(default=0) }}% batterij en dit is voldoende voor {{ d }}. Er is {{d}} maar {{ states(target_soc) | round(default=0) }}% nodig.
            {% if restperuur > 1 %}Je mag de kabel insteken om met zon te laden. Er wordt vandaag nog {{ restzon }} kilowattuur zon verwacht.
            {% elif restperuur <= 1 and m > 5 and ( states(use) == 'thuis' or t.isoweekday() > 5 ) %}Aangezien de auto {{ d }} waarschijnlijk thuis is, mag je wel de kabel insteken om met zon te laden. Er wordt {{ d }} {{ m }} kilowatuur zon verwacht.
            {% endif %}
          {% endif %}
        ttl: 0
        priority: high
        media_stream: alarm_stream_max
  - service: notify.bart_phone
    data:
      message: Welkom thuis! (veeg omlaag voor acties)
      data:
        car_ui: true
        channel: androidauto
        persistent: true
        tag: persistent
        color: red
        timeout: 420
        notification_icon: "mdi:account-heart"
        actions:
        - action: open_garage
          title: Garage
        - action: open_voordeur
          title: Voordeur
        - action: open_voordeur_garage
          title: Voordeur & garage          
  mode: single

- alias: 🏡 Madouce komt thuis met auto 1 = melding auto % + open garage/voordeur
  id: '4a938979-1120-4d05-a5f3-6f572bdeac88'
  description: ''
  # HACS integration sun2 is required to get the sensor.sun_phase sensor
  trigger:
  - platform: device
    device_id: d434bc1199aafa4c5d9e448b1fd55e30
    domain: device_tracker
    entity_id: device_tracker.madouce_s20
    type: enters
    zone: zone.home
  condition:
  - condition: state
    entity_id: binary_sensor.madouce_phone_connected_to_car_1
    state: 'on'
  action:
  - service: notify.madouce_phone
    data:
      message: TTS
      data:
        tts_text: >
          {% if now().hour < 3 %}{% set t = now().date() %}{% set d = 'vandaag' %}
          {% else %}{% set t = now().date() + timedelta(days=1) %}{% set d = 'morgen' %}
          {% endif %}
          {% set target_soc = 'input_number.car_1_min_target_soc_day_' ~ t.isoweekday() %}
          {% set use = 'input_select.car_1_use_day_' ~ t.isoweekday() %}
          {% set v = states('sensor.solar_sim_energy_today_adj') | int %}
          {% set m = states('sensor.solar_sim_energy_tomorrow_adj') | int %}
          {% set nu = states('sensor.sma_today') | float %}
          {% set restzon = (v - nu )| int %}
          {% set resturen = (((states('sensor.sun_next_setting') | as_timestamp) - (now() | as_timestamp)) / 3600 ) %}
          {% set restperuur = (restzon / resturen) | round(1) %}
          Welkom thuis Madoes!
          {% if states('sensor.car_1_soc') | float(default=0) <  states(target_soc) | float(default=0) %}Vergeet de laadkabel niet in te steken. Er moet geladen worden van {{states('sensor.car_1_soc') | round(default=0)}}% naar {{ states(target_soc) | round(default=0) }}%.
            {% if restperuur > 1 and states('sensor.sun_phase') =="Day" %}Je kan met zon laden. Er wordt vandaag nog {{ restzon }} kilowatuur zon verwacht.
            {% endif %}
          {% else %}De auto heeft {{states('sensor.car_1_soc') | round(default=0) }}% batterij en dit is voldoende voor {{ d }}. Er is {{d}} maar {{ states(target_soc) | round(default=0) }}% nodig.
            {% if restperuur > 1 %}Je mag de kabel insteken om met zon te laden. Er wordt vandaag nog {{ restzon }} kilowatuur zon verwacht.
            {% elif restperuur <= 1 and m > 5 and ( states(use) == 'thuis' or t.isoweekday() > 5 ) %}Aangezien de auto {{ d }} waarschijnlijk thuis is, mag je wel de kabel insteken om met zon te laden. Er wordt {{ d }} {{ m }} kilowatuur zon verwacht.
            {% endif %}
          {% endif %}
        ttl: 0
        priority: high
        media_stream: alarm_stream_max
  - service: notify.madouce_phone
    data:
      message: Welkom thuis! (veeg omlaag voor acties)
      data:
        car_ui: true
        channel: androidauto
        persistent: true
        tag: persistent
        color: red
        timeout: 420
        notification_icon: "mdi:account-heart"
        actions:
        - action: open_garage
          title: Garage
        - action: open_voordeur
          title: Voordeur
        - action: open_voordeur_garage
          title: Voordeur & garage    
  mode: single

- alias: Open garage
  id: '17e008ff-4a39-438b-8021-89e07c3cf5cf'
  trigger:
  - platform: event
    event_type: mobile_app_notification_action
    event_data:
      action: open_garage
  action:
  - service: cover.open_cover
    target:
      entity_id: cover.garagepoort
  mode: single
  
- alias: Open voordeur
  id: 'b432c591-0c68-40fe-a22b-0f31296d1ba5'
  trigger:
  - platform: event
    event_type: mobile_app_notification_action
    event_data:
      action: open_voordeur
  action:
  - service: lock.unlock
    target:
      entity_id: lock.voordeur_nuki
  mode: single

- alias: Open voordeur & garage
  id: 'e69cac91-e56e-42ed-9745-a5c14f41ba52'
  trigger:
  - platform: event
    event_type: mobile_app_notification_action
    event_data:
      action: open_voordeur_garage
  action:
  - service: lock.unlock
    target:
      entity_id: lock.voordeur_nuki
  - service: cover.open_cover
    target:
      entity_id: cover.garagepoort      
  mode: single

- alias: 🏡 Madouce is bijna thuis 
  id: '9d978857-e649-455d-8144-1e5dad99eb23'
  description: '9d978857-e649-455d-8144-1e5dad99eb23'
  trigger:
  - platform: numeric_state
    entity_id:
      - proximity.madouce_home
    below: 2
  condition:
  - condition: state
    entity_id: person.bart
    state: home
    for:
      hours: 0
      minutes: 5
      seconds: 0
  - condition: template
    value_template: "{{ states('person.madouce') != 'blocked_zone' }}"
  action:
  - service: notify.bart_phone
    data:
      title: Madouce is bijna thuis.
      message: Hoera.
      data:
        tag: madouce_bijna_thuis
        color: red
        ttl: 0
        timeout: 600
        priority: high
        notification_icon: "mdi:account-heart"
  - if:
      - condition: template
        value_template: "{{ 7 < now().hour < 23 }}"
    then:
      - service: notify.bart_phone
        data:
          message: TTS
          data:
            channel: "alarm_stream"
            volume: 0.5            
            tts_text: "Madouce is bijna thuis."
            ttl: 0
            priority: high
            media_stream: alarm_stream
  mode: single

- alias: 🏡 Bart is bijna thuis 
  id: '50eab11b-f89a-41b3-82ad-e1110b9b0738'
  description: ''
  trigger:
  - platform: numeric_state
    entity_id:
      - proximity.bart_home
    below: 2
  condition:
  - condition: state
    entity_id: person.madouce
    state: home
    for:
      hours: 0
      minutes: 5
      seconds: 0    
  action:
  - service: notify.madouce_phone
    data:
      title: Bart is bijna thuis.
      message: Hoera.
      data:
        tag: bart_bijna_thuis      
        color: red
        ttl: 0
        timeout: 600
        priority: high
        notification_icon: "mdi:account-heart"
  - if:
      - condition: template
        value_template: "{{ 7 < now().hour < 23 }}"
    then:
      - service: notify.madouce_phone
        data:
          message: TTS
          data:
            channel: "alarm_stream"
            tts_text: "Bart is bijna thuis."
            ttl: 0
            priority: high
            media_stream: alarm_stream
  mode: single
  

- alias: Bart komt thuis en binnen wifi bereik = doe voordeur open
  id: 'a60b8335-0ad4-4f0a-9471-599468141952'
  description: ""
  trigger:
    - platform: state
      entity_id:
        - sensor.sm_s916b_wifi_connection
      to: BMWifi
  condition:
    - condition: state
      entity_id: person.bart
      state: home
    - condition: template
      value_template: >-
        {% set dif = as_timestamp(now()) - as_timestamp(states.person.bart.last_changed) %}
        {{ 30 < dif < 600 }}
  action:
    - if:
        - condition: state
          entity_id: lock.voordeur_nuki
          state: unlocked
      then:
        - if:
            - condition: template
              value_template: "{{ 7 < now().hour < 23 }}"
          then:      
            - service: notify.bart_phone
              data:
                message: TTS
                data:
                  channel: "alarm_stream"
                  tts_text: "Welkom thuis Bart. De voordeur is open."
                  ttl: 0
                  priority: high
                  media_stream: alarm_stream_max
    - if:
        - condition: state
          entity_id: lock.voordeur_nuki
          state: locked      
      then:
        - service: lock.unlock
          data: {}
          target:
            entity_id: lock.voordeur_nuki
        - if:
            - condition: template
              value_template: "{{ 7 < now().hour < 23 }}"
          then:
          - service: notify.bart_phone
            data:
              message: TTS
              data:
                channel: "alarm_stream"
                tts_text: "Welkom thuis Bart. Ik heb de voordeur opengedaan en doe ze over 7 minuten weer dicht."
                ttl: 0
                priority: high
                media_stream: alarm_stream_max
        - wait_template: ''
          timeout: "00:07:00"
        - service: lock.lock
          data: {}
          target:
            entity_id: lock.voordeur_nuki            
  mode: single

- alias: Madouce komt thuis en binnen wifi bereik = doe voordeur open
  id: '80beb2a6-8bfc-4905-b32e-5784e97748cd'
  description: ""
  trigger:
    - platform: state
      entity_id:
        - sensor.sm_g986b_wifi_connection
      to: BMWifi
  condition:
    - condition: state
      entity_id: person.madouce
      state: home
    - condition: template
      value_template: >-
        {% set dif = as_timestamp(now()) - as_timestamp(states.person.madouce.last_changed) %}
        {{ 30 < dif < 600 }}
  action:
    - if:
        - condition: state
          entity_id: lock.voordeur_nuki
          state: unlocked      
      then:
        - service: notify.madouce_phone
          data:
            message: TTS
            data:
              channel: "alarm_stream"
              tts_text: "Welkom thuis Madoes. De voordeur is open."
              ttl: 0
              priority: high
              media_stream: alarm_stream_max  
    - if:
        - condition: state
          entity_id: lock.voordeur_nuki
          state: locked      
      then:
        - service: lock.unlock
          data: {}
          target:
            entity_id: lock.voordeur_nuki
        - if:
            - condition: template
              value_template: "{{ 7 < now().hour < 23 }}"
          then:            
            - service: notify.madouce_phone
              data:
                message: TTS
                data:
                  channel: "alarm_stream"
                  tts_text: "Welkom thuis Madoes. Ik heb de voordeur opengedaan en doe ze over 7 minuten weer dicht."
                  ttl: 0
                  priority: high
                  media_stream: alarm_stream_max
        - wait_template: ''
          timeout: "00:07:00"
        - service: lock.lock
          data: {}
          target:
            entity_id: lock.voordeur_nuki            
  mode: single


- alias: 💡 lights // Bart komt thuis en binnen wifi bereik en donker = doe buitenverlichting aan
  id: 'f8ac109d-3e7d-4a31-958a-fc4ad5a60c9f'
  description: ""
  trigger:
    - platform: state
      entity_id:
        - sensor.sm_s916b_wifi_connection
      to: BMWifi
  condition:
    - condition: state
      entity_id: person.bart
      state: home
    - condition: template
      value_template: >-
        {% set dif = as_timestamp(now()) -
        as_timestamp(states.person.bart.last_changed) %} {{ 30 < dif < 600 }}
  action:
    - if:
        - condition: template
          value_template: "{{ states('sensor.oprit_bewegingssensor_light_level') | int < 10 }}"
      then:
        - service: light.turn_on
          data:
            brightness: 150
          target:
            entity_id:
              - light.buiten_oprit
              - light.buiten_voordeur
        - wait_template: ""
          timeout: "00:05:00"
        - service: light.turn_off
          data: {}
          target:
            entity_id:
              - light.buiten_oprit
              - light.buiten_voordeur
  mode: single  

- alias: 💡 lights // Madouce komt thuis en binnen wifi bereik en donker = doe buitenverlichting aan
  id: '68b8a483-f1f1-4a26-93b2-17df92b17736'
  description: ""
  trigger:
    - platform: state
      entity_id:
        - sensor.sm_g986b_wifi_connection
      to: BMWifi
  condition:
    - condition: state
      entity_id: person.madouce
      state: home
    - condition: template
      value_template: >-
        {% set dif = as_timestamp(now()) - as_timestamp(states.person.madouce.last_changed) %}
        {{ 30 < dif < 600 }}
  action:
    - if:
        - condition: template
          value_template: "{{ states('sensor.oprit_bewegingssensor_light_level') | int < 10 }}"
      then:
        - service: light.turn_on
          data:
            brightness: 150
          target:
            entity_id:
              - light.buiten_oprit
              - light.buiten_voordeur
        - wait_template: ''
          timeout: "00:05:00"
        - service: light.turn_off
          data: {}
          target:
            entity_id:
              - light.buiten_oprit
              - light.buiten_voordeur        
  mode: single

- alias: "Tekst voor herinnering bij thuiskomst wordt aangepast"
  id: 82a22db8-f370-42e5-8b56-c7db3c69a8ce
  trigger:
    - platform: state
      entity_id: input_text.arriving_home_reminder_madouce
  condition: []
  action:
    - service: input_boolean.turn_on
      data: {}
      target:
        entity_id: input_boolean.arriving_home_reminder_madouce
  mode: single

- alias: Bart komt thuis na fietsen (iPhone) = doe garagepoort open
  id: '3873a20f-fa6e-4c9e-8469-91b5626bd24a'
  description: ""
  trigger:
    - platform: state
      entity_id:
        - sensor.bartiphone_ssid
      to: BMWifi
  condition:
    - condition: template
      value_template: >-
        {% set act = states('sensor.bartiphone_activity') %} {{ act == 'cycling' }}
    - condition: template
      value_template: >-
        {% set dif = as_timestamp(now()) - as_timestamp(states.cover.garagepoort.last_changed) %} {{ dif > 120 }}    
  action:
    - service: cover.open_cover
      target:
        entity_id: cover.garagepoort
      data: {}
  mode: single

- alias: Bart komt thuis na fietsen = doe garagepoort open
  id: '1534f878-5e7c-46f7-9956-8d2ecf9b0d2d'
  description: ""
  trigger:
    - platform: state
      entity_id:
        - sensor.sm_s916b_wifi_connection
      to: BMWifi
    - platform: state
      entity_id:
        - sensor.sm_s916b_wifi_connection
      to: BMWifiBackup
  condition:
    - condition: template
      value_template: >-
        {% set act = states('sensor.sm_s916b_detected_activity') %} {{ act ==
        "on_bicycle" }} # {{ act == "on_bicycle" or act == "walking" }}
    - condition: template
      value_template: >-
        {% set dif = as_timestamp(now()) -
        as_timestamp(states.cover.garagepoort.last_changed) %} {{ dif > 120 }}    
  action:
    - service: notify.bart_phone
      data:
        message: TTS
        data:
          tts_text: Welkom thuis Bart. De garagepoort gaat nu open.
          ttl: 0
          priority: high
          media_stream: alarm_stream_max
    - service: cover.open_cover
      target:
        entity_id: cover.garagepoort
      data: {}
  mode: single

- alias: Iets na middernacht = reset aankomstuur Bart thuis
  id: 'e8e1872d-3120-441e-9d39-be5af32e8592'
  description: ""
  trigger:
    - platform: time
      at: "00:15:00"
  condition: []
  action:
    - service: input_text.set_value
      data:
        value: "nog geen uur bepaald"
      target:
        entity_id: input_text.arriving_home_time_bart        
  mode: single