

automation:

# You can find the device_id of the switch/button (Aqara/ Philips) via the Developer options / Events. The "listen" to "zha_event" events, fill in zha_event and click on the start to listen button.
# Then click on the (physical) switch/button. A report will be displayed in the listener, including the device_id

# buttons supports: single click, double click, long press
# remote_button_short_press
# remote_button_long_press
# remote_button_long_release


- alias: "button garagepoort: single press = sluit garagepoort"
  id: '02226be6-e34d-4185-9839-3f05db02063d'
  description: ''
  trigger:
  - device_id: 29af8c63a47e9e6e880ee1da155a8a1e
    domain: zha
    platform: device
    type: remote_button_short_press
    subtype: remote_button_short_press
  condition: []
  action:
  - service: cover.close_cover
    target:
      entity_id: cover.garagepoort
  mode: single
  
- alias: "button garagepoort: long press = open garagepoort"
  id: '8578845a-6ef6-4e79-85fa-2b8f0d5481b1'
  description: ''
  trigger:
  - device_id: 29af8c63a47e9e6e880ee1da155a8a1e
    domain: zha
    platform: device
    type: remote_button_long_release
    subtype: remote_button_long_release
  condition: []
  action:
  - service: cover.open_cover
    target:
      entity_id: cover.garagepoort
  - service: media_player.volume_set
    data:
      entity_id: media_player.living_speaker
      volume_level: 0.6
  - service: media_player.volume_set
    data:
      entity_id: media_player.living_speaker
      volume_level: 0.6
  - service: tts.speak
    data:
      entity_id: media_player.living_speaker
      message: Garagepoort gaat open!
  - service: tts.speak
    data:
      entity_id: media_player.living_speaker
      message: Garagepoort gaat open!
  - service: media_player.volume_set
    data:
      entity_id: media_player.living_speaker
      volume_level: 0.4
  - service: media_player.volume_set
    data:
      entity_id: media_player.living_speaker
      volume_level: 0.4
  mode: single       
  
- alias: button nachtkastje Bart info (uitgezonderd 's ochtends)
  id: 'e5b8829b-92b1-400d-aacb-4cd71f93052f'
  description: ''
  trigger:
  # Bart nachtkastje
  - device_id: eff0e9bdff49d94c3646cefe55f8d941
    domain: zha
    platform: device
    type: remote_button_short_press
    subtype: remote_button_short_press
  condition:
  - condition: template
    value_template:  "{{ not (6 < now().hour < 11) }}"
  action:
    - service: tts.edge_tts_say
      data:
        entity_id: media_player.master_bedroom_speaker
        cache: true
        message: >-
          Het is nu {{ as_timestamp(now()) |timestamp_custom('%-H') }} uur {{
          as_timestamp(now()) |timestamp_custom('%-M') }}. Buiten is het {{ states('sensor.eikenbos_temperature') |string|replace('.', ',') }} graden.
    - delay: '00:00:02'
    - wait_template: "{{ is_state('media_player.master_bedroom_speaker', 'idle')}}"
    - service: tts.edge_tts_say 
      data:
        entity_id: media_player.master_bedroom_speaker
        message: >-
          {% from 'relative_time_plus.jinja' import relative_time_plus %}
          Jullie zijn al {{ relative_time_plus('2022-04-30', 4, language='nl') }} getrouwd. {{("Dat begint al te tellen!", "Lukt het nog altijd als man en vrouw?", "Ik vind jullie ringen nog altijd schitterend!", "Het kleur van de jurk was de verrassing van de dag. Weet je nog?", "En lukt het nog met de geloften?" )|random }}
    - delay: '00:00:02'
    - wait_template: "{{ is_state('media_player.master_bedroom_speaker', 'idle')}}"
    # - service: tts.speak
    #   data:
    #     entity_id: media_player.master_bedroom_speaker
    #     message: >-
    #       {% if is_state('lock.audi_e_tron_sportback_door_lock', 'unlocked') %} De auto is niet op slot.
    #       {% else %} De auto is op slot.
    #       {% endif %}
    # - delay: '00:00:02'
    - wait_template: "{{ is_state('media_player.master_bedroom_speaker', 'idle')}}"
    - service: tts.edge_tts_say 
      data:
        entity_id: media_player.master_bedroom_speaker
        message: >-
          {% set soc = states('sensor.car_1_soc') | int %}
          {% set target = states('input_number.car_1_min_target_soc') | int %}
          {% set watt = states('input_number.car_charge_fixed_wattage') %}          
          De auto is {{ soc }}% geladen.
          {% if soc < target %}
          Er moet worden geladen tot {{ target }}%.
            {% if is_state('sensor.car_1_plug_state','connected') %}De laadkabel is verbonden.
            {% else %}Opgelet! De laadkabel is niet verbonden!
            {% endif %}
            {% if states('input_boolean.car_charge_mode_stoptimer') == 'on' %}Om het laaddoel te bereiken om {{ state_attr('input_datetime.car_charge_target_time', 'timestamp') | timestamp_custom('%-H uur %M',) }} zal het laden starten om {{ as_timestamp(states('sensor.car_charge_stoptimer_starttime'),0) | timestamp_custom('%-H uur %M') }}
            Het laden gebeurt aan {{ watt }} kilowatt.
            {% endif %}
          {% else %}
          Het laaddoel van {{ target }}% is al bereikt.
          {% endif %}
    - delay: '00:00:02'
    - wait_template: "{{ is_state('media_player.master_bedroom_speaker', 'idle')}}"
    - service: tts.edge_tts_say 
      data:
        entity_id: media_player.master_bedroom_speaker
        cache: true
        message: >-
          {% if is_state('lock.voordeur_nuki', 'unlocked') %} De voordeur is niet op
          slot. {% else %} De voordeur is op slot. {% endif %}
    - delay: '00:00:02'
    - wait_template: "{{ is_state('media_player.master_bedroom_speaker', 'idle')}}"
    - service: tts.edge_tts_say 
      data:
        entity_id: media_player.master_bedroom_speaker
        cache: true
        message: >-
          {% if is_state('group.alle_raam_sensoren', 'off') %} Alle ramen zijn
          dicht!
          {% else %} De volgende ramen staan nog open:
          {{expand(states.binary_sensor.kamer_amilya_raam,
          states.binary_sensor.kamer_alunya_raam,
          states.binary_sensor.kamer_alunya_schuifraam,
          states.binary_sensor.badkamer_raam_kantel,
          states.binary_sensor.badkamer_raam_wijd,
          states.binary_sensor.berging_raam,
          states.binary_sensor.keuken_raam,
          states.binary_sensor.living_oprit_raam,
          states.binary_sensor.living_tuin_raam,
          states.binary_sensor.master_bedroom_raam_kantel,
          states.binary_sensor.master_bedroom_raam_wijd,
          states.binary_sensor.veranda_schuifraam)
          |selectattr('state','eq','on') | map(attribute='name')| list }}
          {% endif %}
    - delay: '00:00:02'
    - wait_template: "{{ is_state('media_player.master_bedroom_speaker', 'idle')}}"
    - service: tts.edge_tts_say 
      data:
        entity_id: media_player.master_bedroom_speaker
        cache: true
        message: >-
          {% if now().strftime("%H")|int > 20 %} Slaap lekker straks.
          {% elif now().strftime("%H")|int > 22 %} Het is bijna tijd om te slapen.
          {% else %} Nog een prettige dag.
          {% endif %}
  mode: single

- alias: button nachtkastje Bart ochtendinfo
  id: 'b9aefb3b-17fa-4bc0-bdbc-365930f68317'
  description: ''
  trigger:
  # Bart nachtkastje
  - device_id: eff0e9bdff49d94c3646cefe55f8d941
    domain: zha
    platform: device
    type: remote_button_short_press
    subtype: remote_button_short_press
  condition:
  - condition: template
    value_template: "{{ 6 < now().hour < 11 }}"
  action:
    - service: tts.edge_tts_say 
      data:
        entity_id: media_player.master_bedroom_speaker
        cache: true
        message: >-
          Goedemorgen. Het is nu {{ as_timestamp(now()) |timestamp_custom('%-H') }} uur {{
          as_timestamp(now()) |timestamp_custom('%-M') }}. Buiten is het {{ states('sensor.eikenbos_temperature') |string|replace('.', ',') }} graden.
          Het wordt vandaag maximum {{ states('input_number.weather_eikenbos_max_temp_today') | replace(".", ",") }} graden.
          De volgende 4 uren wordt het {{ states('sensor.eikenbos_temperature_average_forecast_4_hours') | round() }} graden.
    - delay: '00:00:02'
    - wait_template: "{{ is_state('media_player.master_bedroom_speaker', 'idle')}}"
    - service: tts.edge_tts_say 
      data:
        entity_id: media_player.master_bedroom_speaker
        cache: true
        message: >-
          Er wordt vandaag {{ states('sensor.solar_sim_energy_today_adj') | round() }} kilowatuur zon verwacht.
    - delay: '00:00:02'
    - wait_template: "{{ is_state('media_player.master_bedroom_speaker', 'idle')}}"
    - service: tts.edge_tts_say 
      data:
        entity_id: media_player.master_bedroom_speaker
        message: >-
          {% set soc = states('sensor.car_1_soc') | int %}
          {% set target = states('input_number.car_1_optimal_target_soc') | int %}
          {% set watt = states('input_number.car_charge_fixed_wattage') %}          
          De auto is {{ soc }}% geladen.
          {% if soc < target %}
          Er moet worden geladen tot {{ target }}%.
            {% if is_state('sensor.car_1_plug_state','connected') %}De laadkabel is verbonden.
            {% else %}Opgelet! De laadkabel is niet verbonden!
            {% endif %}
            {% if states('input_boolean.car_charge_mode_stoptimer') == 'on' %}Om het laaddoel te bereiken om {{ state_attr('input_datetime.car_charge_target_time', 'timestamp') | timestamp_custom('%-H uur %M',) }} zal het laden starten om {{ as_timestamp(states('sensor.car_charge_stoptimer_starttime'),0) | timestamp_custom('%-H uur %M') }}
            Het laden gebeurt aan {{ watt }} kilowatt.
            {% endif %}
          {% else %}
          Het laaddoel van {{ target }}% is al bereikt.
          {% endif %}
    - delay: '00:00:02'
    - wait_template: "{{ is_state('media_player.master_bedroom_speaker', 'idle')}}"
    - service: tts.edge_tts_say 
      data:
        entity_id: media_player.master_bedroom_speaker
        cache: true
        message: >-
          Nog een prettige dag.
  mode: single



- alias: button nachtkastje Madouce (short press) = matrasverwarmer uit 
  id: 'c2d4f8a2-3f38-40f2-8d8a-816813c65c59'
  description: ''
  trigger:
  # Madouce nachtkastje  
  - device_id: 4ac6dc3329bc8cf31a1a294af788ac50
    domain: zha
    platform: device
    type: remote_button_short_press
    subtype: remote_button_short_press
  condition: []
  action:
  - service: switch.turn_off
    target:
      entity_id: switch.madouce_matrasverwarmer
  - condition: time
    after: '09:00:00'
    before: '23:00:00'
  - service: tts.speak
    data:
      entity_id: media_player.master_bedroom_speaker
      cache: true
      message: >-
        {% if is_state('switch.madouce_matrasverwarmer', 'off') %} De matras was al uit. 
        {% else %} De matras wordt uitgeschakeld.
        {% endif %}
  mode: single
  
- alias: button nachtkastje Madouce (long press) = matrasverwarmer aan 
  id: '5339a7c4-6300-4169-ae2a-eb698d1dae39'
  description: ''
  trigger:
  # Madouce nachtkastje  
  - device_id: 4ac6dc3329bc8cf31a1a294af788ac50
    domain: zha
    platform: device
    type: remote_button_long_press
    subtype: remote_button_long_press
  condition: []
  action:
  - service: switch.turn_on
    target:
      entity_id: switch.madouce_matrasverwarmer
  - condition: time
    after: '09:00:00'
    before: '23:00:00'
  - service: tts.speak
    data:
      entity_id: media_player.master_bedroom_speaker
      cache: true
      message: >-
        {% if is_state('switch.madouce_matrasverwarmer', 'on') %} De matras was al aan. Was het nog niet warm genoeg?
        {% else %} De matras wordt ingeschakeld. Geniet van de warmte.
        {% endif %}
  mode: single

- alias: "dimmer nachtkastje Madouce: on/off = licht aan/uit"
  id: 'bc55baca-8fb9-4b7a-a61b-cb480c204800'
  description: ''
  trigger:
  - device_id: 3657c229241277d9a3b5e045468e0377
    domain: zha
    platform: device
    type: remote_button_short_release
    subtype: turn_on
  condition: []
  action:
  - service: light.toggle
    data: {}
    target:
      entity_id:
        - light.master_bedroom_staande_lamp
        - light.master_bedroom_play_madouce
        - light.master_bedroom_play_bart
  mode: single

- alias: "dimmer nachtkastje Madouce: off = licht uit"
  id: '2d90865a-3cd4-49f8-bea0-c9d6eb2576ca'
  description: ''
  trigger:
  - device_id: 3657c229241277d9a3b5e045468e0377
    domain: zha
    platform: device
    type: remote_button_short_release
    subtype: turn_off
  condition: []
  action:
    - service: button.press
      data: {}
      target:
        entity_id: button.pet_feeder_feed
    - wait_template: ""
      timeout: "00:00:05"
  mode: single

- alias: "dimmer nachtkastje Madouce: + = meer licht"
  id: '3ac60e51-7206-4cbc-9f62-5a3f2ba9c519'
  description: ''
  trigger:
  - device_id: 3657c229241277d9a3b5e045468e0377
    domain: zha
    platform: device
    type: remote_button_short_release
    subtype: dim_up
  condition: []
  action:
  - service: light.turn_on
    data:
      brightness_step_pct: 10
    target:
      entity_id:
        - light.master_bedroom_staande_lamp
        - light.master_bedroom_play_madouce
        - light.master_bedroom_play_bart
  mode: single

- alias: "dimmer nachtkastje Madouce: - = minder licht"
  id: '2702aa32-d53e-45cc-9b44-0c1590b6364b'
  description: ''
  trigger:
  - device_id: 3657c229241277d9a3b5e045468e0377
    domain: zha
    platform: device
    type: remote_button_short_release
    subtype: dim_down
  condition: []
  action:
  - service: light.turn_on
    data:
      brightness_step_pct: -10
    target:
      entity_id:
        - light.master_bedroom_staande_lamp
        - light.master_bedroom_play_madouce
        - light.master_bedroom_play_bart
  mode: single