automation:

- alias: "🚗 car 1 // 🔋 charge morning // start-bezig-stop"
  id: '5c0bb63f-49e0-4434-b189-35fd54466dc5'
  trigger:
  - platform: time_pattern
    minutes: /1
  condition:
  - condition: template
    value_template: "{{ as_timestamp(now().replace(hour=6, minute=30, second=0)) < as_timestamp(now()) < as_timestamp(states('sensor.sunrise'))   }}"
    # only if charger cable is connected to home charger or already charging
  - condition: template
    value_template: "{{ states('sensor.charger_status') in ['charging', 'connected'] }}"
  variables:
      wattage: >
        {% set maxpower = states('input_number.car_charge_peak_netwattage') | float(default=0) %}
        {% set net = states('sensor.net_power_avg') | float %}
        {% set charger = states('sensor.charger_current_power') | float(default=0) %}
        {{ (( maxpower - net + charger ) / 1000) | float }}
  action:
    - if:
        - condition: state
          entity_id: input_boolean.car_charge_morning_net
          state: 'on'
        - condition: template
          value_template: "{{ wattage > 1.3 }}"
        # - if:
        #     - condition: template
        #       value_template: "{{ states('sensor.car_1_soc') != unknown }}"
        #   then:
        #     - condition: or
        #       conditions:
        #         - condition: and
        #           conditions:
        #             - condition: state
        #               entity_id: input_select.car_1_charge_limit
        #               state: 'minimaal doel'
        #             - condition: template
        #               value_template: "{{ states('sensor.car_1_soc') < states('input_number.car_1_min_target_soc') }}"
        #         - condition: and
        #           conditions:
        #             - condition: state
        #               entity_id: input_select.car_1_charge_limit
        #               state: 'optimaal doel'
        #             - condition: template
        #               value_template: "{{ states('sensor.car_1_soc') < states('input_number.car_1_optimal_target_soc') }}"
        #   else: []         
      then:
        - service: input_boolean.turn_on
          data: {}
          target:
            entity_id: input_boolean.car_charge_morning_net_busy
        - service: input_number.set_value
          target:
            entity_id: input_number.car_charger_watt
          data:
            value: "{{ wattage }}"
        - wait_template: ''
          timeout: '00:00:05'
        - service: script.start_charger
      else:
        if:
          - condition: template
            value_template: "{{ states('sensor.charger_current_power') | float() > 0 }}"
        then:      
          - service: script.stop_charger
            data: {}
          - service: notify.bart_phone
            data:
              title: Auto is gestopt met laden. Nu 3 minuten wachten.
              message: >
                Gestopt
          - wait_template: ''
            timeout: '00:03:00'
  mode: single