automation:

- alias: Piekvermogen // Reset piek begin van de maand
  id: ccd59f5e-9000-4f33-b51f-29258d56e029
  description: ''
  trigger:
  # run at every 1st of the month
  - platform: template
    value_template: "{{ now().day == 1 }}"
  condition: []     
  action:
    - action: input_number.set_value
      target:
        entity_id: input_number.power_peak
      data:
        value: 0
  mode: single


- alias: Piekvermogen // nieuwe kwarierpiek = opslaan in huidige maand  
  id: 54fda862-be40-4823-a939-7fcc08cf7b08
  description: ''
  trigger:
    - platform: state
      entity_id: sensor.power_peak
  condition:
    - condition: template
      value_template: >
        {{  states('sensor.power_peak') | float(default=0)> states('input_number.power_peak') | float(default=0)}}
  variables:
    peak_month_id: >
      {% set m = now().month %}
      {% set p = 'input_number.power_peak_month_' ~ m %}
      {{ p }}
  action:
    - action: input_number.set_value
      target:
        entity_id: input_number.power_peak
      data:
          value: >
            {{ states('sensor.power_peak') | float(default=0)}}
    - action: input_number.set_value
      target:
        entity_id: "{{ peak_month_id }}"
      data:
        value: "{{ states('sensor.power_peak') }}"
    - action: input_datetime.set_datetime
      data_template:
        datetime: "{{ now().timestamp() | timestamp_local }}"
      target:
        entity_id: input_datetime.power_peak_date_time
    - if:
        - condition: template
          value_template: "{{ states('sensor.power_peak') | float(default=0) > states('input_number.power_peak') | float(default=0) + 0.25 }}"
      then:
        - action: notify.bart_phone
          data:
            title: Nieuwe kwartierpiek
            message: "Nieuwe maandelijkse piek is nu {{ states('sensor.power_peak') }} kW."
            data:
              tag: peak
              color: red        
  mode: parallel


- alias: Piekvermogen // hoog verbruik, mogelijk nieuwe piek
  id: '012e47ae-1b29-4ec4-ae3c-e7300018ad78'
  description: ""
  trigger:
  - platform: template
    value_template: >
      {{ states('sensor.net_power_avg_2min') | float() / 1000 > states('sensor.power_peak') | float() }}
    for: "00:05:00"  
  condition: []
  action:
  - action: notify.bart_phone
    data:
      title: Hoog verbruik. Mogelijk piek van {{ states('sensor.expected_power_peak') | round(2) }}.
      message: 
        Huidig verbruik is {{ (states('sensor.net_power_avg_2min') | float() / 1000) | round(2) }} kW.
        De verwachte kwartierpiek is {{ states('sensor.expected_power_peak') | round(2) }}. De huidige maandelijkse piek is {{ states('sensor.power_peak') | round(2) }} kW.
      data:
        tag: peak
        color: red
        notification_icon: mdi:transmission-tower-export 
  mode: single
