############################ Table of Contents ############################ 
# 
#   Automations
#     🎄 Kerstverlichting buiten aan bij donker
#     🎄 Kerstverlichting buiten aan tijdens week vanaf 7u15
#     🎄 Kerstverlichting buiten uit bij zonsopgang
#     🎄 Kerstverlichting buiten uit om 22u30 zo-do en 23u vrij-za (10 min. random)
#     🎄 Kerstboom binnen aan om 7u00 (weekdagen) (10 min. random)
#     🎄 Kerstboom binnen aan om 9u00 (weekend) (10 min. random)
#     🎄 Kerstboom binnen aan bij thuiskomst
#     🎄 Kerstboom binnen uit om 23u00 of bij niemand thuis (10 min. random)

automation:

##########################
# Kerstverlichting AAN
##########################

- alias: 🎄 kerst // verlichting buiten // zon onder = aan
  id: f37cac92-e0d6-4804-9554-ec59399e2d97
  description: ''
  trigger:
  - platform: sun
    event: sunset
    offset: '0'
  condition: []
  action:
  - service: switch.turn_on
    target:
      entity_id: switch.kerstverlichting
  - service: notify.bart_madouce_phone
    data:
      message: '{{ ["Joehoe, de kerstverlichting brandt weer!","Jingle bells. Laat de lichtjes maar branden!", "Merry Christmas with lots of love.", "Kerst is leuker met lichtjes.", "Wishing you a Christmas that is merry and bright!"] | random }}'
  # rode lamp living links 4 op kerstboom
  - service: light.turn_on
    target:
      entity_id:
        - light.living_links_4
      device_id: []
      area_id: []
    data:
      brightness: 31
      rgb_color:
        - 255
        - 67
        - 106      
  mode: single
  
- alias: 🎄 kerst // verlichting buiten // tijdens week vanaf 7u00 (10 min. random) = aan
  id: 006a516d-4cd0-4201-944c-0cf1b6ae3991
  description: ''
  trigger:
  - platform: time
    at: '07:00:00'
  condition:
  - condition: and
    conditions:
    - condition: time
      weekday:
      - mon
      - tue
      - wed
      - thu
      - fri
    - condition: state
      entity_id: input_boolean.vakantieperiode
      state: 'off'
  action:
  - delay:
      minutes: '{{ range(0,10) | random }}'  
  - service: switch.turn_on
    target:
      entity_id: switch.kerstverlichting
  mode: single

- alias: 🎄 kerst // verlichting buiten // beweging voordeur of oprit of openen voordeur = aan
  id: '03c6e49e-fca7-4bb5-b444-b149ef19e9bd'
  description: ''
  trigger:
  - platform: state
    entity_id: binary_sensor.voordeur_bewegingssensor_motion
    from: 'off'
    to: 'on'
  - platform: state
    entity_id: binary_sensor.oprit_bewegingssensor_motion
    from: 'off'
    to: 'on'
  - platform: state
    entity_id: binary_sensor.voordeur
    to: "on"    
  condition:
  - condition: state
    entity_id: switch.kerstverlichting
    state: 'off' 
  action:
  - service: switch.turn_on
    target:
      entity_id: switch.kerstverlichting
  - wait_template: ''
    timeout: 00:03:00 
  - service: switch.turn_off
    target:
      entity_id: switch.kerstverlichting
  mode: restart


##########################
# Kerstverlichting UIT
##########################

- alias: 🎄 kerst // verlichting buiten // zonsopgang = uit
  id: cea38af6-e8f7-4789-8ed4-86bb846f4aad
  description: ''
  trigger:
  - platform: state
    entity_id: sun.sun
    to: 'above_horizon'
  condition: []    
  action:
  - service: switch.turn_off
    target:
      entity_id: switch.kerstverlichting
  mode: single

- alias: 🎄 kerst // verlichting buiten // 22u30 zo-do en 23u vrij-za (10 min. random) = aan
  id: d771521b-4ba3-4c29-9032-52ec7162acf3
  description: ''
  trigger:
  - platform: time
    at:
    - '22:30'
    - '23:00'
  condition:
  - condition: template
    value_template: >
      {% set h = now().hour %}
      {% set wd = now().isoweekday() %}
      {{ (h == 22 and wd in [1, 2, 3, 4, 7]) or (h == 23 and wd in [5,6]) }}
  action:
  - delay:
      minutes: '{{ range(0,10) | random }}'   
  - service: switch.turn_off
    target:
      entity_id: switch.kerstverlichting
  - service: notify.bart_madouce_phone
    data:
      message: Wat jammer, de kerstverlichting is weer uit!
  mode: single


##########################
# Kerstboom AAN
##########################

- alias: 🎄 kerst // kerstboom // 7u00 (weekdagen) (10 min. random) = aan
  id: 287636ff-a630-4b04-97b7-7e3f17cf7966
  description: ''
  trigger:
  - platform: time
    at: '07:00:00'
  condition:
  - condition: and
    conditions:
    - condition: time
      weekday:
      - mon
      - tue
      - wed
      - thu
      - fri
    - condition: state
      entity_id: group.gezin
      state: "home"
  action:
  - delay:
      minutes: '{{ range(0,10) | random }}'  
  - service: switch.turn_on
    target:
      entity_id: switch.kerstboom
  - service: light.turn_on
    target:
      entity_id:
        - light.living_links_4
      device_id: []
      area_id: []
    data:
      brightness: 31
      rgb_color:
        - 255
        - 67
        - 106      
  mode: single

- alias: 🎄 kerst // kerstboom // om 9u00 (weekend) (10 min. random) = aan
  id: 005242bc-2f69-45b3-9170-49c08a58c3c5
  description: ''
  trigger:
  - platform: time
    at: '09:00:00'
  condition:
  - condition: and
    conditions:
    - condition: time
      weekday:
      - sat
      - sun
    - condition: state
      entity_id: group.gezin
      state: home
  action:
  - delay:
      minutes: '{{ range(0,10) | random }}'   
  - service: switch.turn_on
    target:
      entity_id: switch.kerstboom
  mode: single

- alias: 🎄 kerst // kerstboom // thuiskomst = aan
  id: '92d962fe-1066-49a6-ab20-dfd3c26a73e1'
  trigger:
  - platform: state
    entity_id: group.gezin
    to: 'home'
  condition: []
  action:
  - service: switch.turn_on
    target:
      entity_id: switch.kerstboom
  - service: light.turn_on
    target:
      entity_id:
        - light.living_links_4
      device_id: []
      area_id: []
    data:
      brightness: 31
      rgb_color:
        - 255
        - 67
        - 106        
  mode: single  


##########################
# Kerstboom UIT
##########################

- alias: 🎄 kerst // kerstboom // 23u00 of bij niemand thuis (10 min. random) = uit
  id: aa945472-94cf-4dde-9cad-40eb1bc81245
  description: ''
  trigger:
  - platform: time
    at: '23:00:00'
  - platform: state
    entity_id: group.gezin
    to: 'not_home'
  condition:
  - condition: and
    conditions:
    - condition: time
      weekday:
      - mon
      - tue
      - wed
      - thu
      - fri
      - sat
      - sun
  action:
  - delay:
      minutes: '{{ range(0,10) | random }}'  
  - service: switch.turn_off
    target:
      entity_id: switch.kerstboom
  mode: single
    

- alias: 🎄 kerst // kerstboom // spot aan met switch
  id: 'bb65a17b-c601-4ca1-8a83-a8267072d34a'
  trigger:
  - platform: state
    entity_id: input_boolean.christmas_tree_spot_switch
    to: "on"
  condition: []
  action:
    - service: light.turn_on
      data:
        transition: 3
        rgb_color: 
          - 255
          - 83
          - 231
        brightness_pct: 40
      target:
        entity_id:
          - light.living_links_4       
  mode: single

- alias: 🎄 kerst // kerstboom // spot uit met switch
  id: '4a571da0-5feb-4b45-bc89-97abd17367ac'
  trigger:
  - platform: state
    entity_id: input_boolean.christmas_tree_spot_switch
    to: "off"
  condition: []
  action:
    - service: light.turn_off
      data: {}
      target:
        entity_id:
          - light.living_links_4       
  mode: single  