############################ Table of Contents ############################ 
# 
#   Automations

automation:

- alias: ♨️ Amilya niet thuis = verwarming op automatisch
  id: 'ba1642db-f360-46ab-8c44-3fd16cc20751'
  description: ''
  trigger:
  - platform: state
    entity_id: device_tracker.amilya_iphone_xs
    to: 'not_home'
    for: 00:03:00
    from: 'home'
  condition: []
  action:
    service: climate.set_hvac_mode
    target:
      entity_id: climate.kamer_amilya
    data:
      hvac_mode: auto
  mode: single

- alias: ♨️ Alunya niet thuis = verwarming op automatisch
  id: '14de18f4-ecec-446f-baba-399c0eaf0d9f'
  description: ''
  trigger:
  - platform: state
    entity_id: device_tracker.alunya_samsung_galaxy_a71
    to: 'not_home'
    for: 00:03:00
  condition: []
  action:
    service: climate.set_hvac_mode
    target:
      entity_id: climate.kamer_alunya
    data:
      hvac_mode: auto
  mode: single


- alias: "♨️ >21 °C gevraagd in kamer Amilya = verwarming op automatisch"
  id: '95335e38-c593-48a6-b356-1be5f78db02c'
  description: ''
  trigger:
  - platform: numeric_state
    entity_id: climate.kamer_amilya
    attribute: temperature
    above: '21'
  condition: []
  action:
  - service: notify.bart_phone
    data:
      message: Kamer Amilya op {{state_attr('climate.kamer_amilya', 'temperature') }} gezet = herzet naar automatisch.
  - service: climate.set_hvac_mode
    target:
      entity_id: climate.kamer_amilya
    data:
      hvac_mode: auto      
  mode: single
  
- alias: "♨️ >20 °C gevraagd in kamer Amilya 's nachts = verwarming op automatisch"
  id: 'b5bc7134-9f34-455e-9f89-447ae445cce8'
  description: ''
  trigger:
  - platform: numeric_state
    entity_id: climate.kamer_amilya
    attribute: temperature
    above: '20'
  condition:
  - condition: time
    after: '23:00'
    before: '06:00'
  action:
  - service: notify.bart_phone
    data:
      message: Kamer Amilya op {{state_attr('climate.kamer_amilya', 'temperature') }} 's nachts gezet = herzet naar automatisch.  
  - service: climate.set_hvac_mode
    target:
      entity_id: climate.kamer_amilya
    data:
      hvac_mode: auto
  mode: single

- alias: "♨️ >20 °C gevraagd in kamer Amilya overdag = verwarming op 19"
  id: '434ae070-ac26-40a4-8700-7d5a86b7c2c9'
  description: ''
  trigger:
  - platform: numeric_state
    entity_id: climate.kamer_amilya
    attribute: temperature
    above: '20'
  condition:
  - condition: time
    after: '06:00'
    before: '23:00'
  action:
  - service: notify.bart_phone
    data:
      message: Kamer Amilya op {{state_attr('climate.kamer_amilya', 'temperature') }} gezet (overdag) = herzet naar 19°.
  - service: climate.set_temperature
    data:
      temperature: 19
    target:
      entity_id: climate.kamer_amilya
  mode: single

- alias: "♨️ >20 °C gevraagd in kamer Alunya overdag = verwarming op 19"
  id: 'aefc61ee-9acc-41c0-abd1-1cacc925262f'
  description: ''
  trigger:
  - platform: numeric_state
    entity_id: climate.kamer_alunya
    attribute: temperature
    above: '20'
  condition:
  - condition: time
    after: '06:00'
    before: '23:00'
  action:
  - service: notify.bart_phone
    data:
      message: Kamer Alunya op {{state_attr('climate.kamer_alunya', 'temperature') }} gezet (overdag) = herzet naar 19°.
  - service: climate.set_temperature
    data:
      temperature: 19
    target:
      entity_id: climate.kamer_alunya
  mode: single

- alias: "♨️ verwarming Alunya 's nachts op automatisch"
  id: '0c41db26-ed5a-46c8-b2f5-ba93514fb638'
  description: ''
  trigger:
  - minutes: /30
    platform: time_pattern
  condition:
  - condition: time
    after: '00:00'
    before: '06:00'
  - condition: state
    entity_id: climate.kamer_alunya
    state: "heat"
  action:
  - service: climate.set_hvac_mode
    target:
      entity_id: climate.kamer_alunya
    data:
      hvac_mode: auto
  mode: single
  
- alias: "♨️ verwarming Amilya 's nachts op automatisch"
  id: 'a9ed4d73-ab63-48f1-a05b-e252d9d60694'
  description: ''
  trigger:
  - minutes: /30
    platform: time_pattern
  condition:
  - condition: time
    after: '00:00'
    before: '06:00'
  - condition: state
    entity_id: climate.kamer_amilya
    state: "heat"
  action:
  - service: climate.set_hvac_mode
    target:
      entity_id: climate.kamer_amilya
    data:
      hvac_mode: auto
  mode: single

# - alias: verwarming badkamer aan + raam open = verwarming uit


- alias: ♨️ verwarming badkamer aan 10 minuten voor alarm Madouce (tussen 6 en 7)
  id: 'f41f7eb5-1432-4514-b8b5-83d53808a262'
  description: ''
  trigger:
  - platform: template
    value_template: >
      {{ as_timestamp(states('sensor.sm_g986b_next_alarm')) | int() ==
      as_timestamp(now() + timedelta(minutes=10)) | int() }}
  condition:
  - condition: template
    value_template: >
      {% set alarm = as_local(as_datetime(states('sensor.sm_g986b_next_alarm'))) %}
      {% set alarm_decimal = alarm.hour + (alarm.minute/100) %}
      {{ alarm_decimal }}
      {{ 5.3 <  alarm_decimal < 7 }}
  - condition: numeric_state
    entity_id: sensor.badkamer_temperature
    below: 17.5      
  action:
  - service: climate.set_temperature
    data:
      temperature: 18
    target:
      entity_id: climate.badkamer
  - delay:
      minutes: 25
  - service: climate.set_hvac_mode
    data:
      hvac_mode: auto
    target:
      entity_id: climate.badkamer
  mode: single



# berekening alarm naar decimaal getal (uur,minuten)
# {{ as_timestamp(states('sensor.sm_g986b_next_alarm')) | timestamp_custom('%H', true) | int + ((as_timestamp(states('sensor.sm_g986b_next_alarm')) | timestamp_custom('%M', true) | int) / 100 )}}


- alias: ♨️ badkamer // 18 graden gevraagd
  id: 'e46919a3-f143-48ac-b9cd-451664e2f1fd'
  description: ''
  trigger:
  - platform: state
    entity_id:
      - input_boolean.badkamer_18graden
    from: "off"
    to: "on"
  condition: []
  action:
    - if:
        - condition: template
          value_template: " {{ states('binary_sensor.badkamer_raam_kantel') == 'on' }}"
      then:
        - service: input_boolean.turn_off
          data: {}
          target:
            entity_id: input_boolean.badkamer_18graden      
        - if:
            - condition: template
              value_template: "{{trigger.to_state.context.user_id == '87d0c2e6c3d4403396d34b43046072ae'}}"
          then:
            - service: notify.bart_phone
              data:
                title: Verwarming badkamer
                message: "Het raam staat nog open: de verwarming is niet ingeschakeld."
        - if:
            - condition: template
              value_template: "{{trigger.to_state.context.user_id == '12bbc36927b7443c915b9492d89f6c24'}}"
          then:
            - service: notify.madouce_phone
              data:
                title: Verwarming badkamer
                message: "Het raam staat nog open: de verwarming is niet ingeschakeld."
        - if:
            - condition: template
              value_template: "{{trigger.to_state.context.user_id == '7678e64f5e984bc2aac5d1d92cc318eb'}}"
          then:
            - service: notify.amilya_phone
              data:
                title: Verwarming badkamer
                message: "Het raam staat nog open: de verwarming is niet ingeschakeld."
      else:
        - service: script.badkamer_chauffage_18_graden_30_min
          data: {}
  mode: restart


- alias: "♨️ badkamer // timer gestart = 18 graden"
  id: '8672a60f-20a5-4b28-8f77-614939b031b8'
  description: ""
  trigger:
    - platform: time
      at: input_datetime.badkamer_18graden_starttime
  condition: []
  action:
    - service: script.badkamer_chauffage_18_graden_30_min
      data: {}
  mode: single 