automation:

# INSCHAKELEN

- alias: 💧 humidity // master bedroom ontvochtiger // injectie, vocht in master bedroom = aan
  id: '76f7964b-8362-46e0-a11f-025fa4a4b684'
  description: ""
  trigger:
    - platform: numeric_state
      entity_id: sensor.net_power_avg_15min
      below: -250
  condition:
    - condition: numeric_state
      entity_id: sensor.master_bedroom_humidity
      above: 65
    - condition: template
      value_template: " {{ states('binary_sensor.master_bedroom_raam_wijd') != 'on' }}"
    # Als Bart of Madouce thuis is, tijdens de week na 9u en in het weekend na 10u
    - condition: template
      value_template: >-
        {{ (states('group.bart_madouce') == 'home') and
          ((now().weekday() in range(0, 5) and now().hour >= 9) or
            (now().weekday() in range(5, 7) and now().hour >= 10)) }}
  action:
    - service: switch.turn_on
      data: {}
      target:
        entity_id: switch.master_bedroom_dehumidifier_switch        
  mode: single

- alias: "💧 humidity // master bedroom ontvochtiger // aan = start timer"
  id: '8cba9ab1-f3d8-4d82-aaaf-41af932085d1'
  description: ''
  trigger:
    - platform: state
      entity_id: switch.master_bedroom_dehumidifier_switch
      to: 'on'
  condition: []
  action:
    - service: timer.start
      data:
        duration: "{{ states('input_number.master_bedroom_dehumidifier_timer_minutes') | float * 60 }}"   
      target:
        entity_id: timer.master_bedroom_dehumidifier_timer
  mode: single

- alias: "💧 humidity // master bedroom ontvochtiger // 20u30 & vocht = aan"
  id: '9309eba6-275f-4a93-953a-908b937358ec'
  description: ''
  trigger:
    - platform: time
      at: '20:30'
  condition:
    - condition: numeric_state
      entity_id: sensor.master_bedroom_humidity
      above: '70'
    - condition: state
      entity_id: input_boolean.heating_season
      state: "on"
    - condition: template
      value_template: " {{ states('binary_sensor.master_bedroom_raam_wijd') != 'on' }}"  
  action:
    - service: switch.turn_on
      data: {}
      target:
        entity_id: switch.master_bedroom_dehumidifier_switch
    - service: timer.start
      data:
        duration: "{{ states('input_number.master_bedroom_dehumidifier_timer_minutes') | float * 60 }}"   
      target:
        entity_id: timer.master_bedroom_dehumidifier_timer
    - service: notify.bart_phone
      data:
        title: Ontvochtiger in master bedroom ingeschakeld. 
        message: >
          Vocht is {{states('sensor.master_bedroom_humidity') | round() }}% en {{states('sensor.master_bedroom_thermal_absolute_humidity') | round(1)}} gram
          water /m³.
        data:
          notification_icon: "mdi:water-percent-alert"      
          color: "#0E86D4"
          tag: window_master_bedroom
          channel: Vocht
          actions:
          - action: URI
            title: Meer info
            uri: /lucht-vocht-temperatuur/vocht-gram
  mode: single


# UITSCHAKELEN

- alias: 💧 humidity // master bedroom ontvochtiger // timer komt op 0 of raam open of <65% vocht = uit
  id: 'af5b8e5a-9024-4e37-8289-5a15d6b7beed'
  description: ''
  trigger:
  - platform: state
    entity_id:
      - timer.master_bedroom_dehumidifier_timer
    from: active
    to: idle
  - platform: state
    entity_id: binary_sensor.master_bedroom_raam_kantel
    to: "on"
  - platform: numeric_state
    entity_id: sensor.master_bedroom_humidity
    below: 65
  condition: []
  action:  
    - service: switch.turn_off
      data: {}
      target:
        entity_id: switch.master_bedroom_dehumidifier_switch
    - service: timer.cancel
      data: {}
      target:
        entity_id: timer.master_bedroom_dehumidifier_timer           
  mode: single

- alias: 'zonne-energie // Netverbruik gem. 15 min. meer dan 200 W + master bedroom ontvochtiger aan = ontvochtiger uit'
  id: 'db375ea4-f052-4a61-80e1-fb7ba6d48500'
  description: ''
  trigger:
  - platform: time_pattern
    minutes: /15
  condition:
    - condition: template
      value_template: >
        {% set net = ( states('sensor.net_power_avg_15min') | float() * 0.4 ) + ( states('sensor.net_power_avg_5min') | float() * 0.6 ) %}
        {% set charger = ( states('sensor.charger_current_power_avg_15min') | float() * 0.4 ) + ( states('sensor.charger_current_power_avg_5min') | float() * 0.6 ) %}
        {{ (net - charger) | int() > 200 }}
    - condition: state
      entity_id: switch.master_bedroom_dehumidifier_switch
      state: 'on'      
  action:
  - service: notify.bart_phone
    metadata: {}
    data:
      title: Master bedroom ontvochtiger uitgeschakeld
      message: De laatste 15 min. was er geen 200 W injectie beschikbaar. ({{ states('sensor.net_power_avg_15min') | int() }} W)
  - service: switch.turn_off
    data: {}
    target:
      entity_id: switch.master_bedroom_dehumidifier_switch
  - service: timer.cancel
    data: {}
    target:
      entity_id: timer.master_bedroom_dehumidifier_timer
  mode: single