automation:

- alias: Mobile Vikings Anita onbeschikbaar = integratie herstarten
  # By reloading one of the entities, the whole integration is restarted
  id: 'fb821b76-e4be-424d-a6d6-dadabfd01de1'
  description: ""
  mode: single
  trigger:
    - platform: state
      entity_id: sensor.mobile_vikings_0456109679_product
      to: unavailable
    - platform: time_pattern
      minutes: /25   
  condition:
    - condition: state
      entity_id: sensor.mobile_vikings_0456109679_product
      state: unavailable
  action:
    - action: homeassistant.reload_config_entry
      target:
        entity_id: sensor.mobile_vikings_0456109679_product


- alias: Mobile Vikings Madouce onbeschikbaar = integratie herstarten
  # By reloading one of the entities, the whole integration is restarted
  id: 'e15cba56-35a8-45e3-97a4-2aeb25ef4572'
  description: ""
  mode: single
  trigger:
    - platform: state
      entity_id: sensor.mobile_vikings_332839874_loyalty_points_available
      to: unavailable
    - platform: time_pattern
      minutes: /30      
  condition:
    - condition: state
      entity_id: sensor.mobile_vikings_332839874_loyalty_points_available
      state: unavailable
  action:
    - action: homeassistant.reload_config_entry
      target:
        entity_id: sensor.mobile_vikings_332839874_loyalty_points_available

- alias: Mobile Vikings Anita // credit < 2€ = melding
  description: ""
  trigger:
    - platform: numeric_state
      entity_id:
        - sensor.mobile_vikings_0456109679_credit
      below: 8
    - platform: numeric_state
      entity_id:
        - sensor.mobile_vikings_0456109679_credit
      below: 7
    - platform: numeric_state
      entity_id:
        - sensor.mobile_vikings_0456109679_credit
      below: 6
    - platform: numeric_state
      entity_id:
        - sensor.mobile_vikings_0456109679_credit
      below: 5
    - platform: numeric_state
      entity_id:
        - sensor.mobile_vikings_0456109679_credit
      below: 4                          
    - platform: numeric_state
      entity_id:
        - sensor.mobile_vikings_0456109679_credit
      below: 3
    - platform: numeric_state
      entity_id:
        - sensor.mobile_vikings_0456109679_credit
      below: 2 
    - platform: numeric_state
      entity_id:
        - sensor.mobile_vikings_0456109679_credit
      below: 1      
  condition: []
  action:
  - action: notify.bart_phone
    data:
      title: Mobile Vikings krediet van mama is laag.
      message: >
        Er is nog {{ states('sensor.mobile_vikings_0456109679_credit')}} € krediet.
  mode: single
