automation:

- alias: 🐱 Katten eten geven
  id: 9c495009-925f-4d76-a6ee-6fd89d309cd5
  description: ""
  trigger:
    - platform: time
      at: 
        - "00:00:00"
        - "04:45:00"
        - "06:45:00"
        - "10:00:00"
        - "13:00:00"      
        - "17:30:00"
        - "19:00:00"
  condition: []
  action:
    - action: button.press
      data: {}
      target:
        entity_id: button.pet_feeder_feed
    - wait_template: ""
      timeout: "00:00:05"
  mode: single