automation:

- alias: het regent
  id: 'ecee1739-f190-4e55-812e-e89ab35c9634'
  description: ''
  trigger:
  - platform: numeric_state
    entity_id: sensor.eikenbos_rain_rate_piezo
    above: '0'
  condition: []
  action:
  - action: notify.bart_madouce_phone
    data:
      title: Regen
      message: Het regent. Zijn de ramen dicht?
      data:
        tag: regen
  mode: single

- alias: Het gaat regenen over 15 minuten (en raam nog open ?)
  id: '212d32e6-2fc1-4164-a8de-a4f1a06843dc'
  description: ''
  trigger:
  - platform: numeric_state
    entity_id: sensor.buienalarm_15min_precipitation_forecast_total
    above: '0'
  condition: []
  action:
  - action: notify.bart_madouce_phone
    data:
      message: Het gaat regenen over een {{ states('regenvoorspelling_min')}} minuten.
      data:
        tag: regen      
  mode: single

- alias: Regen en raam open = melding
  id: '01f65789-6050-44b5-93e2-1d8cf701b3ef'
  description: ''
  trigger:
  - platform: numeric_state
    entity_id: sensor.eikenbos_rain_rate_piezo
    above: '0'
  condition:
  - condition: state
    entity_id: binary_sensor.kamer_amilya_raam
    state: 'on'
  action:
  - action: notify.bart_madouce_phone
    data:
      message: Het regent en het raam van Amilya staat open.
      title: Het regent. Doe raam Amilya dicht aub.
      data:
        tag: regen_raam_amilya
        color: blue
        notification_icon: "mdi:weather-rainy"
  mode: single

- alias: Waarschuw voor regen
  description: ''
  id: 3efebc4c-b3ed-4ecd-8cb6-c964c9170b22
  trigger:
    - platform: state
      entity_id: sensor.buienalarm_15min_precipitation_forecast_level
  condition:
    - condition: template
      value_template: "{{ ('sensor.buienalarm_15min_precipitation_forecast_level') | float(default=0) > 1.5 }}"
    - condition: not
      conditions:
        - condition: or
          conditions:
            - condition: state
              entity_id: sensor.buienalarm_15min_precipitation_forecast_level
              state: "0"
            - condition: state
              entity_id: sensor.buienalarm_15min_precipitation_forecast_level
              state: unavailable
  action:
    - action: notify.bart_madouce_phone
      data:
        title: â˜”ï¸ Buienalarm
        message: >
          â˜”ï¸ {{ state_attr(trigger.entity_id,'label') }},
          ({{states('sensor.buienalarm_15min_precipitation_forecast_average')}}
          {{state_attr('sensor.buienalarm_15min_precipitation_forecast_average',
          'unit_of_measurement')}})  vlakbij huis. {{ [ "Vergeet je regenjas ðŸ§¥ niet mee te
          nemen!", "Neem een paraplu ðŸŒ‚ mee!", "Je bent âš ï¸ gewaarschuwd!", "Hou
          buienalarm ðŸŒ§ï¸ in de gaten!" ] | random  }} 
        data:
          url: >-
            https://www.buienalarm.nl/{{state_attr('zone.home', 'latitude')}},
            {{state_attr('zone.home', 'longitude')}}
  mode: single