############################ Table of Contents ############################ 
# 
#   Automations
#     🔐 security // om 20u30, 22u30, 23u00 en 24u00 doe voordeur op slot
#     🔐 security // Niemand meer thuis = doe voordeur op slot
#     🔐 security // kind(eren) alleen thuis = doe voordeur op slot
#     🔐 security // Bart alleen thuis = doe voordeur op slot
#     🔐 security // Madouce alleen thuis = doe voordeur op slot
#     🔐 security // Bart en Madouce op terras = voordeur op slot
#     🔐 security // voordeur lang open = melding
#     🔐 security // Niemand meer thuis en Bart in auto = check voordeur
#     🔐 security // Voordeur opengedaan met code
############################ Automations ################################## 

automation:

- alias: 🔐 security // om 20u30, 22u30, 23u00 en 24u00 doe voordeur op slot
  id: '35bab60f-cbaf-4969-839c-46a117a46e50'
  description: ""
  mode: single
  trigger:
    - platform: time
      at: 
        - "20:30:00"
        - "22:30:00"
        - "23:00:00"
        - "00:00:00"
        - "01:00:00"                 
  condition: []
  action:
    - service: lock.lock
      data: {}
      target:
        entity_id: lock.voordeur_nuki

- alias: 🔐 security // Niemand meer thuis = doe voordeur op slot
  id: '97b2e13f-ab8c-4346-983a-970cfacb4c4e'
  description: ''
  trigger:
  - platform: state
    entity_id: group.gezin
    to: not_home
  condition:
  - condition: state
    entity_id: lock.voordeur_nuki
    state: 'unlocked'
  action:
  - service: lock.lock
    target:
      entity_id: lock.voordeur_nuki
  - service: notify.bart_madouce_phone
    data:
      title: Voordeur 
      message: Niemand thuis. Gelukkig heb ik de voordeur voor jou op slot gedaan. 
      data:
        color: red
  mode: single


- alias: 🔐 security // kind(eren) alleen thuis = doe voordeur op slot
  id: '70541658-6b67-46f1-8e90-64a0600c646d'
  description: ''
  trigger:
  - platform: state
    entity_id: group.bart_madouce
    to: not_home
  - platform: time_pattern
    minutes: '/10'    
  condition:
  - condition: state
    entity_id: lock.voordeur_nuki
    state: 'unlocked'
  - condition: state
    entity_id: group.kinderen
    state: 'home'
  - condition: state
    entity_id: group.bart_madouce
    state: not_home    
  action:
  - service: lock.lock
    target:
      entity_id: lock.voordeur_nuki
  - service: notify.bart_madouce_phone
    data:
      title: Ik heb de voordeur voor jou op slot gedaan.
      message: >-
          {% if is_state('person.amilya', 'home') and is_state('person.alunya', 'home') %}Amilya en Alunya zijn alleen thuis.
          {% elif is_state('person.amilya', 'home') %}Amilya is alleen thuis.
          {% elif is_state('person.alunya', 'home') %}Alunya is alleen thuis.
          {% endif %}
      data:
        color: red
  mode: single
  
- alias: 🔐 security // Bart alleen thuis = doe voordeur op slot
  id: '77234403-213e-41a5-ad01-a159f3b0978c'
  description: ''
  trigger:
  - platform: state
    entity_id: group.alleen_bart
    to: not_home
  - platform: time_pattern
    minutes: '/10'    
  condition:
  - condition: state
    entity_id: lock.voordeur_nuki
    state: 'unlocked'
  - condition: state
    entity_id: group.alleen_bart
    state: not_home    
  action:
  - service: lock.lock
    target:
      entity_id: lock.voordeur_nuki
  - service: notify.bart_phone
    data:
      title: Ik heb de voordeur voor jou op slot gedaan.
      message: Bart, je bent alleen thuis.
      data:
        color: red
  mode: single

- alias: 🔐 security // Madouce alleen thuis = doe voordeur op slot
  id: 'eb26f9a9-6603-4ab5-a224-e845e45790fd'
  description: ''
  trigger:
  - platform: state
    entity_id: group.alleen_madouce
    to: not_home
  - platform: time_pattern
    minutes: '/10'    
  condition:
  - condition: state
    entity_id: lock.voordeur_nuki
    state: 'unlocked'
  - condition: state
    entity_id: group.alleen_madouce
    state: not_home    
  action:
  - service: lock.lock
    target:
      entity_id: lock.voordeur_nuki
  - service: notify.madouce_phone
    data:
      title: Ik heb de voordeur voor jou op slot gedaan.
      message: Madouce, je bent alleen thuis.
      data:
        color: red
  mode: single

- alias: 🔐 security // Bart en Madouce op terras = voordeur op slot
  id: 'b77f3de1-256a-41cb-8c90-44ae5667dc6e'
  description: ''
  trigger:
  - platform: template
    value_template: >
      {{ states('sensor.bart_phone_room') == "terras" and states('sensor.madouce_phone_room') == "terras" }}
  condition:
  - condition: state
    entity_id: lock.voordeur_nuki
    state: 'unlocked'
  action:
  - service: lock.lock
    target:
      entity_id: lock.voordeur_nuki
  - service: notify.bart_phone
    data:
      title: Ik heb de voordeur voor jou op slot gedaan.
      message: Bart, jij en Madouce zitten op het terras.
      data:
        color: red
  mode: single

- alias: 🔐 security // voordeur lang open = melding
  id: 'c1657da2-d8b2-4c18-a2c4-ae5c3c11b85e'
  description: ''
  trigger:
  - platform: state
    entity_id: binary_sensor.voordeur
    from: 'off'
    to: 'on'
    for: '00:03:00'
  condition: []
  action:
  - service: notify.bart_phone
    data:
      title: Voordeur staat al lang open! 
      message: "Staat al {{((as_timestamp(now()) - as_timestamp(states.binary_sensor.voordeur.last_changed)) / 60 )| int() }} minuten open."
      data:
        color: red
        tag: voordeur_staat_open
  - repeat:
      while:
      - condition: state
        entity_id: binary_sensor.voordeur
        state: 'on'
      sequence:
      - delay:
          minutes: 1
      - service: notify.bart_phone      
        data:
          title: Voordeur staat al lang open!
          message: >-
            Staat al {{ (((as_timestamp(now()) - as_timestamp(state_attr('automation.voordeur_staat_lang_open', 'last_triggered') )) / 60 )+ 3  ) | int() }} minuten open.
          data:
            color: red
            tag: voordeur_staat_open
            alert_once: true
  - service: notify.bart_phone
    data:
      title: "Voordeur is nu terug dicht."
      # + 3 = automation is triggered when the door is already 3 minutes open
      message: >-
        Stond {{ (((as_timestamp(now()) - as_timestamp(state_attr('automation.voordeur_staat_lang_open', 'last_triggered') )) / 60 ) + 3) | int() }} minuten open.
      data:
        tag: voordeur_staat_open
  mode: single

- alias: 🔐 security // Niemand meer thuis en Bart in auto = check voordeur
  id: '2a2c5a0a-36e5-45c8-bc20-a18d20fc4388'
  description: ''
  trigger:
  - platform: state
    entity_id: group.gezin
    to: not_home
  condition:
  - condition: state
    entity_id: lock.voordeur_nuki
    state: 'on'
  - condition: state
    entity_id: binary_sensor.bart_phone_connected_to_car_1
    state: 'on'    
  action:
  - service: notify.bart_phone
    data:
      message: TTS
      data:
        tts_text: De voordeur is niet op slot. Ik zal ze nu vergrendelen.
        color: red
        actions:
        - action: URI
          title: Meer info
          uri: /lovelace/alarm
        vibrationPattern: 10, 10, 10, 10, 10, 10, 10
        media_stream: alarm_stream_max
  - service: lock.lock
    target:
      entity_id: lock.voordeur_nuki
  mode: single


- alias: 🔐 security // Voordeur opengedaan met code
  id: 'c9ccdb95-0f71-4dfa-a91f-2c34de88df75'
  description: ''
  trigger:
  - platform: state
    entity_id:
    - sensor.voordeur_nuki_last_unlock_user
  condition: []
  action:
    - if: 
        - condition: template
          value_template: >
            {% set s = states('sensor.voordeur_nuki_last_unlock_user') %}
            {{ s !='Nuki Web ()' or s !='' or s !='Unknown'}}
      then:     
        - service: notify.bart_phone
          data:
            title: "Voordeur zopas open gedaan met numeriek pad."
            message: >
              {% set s = states('sensor.voordeur_nuki_last_unlock_user') | replace(' (Keypad)', '') %}
              Door {{ s }}.
  mode: single  