automation:

- alias: security // Niemand thuis of in auto = check open ramen
  id: '9c3567c0-ab6a-4ac9-83c9-82280a299e14'
  description: ''
  trigger:
  - platform: state
    entity_id: group.gezin
    to: not_home
  - platform: state
    entity_id: binary_sensor.bart_phone_connected_to_car_1
    to: 'on'
  - platform: state
    entity_id: binary_sensor.madouce_phone_connected_to_car_1
    to: 'on'
  - platform: state
    entity_id: binary_sensor.bart_phone_connected_to_car_2
    to: 'on'
  - platform: state
    entity_id: binary_sensor.madouce_phone_connected_to_car_2
    to: 'on'            
  condition:
  - condition: state
    entity_id: group.alle_ramen
    state: 'on'
  action:
  - if:
      - condition: template
        value_template: >
          {{ states('binary_sensor.bart_phone_connected_to_car_1') == on 
          or states('binary_sensor.bart_phone_connected_to_car_2') == on }}
    then:
      - action: notify.bart_phone
        data:
          message: TTS
          data:
            tts_text: >
              Er staan nog ramen open!
              {{expand(states.binary_sensor.kamer_alunya_schuifraam, states.binary_sensor.veranda_schuifraam, states.binary_sensor.badkamer_raam_wijd, states.binary_sensor.master_bedroom_raam_wijd) | selectattr('state','eq','on') | map(attribute='name') | list | join(', ') }}
            color: red
            clickAction: "/lovelace/security"
            vibrationPattern: 10, 10, 10, 10, 10, 10, 10
            media_stream: alarm_stream
  - if:
      - condition: template
        value_template: >
          {{ states('binary_sensor.madouce_phone_connected_to_car_1') == on 
          or states('binary_sensor.madouce_phone_connected_to_car_2') == on }}
    then:
      - action: notify.madouce_phone
        data:
          message: TTS
          data:
            tts_text: >
              Er staan nog ramen open!
              {{expand(states.binary_sensor.badkamer_raam_kantel, states.binary_sensor.badkamer_raam_wijd, states.binary_sensor.berging_raam, states.binary_sensor.kamer_alunya_raam, states.binary_sensor.kamer_amilya_raam, states.binary_sensor.kamer_alunya_schuifraam, states.binary_sensor.keuken_raam, states.binary_sensor.living_oprit_raam, states.binary_sensor.living_tuin_raam, states.binary_sensor.master_bedroom_raam_kantel, states.binary_sensor.master_bedroom_raam_wijd, states.binary_sensor.veranda_schuifraam) | selectattr('state','eq','on') | map(attribute='name') | list | join(', ') }}
            color: red
            clickAction: "/lovelace/security"
            vibrationPattern: 10, 10, 10, 10, 10, 10, 10
            media_stream: alarm_stream
  - if:
    - condition: state
      entity_id: group.gezin
      state: not_home
    then:
      - action: notify.bart_madouce_phone
        data:
          title: Niemand thuis en ramen open
          message: >
            Het volgende raam staat nog open:
            {{expand(states.binary_sensor.badkamer_raam_kantel, states.binary_sensor.badkamer_raam_wijd, states.binary_sensor.berging_raam, states.binary_sensor.kamer_alunya_raam, states.binary_sensor.kamer_amilya_raam, states.binary_sensor.kamer_alunya_schuifraam, states.binary_sensor.keuken_raam, states.binary_sensor.living_oprit_raam, states.binary_sensor.living_tuin_raam, states.binary_sensor.master_bedroom_raam_kantel, states.binary_sensor.master_bedroom_raam_wijd, states.binary_sensor.veranda_schuifraam) | selectattr('state','eq','on') | map(attribute='name') | list | join(', ') }}
          data:
            color: red
  mode: single 

