############################ Table of Contents ############################ 
# 
#   Automations
#   🚀 Pi CPU temp >79 °C = melding
#   🚀 Pi CPU > 50% = melding
#   🚀 system shutdown notification
#   🚀 system restart notification
#   🚀 Low battery level detection & notification for all battery sensors
#   🚀 Database cleanen
#   🚀 Google servers onbereikbaar = melding internetprobleem
#   🚀 Google servers terug bereikbaar = melding sturen
#   🚀 Home Assistant update notification
#   ⏱ toiletteller: beweging = + 1'
#   ⏱ toiletteller: reset om middernacht'
########################################################################### 


automation:

- alias: 🚀 system // Pi CPU temp >70 °C = melding
  id: '64c59baf-e8fb-4fc0-b789-cf74742e57e4'
  description: ''
  trigger:
  - platform: numeric_state
    entity_id: sensor.processor_temperature
    above: '70'
    for: 00:10
  condition: []
  action:
  - action: notify.bart_phone
    data:
      title: Raspberry Pi CPU
      message: CPU van Raspberry Pi werkt aan {{states('sensor.processor_use_percent')}}% en temperatuur is {{states('sensor.processor_temperature')}}°C.
      data:
        color: red
        clickAction: "/lovelace-systeem/1"
  mode: single
  
- alias: 🚀 system // Pi CPU > 50% = melding
  id: 'db887805-238d-4fe2-8512-e10b918eefe3'
  description: ''
  trigger:
  - platform: numeric_state
    entity_id: sensor.processor_use_percent
    above: '50'
    for: 00:15
  condition: []
  action:
  - action: notify.bart_phone
    data:
      title: Raspberry Pi CPU
      message: CPU van Raspberry Pi werkt aan {{states('sensor.processor_use_percent')}}% en temperatuur is {{states('sensor.processor_temperature')}}°C.
      data:
        color: red
        tag: raspberry_cpu
        clickAction: "/lovelace-systeem/1"
  - repeat:
      while:
      - condition: numeric_state
        entity_id: sensor.processor_use_percent
        above: '50'
      sequence:
      - action: notify.bart_phone
        data:
          title: Raspberry Pi CPU
          message: CPU van Raspberry Pi werkt aan {{states('sensor.processor_use_percent')}}% en temperatuur is {{states('sensor.processor_temperature')}}°C.
          data:
            color: red
            tag: raspberry_cpu
            clickAction: "/lovelace-systeem/1"
      - delay:
          hours: 0
          minutes: 15
          seconds: 0
          milliseconds: 0          
  - action: notify.bart_phone
    data:
      title: Raspberry Pi CPU terug normaal.
      message: CPU van Raspberry Pi werkt aan {{states('sensor.processor_use_percent')}}% en temperatuur is {{states('sensor.processor_temperature')}}°C.
      data:
        color: red
        tag: raspberry_cpu
        clickAction: "/lovelace-systeem/1"
  mode: single

- alias: 🚀 system // HA stopt
  id: 'f15aa89e-f40c-45ad-8c54-dfa8317a98d1'
  description: ''
  trigger:
  - platform: homeassistant
    event: shutdown
  action:
  - action: notify.bart_phone
    data:
      message: Home Assistant wordt gestopt.
  mode: single

- alias: 🚀 system // HA is herstart
  id: 'c7eacdc5-7bf3-4a6f-a4a4-03fb7e62262c'
  description: ''
  trigger:
  - platform: homeassistant
    event: start
  condition: []
  action:
  - action: notify.bart_phone
    data:
      message: Home Assistant is volledig gestart.
  mode: single


- alias: 🚀 system // HA update beschikbaar
  id: 'caa45056-75d6-4e17-9620-00e3dda60170'
  description: ""
  trigger:
    - platform: state
      entity_id:
        - binary_sensor.home_assistant_website_update_available
      to: "on"
  condition: []
  action:
    - action: notify.bart_phone
      data:
        title: Home Assistant update beschikbaar.
        message: "Versie {{ states('sensor.home_assistant_website') }} is nu beschikbaar."
  mode: single

- alias: 🚀 system // Melding lage batterij voor alle batterijsensoren
  id: '9e972067-200b-4b7c-9a33-4a1d79543085'
  description: ''
  use_blueprint:
    path: sbyx/low-battery-level-detection-notification-for-all-battery-sensors.yaml
    input:
      threshold: 10
      actions:
      - device_id: b5d28be91fff8c03aece377f73b28dd2
        domain: mobile_app
        type: notify
        title: Batterijen
        message: Batterijen laag van {{sensors}}
      day: 6
      time: '12:00:00'
  mode: single

- alias: 🚀 system // Database cleanen
  id: '9bda21a0-65f4-4c33-8c17-e12f4331522b'
  description: ''
  trigger:
  - platform: time
    at: 04:00
  condition: []
  action:
  - action: recorder.purge
    data:
      keep_days: 7
      repack: true  # if you do not repack, the database size will not reduce
  mode: single

- alias: 🚀 system // Google servers onbereikbaar = melding internetprobleem
  id: 'ba3fab2f-867f-4e94-a699-9580bacd8f27'
  description: ''
  trigger:
  - platform: state
    entity_id: binary_sensor.google_server
    from: 'on'
    to: 'off'
    for: "00:01:00"
  condition: []
  action:
  - action: notify.bart_phone
    data:
      title: Probleem met internettoegang thuis.
      message: Google servers konden niet worden bereikt.
      data:
        color: red
        actions:
        - action: reboot_wifi
          title: herstart wifi
  mode: single

# - alias: system // wifi herstarten
#   id: 'c2176a54-1f37-4923-b61e-9bbe33d093dc'
#   trigger:
#   - platform: event
#     event_type: mobile_app_notification_action
#     event_data:
#       action: reboot_wifi
#   action:
#   - action: notify.bart_phone
#     data:
#       title: Wifi router wordt nu opnieuw gestart.
#       message: Het wifi-netwerk zal enkele minuten onbereikbaar zijn.  
#   - action: googlewifi.reset
#     data:
#       entity_id: binary_sensor.wifi_access_point
#   mode: single

- alias: 🚀 system // Google servers terug bereikbaar = melding sturen
  id: '0f7ada67-01bc-4603-8da3-124b26cf1e24'
  description: ''
  trigger:
  - platform: state
    entity_id: binary_sensor.google_server
    from: 'off'
    to: 'on'
  condition: []
  action:
  - action: notify.bart_phone
    data:
      title: Internettoegang thuis opnieuw OK.
      message: Google servers konden opnieuw worden bereikt.
  mode: single

- alias: 🚀 system // Nieuwe versie Home Assistant beschikbaar
  id: '3a8a47a3-6df3-4ffa-a2f3-71db3ce80938'
  description: ''
  trigger:
  - platform: state
    entity_id: binary_sensor.home_assistant_website_update_available
    to: 'on'
  condition: []
  action:
  - action: notify.bart_phone
    data:
      title: Er is een update van Home Assistant beschikbaar.
      message: >
        Nieuwe versie beschikbaar sinds {{state_attr('sensor.home_assistant_website', 'release_date').split('T')[0] }}.<br>
        Versie: {{states('sensor.home_assistant_website')}}
        Info: {{state_attr('sensor.home_assistant_website','release_notes')}}
  mode: single

- alias: system // switch ventilator niet beschikbaar
  id: 'ffae2d1a-cdf6-4dae-8227-eeb699e6ecf0'
  description: ''
  trigger:
  - platform: state
    entity_id: switch.toilet_douche_ventilatie
    to: 'unavailable'
    for: '00:15:00'
  condition: []
  action:
  - action: notify.bart_phone
    data:
      title: Switch van ventilator onbereikbaar.
      message: "Herstart switch op zolder."
  mode: single    

- alias: "AutoBackup: Daily backup"
  id: 8100fbe8-340c-418f-b4ec-756c03a5fc84
  trigger:
    platform: time
    at: "03:15:00"
  condition: []
  action:
    action: auto_backup.backup_full
    data:
      name: "DailyBackup: {{ now().strftime('%A, %B %-d, %Y') }}"
      keep_days: 7

- alias: battery // batterij voordeur laag
  id: '2f17182f-dbe0-424f-b1a8-c396f4cf4ab6'
  description: ''
  trigger:
  - platform: time
    at: "19:30:00"
  - platform: numeric_state
    entity_id: sensor.voordeur_nuki_battery
    below: '20'
  condition:
  - condition: numeric_state
    entity_id: sensor.voordeur_nuki_battery
    below: '20'  
  action:
  - action: notify.bart_phone
    data:
      title: Batterij voordeur laag
      message: Batterijniveau is maar {{states('sensor.voordeur_nuki_battery')}}%.
      data:
        color: red
  mode: single