############################ Table of Contents ############################ 
# 
########################################################################### 

automation:

- alias: Om 11 uur bepaal max dagtemperatuur uur
  id: 'ed9969de-ed32-4d1d-94ed-48e3622c94b4'
  description: ''
  trigger:
  - platform: time
    at: '11:00'
  condition: []
  action:
  - service: input_datetime.set_datetime
    target:
      entity_id: input_datetime.max_dagtemperatuur_uur
    data:
      time: "{{ states('sensor.day_max_temp_datetime') }}"
  mode: single
  
- alias: max temperatuur van de dag bereikt = melding
  id: '91ed3a1c-ce13-47db-a612-4dc6d912fb89'
  description: ''
  trigger:
  - platform: time
    at: input_datetime.max_dagtemperatuur_uur
  condition: []
  action:
  - service: notify.bart_phone
    data:
      title: Nu is het warmste moment van de dag.
      message: Buiten is het nu {{ states('sensor.eikenbos_temperature')}}°C.
  mode: single

- alias: te warm in kamer Amilya - open raam (Bart)
  id: 'ae5bbb04-af4b-42e2-ba7a-5d57a411c6bc'
  description: ''
  trigger:
  - platform: time_pattern
    hours: /1
  condition:
  - condition: state
    entity_id: binary_sensor.kamer_amilya_raam
    state: 'off'
  - condition: template
    value_template: "{{ states('sensor.kamer_amilya_temperature') | float > 23 }}"
  - condition: template
    value_template: "{{ states('sensor.kamer_amilya_temperature') > states('sensor.eikenbos_temperature') }}"
  - condition: zone
    entity_id: person.bart
    zone: zone.home
  - condition: time
    after: '07:00'
    before: '23:00'
  action:
  - service: notify.bart_phone
    data:
      message: "Temperatuur in kamer Amilya is {{states('sensor.kamer_amilya_temperature')}}°C. Buiten {{states('sensor.eikenbos_temperature')}}°C."
      title: Open het raam van Amilya!
      data:
        color: blue
        channel: Temperatuur
        timeout: 3600
        tag: temp_amilya
        clickAction: "/lovelace/temp_detail"
  mode: single
  
- alias: te warm in kamer Amilya - open raam (Madouce)
  id: '5f334c36-306e-4ab5-84c3-ba771b739748'
  description: ''
  trigger:
  - platform: time_pattern
    hours: /1
  condition:
  - condition: state
    entity_id: binary_sensor.kamer_amilya_raam
    state: 'off'
  - condition: template
    value_template: "{{ states('sensor.kamer_amilya_temperature') | float > 23 }}"
  - condition: template
    value_template: "{{ states('sensor.kamer_amilya_temperature') > states('sensor.eikenbos_temperature') }}"
  - condition: zone
    entity_id: person.madouce
    zone: zone.home
  - condition: time
    after: '07:00:00'
    before: '23:00:00'
  action:
  - service: notify.madouce_phone
    data:
      message: "Temperatuur in kamer Amilya is {{states('sensor.kamer_amilya_temperature')}}°C. Buiten {{states('sensor.eikenbos_temperature')}}°C."
      title: Open het raam van Amilya!
      data:
        color: blue
        channel: Temperatuur
        timeout: 3600
        tag: temp_amilya
        clickAction: "/lovelace/temp_detail"
  mode: single

- alias: temperatuur in huis stijgt snel = melding
  id: '8d121e36-fd46-4a2e-b6ad-e6d15442f352'
  description: ''
  trigger:
    - platform: state
      entity_id:
        - group.home_temp_rising
      to: 'on'
  condition: []
  action:
    - service: notify.bart_madouce_phone
      data:
        title: Temperatuur in huis begint snel te stijgen.
        message: >
          Temperatuur stijgt in: {{expand(states.group.home_temp_rising) |
          selectattr('state','eq','on') | map(attribute='name') | list | join(',
          ') }}<br> {% if is_state('group.alle_raam_sensoren', 'off') %} Gelukkig
          zijn alle ramen dicht! {% else %}
          {{expand(states.group.alle_raam_sensoren) |selectattr('state','eq','on')
          | list | length }} open ramen: 
          {{expand(states.group.alle_raam_sensoren) |
          selectattr('state','eq','on') | map(attribute='name') | list | join(',
          ') }} {% endif %}
        data:
          color: red
          notification_icon: "mdi:window-closed-variant"       
  mode: single

- alias: buiten kouder geworden dan in living = melding
  id: '5ab391c1-772d-44c0-adeb-cbf62f1cbf20'
  description: ''
  trigger:
  - platform: template
    value_template: >
      {% set outdoor = states('sensor.eikenbos_temperature') | float %}
      {% set indoor =  states('sensor.living_temperature') | float %}
      {% if outdoor < indoor %} true
      {% endif %}
  condition:
  - condition: state
    entity_id: group.living_ramen
    state: "off"
  - condition: state
    entity_id: input_boolean.cooling_season
    state: "on"
  action:
  - service: input_boolean.turn_on
    target:
      entity_id: input_boolean.living_raam_moet_open
  - service: input_boolean.turn_off
    target:
      entity_id: input_boolean.living_raam_moet_dicht
  - service: notify.bart_madouce_phone
    data:
      title: Ramen in living mogen open
      message: Buiten wordt het nu koeler ({{outdoor}}°C) dan binnen ({{indoor}}°C).
      data:
        color: green
        channel: ramen
        timeout: 3600
        tag: window_living
        notification_icon: "mdi:window-closed-variant"
  variables:
    outdoor: "{{ states('sensor.eikenbos_temperature') | round(1) }}"
    indoor: "{{ states('sensor.living_temperature')| round(1) }}"         

- alias: buiten kouder geworden dan in veranda = melding
  id: 'bdb9a781-02a1-429a-a4dd-d9bdcdd79807'
  description: ''
  trigger:
  - platform: template
    value_template: >
      {% set outdoor = states('sensor.eikenbos_temperature') |float %}
      {% set indoor =  states('sensor.veranda_temperature') |float %}
      {{ outdoor < indoor }}
  condition:
  - condition: state
    entity_id: binary_sensor.veranda_schuifraam
    state: "off"
  - condition: state
    entity_id: input_boolean.cooling_season
    state: "on"    
  action:
    - service: input_boolean.turn_on
      target:
        entity_id: input_boolean.veranda_schuifraam_moet_open
    - service: input_boolean.turn_off
      target:
        entity_id: input_boolean.veranda_schuifraam_moet_dicht
    - service: notify.bart_madouce_phone
      data:
        title: Raam in veranda mag open
        message: Buiten wordt het nu koeler ({{outdoor}}°C) dan binnen ({{indoor}}°C).
        data:
          color: green
          channel: ramen
          timeout: 3600
          tag: window_veranda 
          notification_icon: "mdi:window-closed-variant"      
  variables:
    outdoor: "{{ states('sensor.eikenbos_temperature') | round(1) }}"
    indoor: "{{ states('sensor.veranda_temperature') | round(1) }}"           

- alias: buiten kouder geworden dan in kamer Amilya = melding
  id: 'ab17e743-817e-4649-a2a4-d222131f0f44'
  description: ''
  trigger:
  - platform: template
    value_template: >
      {% set outdoor = states('sensor.eikenbos_temperature') |float %}
      {% set indoor =  states('sensor.kamer_amilya_temperature') |float %}
      {{ outdoor < indoor }}
  condition:
  - condition: state
    entity_id: binary_sensor.kamer_amilya_raam
    state: "off"
  - condition: state
    entity_id: input_boolean.cooling_season
    state: "on"    
  action:
    - service: input_boolean.turn_on
      target:
        entity_id: input_boolean.kamer_amilya_raam_moet_open
    - service: input_boolean.turn_off
      target:
        entity_id: input_boolean.kamer_amilya_raam_moet_dicht
    - service: notify.bart_madouce_phone
      data:
        title: Raam Amilya mag open
        message: Buiten wordt het nu koeler ({{outdoor}}°C) dan binnen ({{indoor}}°C).
        data:
          color: green
          channel: ramen
          timeout: 3600
          tag: window_amilya
          notification_icon: "mdi:window-closed-variant"                 
  variables:
    outdoor: "{{ states('sensor.eikenbos_temperature') | round(1) }}"
    indoor: "{{ states('sensor.kamer_amilya_temperature') | round(1) }}"           

- alias: buiten kouder geworden dan in kamer Alunya = melding
  id: '6ac20eb1-35ef-4811-8396-84f98646f425'
  description: ''
  trigger:
  - platform: template
    value_template: >
      {% set outdoor = states('sensor.eikenbos_temperature') |float %}
      {% set indoor =  states('sensor.kamer_alunya_temperature') |float %}
      {{ outdoor < indoor }}
  condition:
  - condition: state
    entity_id: group.kamer_alunya_ramen
    state: "off"
  - condition: state
    entity_id: input_boolean.cooling_season
    state: "on"    
  action:
    - service: input_boolean.turn_on
      target:
        entity_id: input_boolean.kamer_alunya_raam_moet_open
    - service: input_boolean.turn_off
      target:
        entity_id: input_boolean.kamer_alunya_raam_moet_dicht
    - service: notify.bart_madouce_phone
      data:
        title: Raam Alunya mag open
        message: Buiten wordt het nu koeler ({{outdoor}}°C) dan binnen ({{indoor}}°C).
        data:
          color: green
          channel: ramen
          timeout: 3600
          tag: window_alunya
          notification_icon: "mdi:window-closed-variant"               
  variables:
    outdoor: "{{ states('sensor.eikenbos_temperature') | round(1) }}"
    indoor: "{{ states('sensor.kamer_alunya_temperature') | round(1) }}"          

- alias: buiten kouder geworden dan in master bedroom = melding
  id: '695898c2-c66e-4d93-9598-ff3337f00e05'
  description: ''
  trigger:
  - platform: template
    value_template: >
      {% set outdoor = states('sensor.eikenbos_temperature') |float %}
      {% set indoor =  states('sensor.master_bedroom_temperature') |float %}
      {{ outdoor < indoor }}
  condition:
  - condition: state
    entity_id: binary_sensor.master_bedroom_raam_kantel
    state: "off"
  - condition: state
    entity_id: input_boolean.cooling_season
    state: "on"    
  action:
    - service: input_boolean.turn_on
      target:
        entity_id: input_boolean.master_bedroom_raam_moet_open
    - service: input_boolean.turn_off
      target:
        entity_id: input_boolean.master_bedroom_raam_moet_dicht
    - service: notify.bart_madouce_phone
      data:
        title: Raam in master bedroom mag open
        message: Buiten wordt het nu koeler ({{outdoor}}°C) dan binnen ({{indoor}}°C).
        data:
          color: green
          channel: ramen
          timeout: 3600
          tag: window_master_bedroom
          notification_icon: "mdi:window-closed-variant"             
  variables:
    outdoor: "{{ states('sensor.eikenbos_temperature') | round(1) }}"
    indoor: "{{ states('sensor.master_bedroom_temperature') | round(1) }}"