automation:

- alias: Alarm // waterlek in kelder
  id: d5a9717b-4c5b-49bd-b71c-921515acee93
  description: ""
  trigger:
    - platform: state
      entity_id:
        - binary_sensor.kelder_waterdetector_vocht
        - binary_sensor.wasmachine_waterdetector_vocht
      to: "on"
  condition: []
  variables:
      locatie: >
        {% if trigger.entity_id =='binary_sensor.kelder_waterdetector_vocht' %}afvoerputje kelder
        {% elif trigger.entity_id =='binary_sensor.wasmachine_waterdetector_vocht' %}wasmachine
        {% endif %}
  action:
    - action: notify.bart_phone
      data:
        message: TTS
        data:
          channel: "alarm_stream"
          tts_text: "Waterlek in Eikenboslaan!"
          ttl: 0
          priority: high
          media_stream: alarm_stream
    - action: notify.bart_phone
      data:
        title: '🚨 Alarm!'
        message: 'Waterlek gedetecteerd aan {{ locatie }}.'
        data:
          notification_icon: mdi:pipe-leak      
          color: red
          sticky: true
          channel: alarm
          clickAction: "/lovelace/security"
          vibrationPattern: 10, 10, 10, 10, 10, 10, 10
  mode: single
