automation:

- alias: 'Waarschoot: alarm wordt ingeschakeld via knop living'
  id: 'f6c83f1d-0413-4e19-bfd7-651f74737fc7'
  description: ''
  trigger:
  - platform: state
    entity_id:
    - switch.waarschoot_living_alarmknop
    to: 'on'
  condition:
  - condition: state
    entity_id: switch.waarschoot_boven_alarmknop
    state: 'off'
  action:
  - action: notify.bart_phone
    data:
      title: "Waarschoot: alarm wordt ingeschakeld."
      message: Via de knop in de living
  mode: single

- alias: 'Waarschoot: alarm wordt ingeschakeld via knop badkamer'
  id: '1851d4c4-690a-4c76-adb3-7bf46201dcb8'
  description: ''
  trigger:
  - platform: state
    entity_id:
    - switch.waarschoot_boven_alarmknop
    to: 'on'
  condition:
  - condition: state
    entity_id: switch.waarschoot_living_alarmknop
    state: 'off'  
  action:
  - action: notify.bart_phone
    data:
      title: "Waarschoot: alarm wordt ingeschakeld."
      message: Via de knop in de badkamer
  mode: single

  
- alias: 'Waarschoot: alarm wordt uitgeschakeld (knop beneden) tijdens vakantiemodus'
  id: 'd4775c3a-8c66-4414-b317-dcb7cfa5a745'
  description: ''
  trigger:
  - platform: state
    entity_id:
    - switch.waarschoot_living_alarmknop
    to: 'off'
  condition:
  - condition: state
    entity_id: input_boolean.waarschoot_holiday_modus
    state: 'on'
  action:
  - action: notify.bart_phone
    data:
      title: "Waarschoot: Alarm wordt voor 1 uur uitgeschakeld."
      message: Huis is in "vakantiemodus".
  - delay:
      hours: 1
      minutes: 0
      seconds: 0
      milliseconds: 0
  - action: switch.turn_on
    data: {}
    target:
      entity_id: switch.waarschoot_living_alarmknop
  - action: notify.bart_phone
    data:
      title: "Waarschoot: Alarm wordt opnieuw ingeschakeld."
      message: Huis is in "vakantiemodus".
  mode: single


- alias: "Waarschoot: verlaten huis = chauffage uit & alarm aan"
  id: '2482386b-5259-4fca-8065-224e32fbf5f0'
  description: ""
  trigger:
    - platform: state
      entity_id:
        - person.anita
      from: Waarschoot
      for:
        hours: 0
        minutes: 1
        seconds: 0
  condition: []
  action:
    - action: climate.set_preset_mode
      data:
        preset_mode: away
      target:
        entity_id:
          - climate.waarschoot_keuken
          - climate.waarschoot_living
          - climate.waarschoot_zitput
          - climate.waarschoot_overloop
          - climate.waarschoot_badkamer
          - climate.waarschoot_slaapkamer
    - action: climate.set_hvac_mode
      data:
        hvac_mode: "off"
      target:
        entity_id:
          - climate.waarschoot_keuken
          - climate.waarschoot_living
          - climate.waarschoot_zitput
          - climate.waarschoot_overloop
          - climate.waarschoot_badkamer
          - climate.waarschoot_slaapkamer
    - action: switch.turn_on
      data: {}
      target:
        entity_id:
          - switch.waarschoot_living_alarmknop
          - switch.waarschoot_living_camera
    - action: notify.anita_phone
      data:
        title: Verwarming uit en alarm aan
        message: >
          De verwarming wordt uitgeschakeld door het verlaten van het huis. Het is
          nu nog {{ states('sensor.waarschoot_living_temperature') }} graden in de
          living.
    - action: notify.bart_phone
      data:
        title: "Waarschoot verlaten: Verwarming uit en alarm aan"
        message: >
          De verwarming wordt uitgeschakeld door het verlaten van het huis.<br>
          Het is nu nog {{ states('sensor.waarschoot_living_temperature') | round(1) }}°C in de living en {{
          states('sensor.waarschoot_keuken_temperature') | round(1) }}°C in de keuken.
    - action: notify.anita_phone
      data:
        message: TTS
        data:
          tts_text: >-
            Dag Anita. De verwarming wordt uitgeschakeld en het alarm wordt
            ingeschakeld.
          ttl: 0
          priority: high
          media_stream: alarm_stream_max
  mode: single

- alias: "Waarschoot: aankomst thuis = verwarming op automatisch en alarm uit"
  id: '4ded95e3-6118-4890-8827-ca8800e43d3d'
  description: ""
  trigger:
    - platform: state
      entity_id:
        - person.anita
      for:
        hours: 0
        minutes: 0
        seconds: 20
      to: Waarschoot
  condition: []
  action:
    - action: climate.set_preset_mode
      data:
        preset_mode: home
      target:
        entity_id:
          - climate.waarschoot_keuken
          - climate.waarschoot_living
          - climate.waarschoot_zitput
          - climate.waarschoot_overloop
          - climate.waarschoot_badkamer
          - climate.waarschoot_slaapkamer
    - action: climate.set_hvac_mode
      data:
        hvac_mode: auto
      target:
        entity_id:
          - climate.waarschoot_keuken
          - climate.waarschoot_living
          - climate.waarschoot_zitput
          - climate.waarschoot_overloop
          - climate.waarschoot_badkamer
          - climate.waarschoot_slaapkamer
    - action: switch.turn_off
      data: {}
      target:
        entity_id:
          - switch.waarschoot_living_alarmknop
          - switch.waarschoot_living_camera
    - action: notify.anita_phone
      data:
        title: Verwarming aan (volgens schema)
        message: >
          De verwarming wordt ingeschakeld bij aankomst thuis.<br>
          Het is nu nog {{ states('sensor.waarschoot_living_temperature') | round(1) }}°C in de living en {{
          states('sensor.waarschoot_keuken_temperature') | round(1) }}°C in de keuken.
    - action: notify.bart_phone
      data:
        title: "Waarschoot thuiskomst: Verwarming aan (volgens schema)"
        message: >
          De verwarming wordt ingeschakeld bij aankomst thuis. Het is nu nog {{
          states('sensor.waarschoot_living_temperature') | round(1) }}°C in de living en {{
          states('sensor.waarschoot_keuken_temperature') | round(1) }}°C in de keuken.
    - action: notify.anita_phone
      data:
        message: TTS
        data:
          tts_text: Dag Anita. Welkom thuis. De verwarming wordt ingeschakeld.
          ttl: 0
          priority: high
          media_stream: alarm_stream_max
  mode: single  