automation:

- alias: "At 23:00 transfer forecast minimum and max temperature to today sensor"
  id: '39c677d6-5f19-4dbe-93cd-40c21cbf893b'
  description: ""
  trigger:
  - platform: time
    at: '23:00'
  condition: []
  action:
    - action: input_number.set_value
      data_template:
        value: >
          {{ states('sensor.weather_eikenbos_min_temp_tomorrow') | float() }}
      target:
        entity_id: input_number.weather_eikenbos_min_temp_today
    - action: input_number.set_value
      data_template:
        value: >
          {{ states('sensor.weather_eikenbos_max_temp_tomorrow') | float() }}
      target:
        entity_id: input_number.weather_eikenbos_max_temp_today        
  mode: single

- alias: "At 7:00 update OpenWeather forecast for Eikenbos"
  id: 'fa7bbf42-475c-4f40-8e5c-4cf05c273120'
  description: ""
  trigger:
  - platform: time
    at: '07:00'
  condition: []
  action:
    - action: weather.get_forecasts
      target:
        entity_id:
          - weather.eikenbos_openweather
      data:
        type: hourly
      response_variable: weather_forecast
  mode: single

- alias: "At 7:15 on workdays announce slipperiness risk"
  id: 'e471c3a2-5061-486c-a50c-9fc240e46367'
  description: ""
  trigger:
  - platform: time
    at: '07:10'
  condition:
    - condition: state
      entity_id: binary_sensor.workday_sensor
      state: "on"
    - condition: numeric_state
      entity_id: sensor.eikenbos_temperature
      below: 4
    - condition: numeric_state
      entity_id: sensor.eikenbos_humidity
      below: 70
  action:
  - action: media_player.volume_set
    data:
      entity_id: media_player.living_speaker
      volume_level: 0.5      
  - action: tts.edge_tts_say
    data:
      entity_id: media_player.living_speaker
      message: >
        Opgelet: het kan buiten glad zijn. Het is {{ states('sensor.eikenbos_temperature') | round() }} graden.
  - delay: '00:00:10'
  - action: media_player.volume_set
    data:
      entity_id: media_player.living_speaker
      volume_level: 0.4
  mode: single
