############################ Table of Contents ############################ 
#
#  Actions to pause window notifications
#
#   living_window_pause
#   kamer_amilya_window_pause
#   veranda_window_pause
#   badkamer_window_pause
#   berging_window_pause
#   kamer_alunya_window_pause
#   master_bedroom_window_pause
#
#
#   zet pauze toggle living naar OFF na 2 uren
#   zet pauze toggle kamer Amilya naar OFF na 2 uren
#   zet pauze toggle veranda naar OFF na 2 uren
#   zet pauze toggle berging naar OFF na 2 uren
#   zet pauze toggle badkamer naar OFF na 2 uren
#   zet pauze toggle kamer Alunya naar OFF na 2 uren
#   zet pauze toggle master bedroom naar OFF na 2 uren
#
###########################################################################

automation:

- alias: "living_window_pause"
  id: '9c9dc01b-190a-43f3-9936-12bca9a1d46c'
  trigger:
  - platform: event
    event_type: mobile_app_notification_action
    event_data:
      action: living_window_pause
  action:
  - action: input_boolean.turn_on
    target:
      entity_id: input_boolean.living_window_pause  

- alias: "kamer_amilya_window_pause"
  id: '4bf3e2f8-5340-4dad-b31a-837d9b4b7789'
  trigger:
  - platform: event
    event_type: mobile_app_notification_action
    event_data:
      action: kamer_amilya_window_pause
  action:
  - action: input_boolean.turn_on
    target:
      entity_id: input_boolean.kamer_amilya_window_pause  

- alias: "veranda_window_pause"
  id: 'dd1996ee-359e-4927-b7d5-037a6dbdf5a6'
  trigger:
  - platform: event
    event_type: mobile_app_notification_action
    event_data:
      action: veranda_window_pause
  action:
  - action: input_boolean.turn_on
    target:
      entity_id: input_boolean.veranda_window_pause  

- alias: "badkamer_window_pause"
  id: '5b8237b5-590a-41a2-b4be-c00060ff6913'
  trigger:
  - platform: event
    event_type: mobile_app_notification_action
    event_data:
      action: badkamer_window_pause
  action:
  - action: input_boolean.turn_on
    target:
      entity_id: input_boolean.badkamer_window_pause  

- alias: "berging_window_pause"
  id: '55246dce-ea35-468e-826a-d4ad661e245c'
  trigger:
  - platform: event
    event_type: mobile_app_notification_action
    event_data:
      action: berging_window_pause
  action:
  - action: input_boolean.turn_on
    target:
      entity_id: input_boolean.berging_window_pause  

- alias: "kamer_alunya_window_pause"
  id: '7d193363-c417-41cc-8efd-de8773243924'
  trigger:
  - platform: event
    event_type: mobile_app_notification_action
    event_data:
      action: kamer_alunya_window_pause
  action:
  - action: input_boolean.turn_on
    target:
      entity_id: input_boolean.kamer_alunya_window_pause  

- alias: "master_bedroom_window_pause"
  id: 'fd21e621-1f88-4a4f-99a9-1a2a9b4d62e0'
  trigger:
  - platform: event
    event_type: mobile_app_notification_action
    event_data:
      action: master_bedroom_window_pause
  action:
  - action: input_boolean.turn_on
    target:
      entity_id: input_boolean.master_bedroom_window_pause  

#######################################
###  reset pauze toggles after 2 hours
#######################################

- alias: "zet pauze toggle living naar OFF na 2 uren"
  id: '31ce80e7-4e3d-4c27-957b-0dba521e38ae'
  description: ''
  mode: single
  trigger:
    - platform: state
      entity_id: input_boolean.living_window_pause
      to: 'on'
  condition: []
  action:
    - delay: '02:00'
    - action: input_boolean.turn_off
      target:
        entity_id: input_boolean.living_window_pause

- alias: "zet pauze toggle kamer Amilya naar OFF na 2 uren"
  id: '7f24f3b5-8b87-49ef-aa5e-74d329f5f0f4'
  description: 'zet pauze toggle kamer Amilya naar OFF na 2 uren'
  mode: single
  trigger:
    - platform: state
      entity_id: input_boolean.kamer_amilya_window_pause
      to: 'on'
  condition: []
  action:
    - delay: '02:00'
    - action: input_boolean.turn_off
      target:
        entity_id: input_boolean.kamer_amilya_window_pause

- alias: "zet pauze toggle veranda naar OFF na 2 uren"
  id: '0892810f-dd42-44a8-8a4b-acfca3c43fcf'
  description: 'zet pauze toggle veranda naar OFF na 2 uren'
  mode: single
  trigger:
    - platform: state
      entity_id: input_boolean.veranda_window_pause
      to: 'on'
  condition: []
  action:
    - delay: '02:00'
    - action: input_boolean.turn_off
      target:
        entity_id: input_boolean.veranda_window_pause

- alias: "zet pauze toggle berging naar OFF na 2 uren"
  id: '0d0a3b38-87ff-42fb-9c69-e747e67310a4'
  description: 'zet pauze toggle berging naar OFF na 2 uren'
  mode: single
  trigger:
    - platform: state
      entity_id: input_boolean.berging_window_pause
      to: 'on'
  condition: []
  action:
    - delay: '02:00'
    - action: input_boolean.turn_off
      target:
        entity_id: input_boolean.berging_window_pause

- alias: "zet pauze toggle badkamer naar OFF na 2 uren"
  id: '96d0ee52-a072-48bb-bf3c-190678f64c90'
  description: 'zet pauze toggle badkamer naar OFF na 2 uren'
  mode: single
  trigger:
    - platform: state
      entity_id: input_boolean.badkamer_window_pause
      to: 'on'
  condition: []
  action:
    - delay: '02:00'
    - action: input_boolean.turn_off
      target:
        entity_id: input_boolean.badkamer_window_pause

- alias: "zet pauze toggle kamer Alunya naar OFF na 2 uren"
  id: '9619c280-f961-497e-bfad-548d006518f2'
  description: 'zet pauze toggle kamer Alunya naar OFF na 2 uren'
  mode: single
  trigger:
    - platform: state
      entity_id: input_boolean.kamer_alunya_window_pause
      to: 'on'
  condition: []
  action:
    - delay: '02:00'
    - action: input_boolean.turn_off
      target:
        entity_id: input_boolean.kamer_alunya_window_pause

- alias: "zet pauze toggle master bedroom naar OFF na 2 uren"
  id: '0eff8c7d-9bb8-4cf7-8c35-bc05caf02a49'
  description: 'zet pauze toggle master bedroom naar OFF na 2 uren'
  mode: single
  trigger:
    - platform: state
      entity_id: input_boolean.master_bedroom_window_pause
      to: 'on'
  condition: []
  action:
    - delay: '02:00'
    - action: input_boolean.turn_off
      target:
        entity_id: input_boolean.master_bedroom_window_pause


#######################################
###  reset pauze toggles at midnight
#######################################

- alias: "middernacht = reset schakelaars"
  id: '57a9ca46-e2ec-4185-8ca2-a5d5e24698dc'
  description: reset booleans voor openzetten ramen ivm vocht
  trigger:
    - platform: time
      at: '00:00'
  condition: []
  action:
    - action: input_boolean.turn_off
      target:
        entity_id:
          - input_boolean.living_window_pause
          - input_boolean.kamer_amilya_window_pause
          - input_boolean.veranda_window_pause
          - input_boolean.berging_window_pause
          - input_boolean.badkamer_window_pause
          - input_boolean.kamer_alunya_window_pause
          - input_boolean.master_bedroom_window_pause
  mode: single
