automation:

- alias: het regent
  id: 'ecee1739-f190-4e55-812e-e89ab35c9634'
  description: ''
  trigger:
  - platform: numeric_state
    entity_id: sensor.eikenbos_rain_rate_piezo
    above: '0'
  condition: []
  action:
  - service: notify.bart_madouce_phone
    data:
      title: Regen
      message: Het regent. Zijn de ramen dicht?
      data:
        tag: regen
  mode: single

- alias: Het gaat regenen over 15 minuten (en raam nog open ?) (Bart)
  id: '212d32e6-2fc1-4164-a8de-a4f1a06843dc'
  description: ''
  trigger:
  - platform: state
    entity_id: sensor.buienradar_precipitation_forecast_total
    from: '0'
  condition: []
  action:
  - service: notify.bart_madouce_phone
    data:
      message: Het gaat regenen over een kwartier. 
  mode: single

- alias: Regen en raam open = melding
  id: '01f65789-6050-44b5-93e2-1d8cf701b3ef'
  description: ''
  trigger:
  - platform: numeric_state
    entity_id: sensor.eikenbos_rain_rate_piezo
    above: '0'
  condition:
  - condition: state
    entity_id: binary_sensor.kamer_amilya_raam
    state: 'on'
  action:
  - service: notify.bart_madouce_phone
    data:
      message: Het regent en het raam van Amilya staat open.
      title: Het regent. Doe raam Amilya dicht aub.
  mode: single
