############################ Table of Contents ############################ 
# 
#   Automations
#

# bluetooth address Etron: 98:49:14:C1:37:0B
# VIN etron: !secret vin

############################ Automations ################################## 

automation:
  
#########################
# Auto climatisatie
#########################  

- alias: 🚗 car 1 // climate // start op uur bepaald door timer
  id: '583aabff-84db-4aac-a7de-023aee0d79f1'
  trigger:
  - platform: time
    at: input_datetime.car_1_climatisation_time
  condition:
  - condition: state
    entity_id: input_boolean.car_1_climatisation_timer
    state: 'on'
  action:
  - action: input_boolean.turn_off
    data: {}
    target:
      entity_id: input_boolean.car_1_climatisation_timer
  - action: script.car_1_climatisation_start    
  mode: restart

- alias: 🚗 car 1 // climate // 19u in Waarschoot en koud = vraag auto climatiseren
  id: '8fa06ed3-7c9f-453d-80d4-a246df6633f8'
  description: ''
  trigger:
  - platform: time
    at: '19:00'
  condition:
  - condition: numeric_state
    entity_id: sensor.eikenbos_temperature
    below: 15
  - condition: state
    entity_id: person.bart
    state: Waarschoot
  - condition: state
    entity_id: device_tracker.bart_s23plus
    state: 0
    attribute: speed
    for:
      hours: 0
      minutes: 2
      seconds: 0
      milliseconds: 0
  action:
  - action: notify.bart_phone
    data:
      message: 🚙 Moet de auto geclimatiseerd worden?
      data:
        tag: auto_climatisatie
        color: green
        notification_icon: "mdi:car-seat-heater"
        actions:
        - action: URI
          title: zo ja, klik hier
          uri: /dashboard-car/car-heater
  mode: single

- alias: 🚗 car 1 // climate // Bart verlaat auto
  id: '63ee4ac0-2944-4531-bc17-a2a6d60ff341'
  description: ''
  trigger:
    - platform: state
      entity_id: binary_sensor.bart_phone_connected_to_car_1
      from: 'on'
      to: 'off'
      for: "00:00:05"
  condition:
    - condition: numeric_state
      entity_id: sensor.eikenbos_temperature
      below: 15
  action:
  - choose:
    # indien aankomst thuis, niets doen
    # - conditions:
    #   - condition: state
    #     entity_id: person.bart
    #     state: "home"
    #   sequence:
    # indien aankomst bij sauna, onmiddellijk vragen
    - conditions:
      - condition: template
        value_template: "{{ states('person.bart') in ['Sauna Elzenhof', 'Sauna Hezemeer', 'Sauna Boetfort', 'The White Oak'] }}"
      sequence:
      - action: notify.bart_phone
        data:
          title: 🚙 Moet de auto straks geclimatiseerd worden?
          message: Geniet van de sauna :)
          data:
            tag: auto_climatisatie   
            color: green
            notification_icon: "mdi:car-seat-heater"            
            actions:
            - action: URI
              title: zo ja, klik hier
              uri: /dashboard-car/car-heater          
    # indien aankomst bij winkel, niets vragen en climatisatie starten na 10 minuten
    - conditions:
      - condition: template
        value_template: "{{ states('person.bart') in ['Aldi Bierbeek', 'Action Bierbeek', 'AH Zaventem', 'Lidl Sterrebeek'] }}"
      sequence:
      - wait_template: ''
        timeout: 00:10:00       
      - action: script.car_1_climatisation_start_now
    # indien aankomst bij plaats met lang verblijf, vragen 
    - conditions:
      - condition: template
        value_template: "{{ states('person.madouce') in ['Waarschoot', 'Koen & Katiana'] }}"
      sequence:
      - action: notify.bart_phone
        data:
          title: 🚙 Auto straks climatiseren?
          message: Een warme auto is altijd lekkerder.
          data:
            tag: auto_climatisatie 
            color: green
            notification_icon: "mdi:car-seat-heater"            
            actions:
            - action: URI
              title: zo ja, klik hier
              uri: /dashboard-car/car-heater
      - wait_template: ''
        timeout: '01:00:00'
      - action: notify.bart_phone
        data:
          message: 🚙 Moet de auto geclimatiseerd worden?
          data:
            tag: auto_climatisatie      
            color: green
            notification_icon: "mdi:car-seat-heater"              
            actions:
            - action: URI
              title: zo ja, klik hier
              uri: /dashboard-car/car-heater
    # alle andere locaties
    default:
    - action: notify.bart_phone
      data:
        title: 🚙 Auto straks climatiseren?
        message: Een warme auto is altijd lekkerder.
        data:
          tag: auto_climatisatie
          color: green
          notification_icon: "mdi:car-seat-heater"          
          actions:
          - action: URI
            title: zo ja, klik hier
            uri: /dashboard-car/car-heater
    - wait_template: ''
      timeout: '01:00:00'
    - action: notify.bart_phone
      data:
        message: 🚙 Moet de auto worden geclimatiseerd?
        data:
          tag: auto_climatisatie      
          color: green
          actions:
          - action: URI
            title: zo ja, klik hier
            uri: /dashboard-car/e-tron-heate
  mode: restart          

- alias: 🚗 car 1 // climate // Madouce verlaat auto
  id: '24b7df67-875f-48f9-8a96-4960bb91687a'
  description: ''
  trigger:
    - platform: state
      entity_id: binary_sensor.madouce_phone_connected_to_car_1
      from: 'on'
      to: 'off'
      for: "00:00:05"
  condition:
    - condition: numeric_state
      entity_id: sensor.eikenbos_temperature
      below: 15
  action:
  - choose:
    # indien aankomst thuis, niets doen
    # - conditions:
    #   - condition: state
    #     entity_id: person.madouce
    #     state: "home"
    #   sequence:
    # indien aankomst bij sauna, onmiddellijk vragen
    - conditions:  
      - condition: template
        value_template: "{{ states('person.madouce') in ['Sauna Elzenhof', 'Sauna Hezemeer', 'Sauna Boetfort', 'The White Oak'] }}"
      sequence:
      - action: notify.madouce_phone
        data:
          title: 🚙 Moet de auto straks geclimatiseerd worden?
          message: Geniet van de sauna :)
          data:
            tag: auto_climatisatie      
            color: green
            notification_icon: "mdi:car-seat-heater"            
            actions:
            - action: URI
              title: zo ja, klik hier
              uri: /dashboard-car/car-heater          
    # indien aankomst bij winkel, niets vragen en climatisatie na 10 minuten starten
    - conditions:
      - condition: template
        value_template: "{{ states('person.madouce') in ['Aldi Bierbeek', 'Action Bierbeek', 'AH Zaventem', 'Lidl Sterrebeek'] }}"
      sequence:
      - wait_template: ''
        timeout: 00:10:00      
      - action: script.car_1_climatisation_start_now
    # indien aankomst bij plaats met lang verblijf, vragen 
    - conditions:
      - condition: template
        value_template: "{{ states('person.madouce') in ['Waarschoot', 'Koen & Katiana'] }}"
      sequence:
      - action: notify.madouce_phone
        data:
          title: 🚙 Auto straks climatiseren?
          message: Een warme auto is altijd lekkerder.
          data:
            tag: auto_climatisatie      
            color: green
            actions:
            - action: URI
              title: zo ja, klik hier
              uri: /dashboard-car/car-heater
      - wait_template: ''
        timeout: '01:00:00'
      - action: notify.madouce_phone
        data:
          message: 🚙 Moet de auto worden geclimatiseerd?
          data:
            tag: auto_climatisatie      
            color: green
            notification_icon: "mdi:car-seat-heater"            
            actions:
            - action: URI
              title: zo ja, klik hier
              uri: /dashboard-car/car-heater
    # alle andere locaties
    default:
    - action: notify.madouce_phone
      data:
        title: 🚙 Auto straks climatiseren?
        message: Een warme auto is altijd lekkerder.
        data:
          tag: auto_climatisatie
          color: green
          notification_icon: "mdi:car-seat-heater"          
          actions:
          - action: URI
            title: zo ja, klik hier
            uri: /dashboard-car/car-heater
    - wait_template: ''
      timeout: '01:00:00'
    - action: notify.madouce_phone
      data:
        message: 🚙 Moet de auto worden geclimatiseerd?
        data:
          tag: auto_climatisatie      
          color: green
          notification_icon: "mdi:car-seat-heater"          
          actions:
          - action: URI
            title: zo ja, klik hier
            uri: /dashboard-car/e-tron-heate
  mode: restart


#########################
# Werkdag Toyota Evere
#########################

- alias: 🚗 car 1 // climate // climatisatie voor vertrek naar Toyota Evere
  id: 'caf13c49-2daa-4e8c-b275-a6811621cf50'
  description: ''
  trigger:
  - platform: time
    at: '07:30'
  condition:
  - condition: template
    value_template: >
      {% set car_1_use_day = 'input_select.car_1_use_day_' ~ now().isoweekday() %}
      {%if states(car_1_use_day) == "Toyota Evere"%} true {% endif %}
  action:
  - action: notify.madouce_phone
    data:
      title: 🚙 De temperatuur in de auto wordt nu aangepast.
      message:  Geniet van de warme rit naar Evere.
      data:
        tag: auto_climatisatie
        color: green
        notification_icon: "mdi:car-seat-heater"        
        clickAction: "/dashboard-car/car-heater"
  - action: script.car_1_climatisation_start_now
  mode: single 


- alias: 🚗 car 1 // climate // Bij aankomst Toyota Evere starttijd bepalen voor climatisatie
  id: '4ed1d4be-1e9b-42b0-90b9-e32d9f584de0'
  description: ''
  trigger:
  - platform: state
    entity_id: binary_sensor.madouce_phone_connected_to_car_1
    from: 'on'
    to: 'off'
    for: "00:00:05"
  - platform: state
    entity_id: device_tracker.audi_e_tron_sportback_position
    to: 'Toyota Evere'
  condition:
  - condition: state
    entity_id: person.madouce
    state: "Toyota Evere"  
  - condition: template
    value_template: >
      {% set car_1_use_day = 'input_select.car_1_use_day_' ~ now().isoweekday() %}
      {% if states(car_1_use_day) == "Toyota Evere"%} true {% endif %}
  action:
  - action: input_datetime.set_datetime
    data:
      datetime: "{{ (now().timestamp()  + (7.5 * 60 * 60) ) | timestamp_local() }}"
    target:
      entity_id: input_datetime.toyota_evere_expected_leaving_time
  - action: notify.madouce_phone
    data:
      message: TTS
      data:
        tts_text: Welkom in Evere. Een prettige werkdag.
        ttl: 0
        priority: high
        media_stream: alarm_stream  
  mode: single

- alias: 🚗 car 1 // climate // climatisatie op einde werkdag bij Toyota Evere
  id: '2e05b1aa-1980-4c0d-b3a7-ee1df7fef055'
  description: ''
  trigger:
  - platform: time
    at: input_datetime.toyota_evere_expected_leaving_time
  condition:
    or:
      - condition: state
        entity_id: person.madouce
        state: "Toyota Evere"
      - condition: state
        entity_id: device_tracker.audi_e_tron_sportback_position
        state: "Toyota Evere"
  action:
  - action: notify.madouce_phone
    data:
      title: 🚙 De temperatuur in de auto wordt nu aangepast.
      message: Een koele/warme auto is altijd lekkerder. Veilige rit dadelijk.
      data:
        tag: auto_climatisatie
        color: green
        notification_icon: "mdi:car-seat-heater"        
        clickAction: "/dashboard-car/car-heater"
  - action: script.car_1_climatisation_start_now          
  mode: single


#########################
# Werkdag Toyota Diest
#########################

- alias: 🚗 car 1 // climate // climatisatie voor vertrek naar Toyota Diest
  id: 'a9955e82-bda5-452a-86d0-b8a320c0b837'
  description: ''
  trigger:
  - platform: time
    at: '07:40'
  condition:
    and:
      - condition: template
        value_template: >
          {% set car_1_use_day = 'input_select.car_1_use_day_' ~ now().isoweekday() %}
          {%if states(car_1_use_day) == "Toyota Diest"%} true {% endif %}
      - condition: numeric_state
        entity_id: sensor.eikenbos_temperature
        below: 15       
  action:
  - action: notify.madouce_phone
    data:
      title: 🚙 De temperatuur in de auto wordt nu aangepast.
      message:  Geniet van de rit naar Diest.
      data:
        tag: auto_climatisatie
        color: green
        notification_icon: "mdi:car-seat-heater"        
        clickAction: "/dashboard-car/car-heater"
  - action: script.car_1_climatisation_start_now
  mode: single


- alias: 🚗 car 1 // climate // Bij aankomst Toyota Diest starttijd bepalen voor climatisatie
  id: '0862a5c1-640f-48b9-b484-4bfc0f5efb41'
  description: ''
  trigger:
  - platform: state
    entity_id: device_tracker.audi_e_tron_sportback_position
    to: 'Toyota Diest'
  - platform: state
    entity_id: binary_sensor.madouce_phone_connected_to_car_1
    from: 'on'
    to: 'off'
    for: "00:00:05"    
  condition:
  - condition: state
    entity_id: person.madouce
    state: "Toyota Diest"
  - condition: template
    value_template: >
      {% set car_1_use_day = 'input_select.car_1_use_day_' ~ now().isoweekday() %}
      {%if states(car_1_use_day) == "Toyota Diest"%} true {% endif %}
  action:
  - action: input_datetime.set_datetime
    data:
      datetime: "{{ (now().timestamp()  + (7.5 * 60 * 60) ) | timestamp_local() }}"
    target:
      entity_id: input_datetime.toyota_diest_expected_leaving_time
  - action: notify.madouce_phone
    data:
      message: TTS
      data:
        tts_text: Welkom in Diest. Een prettige werkdag.
        ttl: 0
        priority: high
        media_stream: alarm_stream
  mode: single

- alias: 🚗 car 1 // climate // Auto climatisatie op einde werkdag bij Toyota Diest
  id: '7c5f1cfa-b20a-4b5b-be63-8ad01ec4e57f'
  description: ''
  trigger:
  - platform: time
    at: input_datetime.toyota_diest_expected_leaving_time
  condition:
    or:
      - condition: state
        entity_id: person.madouce
        state: "Toyota Diest"
      - condition: state
        entity_id: device_tracker.audi_e_tron_sportback_position
        state: "Toyota Diest"
  action:
  - action: notify.madouce_phone
    data:
      title: 🚙 De temperatuur in de auto wordt nu aangepast.
      message: Een koele/warme auto is altijd lekkerder. Veilige rit dadelijk.
      data:
        tag: auto_climatisatie
        color: green
        notification_icon: "mdi:car-seat-heater"        
        clickAction: "/dashboard-car/car-heater"
  - action: script.car_1_climatisation_start_now          
  mode: single

#####################################################
# Automatisch climatiseren bij sauna
#####################################################

- alias: 🚗 car 1 // climate // The White Oak (niet vrijdag) = start climatisatie om 21u50
   # Ma/Woe/Do/Zon/feestdagen open tot 22u30
  id: 'e0f16f48-bc89-4b74-82ba-ebb7ebc3161b'
  description: ''
  trigger:
    - platform: time
      at: '21:50'
  condition:    
    - condition: state
      entity_id: person.bart
      state: "The White Oak"
    - condition: template
      value_template: >
        {% if now().date().isoweekday() != 5 %} true {% endif %}        
  action:      
    - action: script.car_1_climatisation_start_now
  mode: single

- alias: 🚗 car 1 // climate // The White Oak (vrijdag) = start climatisatie om 22u20
  # vrijdag open tot 23u00
  id: 'fa9e136b-7d36-4395-adb0-08a5289699b3'
  description: ''
  trigger:
    - platform: time
      at: '22:20'
  condition:    
    - condition: state
      entity_id: person.bart
      state: "The White Oak"
    - condition: template
      value_template: >
        {% if now().date().isoweekday() == 5 %} true {% endif %}      
  action:      
    - action: script.car_1_climatisation_start_now
  mode: single


- alias: 🚗 car 1 // climate // timerschakelaar climatisatie aan = start timer
  id: '23018dc0-d06f-4866-94b4-331cc30f6d83'
  description: ''
  trigger:
  - platform: state
    entity_id:
      - input_boolean.car_1_climatisation_timer
    to: "on"
  # - platform: numeric_state
  #   entity_id:
  #     - input_datetime.car_1_climatisation_time 
  condition: []
  # - condition: state
  #   entity_id: input_boolean.car_1_climatisation_timer
  #   state: "on"
  action:
  - action: timer.set_duration
    data:
      duration: >
        {% set t = (as_timestamp(now().replace(hour=strptime(states('input_datetime.car_1_climatisation_time'), '%H:%M:%S').hour,
                minute=strptime(states('input_datetime.car_1_climatisation_time'), '%H:%M:%S').minute)) - as_timestamp(now())) | int  %}
        {% if t < 0 %}
          {% set t = t + 86400 %}
        {% endif %}
        {% set hours = (t // 3600) %}
        {% set minutes = ((t % 3600) // 60) %}
        {% set seconds = (t % 60) %}
        {% set timestr = "%02d:%02d:%02d"|format(hours, minutes, seconds) %}
        {{ timestr }}        
    target:
      entity_id: timer.car_1_climatisation
  - action: timer.start
    data: {}
    target:
      entity_id: timer.car_1_climatisation      
  mode: single

- alias: 🚗 car 1 // climate // timer climatisatie gewijzigd en timer ingeschakeld = start timer
  id: '1b04ef03-549b-4ddb-989b-4cebb140d3b9'
  description: ''
  trigger:
  - platform: state
    entity_id:
      - input_datetime.car_1_climatisation_time 
  condition:
  - condition: state
    entity_id: input_boolean.car_1_climatisation_timer
    state: "on"
  action:
  - action: timer.set_duration
    data:
      duration: >
        {% set t = (as_timestamp(now().replace(hour=strptime(states('input_datetime.car_1_climatisation_time'), '%H:%M:%S').hour,
                minute=strptime(states('input_datetime.car_1_climatisation_time'), '%H:%M:%S').minute)) - as_timestamp(now())) | int  %}
        {% if t < 0 %}
          {% set t = t + 86400 %}
        {% endif %}
        {% set hours = (t // 3600) %}
        {% set minutes = ((t % 3600) // 60) %}
        {% set seconds = (t % 60) %}
        {% set timestr = "%02d:%02d:%02d"|format(hours, minutes, seconds) %}
        {{ timestr }}         
    target:
      entity_id: timer.car_1_climatisation
  - action: timer.start
    data: {}
    target:
      entity_id: timer.car_1_climatisation      
  mode: restart


- alias: 🚗 car 1 // climate // timerschakelaar climatisatie uit = timer op 0 
  id: '3e2fd4a4-7e0e-4bf4-b686-db34580b4395'
  description: ''
  trigger:
  - platform: state
    entity_id:
      - input_boolean.car_1_climatisation_timer
    to: "off"
  condition: []
  action:
  - action: notify.bart_madouce_phone
    data:
      message: "clear_notification"
      data:
        tag: auto_climatisatie
        timeout: 18000  # 1800 seconden = half uur
        actions:
        - action: URI
          title: meer info
          uri: /dashboard-car/e-tron   
  - action: timer.set_duration
    data:
      duration: '0'        
    target:
      entity_id: timer.car_1_climatisation
  - action: timer.finish
    data: {}
    target:
      entity_id: timer.car_1_climatisation    
  mode: single

