############################ Table of Contents ############################ 
# 
#   Automations
#


# bluetooth address Etron: 98:49:14:C1:37:0B
# VIN Etron: !secret vin

############################ Automations ################################## 
automation:

- alias: 🚗 car 1 // Audi integratie herstarten als entiteiten onbeschikbaar zijn
  # By reloading one of the entities, the whole integration is restarted
  id: '942be3f6-ee53-4901-af4e-23423cf7063e'
  description: ""
  mode: single
  trigger:
    - platform: state
      entity_id:
        - sensor.audi_e_tron_sportback_range
      to: unavailable
    - platform: time_pattern
      minutes: /25   
  condition:
    - condition: state
      entity_id: sensor.audi_e_tron_sportback_range
      state: unavailable
  action:
    - service: homeassistant.reload_config_entry
      target:
        entity_id: sensor.audi_e_tron_sportback_range


#########################
# Status auto vernieuwen
#########################   

- alias: 🚗 car 1 // Bart 3 km van thuis = vernieuwen status auto
  id: '37cfe751-fb7d-4f9b-9a1e-772eeba15f64'
  trigger:
  - platform: numeric_state
    entity_id:
      - proximity.bart_home
    below: 3
  condition:
  - condition: template
    value_template: '{{ trigger.to_state.attributes.dir_of_travel  == "towards" }}'
  action:
  - service: audiconnect.refresh_cloud_data
    data: {}   
  # - service: audiconnect.refresh_vehicle_data
  #   data:
  #     vin: !secret vin
  mode: single
  
- alias: 🚗 car 1 // Madouce 3 km van thuis = vernieuwen status auto
  id: '533ee396-e37b-450b-a5e6-c981a9696b31'
  trigger:
  - platform: numeric_state
    entity_id:
      - proximity.madouce_home
    below: 3
  condition:
  - condition: template
    value_template: '{{ trigger.to_state.attributes.dir_of_travel  == "towards" }}'
  action:
  - service: audiconnect.refresh_cloud_data
    data: {}   
  # - service: audiconnect.refresh_vehicle_data
  #   data:
  #     vin: !secret vin
  mode: single  
  
- alias: 🚗 car 1 // 🔋 charge // Car sim km veranderd
  id: '0813a89b-64b9-4fa8-934e-7e4ee91ee033'
  description: ''
  trigger:
  - platform: state
    entity_id: input_number.car_sim_km
  condition: []
  action:
  - service: input_number.set_value
    target:
      entity_id: input_number.car_sim_batteryprocent
    data:
      value: >
        {{ ((states('input_number.car_sim_km') | float * 10 ) / (states('sensor.car_range_per_10percent')
        | float(default=0))) | round(1) }}
  - wait_template: ''
    timeout: '00:00:02'
  mode: single

- alias: 🚗 car 1 // 🔋 charge // car sim batterij veranderd
  id: '85f8fbeb-4132-41f4-ad9b-5662d75946e2'
  description: ''
  trigger:
  - platform: state
    entity_id: input_number.car_sim_batteryprocent
  condition: []
  action:
  - service: input_number.set_value
    target:
      entity_id: input_number.car_sim_km
    data:
      value: >
        {{ ( (states('input_number.car_sim_batteryprocent') | float(default=0)) * (states('sensor.car_range_per_10percent')
        | float(default=0) / 10 ) ) | round(1) }}
  - wait_template: ''
    timeout: '00:00:02'
  mode: single

######################################
# Reistijd
######################################

- alias: 🚗 car 1 // travel time // Meld reistijd naar Toyota Evere (bij ochtendwekker + 7u15 en 7u45)
  id: '0195b18e-5fd6-48a8-ae22-ca0e692fde6c'
  description: ''
  trigger:
  - platform: time
    at: 
      - sensor.sm_g986b_next_alarm 
      - '07:15'
      - '07:45'
  condition:
  - condition: template
    value_template: >
      {% set car_1_use_day = 'input_select.car_1_use_day_' ~ now().isoweekday() %}
      {%if states(car_1_use_day) == "Toyota Evere"%} true {% endif %}
  action:
  - service: notify.madouce_phone
    data:
      title: Goede morgen, Madouce!
      message: "Reistijd naar Toyota Evere is {{states('sensor.waze_travel_time_huis_toyota_evere')}} minuten."
      data:
        tag: auto_laden
  mode: single
  
- alias: 🚗 car 1 // travel time // Meld reistijd naar Toyota Diest (bij ochtendwekker + 7u15 en 7u45)
  id: '5d976c12-4cdf-4534-821f-332dc180e65d'
  description: ''
  trigger:
  - platform: time
    at: 
      - sensor.sm_g986b_next_alarm  
      - '07:15'
      - '07:45'
  condition:
  - condition: template
    value_template: >
      {% set car_1_use_day = 'input_select.car_1_use_day_' ~ now().isoweekday() %}
      {%if states(car_1_use_day) == "Toyota Diest"%} true {% endif %}
  action:
  - service: notify.madouce_phone
    data:
      title: Goede morgen, Madouce!
      message: "Reistijd naar Toyota Diest is {{states('sensor.waze_travel_time_huis_toyota_diest')}} minuten."
      data:
        tag: auto_laden
  mode: single  


######################################
# A Better Route Planner (ABPR)
######################################

- alias: 🚗 car 1 // Stuur auto info naar A Better Route Planner
  id: '3301406f-a0d7-4ef8-b0dc-3edfa4aad868'
  trigger:
  # at every change of the SOC
    - platform: state
      entity_id: sensor.audi_e_tron_sportback_primary_engine_range
      to:
  action:
    - service: rest_command.update_abrp



- alias: 🚗 car 1 // trip logging // bewaar ritstatistieken
  id: '9733861e-23dd-482b-99de-fdcce78b9bf6'
  description: ''
  trigger:
    - platform: template
      value_template: "{{ state_attr('sensor.audi_e_tron_sportback_trip_short_current','tripID')  }}"
  condition: []
  action:
  - service: notify.bart_phone
    data:
      title: Nieuwe ritstatistieken beschikbaar
      message: >
        afstand: {{state_attr('sensor.audi_e_tron_sportback_trip_short_current','mileage')}}<br>
        gem. snelheid: {{state_attr('sensor.audi_e_tron_sportback_trip_short_current','averageSpeed')}}<br>
        gem. verbruik: {{state_attr('sensor.audi_e_tron_sportback_trip_short_current','averageFuelConsumption')}}<br>
  mode: single

- alias: 🚗 car 1 // locatie veranderd = melding
  id: d5885051-7845-4b1c-ad4d-70329d383678
  description: ''
  trigger:
    - platform: state
      entity_id: device_tracker.audi_e_tron_sportback_position
  action:
    - service: notify.bart_phone
      data:
        title: Audi op nieuwe locatie
        message: >
          latitude: {{trigger.from_state.attributes.latitude}}
          longitude: {{trigger.from_state.attributes.longitude}}
          second_latitude: {{trigger.to_state.attributes.latitude}}
          second_longitude: {{trigger.to_state.attributes.longitude}}
        tag: car_1_location 
