automation:
 
- alias: "🚗 car 1 // 🔋 charge dag met zon // start-bezig-stop"
  id: '3f95d137-2736-451d-aa66-7b11b748734d'
  trigger:
    - platform: time_pattern
      minutes: '/1'
  condition:
    - condition: state
      entity_id: input_boolean.car_charge_day_sun
      state: 'on'    
    - condition: template
      value_template: "{{ as_timestamp(states('sensor.zon_van_eikenbos_opkomst')) < as_timestamp(now()) < as_timestamp(states('sensor.sunset')) }}"
    # only if charger cable is connected to home charger or already charging        
    - condition: template
      value_template: "{{ states('sensor.charger_status') in ['charging', 'connected'] }}"
  variables:
    wattage: >
        {% set maxpower = states('input_number.car_charge_sun_max_netwattage') | float(default=0) %}
        {% set net = states('sensor.net_power_avg') | float %}
        {% set charger = states('sensor.charger_current_power_avg') | float(default=0) %}
        {{ (( maxpower - net + charger ) / 1000) | float }}
    message: >
      Zon: {{ states('sensor.solar_power') | int }} W | Net: {{ states('sensor.net_power')}} W | Auto laadt nu aan {{states('input_number.car_charger_watt') | round(1)}} kW<br>
      Auto: {{states('sensor.car_1_soc') | round()}}%. Doel: {{ states('input_number.car_1_optimal_target_soc') | round(0)}}%<br>
      Vandaag al {{ states('sensor.car_charge_solar_energy_daily') | round(1) }} kWh geladen met zon en {{ states('sensor.car_charge_net_energy_daily') | round(1) }} kWh van het net.                
  action:
    - if:
        # - condition: state
        #   entity_id: input_boolean.car_charge_day_sun
        #   state: 'on'    
        - condition: template
          value_template: "{{ wattage > 1.3 }}"          
      then:   
        - service: input_boolean.turn_on
          data: {}
          target:
            entity_id: input_boolean.car_charge_busy
        - service: input_number.set_value
          target:
            entity_id: input_number.car_charger_watt
          data:
            value: "{{ wattage }}"
        - wait_template: ''
          timeout: '00:00:05'
        - service: script.start_charger
      else:
        if:
          - condition: template
            value_template: "{{ states('sensor.charger_current_power') | float() > 0 }}"
        then:      
          - service: script.stop_charger
            data: {}
          - service: notify.bart_phone
            data:
              title: Auto is gestopt met laden. Nu 3 minuten wachten.
              message: >
                Gestopt
          - wait_template: ''
            timeout: '00:03:00'             
  mode: single


  # - service: notify.bart_phone
  #   data:
  #     title: Auto is gestart met laden op zonne-energie
  #     message: "{{ message }}"
  #     data:
  #       tag: car_charging_sun
  #       color: green
  #       notification_icon: "mdi:car-electric"
  #       actions:
  #         - action: URI
  #           title: meer info
  #           uri: /dashboard-car/car-charging
 