############################ Table of Contents ############################ 
# 
#   Automations
#     Vocht in huis >75%
#     Vocht master bedroom -> machine aan
#
############################ Automations ################################## 

# dauwpunt
# Hoger dan 26 °C	Ernstig hoog, zelfs dodelijk voor mensen met astma gerelateerde ziekten	65% en hoger
# 24–26 °C	Zeer ongemakkelijk, tamelijk benauwend	62%
# 21–24 °C	Erg vochtig, heel ongemakkelijk	52–60%
# 18–21 °C	Enigszins ongemakkelijk, voor de meeste mensen is de luchtvochtigheid aan de hoge kant	44–52%
# 16–18 °C	OK voor de meeste mensen, maar men merkt al dat de luchtvochtigheid aan de hoge kant is	37–46%
# 13–16 °C	Comfortabel	38–41%
# 10–12 °C	Zeer comfortabel	31–37%
# Lager dan 10 °C	Een beetje droog voor sommige mensen

automation:

- alias: "💧 humidity // Vocht in huis >70%"
  id: '466f577f-83c4-4954-b17e-335ad7fa83f6'
  description: ''
  trigger:
    - platform: numeric_state
      entity_id: sensor.avg_inside_humidity
      above: '70'
      for: '00:15'
  condition:
    - condition: state
      entity_id: person.bart
      state: home
    - condition: time
      after: '07:00:00'
      before: '23:00:00'
  action:
    - service: notify.bart_phone
      data:
        title: Vocht
        message: >
          Vocht % in huis is heel hoog: {{states('sensor.avg_inside_humidity') | int() }}%.
        data:
          color: "#0E86D4"
          clickAction: "/lucht-vocht-temperatuur/vocht-gram"
  mode: single
  
- alias: "💧 humidity // vocht gram in badkamer >14 gram/m³"
  id: 8358a61f-74f1-4045-ba75-563bbca3b4e3
  description: ''
  trigger:
  - platform: numeric_state
    entity_id: sensor.badkamer_thermal_absolute_humidity
    above: '14'
  condition: []
  action:
  - repeat:
      while:
      - condition: numeric_state
        entity_id: sensor.badkamer_thermal_absolute_humidity
        above: '14'
      sequence:
      - service: notify.bart_madouce_phone
        data:
          title: "Veel vocht in badkamer! Raam is {{states('sensor.badkamer_raam')}}."
          message: "{{states('sensor.badkamer_thermal_absolute_humidity') | round(1) }} gram
            water /m³ en {{states('sensor.badkamer_humidity') | round(0) }}% vocht."
          data:
            notification_icon: "mdi:water-percent-alert"          
            color: "#0E86D4"
            tag: badkamer_vocht
            channel: vocht
            clickAction: "/lucht-vocht-temperatuur/vocht-gram"
      - delay:
          hours: 1
  - service: notify.bart_madouce_phone
    data:
      message: "clear_notification"
      data:
        tag: badkamer_vocht
  mode: single
  
- alias: "💧 humidity // vocht % in master bedroom >80%"
  id: 'e1a0cee2-ee78-4e66-a133-9ea28f3a4fb8'
  description: ''
  trigger:
  - platform: numeric_state
    entity_id: sensor.master_bedroom_humidity
    above: '80'
  condition: []
  action:
  - repeat:
      while:
      - condition: numeric_state
        entity_id: sensor.master_bedroom_humidity
        above: '80'
      sequence:
      - service: notify.bart_madouce_phone
        data:
          title: "Veel vocht in master bedroom! Raam is {{states('sensor.master_bedroom_raam')}}"
          message: "{{states('sensor.master_bedroom_thermal_absolute_humidity') | round(1)}} gram
            water /m³ en {{states('sensor.master_bedroom_humidity') | round(0) }}% vocht."
          data:
            notification_icon: "mdi:water-percent-alert"          
            color: "#0E86D4"
            tag: master_bedroom_vocht
            channel: vocht
            clickAction: "/lucht-vocht-temperatuur/vocht-gram"
      - delay:
          hours: 1
  - service: notify.bart_madouce_phone
    data:
      message: "clear_notification"
      data:
        tag: master_bedroom_vocht

  mode: single

- alias: "💧 humidity // vocht % in kamer Alunya >80%"
  id: 'f8d84a81-37f6-429b-be52-c772b4f45570'
  description: ''
  trigger:
  - platform: numeric_state
    entity_id: sensor.kamer_alunya_humidity
    above: '80'
  condition: []
  action:
  - repeat:
      while:
      - condition: numeric_state
        entity_id: sensor.kamer_alunya_humidity
        above: '80'
      sequence:
      - service: notify.bart_madouce_phone
        data:
          title: >
            Veel vocht in kamer Alunya! Raam is {{state_translated('binary_sensor.kamer_alunya_raam')}}.
          message: > 
            {{states('sensor.kamer_alunya_thermal_absolute_humidity') | round(1)}} gram
            water /m³ en {{states('sensor.kamer_alunya_humidity') | round(0) }}% vocht.
          data:
            notification_icon: "mdi:water-percent-alert"          
            color: "#0E86D4"
            tag: kamer_alunya_vocht
            channel: vocht
            clickAction: "/lucht-vocht-temperatuur/vocht-gram"
      - delay:
          hours: 1
  - service: notify.bart_madouce_phone
    data:
      message: "clear_notification"
      data:
        tag: kamer_alunya_vocht
  mode: single


- alias: 💧 humidity // badkamer ventilator aan (hygrostat)
  id: 'cf03f8c4-fb46-4583-abc1-cdbba273e6c8'
  trigger:
    platform: state
    entity_id: binary_sensor.bathroom_hygrostat
    to: 'on'
  action:
    - service: switch.turn_on
      entity_id: switch.toilet_douche_ventilatie
  mode: single

- alias: badkamer ventilator aan (hygrostat)
  id: 'ce94d975-1d1c-4ce3-bff1-c49e04cd3fc1'
  trigger:
    platform: state
    entity_id: binary_sensor.bathroom_hygrostat
    to: 'off'
  action:
    - service: switch.turn_off
      entity_id: switch.toilet_douche_ventilatie
  mode: single      