############################ Table of Contents ############################ 
#
#   #   Prepare notifications to open windows 
#   🪟 ramen - open raam living (Bart en Madouce)
#   🪟 ramen - open raam kamer Amilya (Bart en Madouce)
#   🪟 ramen - open raam veranda (Bart en Madouce)
#   🪟 ramen - open raam berging (Bart en Madouce)
#   🪟 ramen - open raam badkamer (Bart en Madouce)
#   🪟 ramen - open raam kamer Alunya (Bart en Madouce)
#   🪟 ramen - open raam master bedroom (Bart en Madouce)
#
###########################################################################

automation:

- alias: 🪟 ramen - open raam living
  id: '095d6529-f4e6-44df-b25d-2548de7f5958'
  description: ''
  trigger:
  - platform: time_pattern
    minutes: /15
  condition:
  - condition: state
    entity_id: input_boolean.living_raam_moet_open
    state: 'on'
  - condition: state
    entity_id: binary_sensor.keuken_raam
    state: 'off'
  - condition: state
    entity_id: binary_sensor.living_oprit_raam
    state: 'off'
  - condition: state
    entity_id: binary_sensor.living_tuin_raam
    state: 'off'
  - condition: state
    entity_id: input_boolean.living_window_pause
    state: 'off'
  action:
  - service: script.notify_bart_windows_open
    data:
      title: '{{title}}'
      message: '{{reason}}<br>{{message}}'
      tag: '{{tag}}'
      action_window_pause: '{{action_window_pause}}'
      uri: "/lucht-vocht-temperatuur/vocht-gram"      
  - service: script.notify_madouce_windows_open
    data:  
      title: '{{title}}'
      message: '{{reason}}<br>{{message}}'
      tag: '{{tag}}'
      action_window_pause: '{{action_window_pause}}'
      uri: "/lucht-vocht-temperatuur/vocht-gram"
  variables:
    message: >
      Vocht living: {{states('sensor.gram_water_living') | round(1) }} g/m³. Buiten: {{states('sensor.gram_water_outside')}} g/m³.<br>
      Vocht living: {{states('sensor.living_humidity')}}%. Buiten: {{states('sensor.eikenbos_humidity')}}%.<br>
      Temp living: {{states('sensor.living_temperature')}} °C. Buiten: {{states('sensor.eikenbos_temperature')}} °C.
    title: "Open het raam van de living/keuken!"
    tag: "window_living"
    action_window_pause: "living_window_pause"
    reason: >
      {% set d = states('sensor.gram_water_living_diff_outside') | float(default=0) %}
      {% set h = states('sensor.living_humidity') | round() %}
      {% if   d >= 3.0 %} Extreem vochtig binnen. {{ h }}%
      {% elif d >= 1.5 %} Veel te vochtig binnen. {{ h }}%
      {% elif d >= 0.5 %} Beetje te vochtig binnen. {{ h }}%
      {% endif %}
  mode: single

- alias: 🪟 ramen - open raam kamer Amilya
  id: '5e940ddb-56ad-4f8a-b9c5-4fd24b0138c2'
  description: ''
  trigger:
  - platform: time_pattern
    minutes: /15
  condition:
  - condition: state
    entity_id: input_boolean.kamer_amilya_raam_moet_open
    state: 'on'
  - condition: state
    entity_id: binary_sensor.kamer_amilya_raam
    state: 'off'
  - condition: state
    entity_id: input_boolean.kamer_amilya_window_pause
    state: 'off'
  - condition: zone
    entity_id: person.bart
    zone: zone.home
  action:
  - service: script.notify_bart_windows_open
    data:
      title: '{{title}}'
      message: '{{reason}}<br>{{message}}'
      tag: '{{tag}}'
      action_window_pause: '{{action_window_pause}}' 
  - service: script.notify_madouce_windows_open
    data:  
      title: '{{title}}'
      message: '{{reason}}<br>{{message}}'
      tag: '{{tag}}'
      action_window_pause: '{{action_window_pause}}'
      uri: "/lucht-vocht-temperatuur/vocht-gram" 
  variables:
    message: >
      Vocht kamer Amilya: {{states('sensor.gram_water_kamer_amilya') | round(1) }} g/m³. Buiten: {{states('sensor.gram_water_outside')}} g/m³.<br>
      Vocht kamer Amilya: {{states('sensor.kamer_amilya_humidity') | round }}%. Buiten: {{states('sensor.eikenbos_humidity') | }}%.<br>
      Temp kamer Amilya: {{states('sensor.kamer_amilya_temperature') | round(1) }} °C. Buiten: {{states('sensor.eikenbos_temperature')}} °C.
    title: "Open het raam van Amilya!"
    tag: "window_kamer_amilya"
    action_window_pause: "kamer_amilya_window_pause"
    reason: >
      {% set d = states('sensor.gram_water_kamer_amilya_diff_outside') | float(default=0) %}
      {% set h = states('sensor.kamer_amilya_humidity') | round() %}
      {% if   d >= 3.0 %} Extreem vochtig binnen. {{ h }}%
      {% elif d >= 1.5 %} Veel te vochtig binnen. {{ h }}%
      {% elif d >= 0.5 %} Beetje te vochtig binnen. {{ h }}%
      {% endif %}
  mode: single

- alias: 🪟 ramen - open raam veranda
  id: '16b26e4a-ba87-4a26-a72d-310f70e4e5b2'
  description: ''
  trigger:
  - platform: time_pattern
    minutes: /15
  condition:
  - condition: state
    entity_id: input_boolean.veranda_schuifraam_moet_open
    state: 'on'
  - condition: state
    entity_id: binary_sensor.veranda_schuifraam
    state: 'off'
  - condition: state
    entity_id: input_boolean.veranda_window_pause
    state: 'off'
  action:
  - service: script.notify_bart_windows_open
    data:
      title: '{{title}}'
      message: '{{reason}}<br>{{message}}'
      tag: '{{tag}}'
      action_window_pause: '{{action_window_pause}}' 
  - service: script.notify_madouce_windows_open
    data:  
      title: '{{title}}'
      message: '{{reason}}<br>{{message}}'
      tag: '{{tag}}'
      action_window_pause: '{{action_window_pause}}'
      uri: "/lucht-vocht-temperatuur/vocht-gram"
  variables:
    message: >
      Vocht veranda {{states('sensor.gram_water_veranda') | round(1) }} g/m³. Buiten: {{states('sensor.gram_water_outside')}} g/m³.<br>
      Vocht veranda: {{states('sensor.veranda_humidity') | round }}%. Buiten: {{states('sensor.eikenbos_humidity')}}%<br>
      Temp veranda: {{states('sensor.veranda_temperature')}} °C. Buiten: {{states('sensor.eikenbos_temperature')}} °C.
    title: "Open het raam van de veranda!"
    tag: "window_veranda"
    action_window_pause: "veranda_window_pause"
    reason: >
      {% set d = states('sensor.gram_water_veranda_diff_outside') | float(default=0) %}
      {% set h = states('sensor.veranda_humidity') | round() %}
      {% if   d >= 3.0 %} Extreem vochtig binnen. {{ h }}%
      {% elif d >= 1.5 %} Veel te vochtig binnen. {{ h }}%
      {% elif d >= 0.5 %} Beetje te vochtig binnen. {{ h }}%
      {% endif %}
  mode: single

- alias: 🪟 ramen - open raam berging
  id: '58397619-e77f-44d8-9e1a-fb0a9e6eae22'
  description: ''
  trigger:
  - platform: time_pattern
    minutes: /15
  condition:
  - condition: state
    entity_id: input_boolean.berging_raam_moet_open
    state: 'on'
  - condition: state
    entity_id: binary_sensor.berging_raam
    state: 'off'
  - condition: state
    entity_id: input_boolean.berging_window_pause
    state: 'off'
  action:
  - service: script.notify_bart_windows_open
    data:
      title: '{{title}}'
      message: '{{reason}}<br>{{message}}'
      tag: '{{tag}}'
      action_window_pause: '{{action_window_pause}}'
  - service: script.notify_madouce_windows_open
    data:  
      title: '{{title}}'
      message: '{{reason}}<br>{{message}}'
      tag: '{{tag}}'
      action_window_pause: '{{action_window_pause}}'
      uri: "/lucht-vocht-temperatuur/vocht-gram"     
  variables:
    message: >
      Vocht berging {{states('sensor.gram_water_berging') | round(1) }} g/m³. Buiten: {{states('sensor.gram_water_outside')}} g/m³.<br>
      Vocht berging: {{states('sensor.berging_humidity')}}%. Buiten: {{states('sensor.eikenbos_humidity')}}%<br>
      Temp berging: {{states('sensor.berging_temperature')}} °C. Buiten: {{states('sensor.eikenbos_temperature')}} °C.
    title: "Open het raam van de berging!"
    tag: "window_berging"
    action_window_pause: "berging_window_pause"
    reason: >
      {% set d = states('sensor.gram_water_berging_diff_outside') | float(default=0) %}
      {% set h = states('sensor.berging_humidity') | round() %}
      {% if   d >= 3.0 %} Extreem vochtig binnen. {{ h }}%
      {% elif d >= 1.5 %} Veel te vochtig binnen. {{ h }}%
      {% elif d >= 0.5 %} Beetje te vochtig binnen. {{ h }}%
      {% endif %}
  mode: single

- alias: 🪟 ramen - open raam badkamer
  id: '4739d887-11b6-49c9-8086-6c4bd142b6b0'
  description: ''
  trigger:
  - platform: time_pattern
    minutes: /15
  condition:
  - condition: state
    entity_id: input_boolean.badkamer_raam_moet_open
    state: 'on'
  - condition: state
    entity_id: binary_sensor.badkamer_raam_kantel
    state: 'off'
  - condition: state
    entity_id: input_boolean.badkamer_window_pause
    state: 'off'
  action:
  - service: script.notify_bart_windows_open
    data:
      title: '{{title}}'
      message: '{{reason}}<br>{{message}}'
      tag: '{{tag}}'
      action_window_pause: '{{action_window_pause}}'
  - service: script.notify_madouce_windows_open
    data:  
      title: '{{title}}'
      message: '{{reason}}<br>{{message}}'
      tag: '{{tag}}'
      action_window_pause: '{{action_window_pause}}'
      uri: "/lucht-vocht-temperatuur/vocht-gram"
  variables:  
    message: >
      Vocht  badkamer: {{states('sensor.gram_water_badkamer') | round(1) }} g/m³. Buiten: {{states('sensor.gram_water_outside')}} g/m³.<br>
      Vocht badkamer: {{states('sensor.badkamer_humidity')}}%. Buiten: {{states('sensor.eikenbos_humidity')}}%.<br>
      Temp badkamer: {{states('sensor.badkamer_temperature')}} °C. Buiten: {{states('sensor.eikenbos_temperature')}} °C.
    title: "Open het raam van de badkamer!"
    tag: "window_badkamer"
    action_window_pause: "badkamer_window_pause"
    reason: >
      {% set d = states('sensor.gram_water_badkamer_diff_outside') | float(default=0) %}
      {% set h = states('sensor.badkamer_humidity') | round() %}
      {% if   d >= 3.0 %} Extreem vochtig binnen. {{ h }}%
      {% elif d >= 1.5 %} Veel te vochtig binnen. {{ h }}%
      {% elif d >= 0.5 %} Beetje te vochtig binnen. {{ h }}%
      {% endif %}
  mode: single

- alias: 🪟 ramen - open raam kamer Alunya
  id: '73c4f6ed-f3ff-4180-86b8-bebb95b89b6d'
  description: ''
  trigger:
  - platform: time_pattern
    minutes: /15
  condition:
  - condition: state
    entity_id: input_boolean.kamer_alunya_raam_moet_open
    state: 'on'
  - condition: state
    entity_id: binary_sensor.kamer_alunya_raam
    state: 'off'
  - condition: state
    entity_id: binary_sensor.kamer_alunya_schuifraam
    state: 'off'  
  - condition: state
    entity_id: input_boolean.kamer_alunya_window_pause
    state: 'off'
  action:
  - service: script.notify_bart_windows_open
    data:
      title: '{{title}}'
      message: '{{reason}}<br>{{message}}'
      tag: '{{tag}}'
      action_window_pause: '{{action_window_pause}}'
  - service: script.notify_madouce_windows_open
    data:  
      title: '{{title}}'
      message: '{{reason}}<br>{{message}}'
      tag: '{{tag}}'
      action_window_pause: '{{action_window_pause}}'
      uri: "/lucht-vocht-temperatuur/vocht-gram"
  variables:  
    message: >
      Vocht kamer Alunya: {{states('sensor.gram_water_kamer_alunya') | round(1) }} g/m³. Buiten: {{states('sensor.gram_water_outside')}} g/m³.<br>
      Vocht kamer Alunya: {{states('sensor.kamer_alunya_humidity')}}%. Buiten: {{states('sensor.eikenbos_humidity')}}%<br>
      Temp kamer Alunya: {{states('sensor.kamer_alunya_temperature')}} °C. Buiten: {{states('sensor.eikenbos_temperature')}} °C.
    title: "Open het raam van Alunya!"
    tag: "window_kamer_alunya"
    action_window_pause: "kamer_alunya_window_pause"
    reason: >
      {% set d = states('sensor.gram_water_kamer_alunya_diff_outside') | float(default=0) %}
      {% set h = states('sensor.kamer_alunya_humidity') | round() %}
      {% if   d >= 3.0 %} Extreem vochtig binnen. {{ h }}%
      {% elif d >= 1.5 %} Veel te vochtig binnen. {{ h }}%
      {% elif d >= 0.5 %} Beetje te vochtig binnen. {{ h }}%
      {% endif %}
  mode: single

- alias: 🪟 ramen - open raam master bedroom
  id: '64c1f037-4152-4380-b341-9aef8df8fcf0'
  description: ''
  trigger:
  - platform: time_pattern
    minutes: /15
  condition:
  - condition: state
    entity_id: input_boolean.master_bedroom_raam_moet_open
    state: 'on'
  - condition: state
    entity_id: binary_sensor.master_bedroom_raam_kantel
    state: 'off'
  - condition: state
    entity_id: input_boolean.master_bedroom_window_pause
    state: 'off'
  action:
  - service: script.notify_bart_windows_open
    data:
      title: '{{title}}'
      message: '{{reason}}<br>{{message}}'
      tag: '{{tag}}'
      action_window_pause: '{{action_window_pause}}'
  - service: script.notify_madouce_windows_open
    data:  
      title: '{{title}}'
      message: '{{reason}}<br>{{message}}'
      tag: '{{tag}}'
      action_window_pause: '{{action_window_pause}}'
      uri: "/lucht-vocht-temperatuur/vocht-gram"
  variables:
    message: >
      Vocht master bedroom: {{states('sensor.gram_water_master_bedroom') | round(1) }} g/m³. Buiten: {{states('sensor.gram_water_outside')}} g/m³.<br>
      Vocht master bedroom: {{states('sensor.master_bedroom_humidity')}}%. Buiten: {{states('sensor.eikenbos_humidity')}}%.<br>
      Temp master bedroom: {{states('sensor.master_bedroom_temperature')}} °C. Buiten: {{states('sensor.eikenbos_temperature')}} °C.
    title: "Open het raam van de master bedroom!"
    tag: "window_master_bedroom"
    action_window_pause: "master_bedroom_window_pause"
    reason: >
      {% set d = states('sensor.gram_water_master_bedroom_diff_outside') | float(default=0) %}
      {% set h = states('sensor.master_bedroom_humidity') | round() %}
      {% if   d >= 3.0 %} Extreem vochtig binnen. {{ h }}%
      {% elif d >= 1.5 %} Veel te vochtig binnen. {{ h }}%
      {% elif d >= 0.5 %} Beetje te vochtig binnen. {{ h }}%
      {% endif %}
  mode: single

- alias: 🪟 ramen - open raam badkamer (melding op speaker)
  id: '86ec8dc8-381e-460a-af44-3afe02f69147'
  description: ''
  trigger:
    - platform: state
      entity_id: light.badkamer_douche
      to: 'off'
  condition:
    - condition: state
      entity_id: binary_sensor.badkamer_raam_kantel
      state: 'off'
    - condition: state
      entity_id: input_boolean.badkamer_raam_moet_open
      state: 'on'
  action:
    - service: tts.google_say
      data:
        entity_id: media_player.badkamer_speaker
        message: Het raam mag open. Er is {{states('sensor.badkamer_humidity')}}% vocht.
  mode: single
