############################ Table of Contents ############################ 
# 
#   Automations


############################ Automations ################################## 
automation:

######################################
# charge planning
######################################

- alias: "🚗 car 1 // 🔋 charge // planning // planning is veranderd = bepaal minimum SOC per dag"
  id: '6a3d5cef-5531-4e6e-9f94-1777e1217a4a'
  description: ''
  trigger:
  - platform: state
    entity_id: 
    - input_select.car_1_use_day_1
    - input_select.car_1_use_day_2
    - input_select.car_1_use_day_3
    - input_select.car_1_use_day_4
    - input_select.car_1_use_day_5
    - input_select.car_1_use_day_6
    - input_select.car_1_use_day_7
  action:
  - service: script.set_target_soc_based_on_calendar
  - service: input_number.set_value
    target:
      entity_id: input_number.car_1_min_target_soc
    data:
      value: >
        {% set t = (now().date() + timedelta(days=1)) %}
        {% set car_1_min_target_soc_day = 'input_number.car_1_min_target_soc_day_' ~ t.isoweekday() %}  
        {{ states(car_1_min_target_soc_day) | int }}

- alias: "🚗 car 1 // 🔋 charge // planning // om 6u30 vernieuw SOC per dag en bepaal de min en optimale SOC voor vandaag"
  id: '2a4d4e65-51b0-44b4-80fc-d22a39dde38b'
  description: ''
  trigger:
  - platform: time
    at: '06:30:00'
  action:
  - service: script.set_target_soc_based_on_calendar
  - service: input_number.set_value
    target:
      entity_id: input_number.car_1_min_target_soc
    data:
      value: >
        {% set t = (now().date() + timedelta(days=1)) %}
        {% set car_1_min_target_soc_day = 'input_number.car_1_min_target_soc_day_' ~ t.isoweekday() %}  
        {{ states(car_1_min_target_soc_day) | float(default=0) }}
  - service: input_number.set_value
    target:
      entity_id: input_number.car_1_optimal_target_soc
    data:
      value: >
        {% set t = (now().date() + timedelta(days=1)) %}
        {% set car_1_min_target_soc_day = 'input_number.car_1_optimal_target_soc_day_' ~ t.isoweekday() %}  
        {{ states(car_1_min_target_soc_day) | float(default=0) }}
  mode: single