automation:

# INSCHAKELEN

- alias: 💧 humidity // badkamer ontvochtiger // start
  id: '5b2dc339-366f-40d0-af5a-2d56ea56f23c'
  description: ''
  trigger:
  - platform: numeric_state
    entity_id: sensor.dehumidifier_power
    for:
      hours: 0
      minutes: 0
      seconds: 3
    above: 20
  condition: []
  action:
    - service: input_select.select_option
      data:
        option: aan
      target:
        entity_id: input_select.dehumidifier_state
    - service: input_datetime.set_datetime
      data:
        datetime: '{{ now() }}'
      target:
        entity_id: input_datetime.dehumidifier_start_time
    - service: timer.start
      data:
        duration: "{{ states('input_number.dehumidifier_timer_minutes') | float * 60 }}"   
      target:
        entity_id: timer.dehumidifier_timer              
  mode: single

- alias: 💧 humidity // badkamer ontvochtiger // licht douche = inschakelen
  id: 'cef6103e-ddcd-4cf9-abef-41cf20411ded'
  description: ""
  trigger:
  - platform: state
    entity_id:
      - light.badkamer_douche
    to: "on"
    for:
      minutes: 0
      seconds: 45
  condition:
    - condition: template
      value_template: " {{ states('binary_sensor.badkamer_raam_wijd') != 'on' }}"
  action:
    - service: switch.turn_on
      data: {}
      target:
        entity_id: switch.dehumidifier_switch
  mode: single


- alias: 💧 humidity // badkamer ontvochtiger // staat al 15 min. aan
  id: '0bd10dde-0f91-479c-9ddb-ebc484c0178d'
  description: ''
  trigger:
  - platform: numeric_state
    entity_id: sensor.dehumidifier_power
    above: 0
    for: 00:15:00
  condition: []
  action:
  - repeat:
      while:
      - condition: numeric_state
        entity_id: sensor.dehumidifier_power
        above: 0
      sequence:
      - service: notify.bart_phone      
        data:
          title: Ontvochtiger staat al tijdje aan.
          message: >
            {% set t = ((as_timestamp(now()) - starttijd) / 60) | int(default=0) %}
            Staat al {{ t }} minuten aan.
          data:
            tag: ontvochtiger
            notification_icon: "mdi:air-humidifier"
      - delay:
          minutes: 15            
  - service: notify.bart_phone
    data:
      title: "Ontvochtiger staat nu uit."
      message: >
        {% set t = (( as_timestamp(now()) - starttijd ) / 60) | round(default=0) %}
        Stond {{ t }} minuten aan.
      data:
        tag: ontvochtiger
        notification_icon: "mdi:air-humidifier"
  variables:
    starttijd: "{{ as_timestamp(state_attr('automation.ontvochtiger_staat_al_15_min_aan', 'last_triggered')) }}"      
  mode: single

- alias: 💧 humidity // badkamer ontvochtiger // injectie, vocht in badkamer = inschakelen
  id: '7d40ccc1-3c6b-4621-bc2b-4c4a02bc7338'
  description: ""
  trigger:
    - platform: numeric_state
      entity_id: sensor.net_power_avg
      for:
        hours: 0
        minutes: 20
        seconds: 0
      below: -300
  condition:
    - condition: numeric_state
      entity_id: sensor.badkamer_humidity
      above: 65
    - condition: template
      value_template: " {{ states('binary_sensor.badkamer_raam_wijd') != 'on' }}"      
    # - condition: state
    #   entity_id: group.gezin
    #   state: not_home
  action:
    - service: switch.turn_on
      data: {}
      target:
        entity_id: switch.dehumidifier_switch
  mode: single


# UITSCHAKELEN

- alias: 💧 humidity // badkamer ontvochtiger // uit
  id: '35121fab-a415-454e-af0a-fb863aa20b37'
  description: ''
  trigger:
  - platform: numeric_state
    entity_id: sensor.dehumidifier_power
    for:
      hours: 0
      minutes: 0
      seconds: 3
    below: 20
  condition: []
  action:
    - service: input_select.select_option
      data:
        option: uit
      target:
        entity_id: input_select.dehumidifier_state
    - service: input_datetime.set_datetime
      data:
        datetime: '{{ now() }}'
      target:
        entity_id: input_datetime.dehumidifier_stop_time
    - service: timer.finish
      data: {}
      target:
        entity_id: timer.airco_dehumidify_timer
    - service: switch.turn_off
      data: {}
      target:
        entity_id: switch.dehumidifier_switch         
    - service: notify.bart_madouce_phone
      data:
        message: "clear_notification"
        data:
          tag: ontvochtiger                
  mode: single

- alias: 💧 humidity // badkamer ontvochtiger // timer komt op 0 of raam open of <65% vocht = uitschakelen
  id: 'cf189eff-93b5-4452-b62d-8c14cdbd7bb4'
  description: ''
  trigger:
  - platform: state
    entity_id:
      - timer.dehumidifier_timer
    from: active
    to: idle
  - platform: state
    entity_id: binary_sensor.badkamer_raam_kantel
    to: "on"
  - platform: numeric_state
    entity_id: sensor.badkamer_humidity
    below: 65
  condition: []
  action:  
    - service: switch.turn_off
      data: {}
      target:
        entity_id: switch.dehumidifier_switch
    - service: timer.cancel
      data: {}
      target:
        entity_id: timer.dehumidify_timer           
  mode: single

  