automation:

- alias: '♨️ Airco heating master bedroom: aan volgens schema'
  id: 'edef1255-b457-4329-befe-d901277e91c3'
  description: ''
  trigger:
  - platform: numeric_state
    entity_id: sensor.master_bedroom_temperature
    below: 16
  condition:
  - condition: state
    entity_id: schedule.master_bedroom_normal_temperature_schema
    state: 'on'
  - condition: state
    entity_id: group.gezin
    state: home
  action:
  - service: input_number.set_value
    data:
      value: >
        {{ states('input_number.master_bedroom_normal_temperature') | float }}
    target:
      entity_id: input_number.master_bedroom_airco_target_temperature          
  - service: input_number.set_value
    data:
      value: 30
    target:
      entity_id: input_number.master_bedroom_airco_timer_minutes
  - service: script.master_bedroom_airco_start
    data: {} 
  mode: single

- alias: '♨️ Airco heating master bedroom: uit volgens schema/verlaten huis/timer stop'
  id: '6f9dd54d-4168-49d5-8bc4-e9b6d157bb44'
  description: ''
  trigger:
  - platform: state
    entity_id: schedule.master_bedroom_normal_temperature_schema
    to: 'off'
  - platform: state
    entity_id: group.gezin
    to: not_home
  - platform: state
    entity_id: binary_sensor.master_bedroom_raam_kantel
    to: "on"    
  - platform: time
    at: input_datetime.master_bedroom_airco_timer_stop    
  condition: []
  action:
  - service: climate.turn_off
    data: {}
    target:
      device_id: 64296bd295e4506b8a3ec42c8aae7e58
  - service: timer.cancel
    data: {}
    target:
      entity_id: timer.master_bedroom_airco_timer
  mode: single

- alias: "♨️ Airco heating master bedroom: Bart en/of Madouce niet thuis = airco master bedroom uit"
  id: 'c31e15a9-6392-4101-945f-d8070319bac3'
  description: ''
  trigger:
  - platform: state
    entity_id: group.bart_madouce
    to: not_home
  condition: []
  action:
  - service: climate.set_hvac_mode
    data:
      hvac_mode: 'off'
    target:
      device_id: 64296bd295e4506b8a3ec42c8aae7e58
  - service: timer.cancel
    data: {}
    target:
      entity_id: timer.master_bedroom_airco_timer      
  mode: single



