automation:

- alias: "♨️ airco heating // slaapkamers // verwarm van 21u45 tot 22u15" 
  id: '90ff19bc-3090-4950-a9d2-e2263c9c37da'
  description: ''
  trigger:
  - platform: time
    at: '21:45:00'
  condition: []
  action:
    - if:
        - condition: state
          entity_id: group.bart_madouce
          state: home
      then:
        - service: input_number.set_value
          data:
            value: 21
          target:
            entity_id: input_number.master_bedroom_airco_target_temperature  
        - service: input_number.set_value
          data:
            value: 30
          target:
            entity_id: input_number.master_bedroom_airco_timer_minutes
        - delay:
            seconds: 2
        - service: script.master_bedroom_airco_start
    - if:
        - condition: state
          entity_id: person.amilya
          state: home
      then:
        - service: input_number.set_value
          data:
            value: 21
          target:
            entity_id: input_number.amilya_airco_target_temperature  
        - service: input_number.set_value
          data:
            value: 30
          target:
            entity_id: input_number.amilya_airco_timer_minutes
        - delay:
            seconds: 2
        - service: script.amilya_airco_start
    - if:
        - condition: state
          entity_id: person.alunya
          state: home
        - condition: and
          conditions:
            - condition: numeric_state
              entity_id: sensor.kamer_alunya_temperature
              below: 15
      then:
        - service: input_number.set_value
          data:
            value: 21
          target:
            entity_id: input_number.alunya_airco_target_temperature          
        - service: input_number.set_value
          data:
            value: 30
          target:
            entity_id: input_number.alunya_airco_timer_minutes
        - delay:
            seconds: 2
        - service: script.alunya_airco_start
