automation:


- alias: '♨️ airco heating // master bedroom // uit bij verlaten huis/timer stop'
  id: '6f9dd54d-4168-49d5-8bc4-e9b6d157bb44'
  description: ''
  trigger:
  - platform: state
    entity_id: group.bart_madouce
    to: not_home
  - platform: state
    entity_id: binary_sensor.master_bedroom_raam_kantel
    to: "on"    
  - platform: time
    at: input_datetime.master_bedroom_airco_timer_stop    
  condition: []
  action:
  - service: climate.turn_off
    data: {}
    target:
      device_id: 64296bd295e4506b8a3ec42c8aae7e58
  - service: timer.cancel
    data: {}
    target:
      entity_id: timer.master_bedroom_airco_timer
  mode: single

- alias: "♨️ airco heating // master bedroom // Bart en/of Madouce niet thuis = airco master bedroom uit"
  id: 'c31e15a9-6392-4101-945f-d8070319bac3'
  description: ''
  trigger:
  - platform: state
    entity_id: group.bart_madouce
    to: not_home
  condition: []
  action:
  - service: climate.set_hvac_mode
    data:
      hvac_mode: 'off'
    target:
      device_id: 64296bd295e4506b8a3ec42c8aae7e58
  - service: timer.cancel
    data: {}
    target:
      entity_id: timer.master_bedroom_airco_timer      
  mode: single

- alias: "♨️ airco heating // master bedroom // verwarm van 21u45 tot 22u15" 
  id: '90ff19bc-3090-4950-a9d2-e2263c9c37da'
  description: ''
  trigger:
  - platform: time
    at: '21:45:00'
  condition: []
  action:
    - if:
        - condition: state
          entity_id: group.bart_madouce
          state: home
        - condition: state
          entity_id: binary_sensor.master_bedroom_raam_kantel
          state: 'off'
        - condition: numeric_state
          entity_id: sensor.master_bedroom_temperature
          below: 16           
      then:
        - service: input_number.set_value
          data:
            value: 21
          target:
            entity_id: input_number.master_bedroom_airco_target_temperature  
        - service: input_number.set_value
          data:
            value: 30
          target:
            entity_id: input_number.master_bedroom_airco_timer_minutes
        - delay:
            seconds: 2
        - service: script.master_bedroom_airco_start
          data: {}

