automation:

# device_id airco living = 1c560bbc7917f45d737e87d3e2bd0d89

- alias: '♨️ Airco heating living: aan volgens schema normale temp of aankomst'
  id: 'e0a1e10a-5bc5-4b2f-95dd-33e762f61df2'
  description: ''
  trigger:
    - platform: state
      entity_id: schedule.living_normal_temp_schema
      to: "on"
    - platform: state
      entity_id: group.gezin
      to: home
    - platform: template
      value_template: >
        {{ states('sensor.living_temperature') | float <
        states('input_number.living_normal_temperature') | float }}
  condition:
    - condition: state
      entity_id: schedule.living_normal_temp_schema
      state: "on"
    - condition: state
      entity_id: group.gezin
      state: home
    - condition: template
      value_template: >
        {{ states('sensor.living_temperature') | float <
        states('input_number.living_normal_temperature') | float }}
    - condition: state
      entity_id: binary_sensor.living_raam
      state: off  
  action:
  - service: climate.set_temperature
    data:
      hvac_mode: heat
      temperature: >
        {% set adj = (states('input_number.living_normal_temperature') | float) - (states('sensor.living_temperature') | float) %}        
        {{ (state_attr('climate.living_airco', 'current_temperature') + adj ) | round(1, 'half', 0) }}
    target:
      device_id: 1c560bbc7917f45d737e87d3e2bd0d89
  - service: climate.set_preset_mode
    data:
      preset_mode: eco
    target:
      device_id: 1c560bbc7917f45d737e87d3e2bd0d89
  - service: climate.set_swing_mode
    data:
      swing_mode: 3D
    target:
      device_id: 1c560bbc7917f45d737e87d3e2bd0d89
  - service: input_number.set_value
    data:
      value: "{{ states('input_number.living_normal_temperature') | float() }}"
    target:
      entity_id: input_number.living_airco_target_temperature
  mode: single


- alias: '♨️ Airco heating living: aan volgens schema comfort temperatuur'
  id: '9bb6cb31-9f9f-42c2-a4ac-f551cc970eb7'
  description: ''
  trigger:
  - platform: state
    entity_id: schedule.living_comfort_temperature_schema
    to: "on"
  - platform: state
    entity_id: group.bart_madouce
    to: home
  - platform: template
    value_template: >
      temperature: >
        {{ states('sensor.living_temperature') | float <
        states('input_number.living_comfort_temperature') | float }}  
  condition:
  - condition: state
    entity_id: schedule.living_comfort_temperature_schema
    state: "on"
  - condition: state
    entity_id: group.gezin
    state: home
  - condition: template
    value_template: >
      {{ states('sensor.living_temperature') | float <
      states('input_number.living_comfort_temperature') | float }} 
  action:
  - service: climate.set_temperature
    data:
      hvac_mode: heat
      temperature: >
        {% set adj = (states('input_number.living_comfort_temperature') | float) - (states('sensor.living_temperature') | float) %}        
        {{ (state_attr('climate.living_airco', 'current_temperature') + adj) | round(1, 'half', 0) }} 
    target:
      device_id: 1c560bbc7917f45d737e87d3e2bd0d89
  - service: climate.set_preset_mode
    data:
      preset_mode: eco
    target:
      device_id: 1c560bbc7917f45d737e87d3e2bd0d89
  - service: climate.set_swing_mode
    data:
      swing_mode: 3D
    target:
      device_id: 1c560bbc7917f45d737e87d3e2bd0d89
  - service: input_number.set_value
    data:
      value: "{{ states('input_number.living_comfort_temperature') | float() }}"
    target:
      entity_id: input_number.living_airco_target_temperature      
  mode: single

- alias: "♨️ Airco heating living: uit volgens schema/verlaten huis/timer stop"
  id: '075c660b-6d9b-4190-b6fb-3acb07a7f7ce'
  description: ""
  trigger:
    - platform: state
      entity_id:
        - schedule.living_normal_temperature_schema
        - schedule.living_comfort_temperature_schema
      to: "off"
    - platform: state
      entity_id: group.gezin
      to: not_home
    - platform: state
      entity_id: binary_sensor.living_raam
      to: "on"
    - platform: time
      at: input_datetime.living_airco_timer_stop
  condition: []
  action:
    - service: climate.turn_off
      data: {}
      target:
        device_id: 1c560bbc7917f45d737e87d3e2bd0d89
    - service: climate.set_temperature
      data:
        temperature: 14
      target:
        device_id: 1c560bbc7917f45d737e87d3e2bd0d89
    - service: input_number.set_value
      data:
        value: 14
      target:
        entity_id: input_number.living_airco_target_temperature
    - service: timer.finish
      data: {}
      target:
        entity_id: timer.living_airco_timer        
  mode: single


########################
# Handmatige aanpassing
########################

- alias: '♨️ Airco heating living: aan gedurende 30 minuten bij hogere gewenste temperatuur'
  id: 'f747ffe1-4135-4e72-af50-fd6052de540b'
  description: ''
  trigger:
  - platform: template
    value_template: >
      {{ states('sensor.living_temperature') | float < states('input_number.living_airco_target_temperature') | float }}
  condition:
  - condition: state
    entity_id: group.gezin
    state: home
  action:
  - service: input_number.set_value
    data:
      value: 30
    target:
      entity_id: input_number.living_airco_timer_minutes
  - service: script.living_airco_start
    data: {}  
  mode: restart
