automation:

# device_id airco living = 1c560bbc7917f45d737e87d3e2bd0d89

- alias: temperatuur living boven 23 graden
  id: 'clkcycfbi0000ycsndoxz5snk'
  description: ''
  trigger:
  - platform: numeric_state
    entity_id: sensor.living_temperature
    above: 23
  condition: []
  action:
  - service: notify.bart_phone
    data:
      title: Temperatuur living
      message: Temperatuur in living is nu {{ states('sensor.living_temperature') }} graden.
  mode: single