############################ Table of Contents ############################ 
# 
#   Automations


############################ Automations ################################## 
automation:

######################################
# charge planning
######################################

- alias: "🚗 car 1 // 🔋 charge // planning // planning is veranderd = bepaal minimum SOC per dag"
  id: '6a3d5cef-5531-4e6e-9f94-1777e1217a4a'
  description: ''
  trigger:
  - platform: state
    entity_id: 
    - input_select.car_use_day_1
    - input_select.car_use_day_2
    - input_select.car_use_day_3
    - input_select.car_use_day_4
    - input_select.car_use_day_5
    - input_select.car_use_day_6
    - input_select.car_use_day_7
  action:
  - service: script.set_target_soc_based_on_calendar
  - service: input_number.set_value
    target:
      entity_id: input_number.car_charge_target_percentage
    data:
      value: >
        {% set t = (now().date() + timedelta(days=1)) %}
        {% set car_target_soc_day = 'input_number.car_target_soc_day_' ~ t.isoweekday() %}  
        {{ states(car_target_soc_day) | float(default=0) }}  

- alias: "🚗 car 1 // 🔋 charge // planning // om 7u bepaal ideale SOC voor de dag"
  id: '5d3113d4-e1ae-46d6-ac8b-ab5951e71beb'
  trigger:
  - platform: time
    at: '07:00:00'
  action:
  - service: input_number.set_value
    target:
      entity_id: input_number.car_ideal_target_soc
    data:
      value: >
        {% set t = now().date() %}
        {% set soc = 'input_number.car_ideal_target_soc_day_' ~ t.isoweekday() %}  
        {{ states(soc) | round(default=0) }} 

- alias: "🚗 car 1 // 🔋 charge // planning // om 7u00 bepaal minimum SOC per dag"
  id: '2a4d4e65-51b0-44b4-80fc-d22a39dde38b'
  description: ''
  trigger:
  - platform: time
    at: '07:00:00'
  action:
  - service: script.set_target_soc_based_on_calendar

- alias: "🚗 car 1 // 🔋 charge // planning // om 6u30 bepaal min SOC op basis van planning"
  id: '275aac64-70ee-42c5-bcf7-3d522de6a8e5'
  trigger:
  - platform: time
    at: '06:30:00'
  condition: []
  action:
  - service: input_number.set_value
    target:
      entity_id: input_number.car_charge_target_percentage
    data:
      value: >
        {% set t = (now().date() + timedelta(days=1)) %}
        {% set car_target_soc_day = 'input_number.car_target_soc_day_' ~ t.isoweekday() %}  
        {{ states(car_target_soc_day) | float(default=0) }}
  mode: single