############################ Table of Contents ############################ 
# 
#   Automations
#   🚗 car 1 // 🔋 charge // charge mode nu ingeschakeld
#   🚗 car 1 // 🔋 charge // charge mode nu uitgeschakeld
#   🚗 car 1 // 🔋 charge // charge mode stoptimer ingeschakeld
#   🚗 car 1 // 🔋 charge // charge mode stoptimer uitgeschakeld
#   🚗 car 1 // 🔋 charge // charge mode zon ingeschakeld
#   🚗 car 1 // 🔋 charge // charge mode zon uitgeschakeld


############################ Automations ################################## 
automation:


#######################################
# charge modus toggle
######################################

- alias: "🚗 car 1 // 🔋 charge // modus select // directe modus ingeschakeld"
  id: 'eb33ffea-2365-4147-9419-4b223f04b921'
  description: ''
  trigger:
  - platform: state
    entity_id: input_boolean.car_charge_mode_now
    to: 'on'
  condition:
  - condition: template
    value_template: "{{ states('sensor.car_1_soc')| int(2) <= (states('input_number.car_1_optimal_target_soc') | int(2)) }}"
  action:
  - service: notify.bart_phone
    data:
      title: Direct laden gestart.
      message: >
        {% from 'easy_time.jinja' import weekday %}
        {% from 'easy_time.jinja' import month %}
        {% set nog_te_laden_minuten = states('sensor.car_remaining_charge_minutes_min_power') | round(2) %}
        {% set laaddoel = (as_timestamp(now()) + (nog_te_laden_minuten | float(default=0) * 60)) %}
        Directe start aan {{ states('input_number.car_charge_minimum_wattage') | round(1) }} kW + zon.<br>
        Laadtijd maximum {{ (nog_te_laden_minuten | float(default=0) / 60) | int }} uren en {{((nog_te_laden_minuten | float(default=0)) - ((nog_te_laden_minuten | float(default=0) / 60) | int * 60 )) | int() }} minuten.
        Laaddoel wordt ten laatste bereikt op {{ weekday(laaddoel) }} {{ laaddoel | timestamp_custom('%d')}} {{ month(laaddoel) }} {{ laaddoel | timestamp_custom('%-Hu%M')}}.
      data:
        tag: car_charging
        color: red
        notification_icon: "mdi:car-electric"
        actions:
        - action: URI
          title: meer info
          uri: /dashboard-car/car-charging
  - service: input_boolean.turn_on
    data: {}
    target:
      entity_id:
        - input_boolean.car_charge_busy
        - input_boolean.car_charge_sun_busy
        - input_boolean.car_charge_net_busy
  - service: script.charger_define_phase_1_or_3_based_on_watt
  - service: script.charger_define_ampere_based_on_watt
  - service: script.charger_define_and_write_register_based_on_ampere
  mode: restart

- alias: "🚗 car 1 // 🔋 charge // modus select // directe modus uitgeschakeld"
  id: 'f1791b1c-4799-4e85-890f-9a6cd31f7e54'
  description: ''
  trigger:
  - platform: state
    entity_id: input_boolean.car_charge_mode_now
    to: 'off'
  condition: []
  action:
  - service: notify.bart_phone
    data:
      message: "clear_notification"
      data:
        tag: car_charging
  - service: script.stop_charger
    data: {}
  mode: restart

- alias: "🚗 car 1 // 🔋 charge // modus select // starttimer modus ingeschakeld"
  id: '1323e532-64a5-41e3-9405-a6702fe540a0'
  description: ''
  trigger:
  - platform: state
    entity_id: input_boolean.car_charge_mode_starttimer
    to: 'on'
  condition: []
  action:
  - service: notify.bart_phone
    data:
      title: "Laden met starttimer"
      message: >
        Het laden start om {{ state_attr('input_datetime.car_charge_starttimer_starttime','timestamp') | timestamp_custom('%-Hu%M') }}.<br>
        Er wordt geladen van {{states('sensor.car_1_soc') | round(default=0) }}% naar {{states('input_number.car_1_optimal_target_soc') | round(default=0) }}%.
      data:
        tag: car_charging
        color: green
        notification_icon: "mdi:car-electric"        
        actions:
        - action: URI
          title: meer info
          uri: /dashboard-car/car-charging
  mode: restart

- alias: "🚗 car 1 // 🔋 charge // modus select // stoptimer modus ingeschakeld"
  id: '6e284b34-555e-418a-ad8f-c7a7afe2b121'
  description: ''
  trigger:
  - platform: state
    entity_id: input_boolean.car_charge_mode_stoptimer
    to: 'on'
  condition: []
  action:
  - service: input_number.set_value
    target:
      entity_id: input_number.car_charger_watt
    data:
      value: "{{ states('input_number.car_charge_mode_stoptimer_charger_watt') | float }}"
  - service: notify.bart_phone
    data:
      title: "Laden met doeltimer"
      message: >
        Laden van {{ as_timestamp(states('sensor.car_charge_stoptimer_starttime'),0) | timestamp_custom('%a %d %b %-Hu%M') }} tot {{ state_attr('input_datetime.car_charge_target_time','timestamp') | timestamp_custom('%a %d %b %-Hu%M',) }}.<br>
        Er wordt geladen van {{states('sensor.car_1_soc') | round(default=0) }}% naar {{states('input_number.car_1_optimal_target_soc') | round(default=0) }}%.
      data:
        tag: car_charging
        color: green
        notification_icon: "mdi:car-electric"        
        actions:
        - action: URI
          title: meer info
          uri: /dashboard-car/car-charging
  mode: restart

- alias: "🚗 car 1 // 🔋 charge // modus select // stoptimer modus uitgeschakeld"
  id: '10103bac-9dc6-4cae-8db7-5d9c2de8360f'
  description: ''
  trigger:
  - platform: state
    entity_id: input_boolean.car_charge_mode_stoptimer
    to: 'off'
  condition: []
  action:
  - service: notify.bart_phone
    data:
      message: "clear_notification"
      data:
        tag: car_charging  
  # force stop charging by setting charger at 5 A
  - service: script.stop_charger
    data: {}
  mode: restart

- alias: "🚗 car 1 // 🔋 charge // modus select // zon modus ingeschakeld"
  id: 'a8ea0be1-580c-4645-bd01-d16d57be3018'
  description: ''
  trigger:
  - platform: state
    entity_id: input_boolean.car_charge_mode_sun
    to: 'on'
  action:
  - service: notify.bart_phone
    data:
      title: Laden met zon.
      message: "Er zal worden geladen wanneer er zon is. Auto is nu {{ states('sensor.car_1_soc')| int(2)}}% geladen."
      data:
        tag: car_charging
        color: green
        notification_icon: "mdi:car-electric"        
        actions:
        - action: URI
          title: meer info
          uri: /dashboard-car/car-charging
  - service: input_number.set_value
    target:
      entity_id: input_number.car_charger_watt
    data:
      value: "{{ ((( states('sensor.net_power') | float ) / 1000 ) | abs ) - 1 }}"
  mode: restart

- alias: "🚗 car 1 // 🔋 charge // modus select // zon modus uitgeschakeld"
  id: '4ec2782b-8638-44d0-9aa3-45ae916ccf86'
  description: ''
  trigger:
  - platform: state
    entity_id: input_boolean.car_charge_mode_sun
    to: 'off'
  condition: []
  action:
  - service: input_boolean.turn_off
    data: {}
    target:
      entity_id: input_boolean.car_charge_sun_busy  
  - service: notify.bart_phone
    data:
      message: "clear_notification"
      data:
        tag: car_charging        
  # force stop charging by setting charger at 5 A
  - service: script.stop_charger
    data: {}
  mode: restart
