############################ Table of Contents ############################ 
#
#  check to OPEN windows
#  🪟 ramen - check living (moet open)
#  🪟 ramen - check kamer Amilya (moet open)
#  🪟 ramen - check veranda (moet open)
#  🪟 ramen - check berging (moet open)
#  🪟 ramen - check badkamer (moet open)
#  🪟 ramen - check kamer Alunya (moet open)
#  🪟 ramen - check master bedroom (moet open)
###########################################################################

automation:

- alias: 🪟 ramen - check living (moet open)
  id: '856ea331-ad65-41ec-bb62-5eaceb73c301'
  description: ''
  trigger:
  - platform: state
    entity_id: sensor.gram_water_outside
  - platform: state
    entity_id: sensor.eikenbos_average_temperature  
  - platform: state
    entity_id: sensor.gram_water_living    
  condition:
  - condition: template
    value_template: >
      {{trigger.to_state is not none and
        trigger.from_state is not none and
        trigger.to_state.state != trigger.from_state.state}}
  - condition: numeric_state
    entity_id: sensor.living_temperature
    above: '17'            
  - condition: numeric_state
    entity_id: sensor.living_heating
    below: '0.1'
  - condition: template
    value_template: "{{ states('sensor.eikenbos_temperature_average_forecast_4_hours') | float(default=0) >= 16 }}"
  - condition: or
    conditions:    
      - condition: and
        conditions:
          - condition: state
            entity_id: binary_sensor.gram_water_outside_rising
            state: 'off'
          - condition: template
            value_template: "{{ states('sensor.gram_water_living_diff_outside') | float(default=0) >= 0.5 }}"
      - condition: and
        conditions:
          - condition: state
            entity_id: binary_sensor.gram_water_outside_rising
            state: 'on'
          - condition: template
            value_template: "{{ states('sensor.gram_water_living_diff_outside') | float(default=0) >= 1 }}"
  action:
  - service: input_boolean.turn_on
    target:
      entity_id: input_boolean.living_raam_moet_open
  - service: input_boolean.turn_off
    target:
      entity_id: input_boolean.living_raam_moet_dicht
  mode: restart
  
- alias: 🪟 ramen - check kamer Amilya (moet open)
  id: '8098eb97-2af3-4cb1-a3d7-5f9f6422c3a7'
  description: ''
  trigger:
  - platform: state
    entity_id: sensor.gram_water_outside
  - platform: state
    entity_id: sensor.eikenbos_average_temperature    
  - platform: state
    entity_id: sensor.gram_water_kamer_amilya    
  condition:
  - condition: template
    value_template: >
      {{trigger.to_state is not none and
        trigger.from_state is not none and
        trigger.to_state.state != trigger.from_state.state}}
  - condition: numeric_state
    entity_id: sensor.kamer_amilya_temperature
    above: '17'            
  - condition: numeric_state
    entity_id: sensor.kamer_amilya_heating
    below: '0.1'
  - condition: template
    value_template: "{{ states('sensor.eikenbos_temperature_average_forecast_4_hours') | float(default=0) >= 16 }}"    
  - condition: or
    conditions:    
      - condition: and
        conditions:
          - condition: state
            entity_id: binary_sensor.gram_water_outside_rising
            state: 'off'
          - condition: template
            value_template: "{{ states('sensor.gram_water_kamer_amilya_diff_outside') | float(default=0) >= 0.5 }}"    
      - condition: and
        conditions:
          - condition: state
            entity_id: binary_sensor.gram_water_outside_rising
            state: 'on'
          - condition: template
            value_template: "{{ states('sensor.gram_water_kamer_amilya_diff_outside') | float(default=0) >= 1 }}"
  action:
  - service: input_boolean.turn_on
    target:
      entity_id: input_boolean.kamer_amilya_raam_moet_open
  - service: input_boolean.turn_off
    target:
      entity_id: input_boolean.kamer_amilya_raam_moet_dicht
  mode: restart
  
- alias: 🪟 ramen - check veranda (moet open)
  id: 'fe0b3210-40d0-4983-9da8-ef6aa9b43efe'
  description: ''
  trigger:
  - platform: state
    entity_id: sensor.gram_water_outside
  - platform: state
    entity_id: sensor.eikenbos_average_temperature    
  - platform: state
    entity_id: sensor.gram_water_veranda    
  condition:
  - condition: template
    value_template: >
      {{trigger.to_state is not none and
        trigger.from_state is not none and
        trigger.to_state.state != trigger.from_state.state}}        
  action:
  - condition: numeric_state
    entity_id: sensor.veranda_temperature
    above: '17'            
  - condition: numeric_state
    entity_id: sensor.veranda_heating
    below: '0.1'
  - condition: template
    value_template: "{{ states('sensor.eikenbos_temperature_average_forecast_4_hours') | float(default=0) >= 16 }}"
  - condition: or
    conditions:
      # first possible case
      - condition: and
        conditions:
          - condition: state
            entity_id: binary_sensor.gram_water_outside_rising
            state: 'off'
          - condition: template
            value_template: "{{ states('sensor.gram_water_veranda_diff_outside') | float(default=0) >= 0.5 }}"    
      # second possible case
      - condition: and
        conditions:
          - condition: state
            entity_id: binary_sensor.gram_water_outside_rising
            state: 'on'
          - condition: template
            value_template: "{{ states('sensor.gram_water_veranda_diff_outside') | float(default=0) >= 1 }}"
  - service: input_boolean.turn_on
    target:
      entity_id: input_boolean.veranda_schuifraam_moet_open
  - service: input_boolean.turn_off
    target:
      entity_id: input_boolean.veranda_schuifraam_moet_dicht
  mode: restart
  
- alias: 🪟 ramen - check berging (moet open)
  id: '02c51189-81d3-42ba-9739-be889c5916a0'
  description: ''
  trigger:
  - platform: state
    entity_id: sensor.gram_water_outside
  - platform: state
    entity_id: sensor.eikenbos_average_temperature    
  - platform: state
    entity_id: sensor.gram_water_berging
  condition:
  - condition: template
    value_template: >
      {{trigger.to_state is not none and
        trigger.from_state is not none and
        trigger.to_state.state != trigger.from_state.state}}
  - condition: numeric_state
    entity_id: sensor.berging_temperature
    above: '17'            
  - condition: numeric_state
    entity_id: sensor.berging_heating
    below: '0.1'
  - condition: template
    value_template: "{{ states('sensor.eikenbos_temperature_average_forecast_4_hours') | float(default=0) >= 16 }}"
  - condition: or
    conditions:    
      # first possible case
      - condition: and
        conditions:
          - condition: state
            entity_id: binary_sensor.gram_water_outside_rising
            state: 'off'
          - condition: template
            value_template: "{{ states('sensor.gram_water_berging_diff_outside') | float(default=0) >= 0.5 }}"
          - condition: numeric_state
            entity_id: sensor.berging_temperature
            above: '16.5'             
      # second possible case
      - condition: and
        conditions:
          - condition: state
            entity_id: binary_sensor.gram_water_outside_rising
            state: 'on'
          - condition: template
            value_template: "{{ states('sensor.gram_water_berging_diff_outside') | float(default=0) >= 1 }}"
          - condition: numeric_state
            entity_id: sensor.berging_temperature
            above: '16.5'
  action:
  - service: input_boolean.turn_on
    target:
      entity_id: input_boolean.berging_raam_moet_open
  - service: input_boolean.turn_off
    target:
      entity_id: input_boolean.berging_raam_moet_dicht
  mode: restart
    
- alias: 🪟 ramen - check badkamer (moet open)
  id: '150c22d0-196a-4694-a789-0598f49808f3'
  description: ''
  trigger:
  - platform: state
    entity_id: sensor.gram_water_outside
  - platform: state
    entity_id: sensor.eikenbos_average_temperature
  - platform: state
    entity_id: sensor.gram_water_badkamer
  condition:
  - condition: template
    value_template: >
      {{trigger.to_state is not none and
        trigger.from_state is not none and
        trigger.to_state.state != trigger.from_state.state}}
  - condition: numeric_state
    entity_id: sensor.badkamer_temperature
    above: '16'            
  - condition: numeric_state
    entity_id: sensor.badkamer_heating
    below: '0.1' 
  - condition: template
    value_template: "{{ states('sensor.eikenbos_temperature_average_forecast_4_hours') | float(default=0) >= 16 }}"   
  - condition: or
    conditions:    
      - condition: and
        conditions:
          - condition: state
            entity_id: binary_sensor.gram_water_outside_rising
            state: 'off'
          - condition: template
            value_template: "{{ states('sensor.gram_water_badkamer_diff_outside') | float(default=0) >= 0.5 }}"    
      - condition: and
        conditions:
          - condition: state
            entity_id: binary_sensor.gram_water_outside_rising
            state: 'on'
          - condition: template
            value_template: "{{ states('sensor.gram_water_badkamer_diff_outside') | float(default=0) >= 1 }}"
  action:
    - service: input_boolean.turn_on
      target:
        entity_id: input_boolean.badkamer_raam_moet_open
    - service: input_boolean.turn_off
      target:
        entity_id: input_boolean.badkamer_raam_moet_dicht
  mode: restart

- alias: 🪟 ramen - check gang (moet open)
  id: '9258966d-c945-4e75-b772-d733c55ac44c'
  description: ''
  trigger:
  - platform: state
    entity_id: sensor.gram_water_outside
  - platform: state
    entity_id: sensor.eikenbos_average_temperature    
  - platform: state
    entity_id: sensor.gram_water_gang    
  condition:
  - condition: template
    value_template: >
      {{trigger.to_state is not none and
        trigger.from_state is not none and
        trigger.to_state.state != trigger.from_state.state}}
  - condition: numeric_state
    entity_id: sensor.gang_temperature
    above: '17'            
  - condition: numeric_state
    entity_id: sensor.gang_heating
    below: '0.1'
  - condition: template
    value_template: "{{ states('sensor.eikenbos_temperature_average_forecast_4_hours') | float(default=0) >= 16 }}"
  - condition: or
    conditions:    
      # first possible case
      - condition: and
        conditions:
          - condition: state
            entity_id: binary_sensor.gram_water_outside_rising
            state: 'off'
          - condition: template
            value_template: "{{ states('sensor.gram_water_gang_diff_outside') | float(default=0) >= 0.5 }}"
          - condition: numeric_state
            entity_id: sensor.gang_temperature
            above: '16.5'             
      # second possible case
      - condition: and
        conditions:
          - condition: state
            entity_id: binary_sensor.gram_water_outside_rising
            state: 'on'
          - condition: template
            value_template: "{{ states('sensor.gram_water_gang_diff_outside') | float(default=0) >= 1 }}"
          - condition: numeric_state
            entity_id: sensor.gang_temperature
            above: '16.5'
  action:
  - service: input_boolean.turn_on
    target:
      entity_id: input_boolean.gang_raam_moet_open
  - service: input_boolean.turn_off
    target:
      entity_id: input_boolean.gang_raam_moet_dicht
  mode: restart

- alias: 🪟 ramen - check kamer Alunya (moet open)
  id: 'd75da9b2-9b9a-4700-bd21-85b034add09f'
  description: ''
  trigger:
  - platform: state
    entity_id: sensor.gram_water_outside
  - platform: state
    entity_id: sensor.eikenbos_average_temperature    
  - platform: state
    entity_id: sensor.gram_water_kamer_alunya    
  condition:
  - condition: template
    value_template: >
      {{trigger.to_state is not none and
        trigger.from_state is not none and
        trigger.to_state.state != trigger.from_state.state}}
  - condition: numeric_state
    entity_id: sensor.kamer_alunya_temperature
    above: '17'            
  - condition: numeric_state
    entity_id: sensor.kamer_alunya_heating
    below: '0.1'
  - condition: template
    value_template: "{{ states('sensor.eikenbos_temperature_average_forecast_4_hours') | float(default=0) >= 16 }}"     
  - condition: or
    conditions:    
      - condition: and
        conditions:
          - condition: state
            entity_id: binary_sensor.gram_water_outside_rising
            state: 'off'
          - condition: template
            value_template: "{{ states('sensor.gram_water_kamer_alunya_diff_outside') | float(default=0) >= 0.5 }}"    
      - condition: and
        conditions:
          - condition: state
            entity_id: binary_sensor.gram_water_outside_rising
            state: 'on'
          - condition: template
            value_template: "{{ states('sensor.gram_water_kamer_alunya_diff_outside') | float(default=0) >= 1 }}"
  action:
    - service: input_boolean.turn_on
      target:
        entity_id: input_boolean.kamer_alunya_raam_moet_open
    - service: input_boolean.turn_off
      target:
        entity_id: input_boolean.kamer_alunya_raam_moet_dicht
  mode: restart

- alias: 🪟 ramen - check master bedroom (moet open)
  id: 'f3afd520-1f73-439d-990f-cedc77a0ba10'
  description: ''
  trigger:
  - platform: state
    entity_id: sensor.gram_water_outside
  - platform: state
    entity_id: sensor.eikenbos_average_temperature    
  - platform: state
    entity_id: sensor.gram_water_master_bedroom    
  condition:
  - condition: template
    value_template: >
      {{trigger.to_state is not none and
        trigger.from_state is not none and
        trigger.to_state.state != trigger.from_state.state}}
  - condition: numeric_state
    entity_id: sensor.master_bedroom_temperature
    above: '14.5'            
  - condition: numeric_state
    entity_id: sensor.master_bedroom_heating
    below: '0.1'
  - condition: template
    value_template: "{{ states('sensor.eikenbos_temperature_average_forecast_4_hours') | float(default=0) >= 16 }}"
  - condition: or
    conditions:
      # first possible case: vocht buiten stijgt niet + binnen minstens 0.4 gram vocht meer dan buiten + temp binnen hoger dan 16.5 + temperatuurverschil binnen/buiten minder dan 10°
      - condition: and
        conditions:
          - condition: state
            entity_id: binary_sensor.gram_water_outside_rising
            state: 'off'
          - condition: template
            value_template: "{{ states('sensor.gram_water_master_bedroom_diff_outside') | float(default=0) >= 0.5 }}"    
      # second possible case: vocht buiten stijgt wel + binnen minstens 1 gram vocht meer dan buiten + temp binnen hoger dan 16.5 + temperatuurverschil binnen/buiten minder dan 10°
      - condition: and
        conditions:
          - condition: state
            entity_id: binary_sensor.gram_water_outside_rising
            state: 'on'
          - condition: template
            value_template: "{{ states('sensor.gram_water_master_bedroom_diff_outside') | float(default=0) >= 1 }}"
  action:
  - service: input_boolean.turn_on
    target:
      entity_id: input_boolean.master_bedroom_raam_moet_open
  - service: input_boolean.turn_off
    target:
      entity_id: input_boolean.master_bedroom_raam_moet_dicht
  mode: restart
