############################ Table of Contents ############################ 
# 
#   Automations
#     💡 Amilya niet thuis = licht uit
#     💡 Amilya licht badkamer brandt langer dan 20 minuten
#     💡 Alunya niet thuis = licht uit
#     💡 Alunya lichten uit om 1u en 2u 's nachts
#     💡 bij donker living bol inschakelen
#     💡 Donker, <20° buiten en thuis = licht aan
#     💡 Master bedroom deurswitch
#     💡 Licht in garage aan > 10 min
#     💡 TV aan + zon onder = TV strip aan
#     💡 TV uit = TV strip uit
#     💡 master bedroom TV aan 's avonds = gezellig licht

############################ Automations ################################## 

automation:

#################################################  
# Amilya
#################################################

- alias: 💡 Amilya niet thuis = lichten uit
  id: 'c5fc-389d-42e8-8f3f-78f'
  description: ''
  trigger:
  - platform: state
    entity_id: person.amilya
    to: 'not_home'
    for: 00:03:00
    from: 'home'
  condition: []
  action:
  - service: light.turn_off
    target:
      entity_id:
        - light.amilya_badkamer
        - light.amilya_plafond_1
        - light.amilya_plafond_2
        - light.amilya_bol
        - light.amilya_strip
        - light.amilya_strip
  mode: single
  
- alias: 💡 Amilya licht badkamer brandt langer dan 15 minuten -> licht uit
  id: 3e894234-e24b-4c8c-a497-87a05abc3453
  description: ''
  trigger:
  - platform: state
    entity_id: light.amilya_badkamer
    to: 'on'
    for:
      hours: 0
      minutes: 15
      seconds: 0
      milliseconds: 0
  condition: []
  action:
  - service: light.turn_off
    target:
      entity_id: light.amilya_badkamer
  mode: single

- alias: 💡 Amilya lichtschakelaar deur ingedrukt = badkamerlicht aan voor 2 minuten
  # de andere lichten gaan ook gewoon aan, maar enkel licht badkamer gaat nadien uit
  id: 'd40b0f01-3e2f-4382-9480-971874f9d4f6'
  description: ''
  trigger:
  - device_id: 925e49167bd25df143efa1a2e317424d
    domain: hue
    platform: device
    type: short_release
    subtype: 1
    unique_id: beaaeaf3-d5e1-4d50-8aa9-1dfc2065073e
  condition: []
  action:
  - delay:
      hours: 0
      minutes: 2
      seconds: 0
      milliseconds: 0
  - service: light.turn_off
    target:
      entity_id: light.amilya_badkamer
  mode: single

- alias: 💡 Amilya lichten plafond onbereikbaar = lichten plafond uit
  id: '64602e2b-48aa-4304-809c-387d24ca9eee'
  trigger:
  - platform: state
    entity_id: group.amilya_plafond_1
    to: unavailable
  condition: []
  action:
  - service: light.turn_off
    target:
      entity_id:
      - light.amilya_plafond_1
      - light.amilya_plafond_2
  mode: single


#################################################  
# Alunya
#################################################

- alias: 💡 Alunya niet thuis = licht uit
  id: 'b31b70d7-e8c0-4bb8-8a45-335d57d427b8'
  description: ''
  trigger:
  - platform: state
    entity_id: person.alunya
    to: 'not_home'
    for: 00:03:00
  condition: []
  action:
  - service: light.turn_off
    target:
      entity_id:
        - light.alunya_bol
        - light.alunya_staande_lamp
        - light.alunya_wasbak
  mode: single

- alias: 💡 Alunya lichten uit om 1u, 2u, 3u en 4u 's nachts
  id: 'ee497cc7-cb83-4a8d-afd9-dedaf4fe56ff'
  description: ''
  trigger:
  - platform: time
    at: 01:00:00
  - platform: time
    at: 02:00:00
  - platform: time
    at: 03:00:00
  - platform: time
    at: 04:00:00
  condition: []
  action:
  - service: light.turn_off
    target:
      entity_id:
        - light.alunya_bol
        - light.alunya_staande_lamp
        - light.alunya_wasbak
  mode: single


#################################################  
# living
#################################################

- alias: 💡 Donker, <20° buiten en thuis = licht aan
  id: '9652f025-25a5-4eb0-8eb4-6f61ecb57936'
  description: ''
  trigger:
  - platform: state
    entity_id: sun.sun
    to: 'below_horizon'
  condition:
  - condition: state
    entity_id: person.madouce
    state: home
  - condition: numeric_state
    entity_id: sensor.temp_leuven24_wunderground
    below: '20'
  action:
  - service: light.turn_on
    data:
      transition: 10
      brightness: 26
    target:
      device_id: a0297c6061546a2108b2d33e01ed449d 
  mode: single

- alias: 💡 TV aan + zon onder = TV strip aan
  id: 'decc48cf-f977-42e0-8d54-52cc3fad75d1'
  description: ''
  trigger:
  - platform: state
    entity_id: media_player.ue55ju7000
    from: 'off'
    to: 'on'
  - platform: state
    entity_id: sun.sun
    to: 'below_horizon'
  condition:
  - condition: state
    entity_id: sun.sun
    state: below_horizon
  - condition: state
    entity_id: media_player.ue55ju7000
    state: 'on'
  action:
  - service: light.turn_on
    data:
      transition: 20
      color_temp: 500
      brightness: 100
    target:
      entity_id: light.tv_strip
  - service: light.turn_off
    data: {}
    target:
      entity_id: light.living_bol
  mode: single

- alias: 💡 Google TV living playing + zon onder = Hue sync aan
  id: 'cf1702e9-33d4-43cc-be9c-67cafc91d105'
  trigger:
  - platform: state
    entity_id: media_player.living_google_tv
    to: 'playing'
  condition:
  - condition: state
    entity_id: sun.sun
    state: below_horizon
  action:
    - service: huesyncbox.set_sync_state
      target:
        entity_id: media_player.sync_box
      data:
        sync: true
        mode: video
        intensity: subtle
  mode: single

- alias: 💡 TV uit = TV strip uit
  id: 'dfbb4779-8083-49e3-9b83-b045c4db5d43'
  description: ''
  trigger:
  - platform: state
    entity_id: media_player.ue55ju7000
    from: 'on'
    to: 'off'
  condition: []
  action:
  - service: light.turn_off
    data:
      transition: 10
    target:
      entity_id:
      -  light.tv_strip
  mode: single

- alias: 💡 Het wordt donker = living bol inschakelen
  id: 'd754582e-1ba3-44f2-93ef-32a7f9bbc2af'
  description: ''
  trigger:
  - platform: sun
    event: sunset
  condition: []
  action:
  - service: light.turn_on
    data:
      transition: 20
      color_temp: 473
      brightness_pct: 40
    target:
      entity_id: light.living_bol
  mode: single

- alias: living licht uit wanneer buiten voldoende licht
  id: 'b3a7d875-e7c9-4612-a5a5-407f280c2e78'
  description: ""
  trigger:
    - platform: numeric_state
      entity_id: sensor.oprit_bewegingssensor_light_level
      above: 1000
  condition: []
  action:
    - service: light.turn_off
      data: {}
      target:
        entity_id:
          - light.living_links
          - light.living_rechts
  mode: single

- alias: living licht uit wanneer buiten onvoldoende licht en laptop aan
  id: 'ac4fb59a-e33f-464d-805f-c939d7e0d14e'
  description: ""
  trigger:
    - platform: numeric_state
      entity_id: sensor.oprit_bewegingssensor_light_level
      below: 500
  condition:
    - condition: state
      entity_id: switch.madouce_laptop_tme_a_b_1801581_windows_device
      state: "on"
      for:
        minutes: 30
  action:
    - service: light.turn_on
      data: {}
      target:
        entity_id:
          - light.living_links_2
  mode: single



#################################################  
# Master bedroom
#################################################

- alias: 💡 master bedroom TV aan 's avonds = gezellig licht
  id: 62b15358-7447-43f7-9c76-b2d72db61875
  description: ''
  trigger:
  - platform: state
    entity_id: media_player.master_bedroom_tv
    to: 'playing'
  condition:
  - condition: state
    entity_id: sun.sun
    state: below_horizon
  action:
  - service: light.turn_on
    target:
      entity_id:
      - light.master_bedroom_play_bart
      - light.master_bedroom_play_madouce
      - light.master_bedroom_halve_bol
    data:
      color_name: darkorange
      brightness_pct: 30
  - service: light.turn_off
    target:
      entity_id: light.master_bedroom_staande_lamp
  mode: single

- alias: 💡 Master bedroom deurswitch
  id: '0ca77314-116c-4d39-bf43-fd51e9771514'
  description: ''
  trigger:
  - device_id: 4247e8ef769909d83520323811fc6550
    domain: hue
    platform: device
    type: short_release
    subtype: 1
    unique_id: 6e39bb0e-63cc-4dad-9237-29b7cc04d796
  condition:
  - condition: sun
    after: sunset
  action:
  - service: light.turn_on
    target:
      entity_id:
      - light.master_bedroom_play_madouce
      - light.master_bedroom_play_bart
      - light.master_bedroom_staande_lamp
    data:
      brightness_pct: 75
  mode: single

- alias: 💡 Madouce en Bart niet thuis = licht uit
  id: '428317ff-aba5-4c2e-96c6-e1d97eb6ddb8'
  description: ''
  trigger:
  - platform: state
    entity_id: group.bart_madouce
    to: 'not_home'
    for: 00:03:00
  condition: []
  action:
  - service: light.turn_off
    target:
      entity_id: group.master_bedroom_lichten
  mode: single


#################################################  
# Veranda
#################################################

- alias: veranda licht uit wanneer buiten voldoende licht
  id: 'e10f25e1-54d6-486d-8661-023145492c6b'
  description: ""
  trigger:
    - platform: numeric_state
      entity_id: sensor.terras_light_level
      above: 350
  condition: []
  action:
    - service: light.turn_off
      data: {}
      target:
        entity_id:
          - light.veranda
          - light.veranda_staande_lamp
  mode: single


- alias: veranda licht aan wanneer buiten onvoldoende licht en laptop aan
  id: 'd92b6fd4-f928-422e-a2f0-20604bb7f7cb'
  description: ""
  trigger:
    - platform: numeric_state
      entity_id: sensor.terras_light_level
      below: 350
  condition: 
    - condition: state
      entity_id: switch.bart_laptop_brum05007458
      state: "on"
      for:
        minutes: 30
  action:
    - service: light.turn_on
      data: {}
      target:
        entity_id:
          - light.veranda_staande_lamp
  mode: single


#################################################  
# Gang, toilet, garage
#################################################

- alias: '💡 licht in garage'
  id: c3801d8a-dd6e-444e-9a25-0adc8c0655d8
  description: ''
  trigger:
  - platform: numeric_state
    entity_id: sensor.garage_sensor_light_level
    for:
      hours: 0
      minutes: 10
      seconds: 0
      milliseconds: 0
    above: '4'
  condition: []
  action:
  - repeat:
      while:
      - condition: numeric_state
        entity_id: sensor.garage_sensor_light_level
        above: '4'
      sequence:
      - service: notify.bart_phone
        data:
          message: >
            {% set s = ( as_timestamp(now()) - as_timestamp(state_attr('automation.licht_in_garage','last_triggered')) )|int %}
            Licht in garage brandt al {{ '%02du%02d' % ((s/3600)|int, (s%3600)/60) }}.
          title: Licht in garage
          data:
            color: blue
            tag: garage_licht
      - delay:
          minutes: 5
  - service: notify.bart_phone
    data:
      message: "clear_notification"
      data:
        tag: garage_licht
  - service: notify.madouce_phone
    data:
      message: "clear_notification"
      data:
        tag: garage_licht
  mode: single

- alias: 💡 licht gang uit na 3 minuten
  id: 'd268f950-cbb3-4220-a017-850bb950ec4a'
  description: ''
  trigger:
  - platform: device
    type: turned_on
    device_id: dfa6e3e21463bd9dd78d7797538d0856
    entity_id: light.gang_spot_achter
    domain: light
    for:
      hours: 0
      minutes: 3
      seconds: 0
  condition: []
  action:
  - service: light.turn_off
    target:
      entity_id:
        - light.gang_spot_achter
        - light.gang_spot_midden
        - light.gang_spot_voor
  mode: single

- alias: 💡 licht toilet uit na 5 minuten
  id: cb7ab5c4-1930-4495-a55a-85d1d6e26a8b
  description: ''
  trigger:
  - platform: state
    entity_id: light.toilet
    to: 'on'
    for: '00:05:00'
  condition: []
  action:
  - service: light.turn_off
    target:
      entity_id:
      - light.toilet
  mode: single

- alias: 💡 licht toilet 's nachts gedimd
  id: be544a45-af8d-4b1a-b5d9-69c5591f44d6
  description: ''
  trigger:
  - platform: state
    entity_id: light.toilet
    to: 'on'
  condition:
  - condition: time
    after: '22:30:00'
    before: '07:00:00'
  action:
  - service: light.turn_on
    data:
      kelvin: 1500
      brightness_pct: 40
    target:
      entity_id: light.toilet
  mode: single
  
- alias: 💡 licht toilet overdag helder
  id: 94fb34e5-4b03-49b9-9586-f922960cb5c0
  description: ''
  trigger:
  - platform: state
    entity_id: light.toilet
    to: 'on'
  condition:
  - condition: time
    after: '07:00:00'
    before: '23:00:00'
  action:
  - service: light.turn_on
    data:
      kelvin: 2500
      brightness_pct: 100
    target:
      entity_id: light.toilet
  mode: single  

- alias: "💡 licht gang: zon onder = gedimd"
  id: 151c0615-8998-408b-a0ab-0a31af6c3ea8
  description: ''
  trigger:
  - platform: state
    entity_id: light.gang
    to: 'on'
  condition:
  - condition: state
    entity_id: sun.sun
    state: "below_horizon"
  action:
  - service: light.turn_on
    data:
      kelvin: 1500
      brightness_pct: 20
    target:
      entity_id: light.gang
  mode: single

- alias: "💡 licht gang: zon op = helder"
  id: 80b10678-6e3b-41a7-ba87-fdb427cfc2ce
  description: ''
  trigger:
  - platform: state
    entity_id: light.gang
    to: 'on'
  condition:
  - condition: state
    entity_id: sun.sun
    state: "above_horizon"
  action:
  - service: light.turn_on
    data:
      kelvin: 2500
      brightness_pct: 60
    target:
      entity_id: light.gang
  mode: single
