automation:

- alias: 🛌 Madouce thuis en <15° buiten = matras aan om 22u00
  id: d71eddad-0ba8-45b3-84e7-8be3589de0fc
  description: ''
  trigger:
  - platform: time
    at: '22:00'
  condition:
  - condition: state
    entity_id: person.madouce
    state: home
  - condition: numeric_state
    entity_id: sensor.eikenbos_openweather_temperature
    below: '15'
  action:
  - service: switch.turn_on
    target:
      entity_id: switch.madouce_matrasverwarmer
  mode: single

- alias: 🛌 Bij thuiskomst Madouce na 22u15, matras inschakelen
  id: f66e33c4-88b9-4a32-9e15-7d38d5e7120e
  description: ''
  trigger:
  - platform: state
    entity_id: person.madouce
    from: 'not_home'
    to: 'home'
  condition:
  - condition: time
    after: '22:15'
    before: '02:00'
  - condition: numeric_state
    entity_id: sensor.eikenbos_openweather_temperature
    below: '15'
  action:
  - service: switch.turn_on
    target:
      entity_id: switch.madouce_matrasverwarmer
  - service: notify.madouce_phone
    data:
      title: Matrasverwarming ingeschakeld.
      message: Geniet er dadelijk van ;)
  mode: single

- alias: 🛌 Madouce thuis en <15° in slaapkamer = matras aan om 1u, 2u, 3u, 4u en 5u gedurende 10 min.
  id: ad5d827e-8978-4b83-84cd-8260167f51f2
  description: ''
  trigger:
  - platform: time
    at: 
      - '01:00'
      - '02:00'
      - '03:00'        
      - '04:00'
      - '05:00'
      - '06:00'        
  condition:
  - condition: state
    entity_id: person.madouce
    state: home
  - condition: numeric_state
    entity_id: sensor.master_bedroom_temperature
    below: '15'
  action:
  - service: switch.turn_on
    target:
      entity_id: switch.madouce_matrasverwarmer
  - wait_template: ''
    timeout: '00:10:00'
  - service: switch.turn_off
    target:
      entity_id: switch.madouce_matrasverwarmer
  mode: single

- alias: 🛌 Matras uitschakelen als die al 1 uur aanstaat
  id: 6e09a54d-530d-4e8e-a9dd-8af7b9ec7554
  description: ''
  trigger:
  - platform: state
    entity_id: switch.madouce_matrasverwarmer
    to: 'on'
    for:
      hours: 1
      minutes: 0
      seconds: 0
      milliseconds: 0
  condition: []
  action:
  - service: switch.turn_off
    target:
      entity_id: switch.madouce_matrasverwarmer
  mode: single
  
