automation:

- alias: 🐱 Katten eten geven
  id: 9c495009-925f-4d76-a6ee-6fd89d309cd5
  description: ""
  trigger:
    - platform: time
      at: "05:00:00"
    - platform: time
      at: "07:00:00"
    - platform: time
      at: "09:00:00"
    - platform: time
      at: "13:00:00"      
    - platform: time
      at: "17:30:00"
    - platform: time
      at: "17:40:00"      
    - platform: time
      at: "22:00:00"
  condition: []
  action:
    - service: button.press
      data: {}
      target:
        entity_id: button.pet_feeder_feed
    - wait_template: ""
      timeout: "00:00:05"
  mode: single