automation:

- alias: security // Niemand meer thuis = check ramen wijd open en schuiframen
  id: '9c3567c0-ab6a-4ac9-83c9-82280a299e14'
  description: ''
  trigger:
  - platform: state
    entity_id: group.gezin
    to: not_home
  condition:
  - condition: state
    entity_id: group.alle_ramen_wijd_en_schuiframen
    state: 'on'
  action:
  - service: notify.bart_phone
    data:
      message: TTS
      data:
        tts_text: >
          Er staan nog ramen wijd open!
          {{expand(states.binary_sensor.kamer_alunya_schuifraam, states.binary_sensor.veranda_schuifraam, states.binary_sensor.badkamer_raam_wijd, states.binary_sensor.master_bedroom_raam_wijd) | selectattr('state','eq','on') | map(attribute='name') | list | join(', ') }}
        color: red
        actions:
        - action: URI
          title: Meer info
          uri: /lovelace/alarm
        vibrationPattern: 10, 10, 10, 10, 10, 10, 10
        media_stream: alarm_stream
  - service: notify.bart_madouce_phone
    data:
      title: Niemand thuis en ramen open
      message: >
        Het volgende raam staat nog open:
        {{expand(states.binary_sensor.kamer_alunya_schuifraam, states.binary_sensor.veranda_schuifraam, states.binary_sensor.badkamer_raam_wijd, states.binary_sensor.master_bedroom_raam_wijd) | selectattr('state','eq','on') | map(attribute='name') | list | join(', ') }}
      data:
        color: red
  mode: single         

- alias: security // Niemand meer thuis en Bart in auto = check open ramen
  id: 'ab53dc1d-a37e-4c56-a18b-d39bdddb5b17'
  description: ''
  trigger:
  - platform: state
    entity_id: group.gezin
    to: not_home
  condition:
  - condition: state
    entity_id: group.alle_ramen
    state: 'on'
  - condition: state
    entity_id: binary_sensor.bart_phone_connected_to_car_1
    state: 'on'    
  action:
  - service: notify.bart_phone
    data:
      message: TTS
      data:
        tts_text: >
          Er staan nog ramen open!
          {{expand(states.binary_sensor.badkamer_raam_kantel, states.binary_sensor.badkamer_raam_wijd, states.binary_sensor.berging_raam, states.binary_sensor.kamer_alunya_raam, states.binary_sensor.kamer_amilya_raam, states.binary_sensor.kamer_alunya_schuifraam, states.binary_sensor.keuken_raam, states.binary_sensor.living_oprit_raam, states.binary_sensor.living_tuin_raam, states.binary_sensor.master_bedroom_raam_kantel, states.binary_sensor.master_bedroom_raam_wijd, states.binary_sensor.veranda_schuifraam) | selectattr('state','eq','on') | map(attribute='name') | list | join(', ') }}
        color: red
        actions:
        - action: URI
          title: Meer info
          uri: /lovelace/alarm
        vibrationPattern: 10, 10, 10, 10, 10, 10, 10
        media_stream: alarm_stream
  - service: notify.bart_madouce_phone
    data:
      title: Niemand thuis en ramen open
      message: Er staan nog ramen open.
      data:
        color: red
  mode: single

