automation:
 
- alias: snelle polling sensoren berekening verbruik
  id: '92e4e452-ebb1-4db1-9b6a-0c1566a40b0c'
  description: ''
  trigger:
  - platform: time_pattern
    seconds: /30
  condition: []
  action:
  - service: homeassistant.update_entity
    target:
      entity_id:
      - sensor.solar_power
      - sensor.huisverbruik
      - sensor.net_power
  mode: single

- alias: injectie meer dan 2,5 kW = melding dat auto kan worden geladen of machine aangezet
  id: '2d15d773-5a7f-4c83-ab27-fceef60120ae'
  description: ""
  mode: single
  trigger:
    - platform: numeric_state
      entity_id: sensor.net_power
      for:
        hours: 0
        minutes: 10
        seconds: 0
      below: "-2500"
  condition: []
  action:
  - if:
    - condition: template
      # check in calendar if car is supposed to be at home
      value_template: >
        {% set t = 'input_select.car_use_day_' ~ now().date().isoweekday() %}
        {% set loc = states(t) %}
        {% if loc =="thuis" %}true
        {% endif %}
    then:
      - service: notify.bart_phone
        data:
          title: Gebruik de zonne-energie verstandig
          message: >
            Nu {{ states('sensor.net_power') | float | round(0) | abs }} W injectie in het net.<br>
            Eventueel auto laden? Auto nu {{states('sensor.car_1_soc') | round()}}%.<br>
            Vandaag moet er geladen worden tot {{states('input_number.car_charge_target_percentage') | round() }}%.
          data:
            color: yellow
            tag: solar
            channel: solar
            timeout: 3600
    else:
      - service: notify.bart_phone
        data:
          title: Gebruik de zonne-energie verstandig
          message: >
            Nu {{ states('sensor.net_power') | float | round(0) | abs }} W injectie in het net.<br>
            Eventueel vaatwasser, wasmachine of droger aanzetten?
          data:
            color: yellow
            tag: solar
            channel: solar
            timeout: 3600

- alias: Meer dan 4 kW verbruik van het net = melding
  id: '518c0b8f-2031-49cc-bbac-210b2728df07'
  description: ""
  mode: single
  trigger:
    - platform: numeric_state
      entity_id: sensor.net_power
      for:
        hours: 0
        minutes: 5
        seconds: 0
      above: "4000"
  condition: []
  action:
    - service: notify.bart_phone
      data:
        title: Hoog energieverbruik
        message: "Er wordt nu {{ states('sensor.net_power') }} kW verbruikt van het net."
        data:
          notification_icon: "mdi:lightning-bolt"
          color: red
          actions:
          - action: URI
            title: meer info
            uri: /lovelace-verbruik/zonne-energie

- alias: "solar // einde van de zonne-energie productie voor vandaag"
  id: '9a576f40-1363-466d-bab3-915845c02e49'
  description: ''
  trigger:
    - platform: numeric_state
      entity_id: sensor.solar_power
      for:
        hours: 0
        minutes: 10
        seconds: 0
      below: "1"
  condition: []
  action:
    - service: notify.bart_phone
      data:
        title: Zonne-energie
        message: >
          Vandaag heeft de zon {{ states('sensor.sma_today') }} kWh opgebracht.<br>
          Morgen wordt er {{ states('sensor.solar_sim_energy_tomorrow_adj') }} kWh verwacht.
        data:
          notification_icon: mdi:sun-wireless-outline
  mode: single

- alias: solar // bewaar zonneproductie van vandaag
  id: "e1f01cf4-6cca-4cdc-81ff-372f65eabffd"  
  description: ""
  trigger:
    - platform: time
      at: "23:45:00"
  condition: []
  action:
  - service: input_number.set_value
    data:
      value: "{{ states('sensor.sma_today') }}"
    target:
      entity_id: input_number.solar_production_endofday
  mode: single 