############################ Table of Contents ############################ 
# 
#   Automations
#     UV index is 2 of 3 = waarschuwing Bart
#     UV index is 4 of 5 = waarschuwing Bart
#     UV index is 6 of 7 = waarschuwing Bart
#     UV index is 2 of 3 = waarschuwing Madouce
#     UV index is 4 of 5 = waarschuwing Madouce
#     UV index is 6 of 7 = waarschuwing Madouce


############################ Automations ################################## 

automation:

- alias: "😎 UV index is 2 of 3 = waarschuwing Bart"
  id: '119b14e0-0b5e-4d5c-ab73-757ed1095b40'
  description: ''
  trigger:
  - platform: state
    entity_id: sensor.eikenbos_uv_index
    to: '2'
    for: '00:25:00'
  - platform: state
    entity_id: sensor.eikenbos_uv_index
    to: '3'
    for: '00:25:00'
  condition:
  - condition: state
    entity_id: person.bart
    state: home
  action:
  - service: notify.bart_phone
    data:
      title: Zon & gezondheid
      message: "UV-index is hoog: {{states('sensor.eikenbos_uv_index')}}. Huid verbrandt langzaam."
      data:
        color: yellow
        tag: uv_index
        channel: uv_index
        timeout: 10800  # 3 hours        
  mode: single

- alias: "😎 UV index is 4 of 5 = waarschuwing Bart"
  id: '266afd3d-8a25-4be5-8f3f-25462882babd'
  description: ''
  trigger:
  - platform: state
    entity_id: sensor.eikenbos_uv_index
    to: '4'
    for: '00:25:00'
  - platform: state
    entity_id: sensor.eikenbos_uv_index
    to: '5'
    for: '00:25:00'
  condition:
  - condition: state
    entity_id: person.bart
    state: home
  action:
  - service: notify.bart_phone
    data:
      title: "Zon & gezondheid: waarschuwing"
      message: "UV-index is zeer hoog: {{states('sensor.eikenbos_uv_index')}}. Huid verbrandt gemakkelijk."
      data:
        color: yellow
        tag: uv_index
        channel: uv_index
        timeout: 10800  # 3 hours
  mode: single

- alias: "😎 UV index is 6 of 7 = waarschuwing Bart"
  id: 'f1a05abf-73ba-45e6-b692-07cc83b2f692'
  description: ''
  trigger:
  - platform: state
    entity_id: sensor.eikenbos_uv_index
    to: '6'
    for: '00:25:00'
  - platform: state
    entity_id: sensor.eikenbos_uv_index
    to: '7'
    for: '00:25:00'
  condition:
  - condition: state
    entity_id: person.bart
    state: home
  action:
  - service: notify.bart_phone
    data:
      title: "Zon & gezondheid: gevaar"
      message: "UV-index is extreem hoog: {{states('sensor.eikenbos_uv_index')}}. Huid verbrandt zeer snel."
      data:
        color: red
        tag: uv_index
        channel: uv_index
        timeout: 10800  # 3 hours        
  mode: single

- alias: "😎 UV index is 2 of 3 = waarschuwing Madouce"
  id: '84abc4ac-740c-4fcf-a3d2-0ae1e161a5fa'
  description: ''
  trigger:
  - platform: state
    entity_id: sensor.eikenbos_uv_index
    to: '2'
    for: '00:25:00'
  - platform: state
    entity_id: sensor.eikenbos_uv_index
    to: '3'
    for: '00:25:00'
  condition:
  - condition: state
    entity_id: person.madouce
    state: home
  action:
  - service: notify.madouce_phone
    data:
      title: Zon & gezondheid
      message: "UV-index is hoog: {{states('sensor.eikenbos_uv_index')}}. Huid verbrandt langzaam."
      data:
        color: yellow
        tag: uv_index
        channel: uv_index
        timeout: 10800  # 3 hours        
  mode: single

- alias: "😎 UV index is 4 of 5 = waarschuwing Madouce"
  id: 'ff7aa798-78d6-4911-9c41-903085b30ce2'
  description: ''
  trigger:
  - platform: state
    entity_id: sensor.eikenbos_uv_index
    to: '4'
    for: '00:25:00'
  - platform: state
    entity_id: sensor.eikenbos_uv_index
    to: '5'
    for: '00:25:00'
  condition:
  - condition: state
    entity_id: person.madouce
    state: home
  action:
  - service: notify.madouce_phone
    data:
      title: "Zon & gezondheid: waarschuwing"
      message: "UV-index is zeer hoog: {{states('sensor.eikenbos_uv_index')}}. Huid verbrandt gemakkelijk."
      data:
        color: yellow
        tag: uv_index
        channel: uv_index
        timeout: 10800  # 3 hours        
  mode: single

- alias: "😎 UV index is 6 of 7 = waarschuwing Madouce"
  id: '587fc24a-1dde-4cec-8d00-18cb593abb99'
  description: ''
  trigger:
  - platform: state
    entity_id: sensor.eikenbos_uv_index
    to: '6'
    for: '00:25:00'
  - platform: state
    entity_id: sensor.eikenbos_uv_index
    to: '7'
    for: '00:25:00'
  condition:
  - condition: state
    entity_id: person.madouce
    state: home
  action:
  - service: notify.madouce_phone
    data:
      title: "Zon & gezondheid: gevaar"
      message: "UV-index is extreem hoog: {{states('sensor.eikenbos_uv_index')}}. Huid verbrandt zeer snel."
      data:
        color: red
        tag: uv_index
        channel: uv_index
        timeout: 10800  # 3 hours        
  mode: single  