sensor:
  - platform: afvalbeheer
    wastecollector: RecycleApp
    resources:
      - restafval
      - gft
      - papier
      - pmd
    postcode: 3010
    streetname: !secret streetname
    streetnumber: 25
    upcomingsensor: 1
    dateformat: '%d-%m'
    dateonly: 0
    dayofweek: 1
    name: ""
    nameprefix: 1
    builtinicons: 1
    builtiniconsnew: 0
    dutch: 1