schedule:
  living_normal_temperature_schema:
    name: "living normale temperatuur schema"
    monday:
      - from: "06:45:00"
        to: "19:00:00"
    tuesday:
      - from: "06:45:00"
        to: "19:00:00"
    wednesday:
      - from: "06:45:00"
        to: "19:00:00"
    thursday:
      - from: "06:45:00"
        to: "19:00:00"
    friday:
      - from: "06:45:00"
        to: "19:00:00"
    saturday:
      - from: "10:00:00"
        to: "19:00:00"
    sunday:
      - from: "10:30:00"
        to: "19:00:00"

  living_comfort_temperature_schema:
    name: "living comfort temperatuur schema"
    monday:
      - from: "19:02:00"
        to: "22:00:00"
    tuesday:
      - from: "19:02:00"
        to: "22:00:00"
    wednesday:
      - from: "19:02:00"
        to: "22:00:00"
    thursday:
      - from: "19:02:00"
        to: "22:00:00"
    friday:
      - from: "19:02:00"
        to: "22:30:00"
    saturday:
      - from: "19:02:00"
        to: "22:30:00"
    sunday:
      - from: "19:02:00"
        to: "22:00:00"

  kamer_alunya_normal_temperature_schema:
    name: "Kamer Alunya normale temperatuur schema"
    # monday:
    #   - from: "7:00:00"
    #     to: "7:00:00"
    # tuesday:
    #   - from: "07:00:00"
    #     to: "07:00:00"
    # wednesday:
    #   - from: "07:00:00"
    #     to: "07:00:00"
    # thursday:
    #   - from: "07:00:00"
    #     to: "07:00:00"
    # friday:
    #   - from: "07:00:00"
    #     to: "07:00:00"
    saturday:
      - from: "10:00:00"
        to: "22:00:00"
    sunday:
      - from: "10:00:00"
        to: "22:00:00"  

  kamer_amilya_normal_temperature_schema:
    name: "Kamer Amilya normale temperatuur schema"
    # monday:
    #   - from: "7:00:00"
    #     to: "7:00:00"
    # tuesday:
    #   - from: "07:00:00"
    #     to: "07:00:00"
    # wednesday:
    #   - from: "07:00:00"
    #     to: "07:00:00"
    # thursday:
    #   - from: "07:00:00"
    #     to: "07:00:00"
    # friday:
    #   - from: "07:00:00"
    #     to: "07:00:00"
    saturday:
      - from: "10:00:00"
        to: "22:00:00"
    sunday:
      - from: "10:00:00"
        to: "22:00:00"        