sensor:
  - platform: buienalarm
    timeframe: 15
    name: buienalarm_15min
    monitored_conditions:
      - temperature
      - precipitation
      - precipitation_forecast_average
      - precipitation_forecast_total
      - next_rain_forecast

  - platform: buienalarm
    timeframe: 30
    name: buienalarm_30min
    monitored_conditions:
      - temperature
      - precipitation
      - precipitation_forecast_average
      - precipitation_forecast_total
      - next_rain_forecast

template:
  - sensor:
    - name: "Regenvoorspelling (min)"
      unique_id: c0e02c76-e44e-4d40-8ded-d09146ea27e1
      unit_of_measurement: "min"
      state: >
        {% if as_timestamp(states('sensor.buienalarm_15min_next_rain_forecast')) %}
          {{ ( ( as_timestamp(states('sensor.buienalarm_15min_next_rain_forecast')) - as_timestamp(now()) ) / 60 ) | round }}
        {% else %}
          {{ states('nonexistent') }}
        {% endif %}

    - name: buienalarm_precipitation_forecast_level
      unique_id: 8c5e4e22-4cf3-49cf-8ce6-026681c64898
      state: >
        {% set value = states('sensor.buienalarm_15min_precipitation_forecast_average') |float %}
        {% if value < 0.1 %}
          0
        {% elif value < 1 %}
          1
        {% elif value < 3 %}
          2
        {% elif value < 10 %}
          3
        {% elif value >=10 %}
          4
        {% else %}
          unavailable
        {% endif %}
      icon: hass:weather-pouring
      attributes:
        label: >
          {% set value = states('sensor.buienalarm_15min_precipitation_forecast_average') |float %}
          {% if value < 0.1 %}
            Geen neerslag
          {% elif value < 1 %}
            Lichte neerslag
          {% elif value < 3 %}
            Matige neerslag
          {% elif value < 10 %}
            Zware neerslag
          {% elif value >=10 %}
            Zware buien
          {% else %}
            unavailable
          {% endif %}