template:
  - sensor:
      - name: "car charge stoptimer starttime"
        state: >
          {% set remaining_minutes = states('sensor.car_remaining_charge_minutes_fix_power') | int(default=0) %}
          {{ strptime((as_timestamp(states('input_datetime.car_charge_target_time')) - (( remaining_minutes | float(default=0) + 10 ) * 60) ) | timestamp_custom('%Y-%m-%d %H:%M',false), '%Y-%m-%d %H:%M') }}
