
sensor:
- platform: template
  sensors:
    power_peak:
      friendly_name: piekvermogen deze maand
      unique_id: 'f793ef1d-792b-4fc4-aa85-2ad8f0d75d1e'
      unit_of_measurement: kW
      device_class: power
      value_template: >
        {% set peak = ((states.sensor.quarter_hourly_net_power.state | float(default=0)) * 4) %}
        {% set max_peak = (states.input_number.power_peak.state | float(default=0)) %}
        {% macro max(X, Y) -%} {{X|float if X|float > Y|float else Y|float }} {%- endmacro %}
        {{ max(max_peak, peak) }}

    current_power_peak:
      friendly_name: huidig kwartiervermogen 
      unique_id: 'fe54f2c8-45f1-4d18-8d8b-b5d4ff0c6ef0'
      unit_of_measurement: kW
      device_class: power
      value_template: >
        {{ ( states('sensor.quarter_hourly_net_power') | round(2) ) * 4 }}

    expected_power_peak:
      friendly_name: verwacht piekvermogen
      unique_id: '3a56a4b4-9f6b-490f-b6ba-3a35cb7385aa'
      unit_of_measurement: kW
      device_class: power
      value_template: >
        {% set now = as_timestamp(now()) %}
        {% set quarter_hour = ((now // 900) * 900) %}
        {% set minutes = max(1, ((now - quarter_hour) % 900) // 60) | int %}
        {% set power = ( states('sensor.quarter_hourly_net_power') | round(2) ) * 4 %}
        {{ ((power / minutes) * 15 )| round(2) }}     

    power_peak_year:
      friendly_name: Gemiddelde jaarpiek
      unique_id: 113c7524-3a86-4930-86b7-ee941461742c
      unit_of_measurement: kW
      device_class: power
      value_template: >
        {{ (( states('input_number.power_peak_month_1') | float(default=0) +
              states('input_number.power_peak_month_2') | float(default=0) +
              states('input_number.power_peak_month_3') | float(default=0) +
              states('input_number.power_peak_month_4') | float(default=0) +
              states('input_number.power_peak_month_5') | float(default=0) +
              states('input_number.power_peak_month_6') | float(default=0) +
              states('input_number.power_peak_month_7') | float(default=0) +
              states('input_number.power_peak_month_8') | float(default=0) +
              states('input_number.power_peak_month_9') | float(default=0) +
              states('input_number.power_peak_month_10') | float(default=0) +
              states('input_number.power_peak_month_11') | float(default=0) +
              states('input_number.power_peak_month_12') | float(default=0) ) / 12) | round(2)
        }}


###########################################
# helpers voor berekening capaciteitstarief
###########################################

utility_meter:
  quarter_hourly_net_power:
    source: sensor.net_power_in_kwh
    cycle: quarter-hourly

input_datetime:
  power_peak_date_time:
    has_date: true
    has_time: true

input_number:
  power_peak:
      name: Piek deze maand
      min: 0
      max: 20000
      step: 0.001
      mode: box
      unit_of_measurement: kW

  power_peak_month_1:
    name: Piek januari
    min: 0
    max: 20
    step: 0.001
    mode: box
    unit_of_measurement: kW

  power_peak_month_2:
    name: Piek februari
    min: 0
    max: 20
    step: 0.001
    mode: box
    unit_of_measurement: kW

  power_peak_month_3:
    name: Piek maart
    min: 0
    max: 20
    step: 0.001
    mode: box
    unit_of_measurement: kW

  power_peak_month_4:
    name: Piek april
    min: 0
    max: 20
    step: 0.001
    mode: box
    unit_of_measurement: kW

  power_peak_month_5:
    name: Piek mei
    min: 0
    max: 20
    step: 0.001
    mode: box
    unit_of_measurement: kW

  power_peak_month_6:
    name: Piek juni
    min: 0
    max: 20
    step: 0.001
    mode: box
    unit_of_measurement: kW

  power_peak_month_7:
    name: Piek juli
    min: 0
    max: 20
    step: 0.001
    mode: box
    unit_of_measurement: kW

  power_peak_month_8:
    name: Piek augustus
    min: 0
    max: 20
    step: 0.001
    mode: box
    unit_of_measurement: kW    

  power_peak_month_9:
    name: Piek september
    min: 0
    max: 20
    step: 0.001
    mode: box
    unit_of_measurement: kW

  power_peak_month_10:
    name: Piek oktober
    min: 0
    max: 20
    step: 0.001
    mode: box
    unit_of_measurement: kW

  power_peak_month_11:
    name: Piek november
    min: 0
    max: 20
    step: 0.001
    mode: box
    unit_of_measurement: kW

  power_peak_month_12:
    name: Piek december
    min: 0
    max: 20
    step: 0.001
    mode: box
    unit_of_measurement: kW

  