
###############################################################################
# sensors for Alfen Eve Pro charge point 
###############################################################################

template:
  - sensor:
      - name: mode3_sanitized
        force_update: true
        state: "{{states('sensor.charger_mode3_state').replace('\0','') }}"
      - name: charger_status
        force_update: true
        state: >
          {% set m3 = states('sensor.mode3_sanitized') %}
          {% if m3 in ['A', 'E'] %} available
          {% elif m3 in ['B1', 'B2', 'C1', 'D1'] %} connected
          {% elif m3 in ['C2', 'D2'] %} charging
          {% else %} {{ m3 }}
          {% endif %}
