input_datetime:
  badkamer_dehumidifier_start_time:
    name: "badkamer ontvochtiger starttijd"
    has_date: true
    has_time: true

  badkamer_dehumidifier_stop_time:
    name: "badkamer ontvochtiger eindtijd"
    has_date: true
    has_time: true

  master_bedroom_dehumidifier_start_time:
    name: "master bedroom ontvochtiger starttijd"
    has_date: true
    has_time: true

  master_bedroom_dehumidifier_stop_time:
    name: "master bedroom ontvochtiger eindtijd"
    has_date: true
    has_time: true

input_select:
  badkamer_dehumidifier_state:
    name: "badkamer onvochtiger status"
    options:
      - aan
      - uit

  master_bedroom_dehumidifier_state:
    name: "master bedroom onvochtiger status"
    options:
      - aan
      - uit

input_number:
  badkamer_dehumidifier_timer_minutes:
    name: ontvochtigen met ontvochtiger
    min: 0
    max: 240
    step: 5
    mode: box

  master_bedroom_dehumidifier_timer_minutes:
    name: ontvochtigen met master bedroom ontvochtiger
    min: 0
    max: 240
    step: 5
    mode: box


input_boolean:
  # toggle om te zien of ontvochtiger extra draait of door noodzaak (vb. douche)
  badkamer_dehumidifier_extrarun:
    name: extra ontvochtigen

  master_bedroom_dehumidifier_extrarun:
    name: extra ontvochtigen    

timer:
  badkamer_dehumidifier_timer:
    name: "onvochtiger timer"
    duration: "00:30:00"
    restore: true
    icon: mdi:clock

  master_bedroom_dehumidifier_timer:
    name: "master bedroom onvochtiger timer"
    duration: "00:30:00"
    restore: true
    icon: mdi:clock

sensor:
  - platform: integration
    source: sensor.badkamer_dehumidifier_power
    name: ontvochtiger energieverbruik
    unit_prefix: k
    round: 2
    method: left
    # apparaten die bij het starten pieken veroorzaken, moeten de left methode gebruiken
    # creates a sensor called sensor.ontvochtiger_energieverbruik

utility_meter:
  badkamer_dehumidifier_energy_daily:
    source: sensor.ontvochtiger_energieverbruik
    cycle: daily