input_datetime:
  dehumidifier_start_time:
    name: "ontvochtiger starttijd"
    has_date: true
    has_time: true

  dehumidifier_stop_time:
    name: "ontvochtiger eindtijd"
    has_date: true
    has_time: true

  dehumidifier_2_start_time:
    name: "ontvochtiger 2 starttijd"
    has_date: true
    has_time: true

  dehumidifier_2_stop_time:
    name: "ontvochtiger 2 eindtijd"
    has_date: true
    has_time: true

input_select:
  dehumidifier_state:
    name: "onvochtiger status"
    options:
      - aan
      - uit

  dehumidifier_2_state:
    name: "onvochtiger 2 status"
    options:
      - aan
      - uit

input_number:
  dehumidifier_timer_minutes:
    name: ontvochtigen met ontvochtiger
    min: 0
    max: 240
    step: 5
    mode: box

  dehumidifier_2_timer_minutes:
    name: ontvochtigen met ontvochtiger 2
    min: 0
    max: 240
    step: 5
    mode: box


input_boolean:
  # toggle om te zien of ontvochtiger extra draait of door noodzaak (vb. douche)
  dehumidifier_1_extrarun:
    name: extra ontvochtigen

  dehumidifier_2_extrarun:
    name: extra ontvochtigen    

timer:
  dehumidifier_timer:
    name: "onvochtiger timer"
    duration: "00:30:00"
    restore: true
    icon: mdi:clock

  dehumidifier_2_timer:
    name: "onvochtiger 2 timer"
    duration: "00:30:00"
    restore: true
    icon: mdi:clock

sensor:
  - platform: integration
    source: sensor.dehumidifier_power
    name: ontvochtiger energieverbruik
    unit_prefix: k
    round: 2
    method: left
    # apparaten die bij het starten pieken veroorzaken, moeten de left methode gebruiken
    # creates a sensor called sensor.ontvochtiger_energieverbruik

utility_meter:
  dehumidifier_energy_daily:
    source: sensor.ontvochtiger_energieverbruik
    cycle: daily