input_number:
  heating_threshold_temperature_min:
    name: "verwarmingsdrempel lage temperatuur"
    min: -30
    max: 50
    step: 0.1
    unit_of_measurement: °C
    mode: box

  heating_threshold_temperature_max:
    name: "verwarmingsdrempel max temperatuur"
    min: -30
    max: 50
    step: 0.1
    unit_of_measurement: °C
    mode: box
    
  living_target_temperature:
    name: "living doeltemperatuur (verwarmen met zonne-energie)"
    min: 14
    max: 23
    step: 0.5

  living_airco_injection:
    name: "verwarmen living starten bij injectie"
    min: 0
    max: 3000
    step: 50

  alunya_airco_injection:
    name: "verwarmen kamer Alunya starten bij injectie"
    min: 0
    max: 3000
    step: 50  

input_select:
  heating_mode_from_weather_forecast:
    options:
      - 'off'
      - 'eco'
      - 'on'

  heating_mode:
    options:
      - 'airco'
      - 'centrale verwarming'

  living_heating_mode:
    options:
      - 'airco'
      - 'centrale verwarming'

  kamer_alunya_heating_mode:
    options:
      - 'airco'
      - 'centrale verwarming'

input_text:
  heating_mode_from_weather_forecast_log:
    max: 255

  heating_season_startdate:
  
  heating_season_stopdate:

input_boolean:
  badkamer_18graden:
    name: badkamer 18 graden
    icon: mdi:radiator

  heating_season:
    name: stookseizoen
    icon: mdi:radiator

  cooling_season:
    name: koelseizoen
    icon: mdi:snowflake

input_datetime:
  badkamer_18graden_starttime:
    name: badkamer 18 graden start
    has_date: true
    has_time: true

sensor:
  - platform: statistics
    name: "living gem. verwarming laatste 24 uren"
    entity_id: sensor.living_heating
    state_characteristic: average_step
    max_age:
      hours: 24

  - platform: statistics
    name: "kamer Amilya gem. verwarming laatste 24 uren"
    entity_id: sensor.kamer_amilya_heating
    state_characteristic: average_step
    max_age:
      hours: 24

  - platform: statistics
    name: "veranda gem. verwarming laatste 24 uren"
    entity_id: sensor.veranda_heating
    state_characteristic: average_step
    max_age:
      hours: 24      

  - platform: statistics
    name: "berging gem. verwarming laatste 24 uren"
    entity_id: sensor.berging_heating
    state_characteristic: average_step
    max_age:
      hours: 24

  - platform: statistics
    name: "gang gem. verwarming laatste 24 uren"
    entity_id: sensor.gang_heating
    state_characteristic: average_step
    max_age:
      hours: 24      

  - platform: statistics
    name: "badkamer gem. verwarming laatste 24 uren"
    entity_id: sensor.badkamer_heating
    state_characteristic: average_step
    max_age:
      hours: 24

  - platform: statistics
    name: "kamer Alunya gem. verwarming laatste 24 uren"
    entity_id: sensor.kamer_alunya_heating
    state_characteristic: average_step
    max_age:
      hours: 24      

  - platform: statistics
    name: "master bedroom gem. verwarming laatste 24 uren"
    entity_id: sensor.master_bedroom_heating
    state_characteristic: average_step
    max_age:
      hours: 24

