
# binary_sensor:
#   - platform: workday
#     country: BE
#     workdays: [mon, tue, wed, thu, fri]
#     excludes: [sat, sun, holiday]
#     add_holidays:
#       - '2022-04-15'  # goede vrijdag / bankholiday

sensor:
  - platform: next_holiday
    min_future_holidays: 3
    custom_holidays:
        "10-31": "Halloween"
    sources: 
      - country: "BE"