#####################################################################
# historiek laptops
#####################################################################

sensor:  
  - platform: history_stats
    name: "Chromebook Bart/Madouce aan vandaag"
    entity_id: device_tracker.bart_chromebook
    state: "home"
    type: time
    start: '{{ now().replace(hour=0).replace(minute=0).replace(second=0) }}'
    end: '{{ now() }}'
    
  - platform: history_stats
    name: "Laptop Bart Fortis aan vandaag"
    entity_id: device_tracker.bart_laptop_bnpp_fortis
    state: "on"
    type: time
    start: '{{ now().replace(hour=0).replace(minute=0).replace(second=0) }}'
    end: '{{ now() }}'
    
  - platform: history_stats
    name: "Windows laptop aan vandaag"
    entity_id: device_tracker.bart_ultraland_laptop
    state: "on"
    type: time
    start: '{{ now().replace(hour=0).replace(minute=0).replace(second=0) }}'
    end: '{{ now() }}'
