template:
  - sensor:
      - name: "lightning direction"
        state: >
          {% set azimuth = states('sensor.blitzortung_lightning_azimuth') | int %}
          {% if azimuth >= 337.5 or azimuth < 22.5 %}
            noorden
          {% elif azimuth >= 22.5 and azimuth < 67.5 %}
            noordoosten
          {% elif azimuth >= 67.5 and azimuth < 112.5 %}
            oosten
          {% elif azimuth >= 112.5 and azimuth < 157.5 %}
            zuidoosten
          {% elif azimuth >= 157.5 and azimuth < 202.5 %}
            zuiden
          {% elif azimuth >= 202.5 and azimuth < 247.5 %}
            zuidwesten
          {% elif azimuth >= 247.5 and azimuth < 292.5 %}
            westen
          {% else %}
            noordwesten
          {% endif %}

sensor:
  - platform: statistics
    name: "Bliksems afgelopen minuut"
    entity_id: sensor.blitzortung_lightning_counter
    state_characteristic: count
    max_age:
      minutes: 1

input_number:
  lightning_previous_distance:
    name: "Vorige afstand dichtste bliksem"
    min: 0
    max: 100
    step: 1
    mode: box
    icon: mdi:weather-lightning
    unit_of_measurement: km

counter:
  lightning_counter_close_area:
    name: "Bliksemteller nabije zone"
    step: 1
    icon: mdi:weather-lightning
