
sensor:
  - platform: mold_indicator
    name: master_bedroom_mold_indicator
    indoor_temp_sensor: sensor.master_bedroom_temperature
    indoor_humidity_sensor: sensor.master_bedroom_humidity
    outdoor_temp_sensor: sensor.temp_leuven_outdoor
    calibration_factor: 2.0