###############################################################################
# Too good to go
###############################################################################

sensor:
  - platform: tgtg
    email: 'bartland@gmail.com'
    access_token: 'e30.eyJzdWIiOiI0OTkyMTA1IiwiZXhwIjoxNjg1NDM5MTUwLCJ0IjoieE1FZFRXbVJUYm1jNG5CWDYyWll4UTowOjEifQ.wTsZF0gw0FNA9JOcdb1K14YVwmCocyq5pGwf4AKtgag'
    refresh_token: 'e30.eyJzdWIiOiI0OTkyMTA1IiwiZXhwIjoxNzE2ODg4NzUwLCJ0IjoiNGlISzUtVU9SdVNzUzg2Y1cwQnNPUTowOjAifQ.DWbDGXvPTfAa01slWVhOm6qEUBIw3TIyhX38LWzxXBQ'
    user_id: '4992105'
    cookie: 'datadome=6RPh-tudDwpI3RTua0qvLe8WPh20gL1Sdn3Qz1JkEY9GzseUzP35JLjSu3M7fD_ghSs0YIz-OK_BSbhbKpvQ58nvEybORMSKoij12KB-Wl2bQqrrAvRD3FEfDzbeC3Jf; Max-Age=5184000; Domain=.apptoogoodtogo.com; Path=/; Secure; SameSite=Lax'
    scan_interval: 300
    

input_boolean:
  tgtg_geen_brood_nodig:
    name: "Too Good To Go - geen brood nodig"
    icon: mdi:baguette
