###############################################################################
# Too good to go
###############################################################################

sensor:
  - platform: tgtg
    email: 'bartland@gmail.com'
    access_token: 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3MTgwMjkyNzQsImlhdCI6MTcxNzg1NjQ3NCwiaXNzIjoidGd0Z19zb3RlcmlhIiwidCI6IlVZS01ES0hOUUpLanJDc1pVTkY0R0E6MDoxIiwic3ViIjoiNDk5MjEwNSJ9.gwmjzKMdeVGbXt1rYQDjvwNEYb2J0BdNkIGq3QXwWv0'
    refresh_token: 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3NDkzOTI0NzQsImlhdCI6MTcxNzg1NjQ3NCwiaXNzIjoidGd0Z19zb3RlcmlhIiwidCI6Im9rZFlnUEdvU1dTT0dZSUo2N3NDUWc6MDowIiwic3ViIjoiNDk5MjEwNSJ9.gqhSuG_nCyFUhjmL5h-sj2SNN9PyIWsZLgoXOhECM1U'
    user_id: '4992105'
    cookie: 'datadome=0sS9QPxhHXbUHHg9JaRzm8Zf~BHQN8CRMtfEB43pUAPUMauT7kfXqKXudkIrfy91HtzOyWMiiNrEwb6VmC5xcmpqPt5sUgq~AFExQFt0oh99vWppCX7vMQZF~bnRP_4E; Max-Age=5184000; Domain=.apptoogoodtogo.com; Path=/; Secure; SameSite=Lax'
    scan_interval: 300    

input_boolean:
  tgtg_geen_brood_nodig:
    name: "Too Good To Go - geen brood nodig"
    icon: mdi:baguette

