############################ Table of Contents ############################ 
# 
#   Automations
#     💡 lights // Amilya niet thuis = licht uit
#     💡 lights // Amilya licht badkamer brandt langer dan 20 minuten
#     💡 lights // Alunya niet thuis = licht uit
#     💡 lights // Alunya lichten uit om 1u en 2u 's nachts
#     💡 lights // bij donker living bol inschakelen
#     💡 lights // Donker, <20° buiten en thuis = licht aan
#     💡 lights // Master bedroom deurswitch
#     💡 lights // Licht in garage aan > 10 min
#     💡 lights // TV aan + zon onder = TV strip aan
#     💡 lights // TV uit = TV strip uit
#     💡 lights // master bedroom TV aan 's avonds = gezellig licht

############################ Information ################################## 
# Hoeveel lux is er (minimum) nodig in ruimtes?
# werkplek	      500
# algemene ruimte 300
# gang            100
# toilet          100

# Een bureau dat goed verlicht is, verbetert de productiviteit
# en helpt bij activiteiten zoals studeren, werken of lezen.
# Om geconcentreerd te kunnen werken, heb je helder wit licht nodig.
# Een kleurtemperatuur van 3000K is hier aanbevolen.


############################ Automations ################################## 

automation:



#################################################  
# living
#################################################

- alias: 💡 lights // living // Donker, <20° buiten en thuis = 1 licht links aan
  id: '9652f025-25a5-4eb0-8eb4-6f61ecb57936'
  description: ''
  trigger:
  - platform: state
    entity_id: sun.sun
    to: 'below_horizon'
  condition:
  - condition: state
    entity_id: person.madouce
    state: home
  - condition: numeric_state
    entity_id: sensor.eikenbos_temperature
    below: '20'
  action:
  - service: light.turn_on
    data:
      transition: 10
      brightness: 26
    target:
      device_id: a0297c6061546a2108b2d33e01ed449d 
  mode: single

- alias: 💡 lights // TV aan + zon onder = scene activeren tv verlichting
  id: 'decc48cf-f977-42e0-8d54-52cc3fad75d1'
  description: ''
  trigger:
  - platform: state
    entity_id: media_player.ue55ju7000
    from: 'off'
    to: 'on'
  - platform: state
    entity_id: sun.sun
    to: below_horizon
  - platform: numeric_state
    entity_id: sensor.oprit_bewegingssensor_light_level
    below: 100
  condition:
  - condition: template
    value_template: "{{ states('sensor.oprit_bewegingssensor_light_level') |float(default=0) < 150 }}"
  - condition: state
    entity_id: media_player.ue55ju7000
    state: 'on'
  action:
  - service: light.turn_on
    data:
      transition: 20
      color_temp: 500
      brightness: 100
    target:
      entity_id: light.tv_strip
  - service: scene.turn_on
    data:
      transition: 5
    target:
      entity_id: scene.verlichting_als_tv_aanstaat
  # - service: light.turn_off
  #   target:
  #     entity_id: light.living_bol
  #   data:
  #     transition: 10
  mode: single

- alias: 💡 lights // living // Google TV living playing + zon onder = Hue sync aan
  id: 'cf1702e9-33d4-43cc-be9c-67cafc91d105'
  trigger:
  - platform: state
    entity_id: media_player.living_google_tv
    to: 'playing'
  condition:
  - condition: state
    entity_id: sun.sun
    state: below_horizon
  action:
    - service: huesyncbox.set_sync_state
      target:
        entity_id: media_player.sync_box
      data:
        sync: true
        mode: video
        intensity: subtle
  mode: single

- alias: 💡 lights // living // TV uit = TV strip uit
  id: 'dfbb4779-8083-49e3-9b83-b045c4db5d43'
  description: ''
  trigger:
  - platform: state
    entity_id: media_player.ue55ju7000
    from: 'on'
    to: 'off'
    for: 00:05:00    
  condition: []
  action:
  - service: light.turn_off
    data:
      transition: 10
    target:
      entity_id:
      -  light.tv_strip
  mode: single

- alias: 💡 lights // living // TV uit en donker = living rechts 1 aan
  id: '545ec01a-fbf5-4153-aa45-d65b1e946c91'
  description: ''
  trigger:
  - platform: state
    entity_id: media_player.ue55ju7000
    from: 'on'
    to: 'off' 
  condition:
  - condition: state
    entity_id: sun.sun
    state: below_horizon  
  action:
  - service: scene.turn_on
    target:
      entity_id: scene.verlichting_als_tv_uit_gaat
  mode: single


- alias: 💡 lights // living // Het wordt donker = living bol inschakelen
  id: 'd754582e-1ba3-44f2-93ef-32a7f9bbc2af'
  description: ''
  trigger:
  - platform: sun
    event: sunset
  condition: []
  action:
  - service: light.turn_on
    data:
      transition: 20
      color_temp: 473
      brightness_pct: 40
    target:
      entity_id: light.living_bol
  mode: single

- alias: 💡 lights // living // licht uit wanneer buiten voldoende licht
  id: 'b3a7d875-e7c9-4612-a5a5-407f280c2e78'
  description: ""
  trigger:
    - platform: numeric_state
      entity_id: sensor.oprit_bewegingssensor_light_level
      above: 400
      for:
        minutes: 3
    - platform: numeric_state
      entity_id: sensor.oprit_bewegingssensor_light_level
      above: 700
      for:
        minutes: 3        
    - platform: numeric_state
      entity_id: sensor.oprit_bewegingssensor_light_level
      above: 1000
      for:
        minutes: 3          
  condition: []
  action:
    - service: light.turn_off
      target:
        entity_id:
          - light.living_links
          - light.living_rechts
      data:
        transition: 20          
  mode: single

- alias: 💡 lights // living // licht aan wanneer buiten onvoldoende licht en laptop aan
  id: 'ac4fb59a-e33f-464d-805f-c939d7e0d14e'
  description: ""
  trigger:
    - platform: numeric_state
      entity_id: sensor.oprit_bewegingssensor_light_level
      below: 400
      for:
        minutes: 3
    - platform: numeric_state
      entity_id: sensor.oprit_bewegingssensor_light_level
      below: 300
      for:
        minutes: 3         
  condition:
    - condition: state
      entity_id: switch.madouce_laptop_tme_a_b_1801581_windows_device
      state: "on"
      for:
        minutes: 10
  action:
    - service: light.turn_on
      data: {}
      target:
        entity_id:
          - light.living_links_2
  mode: single


- alias: 💡 lights // living // aanwezigheidsensor
  description: ""
  trigger:
    - platform: state
      entity_id:
        - binary_sensor.keuken_presence
      to: "on"
      id: keuken aanwezigheid
    - platform: state
      entity_id:
        - binary_sensor.keuken_presence
      to: "off"
      id: keuken afwezigheid
  condition:
    - condition: numeric_state
      entity_id: sensor.living_keuken_presence_light_level
      below: 15
    - condition: time
      after: "19:00:00"
      before: "17:00:00"
  action:
    - choose:
        - conditions:
            - condition: trigger
              id:
                - keuken aanwezigheid
          sequence:
            - service: light.turn_on
              data:
                brightness_pct: 70
                rgb_color:
                  - 255
                  - 236
                  - 220
              target:
                entity_id: light.living_rechts_4
        - conditions:
            - condition: trigger
              id:
                - keuken afwezigheid
          sequence:
            - wait_template: ""
              timeout: "00:00:02"
            - service: light.turn_off
              data: {}
              target:
                entity_id: light.living_rechts_4
  mode: parallel


#################################################  
# Amilya
#################################################

- alias: 💡 lights // Amilya // Amilya niet thuis = lichten uit
  id: 'c5fc-389d-42e8-8f3f-78f'
  description: ''
  trigger:
  - platform: state
    entity_id: person.amilya
    from: 'home'
    to: 'not_home'
    for: 00:03:00
  condition: []
  action:
  - service: light.turn_off
    target:
      entity_id:
        - light.amilya_badkamer
        - light.amilya_plafond_1
        - light.amilya_plafond_2
        - light.amilya_bol
        - light.amilya_strip
        - light.amilya_strip
  mode: single
  
- alias: 💡 lights // Amilya // Amilya licht badkamer brandt langer dan 15 minuten -> licht uit
  id: 3e894234-e24b-4c8c-a497-87a05abc3453
  description: ''
  trigger:
  - platform: state
    entity_id: light.amilya_badkamer
    to: 'on'
    for:
      hours: 0
      minutes: 15
      seconds: 0
      milliseconds: 0
  condition: []
  action:
  - service: light.turn_off
    target:
      entity_id: light.amilya_badkamer
    data:
      transition: 20      
  mode: single

- alias: 💡 lights // Amilya // Amilya lichtschakelaar deur ingedrukt = badkamerlicht aan voor 2 minuten
  # de andere lichten gaan ook gewoon aan, maar enkel licht badkamer gaat nadien uit
  id: 'd40b0f01-3e2f-4382-9480-971874f9d4f6'
  description: ''
  trigger:
  - device_id: 925e49167bd25df143efa1a2e317424d
    domain: hue
    platform: device
    type: short_release
    subtype: 1
    unique_id: beaaeaf3-d5e1-4d50-8aa9-1dfc2065073e
  condition: []
  action:
  - delay:
      hours: 0
      minutes: 2
      seconds: 0
      milliseconds: 0
  - service: light.turn_off
    target:
      entity_id: light.amilya_badkamer
    data:
      transition: 20      
  mode: single

- alias: 💡 lights // Amilya // Amilya lichten plafond onbereikbaar = lichten plafond uit
  id: '64602e2b-48aa-4304-809c-387d24ca9eee'
  trigger:
  - platform: state
    entity_id: light.amilya_plafond_1
    to: unavailable
  - platform: state
    entity_id: light.amilya_plafond_2
    to: unavailable
  condition: []
  action:
  - service: light.turn_off
    target:
      entity_id:
      - light.amilya_plafond_1
      - light.amilya_plafond_2
  mode: single


#################################################  
# Veranda
#################################################

- alias: 💡 lights // veranda // uit wanneer buiten voldoende licht
  id: 'e10f25e1-54d6-486d-8661-023145492c6b'
  description: ""
  trigger:
    - platform: numeric_state
      entity_id: sensor.terras_light_level
      above: 350
      for:
        minutes: 3  
    - platform: numeric_state
      entity_id: sensor.terras_light_level
      above: 700
      for:
        minutes: 3
    - platform: numeric_state
      entity_id: sensor.terras_light_level
      above: 900
      for:
        minutes: 3          
  condition: []
  action:
    - service: light.turn_off
      target:
        entity_id:
          - light.veranda
          - light.veranda_staande_lamp
      data:
        transition: 20          
  mode: single


- alias: 💡 lights // veranda // aan wanneer buiten onvoldoende licht en laptop aan
  id: 'd92b6fd4-f928-422e-a2f0-20604bb7f7cb'
  description: ""
  trigger:
    - platform: numeric_state
      entity_id: sensor.terras_light_level
      below: 350
      for:
        minutes: 3
    - platform: numeric_state
      entity_id: sensor.terras_light_level
      below: 200
      for:
        minutes: 3
  condition: 
    - condition: state
      entity_id: switch.bart_laptop_brum05007458
      state: "on"
      for:
        minutes: 30
    - condition: time
      weekday:
        - mon
        - tue
        - wed
        - thu
        - fri
      after: "09:00:00"
      before: "17:00:00"
    - condition: state
      entity_id: person.bart
      state: "home"
  action:
    - service: light.turn_on
      data: {}
      target:
        entity_id:
          - light.veranda_staande_lamp
  mode: single



#################################################  
# Alunya
#################################################

- alias: 💡 lights // Alunya // Alunya niet thuis = licht uit
  id: 'b31b70d7-e8c0-4bb8-8a45-335d57d427b8'
  description: ''
  trigger:
  - platform: state
    entity_id: person.alunya
    to: 'not_home'
    for: 00:03:00
  condition: []
  action:
  - service: light.turn_off
    target:
      entity_id:
        - light.alunya_bol
        - light.alunya_staande_lamp
        - light.alunya_nachtkastje
  mode: single

- alias: 💡 lights // Alunya // uit om 1u, 2u, 3u en 4u 's nachts
  id: 'ee497cc7-cb83-4a8d-afd9-dedaf4fe56ff'
  description: ''
  trigger:
  - platform: time
    at:
      - 01:00:00
      - 02:00:00
      - 03:00:00
      - 04:00:00
  condition: []
  action:
  - service: light.turn_off
    target:
      entity_id:
        - light.alunya_bol
        - light.alunya_staande_lamp
        - light.alunya_nachtkastje
  mode: single


#################################################  
# Master bedroom
#################################################

- alias: 💡 lights // master bedroom // master bedroom TV aan 's avonds = gezellig licht
  id: 62b15358-7447-43f7-9c76-b2d72db61875
  description: ''
  trigger:
  - platform: state
    entity_id: media_player.master_bedroom_tv
    to: 'playing'
  condition:
  - condition: state
    entity_id: sun.sun
    state: below_horizon
  action:
  - service: light.turn_on
    target:
      entity_id:
      - light.master_bedroom_play_bart
      - light.master_bedroom_play_madouce
      - light.master_bedroom_halve_bol
    data:
      color_name: darkorange
      brightness_pct: 30
  - service: light.turn_off
    target:
      entity_id: light.master_bedroom_staande_lamp
    data:
      transition: 5
  mode: single

- alias: 💡 lights // master bedroom // deurswitch
  id: '0ca77314-116c-4d39-bf43-fd51e9771514'
  description: ''
  trigger:
  - device_id: 4247e8ef769909d83520323811fc6550
    domain: hue
    platform: device
    type: short_release
    subtype: 1
    unique_id: 6e39bb0e-63cc-4dad-9237-29b7cc04d796
  condition:
  - condition: sun
    after: sunset
  action:
  - service: light.turn_on
    target:
      entity_id:
      - light.master_bedroom_play_madouce
      - light.master_bedroom_play_bart
      - light.master_bedroom_staande_lamp
    data:
      brightness_pct: 75
  mode: single

- alias: 💡 lights // master bedroom // Madouce en Bart niet thuis = licht uit
  id: '428317ff-aba5-4c2e-96c6-e1d97eb6ddb8'
  description: ''
  trigger:
  - platform: state
    entity_id: group.bart_madouce
    to: 'not_home'
    for: 00:03:00
  condition: []
  action:
  - service: light.turn_off
    target:
      entity_id: group.master_bedroom_lichten
  mode: single


#################################################  
# Gang, toilet, garage
#################################################

- alias: '💡 lights // garage // licht lang aan = melding'
  id: c3801d8a-dd6e-444e-9a25-0adc8c0655d8
  description: ''
  trigger:
  - platform: numeric_state
    entity_id: sensor.garage_bewegingssensor_light_level
    for:
      hours: 0
      minutes: 10
      seconds: 0
      milliseconds: 0
    above: '4'
  condition: []
  action:
  - repeat:
      while:
      - condition: numeric_state
        entity_id: sensor.garage_bewegingssensor_light_level
        above: '4'
      sequence:
      - service: notify.bart_madouce_phone
        data:
          message: >
            {% set s = ( as_timestamp(now()) - as_timestamp(state_attr('automation.licht_in_garage','last_triggered')) )|int %}
            Licht in garage brandt al {{ '%02du%02d' % ((s/3600)|int, (s%3600)/60) }}.
          title: Licht in garage
          data:
            color: blue
            tag: garage_licht
      - delay:
          minutes: 5
  - service: notify.bart_madouce_phone
    data:
      message: "clear_notification"
      data:
        tag: garage_licht
  mode: single

- alias: 💡 lights // gang // uit na 3 minuten
  id: 'd268f950-cbb3-4220-a017-850bb950ec4a'
  description: ''
  trigger:
  - platform: device
    type: turned_on
    device_id: dfa6e3e21463bd9dd78d7797538d0856
    entity_id: light.gang_spot_achter
    domain: light
    for:
      hours: 0
      minutes: 3
      seconds: 0
  condition: []
  action:
  - service: light.turn_off
    target:
      entity_id:
        - light.gang_spot_achter
        - light.gang_spot_midden
        - light.gang_spot_voor
    data:
      transition: 20
  mode: single

- alias: 💡 lights // toilet // uit na 7 minuten
  id: cb7ab5c4-1930-4495-a55a-85d1d6e26a8b
  description: ''
  trigger:
  - platform: state
    entity_id: light.toilet
    to: 'on'
    for: '00:07:00'
  condition: []
  action:
  - service: light.turn_off
    target:
      entity_id:
      - light.toilet
    data:
      transition: 60      
  mode: single

- alias: 💡 lights // toilet // 's nachts dimmen
  id: be544a45-af8d-4b1a-b5d9-69c5591f44d6
  description: ''
  trigger:
  - platform: state
    entity_id: light.toilet
    to: 'on'
  condition:
  - condition: time
    after: '22:30:00'
    before: '07:00:00'
  action:
  - service: light.turn_on
    data:
      kelvin: 1500
      brightness_pct: 40
    target:
      entity_id: light.toilet
  mode: single
  
- alias: 💡 lights // toilet // overdag = helder
  id: 94fb34e5-4b03-49b9-9586-f922960cb5c0
  description: ''
  trigger:
  - platform: state
    entity_id: light.toilet
    to: 'on'
  condition:
  - condition: time
    after: '07:00:00'
    before: '23:00:00'
  action:
  - service: light.turn_on
    data:
      kelvin: 2500
      brightness_pct: 100
    target:
      entity_id: light.toilet
  mode: single  

- alias: "💡 lights // gang // zon onder = gedimd"
  id: 151c0615-8998-408b-a0ab-0a31af6c3ea8
  description: ''
  trigger:
  - platform: state
    entity_id: light.gang
    to: 'on'
  condition:
  - condition: state
    entity_id: sun.sun
    state: "below_horizon"
  action:
  - service: light.turn_on
    data:
      kelvin: 1500
      brightness_pct: 20
    target:
      entity_id: light.gang
  mode: single

- alias: "💡 lights // gang // zon op = helder"
  id: 80b10678-6e3b-41a7-ba87-fdb427cfc2ce
  description: ''
  trigger:
  - platform: state
    entity_id: light.gang
    to: 'on'
  condition:
  - condition: state
    entity_id: sun.sun
    state: "above_horizon"
  action:
  - service: light.turn_on
    data:
      kelvin: 2500
      brightness_pct: 60
    target:
      entity_id: light.gang
  mode: single

- alias: 💡 lights // inkomhal // beweging = licht aan
  id: '5a0fc2cc-355d-4274-a816-0508fbf8bdce'
  description: ''
  trigger:
    - platform: state
      entity_id:
        - binary_sensor.hal_motion_sensor_occupancy
      to: "on"
  condition:
    - condition: numeric_state
      entity_id: sensor.hal_motion_sensor_illuminance
      below: 50
  action:
    - service: light.turn_on
      data: {}
      target:
        entity_id: light.inkomhal
    - wait_template: ''
      timeout: 00:00:30
    - service: light.turn_off
      target:
        entity_id: light.inkomhal
      data:
        transition: 20
  mode: restart


#################################################  
# Buiten
#################################################

- alias: 💡 lights // voordeur open en donker = buiten lichten aan
  id: '54a719fd-b21f-4401-913e-fdbb2eb949ff'
  description: ''
  trigger:
    - platform: state
      entity_id: binary_sensor.voordeur
      to: "on"
  condition:
  - condition: state
    entity_id: sun.sun
    state: "below_horizon"
  action:
    - service: light.turn_on
      target:
        entity_id:
          - light.buiten_oprit
          - light.buiten_voordeur
      data:
        brightness_step_pct: 60      
    - wait_template: ''
      timeout: 00:03:00
    - service: light.turn_off
      target:
        entity_id:
          - light.buiten_oprit
          - light.buiten_voordeur
      data: {}
  mode: restart
