# sensor:
#   - platform: template
#     sensors:
#       xiaomi_air_purifier_air_quality_pm25:
#         friendly_name: "Air quality (AQI) PM2.5"
#         value_template: "{{ state_attr('fan.mi_air', 'aqi') }}"
#         unit_of_measurement: "μg/m³"
#         icon_template: "mdi:weather-fog"


# niet nodig, want apparaat heeft zelf een sensor sensor.mi_air_pm2_5