###############################################################################
# map car sensor names to fixed sensor names
###############################################################################

template:
  - sensor:
      - name: "car 1 soc"
        state: "{{ states('sensor.audi_e_tron_sportback_state_of_charge') }}"
        unit_of_measurement: procent

      - name: "car 1 range"
        state: "{{ states('sensor.audi_e_tron_sportback_range') }}"
        unit_of_measurement: km

      - name: "car 1 plug state"
        state: "{{ states('sensor.audi_e_tron_sportback_plug_state') }}"

      - name: "car 1 remaining charge time"
        state: "{{ states('sensor.audi_e_tron_sportback_remaining_charge_time') }}"

      - name: "car 1 charging state"
        state: "{{ states('sensor.audi_e_tron_sportback_charging_state') }}"


###############################################################################
# sensors to calculate charging times 
###############################################################################

sensor:
  - platform: template
    sensors:
      car_range_per_10percent:
        friendly_name: 'range per 10%'
        unit_of_measurement: km
        value_template: "{{ (10 * states('sensor.car_1_range') | float(default=0) / states('sensor.car_1_soc') | float(default=0) ) | round (1) }}"

      car_range_at_target_percentage:
        friendly_name: 'rijbereik bij doelpercentage'
        unit_of_measurement: km
        value_template: "{{ ( states('input_number.car_charge_target_percentage') | float(default=0) * ( states('sensor.car_range_per_10percent') | float(default=0)) / 10 ) | int }}"

      car_remaining_charge_minutes:
        friendly_name: 'resterende laadminuten'
        value_template: >
          {% set targetsoc = states('input_number.car_charge_target_percentage') | float(default=0) %}
          {% set soc = states('sensor.car_1_soc') | float(default=0) %}
          {% set socdif = [targetsoc - soc, 0] | max %}
          {{ socdif * states('input_number.car_1_min_per_1pct') | round(2) }}        


utility_meter:
  car_today_km:
    source: sensor.audi_e_tron_sportback_mileage
    cycle: daily

  car_monthly_km:
    source: sensor.audi_e_tron_sportback_mileage
    cycle: monthly


