
sensor:
- platform: template
  sensors:
    max_peak:
      friendly_name: Maximum piek
      unit_of_measurement: W
      device_class: power
      value_template: >
        {% set peak = ((states.sensor.quarter_hourly_net_power.state | float(default=0)) * 4) %}
        {% set max_peak = (states.input_number.max_peak.state | float(default=0)) %}
        {% macro max(X, Y) -%} {{X|float if X|float > Y|float else Y|float }} {%- endmacro %}
        {{ max(max_peak, peak) }}

    year_peak:
      friendly_name: Gemiddelde jaarpiek
      unit_of_measurement: W
      device_class: power
      value_template: >
        {{ (( states('input_number.january_peak') | float(default=0) +
              states('input_number.february_peak') | float(default=0) +
              states('input_number.march_peak') | float(default=0) +
              states('input_number.april_peak') | float(default=0) +
              states('input_number.may_peak') | float(default=0) +
              states('input_number.june_peak') | float(default=0) +
              states('input_number.july_peak') | float(default=0) +
              states('input_number.august_peak') | float(default=0) +
              states('input_number.september_peak') | float(default=0) +
              states('input_number.october_peak') | float(default=0) +
              states('input_number.november_peak') | float(default=0) +
              states('input_number.december_peak') | float(default=0) ) / 12) | round(2)
        }}


utility_meter:
  quarter_hourly_net_power:
    source: sensor.net_power
    cycle: quarter-hourly

input_number:
  max_peak:
      name: Maximum piek
      min: 0.1
      max: 12.0
      step: 0.001
      mode: box
      unit_of_measurement: W
    
  january_peak:
    name: Piek januari
    min: 2.5
    max: 12.0
    step: 0.001
    mode: box
    unit_of_measurement: W
  
  february_peak:
    name: Piek februari
    min: 2.5
    max: 12.0
    step: 0.001
    mode: box
    unit_of_measurement: W
  
  march_peak:
    name: Piek maart
    min: 2.5
    max: 12.0
    step: 0.001
    mode: box
    unit_of_measurement: W

  april_peak:
    name: Piek april
    min: 2.5
    max: 12.0
    step: 0.001
    mode: box
    unit_of_measurement: W

  may_peak:
    name: Piek mei
    min: 2.5
    max: 12.0
    step: 0.001
    mode: box
    unit_of_measurement: W

  june_peak:
    name: Piek juni
    min: 2.5
    max: 12.0
    step: 0.001
    mode: box
    unit_of_measurement: W

  july_peak:
    name: Piek juli
    min: 2.5
    max: 12.0
    step: 0.001
    mode: box
    unit_of_measurement: W

  august_peak:
    name: Piek augustus
    min: 2.5
    max: 12.0
    step: 0.001
    mode: box
    unit_of_measurement: W

  september_peak:
    name: Piek september
    min: 2.5
    max: 12.0
    step: 0.001
    mode: box
    unit_of_measurement: W

  october_peak:
    name: Piek oktober
    min: 2.5
    max: 12.0
    step: 0.001
    mode: box
    unit_of_measurement: W

  november_peak:
    name: Piek november
    min: 2.5
    max: 12.0
    step: 0.001
    mode: box
    unit_of_measurement: W

  december_peak:
    name: Piek december
    min: 2.5
    max: 12.0
    step: 0.001
    mode: box
    unit_of_measurement: W
