input_select:
  car_charge_minimum_wattage:
    name: autolader minimum wattage
    options:
      - "1.4 kW (1 fase 6 ampère)"
      - "2.2 kW (1 fase 10 ampère)"
      - "4.0 kW (3 fasen 6 ampère)"
      - "5.3 kW (3 fasen 8 ampère)"
    icon: mdi:power

input_number:
  car_charge_minimum_wattage:
    name: autolader minimum wattage
    min: 0
    max: 10
    step: 0.1