input_datetime:
  badkamer_electric_heater_start_time:
    name: "elektrische verwarming starttijd"
    has_date: true
    has_time: true

  badkamer_electric_heater_stop_time:
    name: "elektrische verwarming eindtijd"
    has_date: true
    has_time: true

sensor:
  - platform: integration
    source: sensor.badkamer_electric_heater_power
    name: badkamer elektrische verwarming energieverbruik
    unit_prefix: k
    round: 2
    method: left

utility_meter:
  badkamer_electric_heater_energy_daily:
    source: sensor.badkamer_elektrische_verwarming_energieverbruik
    cycle: daily