schedule:
  badkamer_verwarmingsschema:
    name: "badkamer verwarmingsschema"
    monday:
      - from: "07:00:00"
        to: "07:15:00"
    tuesday:
      - from: "07:00:00"
        to: "07:15:00"
    wednesday:
      - from: "07:00:00"
        to: "07:15:00"
    thursday:
      - from: "07:00:00"
        to: "07:15:00"
    friday:
      - from: "07:00:00"
        to: "07:15:00"
    # saturday:
    #   - from: "09:15:00"
    #     to: "09:30:00"
    # sunday:
    #   - from: "10:30:00"
    #     to: "11:00:00"