# fan:
#   - platform: xiaomi_miio_fan
#     name: Xiaomi Smart Fan 3C
#     host: 192.168.86.30
#     token: !secret fan_3C_token
#     # MAC address = 40:31:3C:49:7E:F2

#   - platform: xiaomi_miio_fan
#     name: Xiaomi Smart Fan 1C
#     host: 192.168.86.31
#     token: !secret fan_1C_token
#     # MAC address = 44:23:7C:C7:B8:AA

