###############################################################################
#
# Sensors to detect rising/falling humidity outside and in every room 
# Used to calculate when to open/close the windows
#
###############################################################################

binary_sensor:
  - platform: trend
    sensors:

      gram_water_outside_rising:
        entity_id: sensor.gram_water_outside
        sample_duration: 4800
        max_samples: 20
        # 1 sample every second. 1800 seconds = 30 minutes  3600 seconds = 1 hour
        min_gradient: 0.00011      # The gradient is measured in sensor units per second (independent from the duration ?)
        # If you want to know when the humidity is rising by 0.5 gram per hour, use a gradient of (0.5) / (60 x 60) = 0.000139
        
      gram_water_outside_falling:
        entity_id: sensor.gram_water_outside
        sample_duration: 4800
        max_samples: 20
        # 1 sample every second. 1800 seconds = 30 minutes
        min_gradient: -0.00011
        # The gradient is measured in sensor units per second
        # If you want to know when the humidity is rising by 0.5 gram per hour, use a gradient of (0.5) / (60 x 60) = 0.000139

      gram_water_master_bedroom_rising:
        entity_id: sensor.gram_water_master_bedroom
        sample_duration: 3600
        # 1 sample every second. 1800 seconds = 30 minutes
        min_gradient: 0.00011      # The gradient is measured in sensor units per second (independent from the duration ?)
        # If you want to know when the humidity is rising by 0.5 gram per hour, use a gradient of (0.8) / (60 x 60) = 0.000139
        max_samples: 10

      humidity_master_bedroom_rising:
        entity_id: sensor.master_bedroom_humidity
        sample_duration: 3600
        # 1 sample every second. 1800 seconds = 30 minutes
        min_gradient: 0.0004
        device_class: moisture
        # The gradient is measured in sensor units per second
        # If you want to know when the humidity is rising by 4 % per hour, use a gradient of (4) / (60 x 60) = 0.00111111111
        
      humidity_kamer_alunya_rising:
        entity_id: sensor.kamer_alunya_humidity
        sample_duration: 3600
        # 1 sample every second. 1800 seconds = 30 minutes
        min_gradient: 0.00027777777
        device_class: moisture

      humidity_badkamer_rising:
        entity_id: sensor.badkamer_humidity
        sample_duration: 3600
        # 1 sample every second. 1800 seconds = 30 minutes
        min_gradient: 0.0004
        device_class: moisture

      humidity_eikenbos_rising:
        entity_id: sensor.humidity_leuven24_wunderground
        sample_duration: 3600  # 1 hour
        min_gradient: 0.00027777777
        # 4% increase per hour = 4/(60x60) = 0.00111111111
        device_class: moisture

      humidity_eikenbos_falling:
        entity_id: sensor.humidity_leuven24_wunderground
        sample_duration: 3600  # 1 hour
        min_gradient: -0.00027777777
        # 4% increase per hour = 4/(60x60) = 0.00111111111
        device_class: moisture
