
sensor:
  - platform: integration
    source: sensor.infrared_panel_power
    name: infraroodpaneel energieverbruik
    unit_prefix: k
    round: 2
    method: left

utility_meter:
  infrared_panel_energy_daily:
    source: sensor.infraroodpaneel_energieverbruik
    cycle: daily

timer:
  infrared_panel_timer:
    name: "infraroodpaneel timer"
    restore: true
    icon: mdi:clock     

input_number:
  infrared_panel_timer_minutes:
    name: "infraroodpaneel timer"
    min: 0
    max: 120
    step: 5  