
###############################################################################
# Powercalc creates a power sensor (W) and energy sensor (kWh) for lights 
###############################################################################

powercalc:
  sensors:

    - create_group: living alle lichten
      entities:
        -  entity_id: light.living_links_1
        -  entity_id: light.living_links_2
        -  entity_id: light.living_links_3
        -  entity_id: light.living_links_4
        -  entity_id: light.living_links_5
        -  entity_id: light.living_rechts_1  
        -  entity_id: light.living_rechts_2
        -  entity_id: light.living_rechts_3
        -  entity_id: light.living_rechts_4
        -  entity_id: light.living_rechts_5
      manufacturer: signify
      model: LCT003
      # creates 2 sensors called
      #   sensor.living_alle_lichten_power (in W)
      #   sensor.living_alle_lichten_energy (in kWh)

    - entity_id: light.living_bol
      manufacturer: signify
      model: LCT015
      # creates a sensor called sensor.living_bol_power

    - create_group: Amilya alle lichten
      entities:
        -  entity_id: light.amilya_badkamer
        -  entity_id: light.amilya_bol
        -  entity_id: light.amilya_strip
        -  entity_id: light.amilya_plafond_1
        -  entity_id: light.amilya_plafond_2

    - entity_id: light.veranda
      manufacturer: signify
      model: LCT015

    - create_group: badkamer alle lichten
      entities:
        -  entity_id: light.badkamer_bad
        -  entity_id: light.badkamer_douche
        -  entity_id: light.badkamer_wasbak_rechts
      model: LTW013

    - create_group: Alunya alle lichten
      entities:
        -  entity_id: light.alunya_bol
        -  entity_id: light.alunya_staande_lamp
        -  entity_id: light.alunya_wasbak

    - create_group: master bedroom alle lichten
      entities:
        -  entity_id: light.master_bedroom_play_bart
        -  entity_id: light.master_bedroom_play_madouce
        -  entity_id: light.master_bedroom_staande_lamp

    - create_group: master bedroom play bar lights 
      entities:
        -  entity_id: light.master_bedroom_play_bart
        -  entity_id: light.master_bedroom_play_madouce
      multiply_factor: 2
      manufacturer: signify
      model: LCT024
      
    - entity_id: light.buiten
      manufacturer: signify
      model: LCT015     # model 1744630P7 not found
      multiply_factor: 2

    - create_group: tuin alle lichten
      entities:
        -  entity_id: light.tuin_spot_1
        -  entity_id: light.tuin_spot_2
        -  entity_id: light.tuin_spot_3
        -  entity_id: light.tuin_spot_4
        -  entity_id: light.tuin_spot_5
      manufacturer: signify
      model: LCS001

    - create_group: gang alle lichten
      entities:
        -  entity_id: light.gang_spot_voor
        -  entity_id: light.gang_spot_midden
        -  entity_id: light.gang_spot_achter
      manufacturer: signify
      model: LTW013

    - create_group: berging alle lichten
      entities:
        -  entity_id: light.berging_spot_1
        -  entity_id: light.berging_spot_2
        -  entity_id: light.berging_spot_3
      manufacturer: signify
      model: LWG001 

