multiscrape:
  - name: mazoutprijs
    resource: https://mazout.com/belgie/mazoutprijs
    scan_interval: 3600
    sensor:
      - name: mazoutprijs_morgen_minder_2000L
        select: "#price_table_3945434934 > rc-http > div > div > price-table > table > tbody > tr:nth-child(1) > td:nth-child(4)"
#        unit_of_measurement: EUR

  - name: pv_opbrengst
    resource: https://pvoutput.org/compare.jsp?sid=94261&sid1=8895&c=-1
    scan_interval: 3600
    sensor:
      - name: pv_opbrengst_vandaag_cricket
        select: "#tb > tbody > tr:nth-child(3) > td:nth-child(5)"
