multiscrape:
  - name: mazoutprijs
    resource: https://mazout.com/belgie/mazoutprijs
    scan_interval: 3600
    sensor:
      - name: mazoutprijs_morgen_minder_2000L
        select: "#price_table_3945434934 > rc-http > div > div > price-table > table > tbody > tr:nth-child(1) > td:nth-child(4)"
        unit_of_measurement: EUR


