# MAC address SMA solar inverter: 70:74:14:92:6b:cd

modbus:
  - name: sma
    type: tcp
    #host: 192.168.86.102
    host: 192.168.1.6
    port: 502
    sensors:
      - name: SMA power AC
        unit_of_measurement: W
        slave: 3
        address: 30775
        count: 2
        data_type: uint32
        # the SMA app updates the sensors every 10 seconds
        # The Shelly energy meter updates every 30 seconds
        # if there is a difference in the interval between these 2 meters,
        # you get off-sync results
        scan_interval: 10
        device_class: power        #werkt OK
        state_class: measurement   #werkt OK
      - name: SMA_energy_today
        unit_of_measurement: kWh
        slave: 3
        address: 30517
        count: 4
        scale: 0.001
        state_class: total_increasing
        device_class: energy
        precision: 3
        data_type: int64
      - name: SMA total
        unit_of_measurement: kWh  # of MWh
        slave: 3
        address: 30513
        count: 4
        data_type: int64
      - name: SMA Volt
        unit_of_measurement: V
        slave: 3
        address: 30783
        count: 2
        data_type: int32
      - name: SMA power L1 AC
        unit_of_measurement: W
        slave: 3
        address: 30777
        count: 2
        data_type: uint32
      - name: SMA power L2 AC
        unit_of_measurement: W
        slave: 3
        address: 30779
        count: 2
        data_type: uint32
      - name: SMA power L3 AC
        unit_of_measurement: W
        slave: 3
        address: 30781
        count: 2
        data_type: uint32
      - name: SMA_energy_total
        unit_of_measurement: kWh
        slave: 3
        address: 30531
        input_type: input
        device_class: energy
        count: 2
        data_type: int32
      - name: SMA power A channel
        unit_of_measurement: W
        slave: 3
        address: 30773
        count: 2
        data_type: uint32
        scan_interval: 30
      - name: SMA power B channel
        unit_of_measurement: W
        slave: 3
        address: 30961
        count: 2       
        data_type: uint32
        scan_interval: 30
      - name: SMA today
        unit_of_measurement: kWh
        slave: 3
        address: 30535
        count: 2
        data_type: uint32
        scale: 0.001
        precision: 2
        scan_interval: 10       
      - name: SMA status
        slave: 3
        address: 30201
        scan_interval: 60
        count: 2
        data_type: int32        
      - name: SMA temp
        unit_of_measurement: °C
        slave: 3
        address: 30953
        scan_interval: 60
        count: 2
        scale: 0.1
        precision: 1
        data_type: int32


template:
  - sensor:
      - name: "PV Status"
        state: "{% if is_state('sensor.SMA_status', '307' ) %} OK
            {% elif is_state('sensor.SMA_status', '303' ) %} Uit
            {% elif is_state('sensor.SMA_status', '455' ) %} Waarschuwing
            {% elif is_state('sensor.SMA_status', '35' ) %} Fout
            {% endif %}"