
sensor:
- platform: template
  sensors:
    solar_power:
      # converts the sma_power_ac sensor to sensor.solar_power
      # but cutting of incorrect (too high) values to 10000
      unique_id: '136e925b-8fa2-446f-b0b5-222cfd4742f1'
      unit_of_measurement: "W"
      friendly_name: "zonne-energie productie"
      icon_template: "mdi:solar-power"
      value_template: >
        {% if states('sensor.sma_power_ac') | float(default=0) >=10000 %}
        0
        {% elif states('sensor.sma_power_ac') | float(default=0) <= 10000 %}
        {{ states('sensor.sma_power_ac') | float(default=0) }}
        {% endif %}

    solar_sim_energy_today:
      # totaal van de gesimuleerde productie  (= solar integratie)
      unique_id: 'd7878be1-3fb7-4f10-a090-92bf0640868c'
      unit_of_measurement: "kWh"
      friendly_name: "zonne-energie productie simulatie vandaag"
      icon_template: "mdi:solar-power"
      value_template: >-
        {% set s1 = states('sensor.energy_production_today')  | float(default=0) %}
        {% set s2 = states('sensor.energy_production_today_2')| float(default=0) %}
        {{ s1 + s2 }}

    solar_sim_energy_tomorrow:
      # totaal van de gesimuleerde energie  (= solar integratie)
      unit_of_measurement: "kWh"
      friendly_name: "zonne-energie productie simulatie morgen"
      icon_template: "mdi:solar-power"
      value_template: >-
        {% set s1 = states('sensor.energy_production_tomorrow')  | float(default=0) %}
        {% set s2 = states('sensor.energy_production_tomorrow_2')| float(default=0) %}
        {{ s1 + s2 }}

    # Code voor het wegfilteren van exuberante waarden
    # https://www.zonstraal.be/forum/viewtopic.php?t=23979&start=45
    # sensor:
    #   - name: PV_Vermogen_AC
    #     unit_of_measurement: W
    #     device_class: power
    #     state: "{% if states('sensor.PV_Vermogen_AC_r') is not none %}
    #                {% if states('sensor.PV_Vermogen_AC_r') | int < 0 %}
    #                   {{ 0 }}
    #                {% else %}
    #                   {{ states('sensor.PV_Vermogen_AC_r') | int }}
    #                {% endif %}
    #              {% else %}
    #                {{ 'error' }}
    #              {% endif %}"

    net_neutrality:
      unit_of_measurement: "%"
      friendly_name: "netonafhankelijkheid totaal"
      icon_template: "mdi:solar-power"
      value_template: >-
        {% set sp = states('sensor.sma_energy_total') | float %}
        {% set nc = states('sensor.net_consumption_energy_total') | float %}
        {% set ni = states('sensor.net_injection_energy_total') | float %}
        {{ ((sp - ni ) / ( sp - ni + nc) * 100 ) | round(1) }}

    net_neutrality_home:
      unit_of_measurement: "%"
      friendly_name: "netonafhankelijkheid huis"
      icon_template: "mdi:solar-power"
      value_template: >-
        {% set sp = states('sensor.sma_energy_total') | float %}
        {% set nc = states('sensor.net_consumption_energy_total') | float %}
        {% set ni = states('sensor.net_injection_energy_total') | float %}
        {% set car_net = states('sensor.car_charge_net_energy') | round() %}
        {% set car_sun = states('sensor.car_charge_solar_energy') | round() %}
        {{ (((sp - ni - car_sun) / (sp - ni + nc - car_net - car_sun) ) * 100 ) | round(1) }}

    net_neutrality_car:
      unit_of_measurement: "%"
      friendly_name: "netonafhankelijkheid auto"
      icon_template: "mdi:solar-power"
      value_template: >-
        {% set car_net = states('sensor.car_charge_net_energy') | round() %}
        {% set car_sun = states('sensor.car_charge_solar_energy') | round() %}
        {{ (car_sun / (car_net + car_sun) * 100 ) | round(1)}}

    solar_self_consumption:
      unit_of_measurement: "kWh"
      friendly_name: "zelfverbruik zonne-energie"
      icon_template: "mdi:solar-power"
      value_template: >-
        {% set sp = states('sensor.sma_energy_total') | float %}
        {% set ni = states('sensor.net_injection_energy_total') | float %}
        {{ sp - ni }}

    net_neutrality_now:
      unit_of_measurement: "%"
      friendly_name: "netonafhankelijkheid nu"
      icon_template: "mdi:solar-power"
      value_template: >-
        {% set sp = states('sensor.solar_power') | float %}
        {% set hc = states('sensor.huisverbruik') | float %}
        {% set result = [((sp  / hc ) * 100 ) | round(1), 100] | min %}
        {{ result }}
      availability_template: >
        {% if result < 0 %}
          false
        {% endif %}

    net_injection_savings:
      unit_of_measurement: "EUR"
      friendly_name: "winst teruggave"
      value_template: >-
          {% set np = states('sensor.net_injection_daily') | float(default=0) %}
          {% set i = states('input_number.elektriciteitsprijs_injectie') | float() %}
          {{ (np * i) | round(1) }}

    solar_selfconsumption_savings:
      unit_of_measurement: "EUR"
      friendly_name: "winst zelfverbruik"
      value_template: >-
          {% set sp = states('sensor.zonne_energie_totaal') | float(default=0) %}
          {% set i = states('sensor.net_injection_daily') | float(default=0) %}
          {% set c = states('input_number.elektriciteitsprijs_afname') | float() %}
          {{ ((sp - i ) * c ) | round(1) }}

    solar_terraszijde_efficiency:
      unit_of_measurement: "%"
      friendly_name: zonnepanelen terraszijde efficiëntie
      value_template: >-
        {{ (states('sensor.solar_terraszijde_energie_daily') | float / 6150 * 1000 * 100) | round(1) }}

    solar_voorzijde_efficiency:
      unit_of_measurement: "%"
      friendly_name: zonnepanelen voorzijde efficiëntie
      value_template: >-
        {{ (states('sensor.solar_voorzijde_energie_daily') | float / 8610 * 1000 * 100) | round(1) }}

- platform: integration
  source: sensor.sma_power_A_channel
  name: solar terraszijde energie
  unit_prefix: k
  method: left
  round: 2

- platform: integration
  source: sensor.sma_power_B_channel
  name: solar voorzijde energie
  unit_prefix: k
  method: left
  round: 2


utility_meter:
  solar_terraszijde_energie_daily:
    source: sensor.solar_terraszijde_energie
    cycle: daily

  solar_terraszijde_energie_monthly:
    source: sensor.solar_terraszijde_energie
    cycle: monthly

  solar_voorzijde_energie_daily:
    source: sensor.solar_voorzijde_energie
    cycle: daily

  solar_voorzijde_energie_monthly:
    source: sensor.solar_voorzijde_energie
    cycle: monthly    

  net_injection_savings_monthly:
    source: sensor.net_injection_savings
    cycle: monthly

  solar_selfconsumption_savings_monthly:
    source: sensor.solar_selfconsumption_savings
    cycle: monthly

  net_injection_savings_yearly:
    source: sensor.net_injection_savings
    cycle: yearly

  solar_selfconsumption_savings_yearly:
    source: sensor.solar_selfconsumption_savings
    cycle: yearly
    
  net_consumption_daily:
    source: sensor.net_consumption_energy_total
    cycle: daily

  net_injection_daily:
    unique_id: '777f5014-d5e3-4b88-af36-f6583325c10f'
    source: sensor.net_injection_energy_total
    cycle: daily

  net_energy_daily:
    unique_id: '003c3f3c-5a3e-495b-81d6-2d74ea356b57'
    source: sensor.net_energy
    cycle: daily

  net_energy_monthly:
    unique_id: '7ad9df31-7589-4331-83fe-60a11675763a'  
    source: sensor.net_energy
    cycle: monthly

  net_energy_yearly:
    unique_id: '4b4078f6-b1e6-4f73-9ac7-3968369ddeae'  
    source: sensor.net_energy
    cycle: yearly

  solar_energy_daily:
    unique_id: 'fde4c082-6b5d-43c6-9988-c7f3d25b4152'
    source: sensor.zonne_energie_totaal
    cycle: daily

  solar_energy_weekly:
    unique_id: '7b40b4bd-cc07-433d-9d3e-6229123999fa'
    source: sensor.zonne_energie_totaal
    cycle: weekly

  solar_energy_monthly:
    unique_id: '45ac36a8-d58e-4d64-b08a-45a6b6acca7e'
    source: sensor.zonne_energie_totaal 
    cycle: monthly

  solar_energy_yearly:
    unique_id: '7b459a97-69ab-407a-a9c5-cae18ace8772'
    source: sensor.zonne_energie_totaal 
    cycle: yearly

  realised_sun_production_today:
    unique_id: 'aa95f490-df7d-4c80-b798-33225a1afe4d'  
    source: sensor.gerealiseerde_zonneproductie
    cycle: daily    