###############################################################################
# Too good to go
###############################################################################
  # sensor:
  # - platform: tgtg
  #   username: 'bartland@gmail.com'
  #   access_token: 'e30.eyJzdWIiOiI0OTkyMTA1IiwiZXhwIjoxNjUwMTA4Mzg4LCJ0IjoiMVVuaHpIMEJRLWV3RTRwakVTRDBRZzowOjEifQ.1mkWH_bvNhWAHDT4-j9UOyY5zrBoG40dCgi0KHDRF-Q'
  #   refresh_token: 'e30.eyJzdWIiOiI0OTkyMTA1IiwiZXhwIjoxNjgxNDcxNTg4LCJ0IjoiUkVQQ3pUY19UMm1VWGRTejl2MXVIZzowOjAifQ.EE3A_1FPlbpBK47MSkCndqR_MBrEUZvKfGjktFnUPOA'
  #   user_id: '4992105'
  #   scan_interval: 150


  sensor:
    - platform: tgtg
      email: 'bartland@gmail.com'
      access_token: 'e30.eyJzdWIiOiI0OTkyMTA1IiwiZXhwIjoxNjc1MzM5MzIwLCJ0IjoiQkw0bzJzdllSbXVRajlyRE9pMk9rUTowOjEifQ.pXjhfSNvlBJ_GVQ5Vd3vLH0D51fPI1ymGOxGkN-ghgM'
      refresh_token: 'e30.eyJzdWIiOiI0OTkyMTA1IiwiZXhwIjoxNzA2NzAyNTIwLCJ0IjoiUnpxS0lzM3JUdld5U1Y1eWl6Tmd6UTowOjAifQ.jPOSf90KVtMhcyJaCzjDs_CKxrqz3bOgUJYYi89Pp00'
      user_id: '4992105'
      cookie: 'datadome=7u~ZM05B43lLB5VD3lAUaPJ0BNsjQ3w6BMjyJrPKEfDUMZdc0umbdlIMXdQ6LeVEaCB5zgO76XHu51rru_AOKnEAfwsM6vRXLVRlGV0anw71sNHx6CW7Xip_bhTGRuu9; Max-Age=31536000; Domain=.apptoogoodtogo.com; Path=/; Secure; SameSite=Lax'
      scan_interval: 300
    