###############################################################################
# Too good to go
###############################################################################

  sensor:
    - platform: tgtg
      email: 'bartland@gmail.com'
      access_token: 'e30.eyJzdWIiOiI0OTkyMTA1IiwiZXhwIjoxNjc2ODkzOTcxLCJ0IjoiNklhN3NpMkZULXExTWJhZ3BjVGxZUTowOjEifQ.ydawNA4iffrf1VIJNj6JaMzy6h_gpINuqhOF8E0hG1k'
      refresh_token: 'e30.eyJzdWIiOiI0OTkyMTA1IiwiZXhwIjoxNzA4MjU3MTcxLCJ0IjoiRFZKU2xQZTFUdy1UNkllNEVIZU5rdzowOjAifQ.MGnFAXbfTnxc4Y5c4iZm3-JpSmAZtEHFTQwiHcs69DU'
      user_id: '4992105'
      cookie: 'datadome=5BCEXlMT1hg3ij47ktNAVCalnEQZGsf5sTM4W9ZmAYlEdbJbGcl6EIb~a8cbjqU8Qs_J8Qsm6mJWtAIE~PlzF8WLaTfWQZE4Rf_D5A_Kh5grHnhVF2_IdW7SCKtC14Cl; Max-Age=31536000; Domain=.apptoogoodtogo.com; Path=/; Secure; SameSite=Lax'
      scan_interval: 300
    