
input_number:
  weather_eikenbos_min_temp_today:
    name: "Eikenbos minimum temperatuur vandaag"
    min: -30
    max: 50
    step: 0.1
    mode: box
    unit_of_measurement: °C

  weather_eikenbos_max_temp_today:
    name: "Eikenbos maximum temperatuur vandaag"
    min: -30
    max: 50
    step: 0.1
    mode: box
    unit_of_measurement: °C

template:
  - sensor:
      - name: "weather_eikenbos_min_temp_tomorrow"
        state: >
          {{ state_attr('weather.eikenbos_met_no', 'forecast')[0].templow }}
        device_class: temperature
        state_class: measurement
        unit_of_measurement: °C
      - name: "weather_eikenbos_max_temp_tomorrow"
        state: >
          {{ state_attr('weather.eikenbos_met_no', 'forecast')[0].temperature }}
        device_class: temperature
        state_class: measurement
        unit_of_measurement: °C

sensor:
  - platform: template
    sensors:
      eikenbos_temperature_average_forecast_4_hours:
        # You can get a free api key from Openweather
        # To have hourly temperature forecast, in the OpenWeather integration select the option "onecall_hourly"
        friendly_name: "Eikenbos gemiddelde temperatuur volgende 4 uren"
        value_template: "{{ state_attr('weather.eikenbos_openweather', 'forecast')[:4] | map(attribute='temperature') | average | round(1) }}"
        unit_of_measurement: °C
        device_class: temperature

      eikenbos_temperature_average_forecast_2_hours:
        # You can get a free api key from Openweather
        # To have hourly temperature forecast, in the OpenWeather integration select the option "onecall_hourly"
        friendly_name: "Eikenbos gemiddelde temperatuur volgende 2 uren"
        value_template: "{{ state_attr('weather.eikenbos_openweather', 'forecast')[:2] | map(attribute='temperature') | average | round(1) }}"
        unit_of_measurement: °C
        device_class: temperature
  
      eikenbos_temperature_minimum_forecast_8_hours:
        # You can get a free api key from Openweather
        # To have hourly temperature forecast, in the OpenWeather integration select the option "onecall_hourly"
        friendly_name: "Eikenbos minimum temperatuur volgende 8 uren"
        value_template: "{{ state_attr('weather.eikenbos_openweather', 'forecast')[:8] | map(attribute='temperature') | min | round(1) }}"
        unit_of_measurement: °C
        device_class: temperature

  - platform: min_max
    name: "Eikenbos average temperature"
    type: mean
    round_digits: 1
    entity_ids:
      - sensor.leuven_temperature
      - sensor.terrastafel_temperature
      - sensor.terrasmuur_temperature
      - sensor.voordeur_bewegingssensor_temperature