#####################################################################
# historiek ramen
#####################################################################

sensor:
  - platform: history_stats
    name: "keuken raam open vandaag"
    entity_id: binary_sensor.keuken_raam 
    state: 'on'
    type: time
    start: '{{ now().replace(hour=0).replace(minute=0).replace(second=0) }}'
    end: '{{ now() }}'

  - platform: history_stats
    name: "kamer Amilya raam open vandaag"
    entity_id: binary_sensor.kamer_amilya_raam 
    state: 'on'
    type: time
    start: '{{ now().replace(hour=0).replace(minute=0).replace(second=0) }}'
    end: '{{ now() }}'

  - platform: history_stats
    name: "badkamer raam gekanteld vandaag"
    entity_id: binary_sensor.badkamer_raam_kantel 
    state: 'on'
    type: time
    start: '{{ now().replace(hour=0).replace(minute=0).replace(second=0) }}'
    end: '{{ now() }}'

  - platform: history_stats
    name: "badkamer raam wijd open vandaag"
    entity_id: binary_sensor.badkamer_raam_wijd
    state: 'on'
    type: time
    start: '{{ now().replace(hour=0).replace(minute=0).replace(second=0) }}'
    end: '{{ now() }}'

  - platform: history_stats
    name: "kamer Alunya raam open vandaag"
    entity_id: binary_sensor.kamer_alunya_raam 
    state: 'on'
    type: time
    start: '{{ now().replace(hour=0).replace(minute=0).replace(second=0) }}'
    end: '{{ now() }}'

  - platform: history_stats
    name: "kamer Alunya schuifraam open vandaag"
    entity_id: binary_sensor.kamer_alunya_schuifraam 
    state: 'on'
    type: time
    start: '{{ now().replace(hour=0).replace(minute=0).replace(second=0) }}'
    end: '{{ now() }}'

  - platform: history_stats
    name: "master bedroom raam gekanteld vandaag"
    entity_id: binary_sensor.master_bedroom_raam_kantel 
    state: 'on'
    type: time
    start: '{{ now().replace(hour=0).replace(minute=0).replace(second=0) }}'
    end: '{{ now() }}'

  - platform: history_stats
    name: "master bedroom raam wijd open vandaag"
    entity_id: binary_sensor.master_bedroom_raam_wijd 
    state: 'on'
    type: time
    start: '{{ now().replace(hour=0).replace(minute=0).replace(second=0) }}'
    end: '{{ now() }}'
