template:
  - sensor:
      - name: "car charge stoptimer starttime"
        state: >
          {% set target = states('input_number.car_charge_target_percentage') | float(default=0) %}
          {% set soc = states('sensor.audi_e_tron_sportback_state_of_charge') | float(default=0) %}
          {% set nog_te_laden_procent = [target - soc, 0] | max %}
          {% set nog_te_laden_minuten = nog_te_laden_procent * states('input_number.minuten_voor_1_laden') | round(2) %}
          {{ strptime((as_timestamp(states('input_datetime.car_charge_target_time')) - ((nog_te_laden_minuten | float(default=0) + 10 ) * 60) ) | timestamp_custom('%Y-%m-%d %H:%M',false), '%Y-%m-%d %H:%M') }}
