sensor:
  - platform: template
    sensors:
      car_solar_wattmeter:
        friendly_name: "auto zonne-energie"
        unique_id: '6d159574-486d-4e8f-85dc-f5965cfa4647' 
        unit_of_measurement: W
        value_template: >
          {% set charger = states('sensor.charger_real_power') | float(default=0) %}
          {% set solar = states('sensor.solar_power') | float(default=0) %}
          {% if charger > 0 and solar >= charger %}
            {{ charger }}
          {% elif charger > 0 and solar < charger %}
            {{ solar }}
          {% else %}
            0
          {% endif %}

      car_net_wattmeter:
        friendly_name: "auto netstroom"
        unique_id: 'b4a3fda6-2a3e-44f0-aa8b-ae833b86acf0' 
        unit_of_measurement: W
        value_template: >
          {% set charger = states('sensor.charger_real_power') | float(default=0) %}
          {% set solar = states('sensor.solar_power') | float(default=0) %}
          {% set net = states('sensor.net_power') | float(default=0) %}
          {% if solar <= charger %}
              {{ charger - solar }}
          {% elif net <= 0 and charger >= 0 %}
              0
          {% endif %}