#####################################################################
# historiek laptops
#####################################################################

sensor:  
  - platform: history_stats
    name: "Chromebook Bart/Madouce aan vandaag"
    entity_id: switch.bart_chromebook_chromeos_device
    state: "on"
    type: time
    start: '{{ now().replace(hour=0).replace(minute=0).replace(second=0) }}'
    end: '{{ now() }}'
    
  - platform: history_stats
    name: "Laptop Bart Fortis aan vandaag"
    entity_id: switch.bart_laptop_fortis_brum05007458
    state: "on"
    type: time
    start: '{{ now().replace(hour=0).replace(minute=0).replace(second=0) }}'
    end: '{{ now() }}'
    
  - platform: history_stats
    name: "Windows laptop aan vandaag"
    entity_id: switch.bart_utraland_notebook_wifi_windows_device
    state: "on"
    type: time
    start: '{{ now().replace(hour=0).replace(minute=0).replace(second=0) }}'
    end: '{{ now() }}'
