sensor:
  - platform: nmbs
    station_from: "Leuven"
    station_to: "Brussel-Centraal/Bruxelles-Central"
    exclude_vias: true

  - platform: nmbs
    station_from: "Brussel-Centraal/Bruxelles-Central"
    station_to: "Leuven"
    exclude_vias: true    
