###############################################################################
#
# binary sensors: warmer/kouder dan binnen/buiten
# 
###############################################################################

binary_sensor:
  - platform: template
    sensors:
      warm_outside_living:
        friendly_name: "buiten warmer dan in living"
        value_template: "{{ states('sensor.temp_leuven24_wunderground') > states('sensor.living_temperature') }}"
      warm_inside_living:
        friendly_name: "in living warmer dan buiten"
        value_template: "{{ states('sensor.living_temperature') > states('sensor.temp_leuven24_wunderground') }}"
      warm_outside_amilya:
        friendly_name: "buiten warmer dan in kamer Amilya"
        value_template: "{{ states('sensor.temp_leuven24_wunderground') > states('sensor.kamer_amilya_temperature') }}"
      warm_inside_amilya:
        friendly_name: "in kamer Amilya warmer dan buiten"
        value_template: "{{ states('sensor.kamer_amilya_temperature') > states('sensor.temp_leuven24_wunderground') }}"
      warm_outside_veranda:
        friendly_name: "buiten warmer dan in veranda"
        value_template: "{{ states('sensor.temp_leuven24_wunderground') > states('sensor.veranda_temperature') }}"
      warm_inside_veranda:
        friendly_name: "in veranda warmer dan buiten"
        value_template: "{{ states('sensor.veranda_temperature') > states('sensor.temp_leuven24_wunderground') }}"
      warm_outside_bedroom:
        friendly_name: "buiten warmer dan in master bedroom"
        value_template: "{{ states('sensor.temp_leuven24_wunderground') > states('sensor.master_bedroom_temperature') }}"
      warm_inside_bedroom:
        friendly_name: "in master bedroom warmer dan buiten"
        value_template: "{{ states('sensor.master_bedroom_temperature') > states('sensor.temp_leuven24_wunderground') }}"
