template:
- sensor:
    - name: "washing machine expected time left"
      unique_id: 'c04aa3c3-ef3e-4329-88c3-706a66ec7968'
      state: >
        {% set washing_started = as_timestamp(states('input_datetime.washing_started')) %}
        {% set washing_stopped = as_timestamp(states('input_datetime.washing_stopped')) %}
        {% set washing_expected_runtime = states('input_number.washing_expected_runtime') | float(0) %}
        {% set expected_end_time = washing_started + washing_expected_runtime %}
        {% set expected_time_left = expected_end_time - now().timestamp() %}
        {{ expected_time_left }}

input_number:
  washing_expected_runtime:
    name: "wasmachine geschatte duur"
    min: 0
    max: 1000000000
    step: 1
    mode: slider

input_datetime:
  washing_expected_time_to_stop:
    name: "wasmachine verwachte eindtijd"
    has_date: true
    has_time: true

  washing_started:
    name: "wasmachine starttijd"
    has_date: true
    has_time: true

  washing_stopped:
    name: "wasmachine eindtijd"
    has_date: true
    has_time: true
