
template:
  - sensor:
      - name: "badkamer raam"
        state: >
          {% if is_state('binary_sensor.badkamer_raam_wijd', 'on') %}
            wijd open
          {% elif is_state('binary_sensor.badkamer_raam_kantel', 'on') %}
            gekanteld
          {% else %}
            gesloten
          {% endif %}

      - name: "master bedroom raam"
        state: >
          {% if is_state('binary_sensor.master_bedroom_raam_wijd', 'on') %}
            wijd open
          {% elif is_state('binary_sensor.master_bedroom_raam_kantel', 'on') %}
            gekanteld
          {% else %}
            gesloten
          {% endif %}