automation:

##############################
# verluchting kamers
##############################

- alias: Om 6 uur bepaal max dagtemperatuur uur
  id: 'ed9969de-ed32-4d1d-94ed-48e3622c94b4'
  description: ''
  trigger:
  - platform: time
    at: 06:00
  condition: []
  action:
  - service: input_datetime.set_datetime
    target:
      entity_id: input_datetime.max_dagtemperatuur_uur
    data:
      time:
        sensor.day_max_temp_datetime
  mode: single
  
- alias: max temperatuur van de dag bereikt = melding
  id: '91ed3a1c-ce13-47db-a612-4dc6d912fb89'
  description: ''
  trigger:
  - platform: time
    at: input_datetime.max_dagtemperatuur_uur
  condition: []
  action:
  - service: notify.bart_phone
    data:
      title: Nu is het warmste deel van de dag.
      message: Nu is het warmste deel van de dag.
  mode: single

- alias: 🪟 raam Amilya openen op warmste moment van de dag
  id: '63cf0cbd-bc53-422d-9095-90cffa3eea3e'
  description: ''
  trigger:
  - platform: time
    at: input_datetime.max_dagtemperatuur_uur
  condition:
  - condition: template
    value_template: "{{ ('sensor.amilya_raam_open_vandaag')| int(2) | float(default=0) == 0 }}"
  - condition: template
    value_template: "{{ ('sensor.kamer_amilya_heating')| int(2) | float(default=0) == 0 }}"
  action:
  - service: input_boolean.turn_on
    target:
      entity_id: input_boolean.kamer_amilya_raam_moet_open    
  - service: script.notify_bart_windows
    data_template:
      title: Zet raam Amilya nu even open. Beste moment van de dag.
      message: "Temp buiten: {{states('sensor.temp_leuven24_wunderground')}} °C. Vocht kamer Amilya: {{states('sensor.kamer_amilya_humidity')}}%.<br>Raam is vandaag nog niet open geweest."
      tag: window_kamer_amilya  
  - service: script.notify_madouce_windows
    data_template:
      title: Zet raam Amilya nu even open. Beste moment van de dag.
      message: "Temp buiten: {{states('sensor.temp_leuven24_wunderground')}} °C. Vocht kamer Amilya: {{states('sensor.kamer_amilya_humidity')}}%.<br>Raam is vandaag nog niet open geweest."
      tag: window_kamer_amilya
  mode: single

- alias: 🪟 raam Alunya openen op warmste moment van de dag
  id: 'f2d84987-861d-460a-9ff0-79535903143a'
  description: ''
  trigger:
  - platform: time
    at: input_datetime.max_dagtemperatuur_uur
  condition:
  - condition: template
    value_template: "{{ ('sensor.alunya_raam_open_vandaag')| int(2) | float(default=0) == 0 }}"
  - condition: template
    value_template: "{{ ('sensor.kamer_alunya_heating')| int(2) |float(default=0) == 0 }}"
  action:
  - service: input_boolean.turn_on
    target:
      entity_id: input_boolean.kamer_alunya_raam_moet_open
  - service: script.notify_bart_windows
    data_template:
      title: Zet raam Alunya nu even open. Beste moment van de dag.
      message: "Temp buiten: {{states('sensor.temp_leuven24_wunderground')}} °C. Vocht kamer Alunya: {{states('sensor.kamer_alunya_humidity')}}%.<br>Raam is vandaag nog niet open geweest."
      tag: window_kamer_alunya
  - service: script.notify_madouce_windows
    data_template:
      title: Zet raam Alunya nu even open. Beste moment van de dag.
      message: "Temp buiten: {{states('sensor.temp_leuven24_wunderground')}} °C. Vocht kamer Alunya: {{states('sensor.kamer_alunya_humidity')}}%.<br>Raam is vandaag nog niet open geweest."
      tag: window_kamer_alunya      
  mode: single

- alias: 🪟 raam keuken openen op warmste moment van dag
  id: 615fc634-795d-489e-9c25-4f36d912b7ca
  description: als het raam nog niet geopend geweest is vandaag = melding sturen op warmste moment van de dag
  trigger:
  - platform: time
    at: input_datetime.max_dagtemperatuur_uur
  condition:
  - condition: template
    value_template: "{{ ('sensor.keuken_raam_open_vandaag')| int(2) | float(default=0) == 0 }}"
  - condition: template
    value_template: "{{ ('sensor.living_room_heating')| int(2) | float(default=0) == 0 }}"
  action:
  - service: input_boolean.turn_on
    target:
      entity_id: input_boolean.living_room_raam_moet_open  
  - service: script.notify_bart_windows
    data_template:
      title: "Zet keukenraam nu even open. Beste moment van de dag."
      message: "Temp buiten: {{states('sensor.temp_leuven24_wunderground')}} °C. Vocht living: {{states('sensor.living_room_humidity')}}%.<br>Raam is vandaag nog niet open geweest."
      tag: "window_living_room"
  - service: script.notify_madouce_windows
    data_template:
      title: "Zet keukenraam nu even open. Beste moment van de dag."
      message: "Temp buiten: {{states('sensor.temp_leuven24_wunderground')}} °C. Vocht living: {{states('sensor.living_room_humidity')}}%.<br>Raam is vandaag nog niet open geweest."
      tag: "window_living_room"
  mode: single


##############################
# luchtzuivering living
##############################

- alias: 💨 Air Quality Index > 8 = purifier aan
  id: '7e3043d1-8299-4121-ad8b-08da26340065'
  description: ''
  trigger:
  - minutes: /5
    platform: time_pattern
  condition:
  - condition: template
    value_template: "{{ state_attr('fan.xiaomi_air_purifier_3h', 'aqi')| float(default=0) > 8  }}"
  - condition: state
    entity_id: group.gezin
    state: 'home'
  - condition: time
    after: '7:00'
    before: '23:30'
  action:
  - service: fan.set_preset_mode
    data:
      entity_id: fan.xiaomi_air_purifier_3h
      preset_mode: auto
  mode: single

- alias: 💨 Air Quality Index < 8 = purifier uit
  id: '991a6848-2b77-4573-a2c4-76d603eeb899'
  description: ''
  trigger:
  - minutes: /5
    platform: time_pattern
  condition:
  - condition: template
    value_template: "{{ state_attr('fan.xiaomi_air_purifier_3h', 'aqi')| float(default=0) < 8  }}"
  - condition: state
    entity_id: input_boolean.busy_cooking
    state: 'off'    
  action:
  - service: fan.turn_off
    target:
      entity_id: fan.xiaomi_air_purifier_3h
  mode: single

- alias: 💨 not home = Air purifier uit
  id: '0c3adcca-2586-4ee3-a3bc-a78f38f65937'
  description: ''
  trigger:
  - platform: state
    entity_id: group.gezin
    to: 'not_home'
    for: 00:05:00
  condition: []
  action:
  - service: fan.turn_off
    target:
      entity_id: fan.xiaomi_air_purifier_3h
  mode: single

- alias: 💨 om 23u00 = Air purifier uit
  id: 'c046f93d-d49a-4db3-8dbf-4e3231374926'
  description: ''
  trigger:
  - platform: time
    at: '23:00:00'
  condition: []
  action:
  - service: fan.turn_off
    target:
      entity_id: fan.xiaomi_air_purifier_3h
  mode: single

- alias: 💨 aan het koken = air purifier aan
  id: 'ef2b8563-60f8-4962-a357-6ac1589b08cd'
  description: ''
  trigger:
  - platform: state
    entity_id: input_boolean.busy_cooking
    to: 'on'
  - device_id: dd2e7860b0b3eade0fbecf9965c6106a
    domain: deconz
    platform: device
    type: remote_button_short_press
    subtype: turn_on  
  condition: []
  action:
  - service: input_boolean.turn_on
    target:
      entity_id: input_boolean.busy_cooking
  - service: fan.turn_on
    target:
      entity_id: fan.xiaomi_air_purifier_3h
    data: {}
  - service: notify.bart_phone
    data:
      message: Lekker aan het koken? De lucht wordt gezuiverd.
  - service: media_player.volume_set
    data:
      entity_id: media_player.living_speaker
      volume_level: 0.5      
  - service: tts.google_say
    data:
      entity_id: media_player.living_speaker
      message: Laat het dadelijk smaken! Ik zorg voor de zuivere lucht.  
  - delay: '00:00:10'
  - service: media_player.volume_set
    data:
      entity_id: media_player.living_speaker
      volume_level: 0.3
  - delay: '01:00:00'
  - service: input_boolean.turn_off
    target:
      entity_id: input_boolean.busy_cooking
  mode: restart
  
- alias: 💨 koken gedaan = air purifier uit
  id: 'dd3f89f5-e628-408a-a5aa-9aa9afbbd6d6'
  description: ''
  trigger:
  - platform: state
    entity_id: input_boolean.busy_cooking
    to: 'off'
  condition: []
  action:
  - service: fan.turn_off
    target:
      entity_id: fan.xiaomi_air_purifier_3h
    data: {}
  - service: tts.google_say
    data:
      entity_id: media_player.living_speaker
      message: De kooksessie is gedaan. Hopelijk heeft het gesmaakt.
  mode: restart


##############################
# ventilatie toilet
##############################

- alias: 💨 beweging in toilet = ventilator aan na 1,5 minuten tot 5 minuten na laatste beweging
  id: '8215c271-a2bb-4a05-a083-9e31db80b3a1'
  description: ''
  trigger:
  - platform: state
    entity_id: binary_sensor.toilet_motion_sensor_motion
    to: 'on'
    for:
      hours: 0
      minutes: 1
      seconds: 30
  # only trigger when there is more than 1,5 minutes of motion    
  condition:
  - condition: time
    after: '7:0:0'
    before: '23:30:00'
  action:
  - service: switch.turn_on
    target:
      entity_id:
      - switch.toilet_douche_ventilatie
  - service: notify.bart_phone
    data:
      message: Ventilatie toilet START nu.
  - delay:
      hours: 0
      minutes: 5
      seconds: 0
      milliseconds: 0
  - service: switch.turn_off
    target:
      entity_id: switch.toilet_douche_ventilatie
  - service: notify.bart_phone
    data:
      message: Ventilatie toilet STOPT nu.
  mode: restart
  
- alias: 💨 1,5 min. licht in toilet = ventilator aan gedurende 3 minuten
  id: 'b5f5d558-a745-409f-8989-f0749a5992b4'
  description: ''
  trigger:
  - platform: state
    entity_id: light.toilet
    to: 'on'
    for: '00:01:30'
  condition:
  - condition: time
    after: '7:0:0'
    before: '23:30:00'
  action:
  - service: switch.turn_on
    target:
      entity_id:
      - switch.toilet_douche_ventilatie
  - delay:
      hours: 0
      minutes: 3
      seconds: 0
      milliseconds: 0
  - service: switch.turn_off
    target:
      entity_id: switch.toilet_douche_ventilatie
  mode: single


##############################
# ventilatie badkamer
##############################
- alias: 💨 beweging in douche = ventilator aan na 1,5 minuten
  id: '26b154d2-b891-4df6-84c3-b954e639a08e'
  description: ''
  trigger:
  - platform: state
    entity_id: binary_sensor.douche_sensor_motion
    to: 'on'
    for:
      hours: 0
      minutes: 0
      seconds: 30
  # only trigger when there is more than 30 seconds of motion    
  condition: []
  action:
  - service: switch.turn_on
    target:
      entity_id:
      - switch.toilet_douche_ventilatie
  - service: notify.bart_phone
    data:
      message: Ventilatie douche START nu.
  mode: single

- alias: 💨 Geen beweging meer in douche = ventilator uit na 10 minuten
  id: 'b17903c4-7fb3-434e-9264-0f8c1f874731'
  description: ''
  trigger:
  - platform: state
    entity_id: binary_sensor.douche_sensor_motion
    to: 'off'
    for:
      hours: 0
      minutes: 10
      seconds: 0
  # only trigger when there is no motion during 10 minutes    
  condition: []
  action:
  - service: switch.turn_off
    target:
      entity_id:
      - switch.toilet_douche_ventilatie
  - service: notify.bart_phone
    data:
      message: Ventilatie douche STOPT nu.
  mode: single

- alias: 🪟 badkamer raam wijd open = ventilator uit
  id: '09185cc1-4293-4cc0-9f89-831f0be7a74e'
  description: ''
  trigger:
  - platform: state
    entity_id: binary_sensor.badkamer_raam_wijd
    to: 'on'
    for:
      hours: 0
      minutes: 0
      seconds: 30
      milliseconds: 0
  condition: []
  action:
  - service: switch.turn_off
    target:
      entity_id: switch.toilet_douche_ventilatie
  mode: single  

- alias: 💨 ventilator al 20 minuten aan = ventilator uit
  id: '6754188c-c368-4013-89cc-1acc82b30ad3'
  description: ''
  trigger:
  - platform: state
    entity_id: switch.toilet_douche_ventilatie
    to: 'on'
    for:
      hours: 0
      minutes: 20
      seconds: 0
  condition: []
  action:
  - service: switch.turn_off
    target:
      entity_id:
      - switch.toilet_douche_ventilatie
  mode: single

- alias: 💨 licht in douche = ventilator aan zolang licht brandt + 10 minuten
  id: 'c4f8b201-16f1-41db-a285-7fb33b277343'
  description: ''
  trigger:
  - platform: state
    entity_id: light.badkamer_douche
    to: 'on'
    for: '00:00:30'
  condition:
  - condition: time
    after: '6:30:0'
    before: '23:30:00'
  action:
  - repeat:
      while:
      - condition: state
        entity_id: light.badkamer_douche
        state: 'on'
      sequence:
      - service: switch.turn_on
        target:
          entity_id:
          - switch.toilet_douche_ventilatie
  - delay:
      hours: 0
      minutes: 10
      seconds: 0
      milliseconds: 0
  - service: switch.turn_off
    target:
      entity_id: switch.toilet_douche_ventilatie
  mode: single

##############################
# ventilator (algemeen)
##############################

- alias: Ventilator 10 min aan
  id: 'b1f343ba-5201-43ee-9502-f1d96abe99f9'
  trigger:
  - platform: event
    event_type: mobile_app_notification_action
    event_data:
      action: toilet_douche_ventilator_10_min_aan
  action:
  - service: switch.turn_on
    target:
      entity_id:
      - switch.toilet_douche_ventilatie
  - delay:
      hours: 0
      minutes: 10
      seconds: 0
      milliseconds: 0
  - service: switch.turn_off
    target:
      entity_id:
      - switch.toilet_douche_ventilatie
  mode: single