automation:

- alias: 💨 Air Quality Index > 8 = purifier on
  id: '7e3043d1-8299-4121-ad8b-08da26340065'
  description: ''
  trigger:
  - minutes: /5
    platform: time_pattern
  condition:
  - condition: numeric_state
    entity_id: fan.xiaomi_air_purifier_3h
    attribute: aqi
    above: '8'
  - condition: state
    entity_id: group.gezin
    state: home
  - condition: time
    after: '7:00'
    before: '23:30'
  action:
  - service: fan.set_preset_mode
    data:
      entity_id: fan.xiaomi_air_purifier_3h
      preset_mode: auto
  mode: single

- alias: 💨 not home = Air purifier off
  id: '0c3adcca-2586-4ee3-a3bc-a78f38f65937'
  description: ''
  trigger:
  - platform: state
    entity_id: group.gezin
    to: not_home
    for: 00:05:00
  condition: []
  action:
  - service: fan.turn_off
    target:
      entity_id: fan.xiaomi_air_purifier_3h
  mode: single

- alias: 💨 Air Quality Index < 8 = purifier off
  id: '991a6848-2b77-4573-a2c4-76d603eeb899'
  description: ''
  trigger:
  - minutes: /5
    platform: time_pattern
  condition:
  - condition: numeric_state
    entity_id: fan.xiaomi_air_purifier_3h
    attribute: aqi
    below: '8'
  action:
  - service: fan.turn_off
    target:
      entity_id: fan.xiaomi_air_purifier_3h
  mode: single

- alias: 💨 purifier off @ 23u30
  id: '1894cdae-230b-4faa-a1cf-209e92df141b'
  description: ''
  trigger:
  - platform: time
    at: '23:30'
  condition: []
  action:
  - service: fan.turn_off
    target:
      entity_id: fan.xiaomi_air_purifier_3h
  mode: single
