automation:

- alias: 💨 Air Quality Index > 8 = purifier on
  id: '7e3043d1-8299-4121-ad8b-08da26340065'
  description: ''
  trigger:
  - minutes: /5
    platform: time_pattern
  condition:
  - condition: numeric_state
    entity_id: fan.xiaomi_air_purifier_3h
    attribute: aqi
    above: '8'
  - condition: state
    entity_id: group.gezin
    state: home
  - condition: time
    after: '7:00'
    before: '23:30'
  action:
  - service: fan.set_preset_mode
    data:
      entity_id: fan.xiaomi_air_purifier_3h
      preset_mode: auto
  mode: single

- alias: 💨 not home = Air purifier off
  id: '0c3adcca-2586-4ee3-a3bc-a78f38f65937'
  description: ''
  trigger:
  - platform: state
    entity_id: group.gezin
    to: 'not_home'
    for: 00:05:00
  condition: []
  action:
  - service: fan.turn_off
    target:
      entity_id: fan.xiaomi_air_purifier_3h
  mode: single

- alias: 💨 Air Quality Index < 8 = purifier off
  id: '991a6848-2b77-4573-a2c4-76d603eeb899'
  description: ''
  trigger:
  - minutes: /5
    platform: time_pattern
  condition:
  - condition: numeric_state
    entity_id: fan.xiaomi_air_purifier_3h
    attribute: aqi
    below: '8'
  - condition: state
    entity_id: input_boolean.busy_cooking
    state: 'off'    
  action:
  - service: fan.turn_off
    target:
      entity_id: fan.xiaomi_air_purifier_3h
  mode: single

- alias: 💨 purifier off @ 23u30
  id: '1894cdae-230b-4faa-a1cf-209e92df141b'
  description: ''
  trigger:
  - platform: time
    at: '23:30'
  condition: []
  action:
  - service: fan.turn_off
    target:
      entity_id: fan.xiaomi_air_purifier_3h
  mode: single
  
- alias: 💨 aan het koken = air purifier inschakelen
  id: 'ef2b8563-60f8-4962-a357-6ac1589b08cd'
  description: ''
  trigger:
  - platform: state
    entity_id: input_boolean.busy_cooking
    to: 'on'
  - device_id: dd2e7860b0b3eade0fbecf9965c6106a
    domain: deconz
    platform: device
    type: remote_button_short_press
    subtype: turn_on  
  condition: []
  action:
  - service: input_boolean.turn_on
    target:
      entity_id: input_boolean.busy_cooking
  - service: fan.turn_on
    target:
      entity_id: fan.xiaomi_air_purifier_3h
    data: {}
  - service: notify.bart_phone
    data:
      message: Lekker aan het koken? De lucht wordt gezuiverd.
  - service: media_player.volume_set
    data:
      entity_id: media_player.living_speaker
      volume_level: 0.5      
  - service: tts.google_say
    data:
      entity_id: media_player.living_speaker
      message: Laat het dadelijk smaken! Ik zorg voor de zuivere lucht.  
  - delay: '00:00:10'
  - service: media_player.volume_set
    data:
      entity_id: media_player.living_speaker
      volume_level: 0.3
  - delay: '01:00:00'
  - service: input_boolean.turn_off
    target:
      entity_id: input_boolean.busy_cooking
  mode: restart
  
- alias: 💨 koken gedaan = air purifier uitschakelen
  id: 'dd3f89f5-e628-408a-a5aa-9aa9afbbd6d6'
  description: ''
  trigger:
  - platform: state
    entity_id: input_boolean.busy_cooking
    to: 'off'
  condition: []
  action:
  - service: fan.turn_off
    target:
      entity_id: fan.xiaomi_air_purifier_3h
    data: {}
  - service: tts.google_say
    data:
      entity_id: media_player.living_speaker
      message: De kooksessie is gedaan. Hopelijk heeft het gesmaakt.
  mode: restart

- alias: Om 6 uur bepaal max dagtemperatuur uur
  id: 'ed9969de-ed32-4d1d-94ed-48e3622c94b4'
  description: ''
  trigger:
  - platform: time
    at: 06:00
  condition: []
  action:
  - service: input_datetime.set_datetime
    target:
      entity_id: input_datetime.max_dagtemperatuur_uur
    data:
      time:
        sensor.day_max_temp_datetime
  mode: single
  
- alias: max temperatuur van de dag bereikt = melding
  id: '91ed3a1c-ce13-47db-a612-4dc6d912fb89'
  description: ''
  trigger:
  - platform: time
    at: input_datetime.max_dagtemperatuur_uur
  condition: []
  action:
  - service: notify.bart_phone
    data:
      title: Nu is het warmste deel van de dag.
      message: Nu is het warmste deel van de dag.
  mode: single

- alias: 🪟 raam Alunya openen op warmste moment van de dag
  id: 'f2d84987-861d-460a-9ff0-79535903143a'
  description: ''
  trigger:
  - platform: time
    at: input_datetime.max_dagtemperatuur_uur
  condition:
    - condition: numeric_state
      entity_id: sensor.alunya_raam_open_vandaag
      below: '0.1'
    - condition: numeric_state
      entity_id: sensor.kamer_alunya_heating
      below: '0.1'     
  action:
  - service: notify.bart_phone
    data:
      title: Zet raam Alunya nu even open. Beste moment van de dag.
      message: "Temp buiten: {{states('sensor.temp_leuven24_wunderground')}} °C.<br>Raam is vandaag nog niet open geweest."
  - service: notify.madouce_phone
    data:
      title: Zet raam Alunya nu even open. Beste moment van de dag.
      message: "Temp buiten: {{states('sensor.temp_leuven24_wunderground')}} °C.<br>Raam is vandaag nog niet open geweest."
  mode: single

- alias: 🪟 raam Amilya openen op warmste moment van de dag
  id: '63cf0cbd-bc53-422d-9095-90cffa3eea3e'
  description: ''
  trigger:
  - platform: time
    at: input_datetime.max_dagtemperatuur_uur
  condition:
    - condition: numeric_state
      entity_id: sensor.amilya_raam_open_vandaag
      below: '0.1'
    - condition: numeric_state
      entity_id: sensor.kamer_amilya_heating
      below: '0.1'
  action:
  - service: notify.bart_phone
    data:
      title: Zet raam Amilya nu even open. Beste moment van de dag.
      message: "Temp buiten: {{states('sensor.temp_leuven24_wunderground')}} °C.<br>Raam is vandaag nog niet open geweest."
  - service: notify.madouce_phone
    data:
      title: Zet raam Amilya nu even open. Beste moment van de dag.
      message: "Temp buiten: {{states('sensor.temp_leuven24_wunderground')}} °C.<br>Raam is vandaag nog niet open geweest."
  mode: single

- alias: 🪟 raam keuken openen op warmste moment van dag
  id: aaa23215-35b5-4159-a036-0c6ee66e0646
  description: als het raam nog niet geopend geweest is vandaag = melding sturen op warmste moment van de dag
  trigger:
  - platform: time
    at: input_datetime.max_dagtemperatuur_uur
  condition:
    - condition: numeric_state
      entity_id: sensor.keuken_raam_open_vandaag
      below: 'O.1'
    - condition: numeric_state
      entity_id: sensor.living_room_heating
      below: '0.1'
  action:
  - service: notify.bart_phone
    data:
      title: Zet keukenraam nu even open. Beste moment van de dag.
      message: "Temp buiten: {{states('sensor.temp_leuven24_wunderground')}} °C.<br>Raam is vandaag nog niet open geweest."
  - service: notify.madouce_phone
    data:
      title: Zet keukenraam nu even open. Beste moment van de dag.
      message: "Temp buiten: {{states('sensor.temp_leuven24_wunderground')}} °C.<br>Raam is vandaag nog niet open geweest."
  mode: single
