############################ Table of Contents ############################ 
# 
#   Automations
#
#     batterij laag en niet verbonden (week)
#     batterij laag en niet verbonden (weekend)
#     autolader is verbonden
#     auto laadt = melding
#     auto gedaan met laden = melding
#     Auto 's avonds op slot?
#     auto sluiten
#     auto op slot = melding wissen
#     Auto 10 min. niet op slot = melding
#

############################ Automations ################################## 
automation:

#########################
# Auto laden
#########################

- alias: 🚗 batterij <60% en niet verbonden (week)
  id: '1622708363419'
  description: ''
  trigger:
  - platform: time
    at: '21:30'
  condition:
  - condition: time
    weekday:
    - mon
    - tue
    - wed
    - thu
    - sun
  - condition: template
    value_template: '{% if states.sensor.audi_e_tron_sportback_55_state_of_charge.state
      | float < 60.0 %} true {% endif %}'
  - condition: state
    entity_id: device_tracker.audi_e_tron_sportback_55_position
    state: home
  - condition: state
    entity_id: sensor.audi_e_tron_sportback_55_plug_state
    state: disconnected
  action:
  - service: notify.bart_phone
    data:
      title: Auto laden?
      message: "🚙 Auto maar {{states('sensor.audi_e_tron_sportback_55_state_of_charge')}}% = {{states('sensor.audi_e_tron_sportback_55_primary_engine_range')}} km."
      data:
        color: green
        tag: auto_laden
  - service: notify.madouce_phone
    data:
      title: Auto laden?
      message: "🚙 Auto maar {{states('sensor.audi_e_tron_sportback_55_state_of_charge')}}% = {{states('sensor.audi_e_tron_sportback_55_primary_engine_range')}} km."
      data:
        color: green
        tag: auto_laden
  mode: single

- alias: 🚗 batterij <80% en niet verbonden (weekend)
  id: '1625819980111'
  description: ''
  trigger:
  - platform: time
    at: '21:45'
  condition:
  - condition: time
    weekday:
    - fri
    - sat
  - condition: template
    value_template: '{% if states.sensor.audi_e_tron_sportback_55_state_of_charge.state
      | float < 80.0 %} true {% endif %}'
  - condition: state
    entity_id: device_tracker.audi_e_tron_sportback_55_position
    state: home
  - condition: state
    entity_id: sensor.audi_e_tron_sportback_55_plug_state
    state: disconnected
  action:
  - service: notify.bart_phone
    data:
      title: Auto laden voor het weekend?
      message: "🚙 Auto maar {{states('sensor.audi_e_tron_sportback_55_state_of_charge')}}% = {{states('sensor.audi_e_tron_sportback_55_primary_engine_range')}} km."
      data:
        color: green
        tag: auto_laden
  - service: notify.madouce_phone
    data:
      title: Auto laden voor het weekend?
      message: "🚙 Auto maar {{states('sensor.audi_e_tron_sportback_55_state_of_charge')}}% = {{states('sensor.audi_e_tron_sportback_55_primary_engine_range')}} km."
      data:
        color: green
        tag: auto_laden
  mode: single

- alias: 🚗 autolader is verbonden
  id: '1626274710956'
  description: ''
  trigger:
  - platform: state
    entity_id: sensor.audi_e_tron_sportback_55_plug_state
    to: connected
  condition:
  action:
  - service: notify.bart_phone
    data:
      message: 🚙 Autolader is verbonden.
      data:
        color: green
        tag: auto_laden
        timeout: 300
  - service: notify.madouce_phone
    data:
      message: 🚙 Autolader is verbonden.
      data:
        color: green
        tag: auto_laden
        timeout: 300
  mode: single

- alias: 🚗 auto laadt = melding
  id: '10f06a54-7eea-4d86-9bf8-2ef07549a4d6'
  description: ''
  trigger:
  - platform: state
    entity_id: sensor.audi_e_tron_sportback_55_charging_state
    from: off
    to: charging
    for: 00:01:00
  condition: []
  action:
  - service: notify.bart_phone
    data:
      message: 🚙 Auto is aan het laden. Nu {{states('sensor.audi_e_tron_sportback_55_state_of_charge')}}%.
        Nog {{states('sensor.audi_e_tron_sportback_55_remaining_charge_time')}} laden.
      data:
        color: green
        tag: auto_laden
        timeout: 300
        actions:
        - action: URI
          title: meer info
          uri: /lovelace/e-tron
  - service: notify.madouce_phone
    data:
      message: 🚙 Auto is aan het laden. Nu {{states('sensor.audi_e_tron_sportback_55_state_of_charge')}}%.
        Nog {{states('sensor.audi_e_tron_sportback_55_remaining_charge_time')}} laden.
      data:
        color: green
        tag: auto_laden
        timeout: 300
        actions:
        - action: URI
          title: meer info
          uri: /lovelace/e-tron
  mode: single

- alias: 🚗 auto gedaan met laden = melding
  id: '1626508135498'
  description: ''
  trigger:
  - platform: state
    entity_id: sensor.audi_e_tron_sportback_55_charging_state
    to: completed
  condition: []
  action:
  - service: notify.bart_phone
    data:
      message: "🚙 Auto heeft gedaan met laden. Nu {{states('sensor.audi_e_tron_sportback_55_state_of_charge')}}%. {{states('sensor.audi_e_tron_sportback_55_primary_engine_range')}} km."
      data:
        color: green
        tag: auto_laden
        timeout: 43200
        actions:
        - action: URI
          title: meer info
          uri: /lovelace/e-tron
  - service: notify.madouce_phone
    data:
      message: "🚙 Auto heeft gedaan met laden. Nu {{states('sensor.audi_e_tron_sportback_55_state_of_charge')}}%. {{states('sensor.audi_e_tron_sportback_55_primary_engine_range')}} km."
      data:
        color: green
        tag: auto_laden
        timeout: 43200
        actions:
        - action: URI
          title: meer info
          uri: /lovelace/e-tron
  mode: single

#########################
# Auto op slot
#########################

- alias: 🚗 Auto 's avonds op slot?
  id: '1523708463420'
  description: Stuur een bericht als auto om 22u30 nog open is.
  trigger:
  - platform: time
    at: '22:30:00'
  condition:
  - condition: state
    entity_id: lock.audi_e_tron_sportback_55_door_lock_2
    state: unlocked
  action:
  - service: notify.bart_phone
    data:
      title: Auto niet op slot!
      message: 🚙 Er wordt nu geprobeerd om de auto te sluiten.
      data:
        channel: Important
        tag: slot_auto
        color: red
  - service: lock.lock
    target:
      entity_id: lock.audi_e_tron_sportback_55_door_lock_2
  - service: notify.madouce_phone
    data:
      title: Auto niet op slot!
      message: 🚙 Er wordt nu geprobeerd om de auto te sluiten.
      data:
        channel: Important
        tag: slot_auto
        color: red
  - service: lock.lock
    target:
      entity_id: lock.audi_e_tron_sportback_55_door_lock_2
  mode: single

- alias: auto sluiten
  id: '1626251778020'
  trigger:
  - platform: event
    event_type: mobile_app_notification_action
    event_data:
      action: lock_car
  action:
  - service: lock.lock
    target:
      entity_id: lock.audi_e_tron_sportback_55_door_lock_2
  mode: single

- alias: 🚗 auto is op slot (clear_notification)
  id: '1626270837776'
  description: ''
  trigger:
  - platform: state
    entity_id: lock.audi_e_tron_sportback_55_door_lock_2
    to: locked
  condition: []
  action:
  - service: notify.bart_phone
    data:
      message: "clear_notification"
      data:
        tag: slot_auto
  - service: notify.madouce_phone
    data:
      message: "clear_notification"
      data:
        tag: slot_auto        
  mode: single

- alias: 🚗 Auto 2 min. niet op slot = melding
  id: 'a2af962e-7fcf-4e6e-822e-5b33bc450628'
  description: ''
  trigger:
  - platform: time_pattern
    minutes: /2
  condition:
  - condition: state
    entity_id: lock.audi_e_tron_sportback_55_door_lock_2
    state: 'unlocked'
    for:
      hours: 0
      minutes: 2
      seconds: 0
      milliseconds: 0
  - condition: state
    entity_id: device_tracker.bart_s10
    state: 0
    attribute: speed
    for:
      hours: 0
      minutes: 2
      seconds: 0
      milliseconds: 0
  - condition: state
    entity_id: device_tracker.madouce_s20
    state: 0
    attribute: speed
    for:
      hours: 0
      minutes: 2
      seconds: 0
      milliseconds: 0
  action:
  - service: notify.bart_phone
    data:
      message: 🚙 Auto niet op slot! (veeg omlaag voor acties)
      data:
        channel: Important
        tag: slot_auto
        color: red
        actions:
        - action: lock_car
          title: SLUIT AUTO
  - service: notify.madouce_phone
    data:
      message: 🚙 Auto niet op slot! (veeg omlaag voor acties)
      data:
        channel: Important
        tag: slot_auto
        color: red
        actions:
        - action: lock_car
          title: SLUIT AUTO          
  mode: single
  
#########################
# Auto climatisatie
#########################  

- alias: 🚗 start auto climatisatie op uur bepaald in GUI
  id: '583aabff-84db-4aac-a7de-023aee0d79f1'
  trigger:
  - platform: template
    value_template: '{{ states(''sensor.time'') == (states.input_datetime.car_climatisation_time.attributes.timestamp
      | int | timestamp_custom(''%H:%M'', False)) }}'
  condition:
  - condition: state
    entity_id: input_boolean.car_climatisation_timer
    state: 'on'
  action:
   - service: script.auto_start_climatisation
  mode: restart
