############################ Table of Contents ############################ 
# 
#   Automations
#
#     batterij laag en niet verbonden (week)
#     batterij laag en niet verbonden (weekend)
#     autolader is verbonden
#     auto laadt = melding
#     auto gedaan met laden = melding
#     Auto 's avonds op slot?
#     auto sluiten
#     auto op slot = melding wissen
#     Auto 10 min. niet op slot = melding
#

############################ Automations ################################## 
automation:

#########################
# Auto laden
#########################

- alias: 🚗 batterij <60% en niet verbonden (week)
  id: '19c7cda6-2abb-4e28-9025-0ea5c4e1caa1'
  description: ''
  trigger:
  - platform: time
    at: '21:30'
  condition:
  - condition: time
    weekday:
    - mon
    - tue
    - wed
    - thu
    - sun
  - condition: template
    value_template: "{% if states('sensor.audi_e_tron_sportback_55_state_of_charge') | float < 60.0 %} true {% endif %}"
  - condition: state
    entity_id: device_tracker.audi_e_tron_sportback_55_position
    state: home
  - condition: state
    entity_id: sensor.audi_e_tron_sportback_55_plug_state
    state: disconnected
  action:
  - service: notify.bart_phone
    data:
      title: Auto laden?
      message: "🚙 Auto maar {{states('sensor.audi_e_tron_sportback_55_state_of_charge')}}% = {{states('sensor.audi_e_tron_sportback_55_primary_engine_range')}} km."
      data:
        color: green
        tag: auto_laden
        actions:
        - action: URI
          title: meer info
          uri: /eikenbos-dashboard/e-tron        
  - service: notify.madouce_phone
    data:
      title: Auto laden?
      message: "🚙 Auto maar {{states('sensor.audi_e_tron_sportback_55_state_of_charge')}}% = {{states('sensor.audi_e_tron_sportback_55_primary_engine_range')}} km."
      data:
        color: green
        tag: auto_laden
        actions:
        - action: URI
          title: meer info
          uri: /eikenbos-dashboard/e-tron        
  mode: single

- alias: 🚗 batterij <80% en niet verbonden (weekend)
  id: '30ea35b4-3f2a-4702-9df4-323965d8bf70'
  description: ''
  trigger:
  - platform: time
    at: '21:45'
  condition:
  - condition: time
    weekday:
    - fri
    - sat
  - condition: template
    value_template: "{% if states('sensor.audi_e_tron_sportback_55_state_of_charge') | float < 80.0 %} true {% endif %}"
  - condition: state
    entity_id: device_tracker.audi_e_tron_sportback_55_position
    state: home
  - condition: state
    entity_id: sensor.audi_e_tron_sportback_55_plug_state
    state: disconnected
  action:
  - service: notify.bart_phone
    data:
      title: Auto laden voor het weekend?
      message: "🚙 Auto maar {{states('sensor.audi_e_tron_sportback_55_state_of_charge')}}% = {{states('sensor.audi_e_tron_sportback_55_primary_engine_range')}} km."
      data:
        color: green
        tag: auto_laden
        actions:
        - action: URI
          title: meer info
          uri: /eikenbos-dashboard/e-tron        
  - service: notify.madouce_phone
    data:
      title: Auto laden voor het weekend?
      message: "🚙 Auto maar {{states('sensor.audi_e_tron_sportback_55_state_of_charge')}}% = {{states('sensor.audi_e_tron_sportback_55_primary_engine_range')}} km."
      data:
        color: green
        tag: auto_laden
        actions:
        - action: URI
          title: meer info
          uri: /eikenbos-dashboard/e-tron        
  mode: single

- alias: 🚗 autolader is verbonden
  id: 'cdd4783a-a810-4b0a-b46d-1b1bf58eb80e'
  description: ''
  trigger:
  - platform: state
    entity_id: sensor.audi_e_tron_sportback_55_plug_state
    to: 'connected'
  condition: []
  action:
  - service: notify.bart_phone
    data:
      title: "🚙 Autolader is verbonden." 
      message: "Nu {{states('sensor.audi_e_tron_sportback_55_state_of_charge')}}%. Nog {{states('sensor.audi_e_tron_sportback_55_remaining_charge_time')}} laden."
      data:
        color: green
        tag: auto_laden
        timeout: 300
        actions:
        - action: URI
          title: meer info
          uri: /eikenbos-dashboard/e-tron        
  - service: notify.madouce_phone
    data:
      message: "🚙 Autolader is verbonden. Nu {{states('sensor.audi_e_tron_sportback_55_state_of_charge')}}%."
      data:
        color: green
        tag: auto_laden
        timeout: 300
        actions:
        - action: URI
          title: meer info
          uri: /eikenbos-dashboard/e-tron        
  mode: single

- alias: 🚗 auto laadt = melding
  id: '10f06a54-7eea-4d86-9bf8-2ef07549a4d6'
  description: ''
  trigger:
  - platform: state
    entity_id: sensor.audi_e_tron_sportback_55_charging_state
    from: 'off'
    to: 'charging'
    for: 00:01:00
  condition: []
  action:
  - service: notify.bart_phone
    data:
      title: 🚙 Auto is aan het laden.
      message: Nu {{states('sensor.audi_e_tron_sportback_55_state_of_charge')}}%.
        Nog {{states('sensor.audi_e_tron_sportback_55_remaining_charge_time')}} laden.
        Nu {{states('sensor.audi_e_tron_sportback_55_primary_engine_range')}} km.
      data:
        color: green
        tag: auto_laden
        timeout: 300
        actions:
        - action: URI
          title: meer info
          uri: /eikenbos-dashboard/e-tron
  - service: notify.madouce_phone
    data:
      message: 🚙 Auto is aan het laden. Nu {{states('sensor.audi_e_tron_sportback_55_state_of_charge')}}%.
        Nog {{states('sensor.audi_e_tron_sportback_55_remaining_charge_time')}} laden.
      data:
        color: green
        tag: auto_laden
        timeout: 300
        actions:
        - action: URI
          title: meer info
          uri: /eikenbos-dashboard/e-tron
  mode: single

- alias: 🚗 auto gedaan met laden = melding
  id: '23ebfe4a-e944-49dc-aa3f-e8a1983e8a56'
  description: ''
  trigger:
  - platform: state
    entity_id: sensor.audi_e_tron_sportback_55_charging_state
    to: 'completed'
  condition: []
  action:
  - service: notify.bart_phone
    data:
      message: "🚙 Auto heeft gedaan met laden. Nu {{states('sensor.audi_e_tron_sportback_55_state_of_charge')}}%. {{states('sensor.audi_e_tron_sportback_55_primary_engine_range')}} km."
      data:
        color: green
        tag: auto_laden
        timeout: 43200
        actions:
        - action: URI
          title: meer info
          uri: /eikenbos-dashboard/e-tron
  - service: notify.madouce_phone
    data:
      message: "🚙 Auto heeft gedaan met laden. Nu {{states('sensor.audi_e_tron_sportback_55_state_of_charge')}}%. {{states('sensor.audi_e_tron_sportback_55_primary_engine_range')}} km."
      data:
        color: green
        tag: auto_laden
        timeout: 43200
        actions:
        - action: URI
          title: meer info
          uri: /eikenbos-dashboard/e-tron
  mode: single


#########################
# Auto op slot
#########################

- alias: 🚗 Auto 's avonds op slot?
  id: 'b35dc129-9a89-4655-b8da-32e7798880c1'
  description: Stuur een bericht als auto om 22u30 nog open is.
  trigger:
  - platform: time
    at: '22:30:00'
  condition:
  - condition: state
    entity_id: lock.audi_e_tron_sportback_55_door_lock_2
    state: unlocked
  - condition: state
    entity_id: device_tracker.bart_s10
    state: 0
    attribute: speed
    for:
      hours: 0
      minutes: 2
      seconds: 0
      milliseconds: 0
  - condition: state
    entity_id: device_tracker.madouce_s20
    state: 0
    attribute: speed
    for:
      hours: 0
      minutes: 2
      seconds: 0
      milliseconds: 0  
  action:
  - service: notify.bart_phone
    data:
      title: Auto niet op slot!
      message: 🚙 Er wordt nu geprobeerd om de auto te sluiten.
      data:
        channel: Important
        tag: slot_auto
        color: red
        actions:
        - action: URI
          title: meer info
          uri: /eikenbos-dashboard/e-tron        
  - service: notify.madouce_phone
    data:
      title: Auto niet op slot!
      message: 🚙 Er wordt nu geprobeerd om de auto te sluiten.
      data:
        channel: Important
        tag: slot_auto
        color: red
        actions:
        - action: URI
          title: meer info
          uri: /eikenbos-dashboard/e-tron        
  - service: lock.lock
    target:
      entity_id: lock.audi_e_tron_sportback_55_door_lock_2
  mode: single

- alias: auto sluiten
  id: 'ead368ce-23d8-4cd2-b63b-ad6cc916bae0'
  trigger:
  - platform: event
    event_type: mobile_app_notification_action
    event_data:
      action: lock_car
  action:
  - service: lock.lock
    target:
      entity_id: lock.audi_e_tron_sportback_55_door_lock_2
  mode: single

- alias: 🚗 auto is op slot (clear_notification)
  id: 'aef6ff87-883d-40ed-b638-a59c6eb66837'
  description: ''
  trigger:
  - platform: state
    entity_id: lock.audi_e_tron_sportback_55_door_lock_2
    to: 'locked'
  condition: []
  action:
  - service: notify.bart_phone
    data:
      message: "clear_notification"
      data:
        tag: slot_auto
  - service: notify.madouce_phone
    data:
      message: "clear_notification"
      data:
        tag: slot_auto        
  mode: single

- alias: 🚗 Auto 2 min. niet op slot = refresh & melding
  id: 'a2af962e-7fcf-4e6e-822e-5b33bc450628'
  description: ''
  trigger:
  - platform: state
    entity_id: lock.audi_e_tron_sportback_55_door_lock_2
    to: 'unlocked'
    for:
      hours: 0
      minutes: 2
      seconds: 0
  condition:
  - condition: state
    entity_id: device_tracker.bart_s10
    state: 0
    attribute: speed
    for:
      hours: 0
      minutes: 2
      seconds: 0
      milliseconds: 0
  - condition: state
    entity_id: device_tracker.madouce_s20
    state: 0
    attribute: speed
    for:
      hours: 0
      minutes: 2
      seconds: 0
      milliseconds: 0
  action:
  - service: audiconnect.refresh_data
    data:
      vin: WAUZZZGE6MB019131
  - delay:
      minutes: 2      
  - service: notify.bart_phone
    data:
      message: 🚙 Auto niet op slot! (veeg omlaag voor acties)
      data:
        channel: Important
        tag: slot_auto
        color: red
        actions:
        - action: lock_car
          title: sluit auto
        - action: URI
          title: meer info
          uri: /eikenbos-dashboard/e-tron          
  - service: notify.madouce_phone
    data:
      message: 🚙 Auto niet op slot! (veeg omlaag voor acties)
      data:
        channel: Important
        tag: slot_auto
        color: red
        actions:
        - action: lock_car
          title: sluit auto          
        - action: URI
          title: meer info
          uri: /eikenbos-dashboard/e-tron
  mode: single

  
#########################
# Auto climatisatie
#########################  

- alias: 🚗 start auto climatisatie op uur bepaald in GUI
  id: '583aabff-84db-4aac-a7de-023aee0d79f1'
  trigger:
  - platform: template
    value_template: "{{ states('sensor.time') == (states.input_datetime.car_climatisation_time.attributes.timestamp
      | int | timestamp_custom('%H:%M', False)) }}"
  condition:
  - condition: state
    entity_id: input_boolean.car_climatisation_timer
    state: 'on'
  action:
   - service: script.auto_start_climatisatie_nu
  mode: restart

- alias: 🚗 Om 19u in Waarschoot en koud = vraag auto voorverwarmen
  id: '8fa06ed3-7c9f-453d-80d4-a246df6633f8'
  description: ''
  trigger:
  - platform: time
    at: '19:00'
  condition:
  - condition: numeric_state
    entity_id: weather.eikenbos
    attribute: temperature
    below: 15
  - condition: state
    entity_id: person.bart
    state: Waarschoot
  - condition: state
    entity_id: device_tracker.bart_s10
    state: 0
    attribute: speed
    for:
      hours: 0
      minutes: 2
      seconds: 0
      milliseconds: 0
  action:
  - service: notify.bart_phone
    data:
      message: 🚙 Moet de auto worden voorverwamd?
      data:
        color: green
        actions:
        - action: URI
          title: zo ja, klik hier
          uri: /eikenbos-dashboard/e-tron-heater
  mode: single

- alias: 🚗 Madouce bij mama Madouce = vraag auto voorverwarmen
  id: '8fa06ed3-7c9f-453d-80d4-a246df6633f8'
  description: ''
  trigger:
  - condition: state
    entity_id: person.madouce
    state: "mama Madouce"
    for:
      hours: 1
      minutes: 0 
      seconds: 0
      milliseconds: 0
  condition:
  - condition: numeric_state
    entity_id: weather.eikenbos
    attribute: temperature
    below: 15
  - condition: state
    entity_id: device_tracker.madouce_s20
    state: 0
    attribute: speed
    for:
      hours: 0
      minutes: 2
      seconds: 0
      milliseconds: 0
  action:
  - service: notify.madouce_phone
    data:
      message: 🚙 Moet de auto worden voorverwamd?
      data:
        color: green
        actions:
        - action: URI
          title: zo ja, klik hier
          uri: /eikenbos-dashboard/e-tron-heater
  mode: single
