############################ Table of Contents ############################ 
# 
#   Automations
#


# bluetooth address Etron: 98:49:14:C1:37:0B
# VIN etron: WAUZZZGE6MB019131

############################ Automations ################################## 
automation:
 
#########################
# Status auto verversen
#########################   

- alias: Bart 3 km van thuis = verversen status auto
  id: '37cfe751-fb7d-4f9b-9a1e-772eeba15f64'
  trigger:
  - platform: numeric_state
    entity_id:
      - proximity.bart_home
    below: 3
  condition:
  - condition: template
    value_template: '{{ trigger.to_state.attributes.dir_of_travel  == "towards" }}'
  action:
  - service: audiconnect.refresh_data
    data:
      vin: WAUZZZGE6MB019131
  mode: single
  
- alias: Madouce 3 km van thuis = verversen status auto
  id: '533ee396-e37b-450b-a5e6-c981a9696b31'
  trigger:
  - platform: numeric_state
    entity_id:
      - proximity.madouce_home
    below: 3
  condition:
  - condition: template
    value_template: '{{ trigger.to_state.attributes.dir_of_travel  == "towards" }}'
  action:
  - service: audiconnect.refresh_data
    data:
      vin: WAUZZZGE6MB019131
  mode: single  
  
- alias: Car sim km veranderd
  id: '0813a89b-64b9-4fa8-934e-7e4ee91ee033'
  description: ''
  trigger:
  - platform: state
    entity_id: input_number.car_sim_km
  condition: []
  action:
  - service: input_number.set_value
    target:
      entity_id: input_number.car_sim_batteryprocent
    data:
      value: '{{ ((states(''input_number.car_sim_km'') | float * 10 ) / (states(''sensor.car_range_per_10percent'')
        | float)) | round(1) }}'
  mode: single

#######################################
# Reistijd
######################################

- alias: Meld reistijd naar Toyota Evere (bij ochtendwekker + 7u15 en 7u45)
  id: '0195b18e-5fd6-48a8-ae22-ca0e692fde6c'
  description: ''
  trigger:
  - platform: time
    at: sensor.sm_g986b_next_alarm  
  - platform: time
    at: '07:15'
  - platform: time
    at: '07:45'
  condition:
  - condition: template
    value_template: >
      {% set car_use_day = 'input_select.car_use_day' ~ now().isoweekday() %}
      {%if states(car_use_day) == "Toyota Evere"%} true {% endif %}
  action:
  - service: notify.madouce_phone
    data:
      title: Goede morgen, schat!
      message: "Reistijd naar Toyota Evere is {{states('sensor.waze_travel_time_huis_toyota_evere')}} minuten."
      data:
        tag: auto_laden
  mode: single
  
- alias: Meld reistijd naar Toyota Diest (bij ochtendwekker + 7u15 en 7u45)
  id: '5d976c12-4cdf-4534-821f-332dc180e65d'
  description: ''
  trigger:
  - platform: time
    at: sensor.sm_g986b_next_alarm  
  - platform: time
    at: '07:15'
  - platform: time
    at: '07:45'
  condition:
  - condition: template
    value_template: >
      {% set car_use_day = 'input_select.car_use_day' ~ now().isoweekday() %}
      {%if states(car_use_day) == "Toyota Diest"%} true {% endif %}
  action:
  - service: notify.madouce_phone
    data:
      title: Goede morgen, schat!
      message: "Reistijd naar Toyota Diest is {{states('sensor.waze_travel_time_huis_toyota_diest')}} minuten."
      data:
        tag: auto_laden
  mode: single  

