############################ Table of Contents ############################ 
# 
#   Automations
#

# bluetooth address Etron: 98:49:14:C1:37:0B
# VIN etron: WAUZZZGE6MB019131

############################ Automations ################################## 
automation:
  
#########################
# Auto climatisatie
#########################  

- alias: 🚗 start auto climatisatie op uur bepaald in GUI
  id: '583aabff-84db-4aac-a7de-023aee0d79f1'
  trigger:
  - platform: template
    value_template: "{{ states('sensor.time') == (states.input_datetime.car_climatisation_time.attributes.timestamp
      | int | timestamp_custom('%H:%M', False)) }}"
  condition:
  - condition: state
    entity_id: input_boolean.car_climatisation_timer
    state: 'on'
  action:
   - service: script.auto_start_climatisatie_nu
  mode: restart

- alias: 🚗 Om 19u in Waarschoot en koud = vraag auto voorverwarmen
  id: '8fa06ed3-7c9f-453d-80d4-a246df6633f8'
  description: ''
  trigger:
  - platform: time
    at: '19:00'
  condition:
  - condition: numeric_state
    entity_id: sensor.audi_e_tron_sportback_outdoor_temperature
    below: 15
  - condition: state
    entity_id: person.bart
    state: Waarschoot
  - condition: state
    entity_id: device_tracker.bart_s10
    state: 0
    attribute: speed
    for:
      hours: 0
      minutes: 2
      seconds: 0
      milliseconds: 0
  action:
  - service: notify.bart_phone
    data:
      message: 🚙 Moet de auto worden voorverwamd?
      data:
        tag: auto_verwarmen
        color: green
        actions:
        - action: URI
          title: zo ja, klik hier
          uri: /eikenbos-dashboard/e-tron-heater
  mode: single

- alias: 🚗 Bart verlaat auto
  id: '63ee4ac0-2944-4531-bc17-a2a6d60ff341'
  description: ''
  trigger:
    - platform: state
      entity_id: binary_sensor.bart_phone_connected_to_car
      from: 'on'
      to: 'off'
      for: "00:00:05"
  condition:
    - condition: numeric_state
      entity_id: sensor.audi_e_tron_sportback_outdoor_temperature
      below: 15
  action:
  - choose:
    # indien aankomst thuis, niets doen
    - conditions:
      - condition: state
        entity_id: person.bart
        state: "home"
      sequence:
    # indien aankomst bij sauna, onmiddellijk vragen
    - conditions:
        - condition: or
          conditions:
            - condition: state
              entity_id: person.bart
              state: "Sauna Elzenhof"
            - condition: state
              entity_id: person.bart
              state: "Sauna Hezemeer"
            - condition: state
              entity_id: person.bart
              state: "Sauna Boetfort"
      sequence:
      - service: notify.bart_phone
        data:
          title: 🚙 Moet de auto straks worden voorverwamd?
          message: Geniet van de sauna :)
          data:
            tag: auto_verwarmen      
            color: green
            actions:
            - action: URI
              title: zo ja, klik hier
              uri: /eikenbos-dashboard/e-tron-heater          
    # indien aankomst bij winkel, niets vragen en blijven verwarmen
    - conditions:
        - condition: or
          conditions:
            - condition: state
              entity_id: person.bart
              state: "Aldi Bierbeek"
            - condition: state
              entity_id: person.bart
              state: "Action Bierbeek"
            - condition: state
              entity_id: person.bart
              state: "AH Zaventem"
            - condition: state
              entity_id: person.bart
              state: "Lidl Sterrebeek"
      sequence:
      - service: script.auto_start_climatisatie_nu
    # indien aankomst bij plaats met lang verblijf, vragen 
    - conditions:
        - condition: or
          conditions:
            - condition: state
              entity_id: person.bart
              state: "Waarschoot"
            - condition: state
              entity_id: person.bart
              state: "Koen & Katiana"
      sequence:
      - service: notify.bart_phone
        data:
          title: 🚙 Auto straks voorverwamen?
          message: Een warme auto is altijd lekkerder.
          data:
            tag: auto_verwarmen      
            color: green
            actions:
            - action: URI
              title: zo ja, klik hier
              uri: /eikenbos-dashboard/e-tron-heater
      - wait_template: ''
        timeout: '01:00:00'
      - service: notify.bart_phone
        data:
          message: 🚙 Moet de auto worden voorverwamd?
          data:
            tag: auto_verwarmen      
            color: green
            actions:
            - action: URI
              title: zo ja, klik hier
              uri: /eikenbos-dashboard/e-tron-heater
    # alle andere locaties
    default:
    - service: notify.bart_phone
      data:
        title: 🚙 Auto straks voorverwamen?
        message: Een warme auto is altijd lekkerder.
        data:
          tag: auto_verwarmen
          color: green
          actions:
          - action: URI
            title: zo ja, klik hier
            uri: /eikenbos-dashboard/e-tron-heater
    - wait_template: ''
      timeout: '01:00:00'
    - service: notify.bart_phone
      data:
        message: 🚙 Moet de auto worden voorverwamd?
        data:
          tag: auto_verwarmen      
          color: green
          actions:
          - action: URI
            title: zo ja, klik hier
            uri: /eikenbos-dashboard/e-tron-heate
  mode: restart          

- alias: 🚗 Madouce verlaat auto
  id: '24b7df67-875f-48f9-8a96-4960bb91687a'
  description: ''
  trigger:
    - platform: state
      entity_id: binary_sensor.madouce_phone_connected_to_car
      from: 'on'
      to: 'off'
      for: "00:00:05"
  condition:
    - condition: numeric_state
      entity_id: sensor.audi_e_tron_sportback_outdoor_temperature
      below: 15
  action:
  - choose:
    # indien aankomst thuis, niets doen
    - conditions:
      - condition: state
        entity_id: person.madouce
        state: "home"
      sequence:
    # indien aankomst bij sauna, onmiddellijk vragen
    - conditions:
        - condition: or
          conditions:
            - condition: state
              entity_id: person.madouce
              state: "Sauna Elzenhof"
            - condition: state
              entity_id: person.madouce
              state: "Sauna Hezemeer"
            - condition: state
              entity_id: person.madouce
              state: "Sauna Boetfort"
      sequence:
      - service: notify.madouce_phone
        data:
          title: 🚙 Moet de auto straks worden voorverwamd?
          message: Geniet van de sauna :)
          data:
            tag: auto_verwarmen      
            color: green
            actions:
            - action: URI
              title: zo ja, klik hier
              uri: /eikenbos-dashboard/e-tron-heater          
    # indien aankomst bij winkel, niets vragen en blijven verwarmen
    - conditions:
        - condition: or
          conditions:
            - condition: state
              entity_id: person.madouce
              state: "Aldi Bierbeek"
            - condition: state
              entity_id: person.madouce
              state: "Action bierbeek"
            - condition: state
              entity_id: person.madouce
              state: "AH Zaventem"
            - condition: state
              entity_id: person.madouce
              state: "Lidl Sterrebeek"
      sequence:
      - service: script.auto_start_climatisatie_nu
    # indien aankomst bij plaats met lang verblijf, vragen 
    - conditions:
        - condition: or
          conditions:
            - condition: state
              entity_id: person.madouce
              state: "waarschoot"
            - condition: state
              entity_id: person.madouce
              state: "Koen & Katiana"
      sequence:
      - service: notify.madouce_phone
        data:
          title: 🚙 Auto straks voorverwamen?
          message: Een warme auto is altijd lekkerder.
          data:
            tag: auto_verwarmen      
            color: green
            actions:
            - action: URI
              title: zo ja, klik hier
              uri: /eikenbos-dashboard/e-tron-heater
      - wait_template: ''
        timeout: '01:00:00'
      - service: notify.madouce_phone
        data:
          message: 🚙 Moet de auto worden voorverwamd?
          data:
            tag: auto_verwarmen      
            color: green
            actions:
            - action: URI
              title: zo ja, klik hier
              uri: /eikenbos-dashboard/e-tron-heater
    # alle andere locaties
    default:
    - service: notify.madouce_phone
      data:
        title: 🚙 Auto straks voorverwamen?
        message: Een warme auto is altijd lekkerder.
        data:
          tag: auto_verwarmen
          color: green
          actions:
          - action: URI
            title: zo ja, klik hier
            uri: /eikenbos-dashboard/e-tron-heater
    - wait_template: ''
      timeout: '01:00:00'
    - service: notify.madouce_phone
      data:
        message: 🚙 Moet de auto worden voorverwamd?
        data:
          tag: auto_verwarmen      
          color: green
          actions:
          - action: URI
            title: zo ja, klik hier
            uri: /eikenbos-dashboard/e-tron-heate
  mode: restart
- alias: 🚗 Auto verwarmen bij begin werkdag bij Toyota Diest
  id: '4ed1d4be-1e9b-42b0-90b9-e32d9f584de0'
  description: ''
  trigger:
  - platform: time
    at: '07:00'
  condition:
  - condition: numeric_state
    entity_id: sensor.audi_e_tron_sportback_outdoor_temperature
    below: 15
  - condition: template
    value_template: >
      {% set car_use_day = 'input_select.car_use_day' ~ now().isoweekday() %}
      {%if states(car_use_day) == "Toyota Diest"%} true {% endif %}
  action:
  - service: notify.madouce_phone
    data:
      title: 🚙 De auto wordt nu voorverwarmd.
      message:  Geniet van de warme rit naar Diest.
      data:
        tag: auto_verwarmen
        color: green
        actions:
        - action: URI
          title: Voor meer info, klik hier
          uri: /eikenbos-dashboard/e-tron-heater
  - service: script.auto_start_climatisatie_nu
  mode: single 
 
- alias: 🚗 Auto verwarmen bij begin werkdag bij Toyota Evere
  id: 'caf13c49-2daa-4e8c-b275-a6811621cf50'
  description: ''
  trigger:
  - platform: time
    at: '07:30'
  condition:
  - condition: numeric_state
    entity_id: sensor.audi_e_tron_sportback_outdoor_temperature
    below: 15
  - condition: template
    value_template: >
      {% set car_use_day = 'input_select.car_use_day' ~ now().isoweekday() %}
      {%if states(car_use_day) == "Toyota Evere"%} true {% endif %}
  action:
  - service: notify.madouce_phone
    data:
      title: 🚙 De auto wordt nu voorverwarmd.
      message:  Geniet van de warme rit naar Evere.
      data:
        tag: auto_verwarmen
        color: green
        actions:
        - action: URI
          title: Voor meer info, klik hier
          uri: /eikenbos-dashboard/e-tron-heater
  - service: script.auto_start_climatisatie_nu
  mode: single 

- alias: 🚗 Auto verwarmen na werkdag bij Toyota Evere
  id: '2e05b1aa-1980-4c0d-b3a7-ee1df7fef055'
  description: ''
  trigger:
  - platform: time
    at: '16:20'
  condition:
  - condition: numeric_state
    entity_id: sensor.audi_e_tron_sportback_outdoor_temperature
    below: 15
  - condition: state
    entity_id: person.madouce
    state: "Toyota Evere"
  action:
  - service: notify.madouce_phone
    data:
      title: 🚙 De auto wordt nu voorverwarmd.
      message: Een warme auto is altijd lekkerder. Veilige rit dadelijk.
      data:
        tag: auto_verwarmen
        color: green
        actions:
        - action: URI
          title: Voor meer info, klik hier
          uri: /eikenbos-dashboard/e-tron-heater
  - service: script.auto_start_climatisatie_nu          
  mode: single

- alias: 🚗 Auto verwarmen na werkdag bij Toyota Diest
  id: '7c5f1cfa-b20a-4b5b-be63-8ad01ec4e57f'
  description: ''
  trigger:
  - platform: time
    at: '16:20'
  condition:
  - condition: numeric_state
    entity_id: sensor.audi_e_tron_sportback_outdoor_temperature
    below: 15
  - condition: state
    entity_id: person.madouce
    state: "Toyota Diest"
  action:
  - service: notify.madouce_phone
    data:
      title: 🚙 De auto wordt nu voorverwarmd.
      message: Een warme auto is altijd lekkerder. Veilige rit dadelijk.
      data:
        tag: auto_verwarmen
        color: green
        actions:
        - action: URI
          title: Voor meer info, klik hier
          uri: /eikenbos-dashboard/e-tron-heater
  - service: script.auto_start_climatisatie_nu          
  mode: single 

