
automation:

- alias: 🎄 Kerstverlichting buiten aan bij donker
  id: f37cac92-e0d6-4804-9554-ec59399e2d97
  description: ''
  trigger:
  - platform: sun
    event: sunset
    offset: '0'
  condition: []
  action:
  - service: switch.turn_on
    target:
      entity_id: switch.plug_1
  - service: notify.bart_phone
    data_template:
      message: '{{ ["Joehoe, de kerstverlichting brandt weer!","Jingle bells", "Merry Christmas with lots of love.", "Kerst is leuker met lichtjes.", "Wishing you a Christmas that is merry and bright!"] | random }}'
  - service: notify.madouce_phone
    data_template:
      message: '{{ ["Joehoe, de kerstverlichting brandt weer!","Jingle bells", "Merry Christmas with lots of love.", "Kerst is leuker met lichtjes.", "Wishing you a Christmas that is merry and bright!"] | random }}'
  mode: single
  
- alias: 🎄 Kerstverlichting buiten aan tijdens week vanaf 7u15
  id: 006a516d-4cd0-4201-944c-0cf1b6ae3991
  description: ''
  trigger:
  - platform: time
    at: '07:15:00'
  condition:
  - condition: and
    conditions:
    - condition: time
      weekday:
      - mon
      - tue
      - wed
      - thu
      - fri
    - condition: state
      entity_id: input_boolean.vakantieperiode
      state: 'off'
  action:
  - service: switch.turn_on
    target:
      entity_id: switch.plug_1
  mode: single

- alias: 🎄 Kerstverlichting buiten uit bij zonsopgang
  id: cea38af6-e8f7-4789-8ed4-86bb846f4aad
  description: ''
  trigger:
  - platform: state
    entity_id: sun.sun
    to: "above_horizon"
  condition: []    
  action:
  - service: switch.turn_off
    target:
      entity_id: switch.plug_1
  mode: single

- alias: 🎄 Kerstverlichting buiten uit om 22u30 zo-do en 23u vrij-za
  id: d771521b-4ba3-4c29-9032-52ec7162acf3
  description: ''
  trigger:
  - platform: time
    at:
    - '22:30'
    - '23:00'
  condition:
  - condition: template
    value_template: "{% set h = now().hour %} {% set wd = now().isoweekday() %} {{\
      \ (h == 22 and wd in [1, 2, 3, 4, 7]) or\n   (h == 23 and wd in [5,6]) }}\n"
  action:
  - service: switch.turn_off
    target:
      entity_id: switch.plug_1
  - service: notify.bart_phone
    data:
      message: Wat jammer, de kerstverlichting is weer uit!
  - service: notify.madouce_phone
    data:
      message: Wat jammer, de kerstverlichting is weer uit!
  mode: single

- alias: 🎄 Kerstboom binnen aan om 7u15 (weekdagen)
  id: 287636ff-a630-4b04-97b7-7e3f17cf7966
  description: ''
  trigger:
  - platform: time
    at: '07:15:00'
  condition:
  - condition: and
    conditions:
    - condition: time
      weekday:
      - mon
      - tue
      - wed
      - thu
      - fri
    - condition: state
      entity_id: group.gezin
      state: "home"
  action:
  - service: switch.turn_on
    target:
      entity_id: switch.plug_2
  mode: single

- alias: 🎄 Kerstboom binnen aan om 9u00 (weekend)
  id: 005242bc-2f69-45b3-9170-49c08a58c3c5
  description: ''
  trigger:
  - platform: time
    at: '09:00:00'
  condition:
  - condition: and
    conditions:
    - condition: time
      weekday:
      - sat
      - sun
    - condition: state
      entity_id: group.gezin
      state: home
  action:
  - service: switch.turn_on
    target:
      entity_id: switch.plug_2
  mode: single

- alias: 🎄 Kerstboom binnen uit om 23u00
  id: aa945472-94cf-4dde-9cad-40eb1bc81245
  description: ''
  trigger:
  - platform: time
    at: '23:00:00'
  - platform: state
    entity_id: group.gezin
    to: not_home
  condition:
  - condition: and
    conditions:
    - condition: time
      weekday:
      - mon
      - tue
      - wed
      - thu
      - fri
      - sat
      - sun
  action:
  - service: switch.turn_off
    target:
      entity_id: switch.plug_2
  mode: single