automation:

- alias: ⚡stekker living uit om middernacht of niemand thuis
  id: 'df3e3a84-96d7-4201-ae3d-6ad86a3842f9'
  description: ''
  trigger:
  - platform: time
    at:
    - '00:00:00'
  - platform: state
    entity_id: group.gezin
    to: not_home
  action:
  - service: switch.turn_off
    target:
      entity_id: switch.living_plug
  mode: single
  
- alias: ⚡ stekker living aan om 7u of bij thuiskomst
  id: '15579822-c648-4309-8676-da47d24802fb'
  description: ''
  trigger:
  - platform: time
    at:
    - '07:00:00'
  - platform: state
    entity_id: group.gezin
    to: home
  action:
  - service: switch.turn_on
    target:
      entity_id: switch.living_plug 
  mode: single 
  
- alias: ⚡ check om 20u als laptop van het werk uit staat
  id: 'd623e813-117a-485c-b7f1-ea50c8635010'
  trigger:
  - platform: time
    at: "20:00"
  condition:
  - condition: state
    entity_id: switch.bart_laptop_fortis_brum05007458
    state: 'on'
  action:
  - service: notify.bart_phone
    data:
      message: De laptop van het werk staat nog aan.
  mode: single