automation:

- alias: ⚡  stekker living uit om middernacht of nieamand thuis
  id: 'df3e3a84-96d7-4201-ae3d-6ad86a3842f9'
  description: ''
  trigger:
  - platform: time
    at:
    - '00:00'
  - platform: state
    entity_id: group.gezin
    to: not_home
  action:
  - service: switch.turn_off
    target:
      entity_id: switch.switch_1
  mode: single
  
- alias: ⚡stekker living aan om 7u of bij thuiskomst
  id: '15579822-c648-4309-8676-da47d24802fb'
  description: ''
  trigger:
  - platform: time
    at:
    - '07:00'
  - platform: state
    entity_id: group.gezin
    to: home
  action:
  - service: switch.turn_on
    target:
      entity_id: switch.switch_1
  mode: single 