automation:

- alias: Amilya niet thuis = verwarming op automatisch
  id: 'ba1642db-f360-46ab-8c44-3fd16cc20751'
  description: ''
  trigger:
  - platform: state
    entity_id: device_tracker.amilya_iphone_xs
    to: not_home
    for: 00:03:00
    from: home
  condition: []
  action:
    service: climate.set_hvac_mode
    target:
      entity_id: climate.kamer_amilya
    data:
      hvac_mode: auto
  mode: single

- alias: Alunya niet thuis = verwarming op automatisch
  id: '14de18f4-ecec-446f-baba-399c0eaf0d9f'
  description: ''
  trigger:
  - platform: state
    entity_id: device_tracker.alunya_samsung_galaxy_a71
    to: not_home
    for: 00:03:00
  condition: []
  action:
    service: climate.set_hvac_mode
    target:
      entity_id: climate.kamer_alunya
    data:
      hvac_mode: auto
  mode: single

- alias: Alunya verwarming aan + raam open = verwarming automatisch
  id: '8249d33e-5737-46b7-9558-46a804c419f2'
  description: ''
  trigger:
  - platform: numeric_state
    entity_id: sensor.kamer_alunya_heating
    above: '0'
  condition:
  - condition: state
    entity_id: binary_sensor.kamer_alunya_raam_sensor
    state: 'on'
    for:
      hours: 0
      minutes: 0
      seconds: 0
      milliseconds: 0
  action:
  - service: climate.set_hvac_mode
    target:
      entity_id: climate.kamer_alunya
    data:
      hvac_mode: auto
  mode: single

- alias: Amilya verwarming aan + raam open = verwarming automatisch
  id: 'ccc11c3d-1926-4e42-81f5-38929a09644b'
  description: ''
  trigger:
  - platform: numeric_state
    entity_id: sensor.kamer_amilya_heating
    above: '0'
  condition:
  - condition: state
    entity_id: binary_sensor.kamer_amilya_raam_sensor
    state: 'on'
    for:
      hours: 0
      minutes: 0
      seconds: 0
      milliseconds: 0
  action:
  - service: climate.set_hvac_mode
    target:
      entity_id: climate.kamer_amilya
    data:
      hvac_mode: auto
  mode: single

