############################ Table of Contents ############################ 
# 
#   Automations

automation:

- alias: ♨️ Amilya niet thuis = verwarming op automatisch
  id: 'ba1642db-f360-46ab-8c44-3fd16cc20751'
  description: ''
  trigger:
  - platform: state
    entity_id: device_tracker.amilya_iphone_xs
    to: 'not_home'
    for: 00:03:00
    from: 'home'
  condition: []
  action:
    service: climate.set_hvac_mode
    target:
      entity_id: climate.kamer_amilya
    data:
      hvac_mode: auto
  mode: single

- alias: ♨️ Alunya niet thuis = verwarming op automatisch
  id: '14de18f4-ecec-446f-baba-399c0eaf0d9f'
  description: ''
  trigger:
  - platform: state
    entity_id: device_tracker.alunya_samsung_galaxy_a71
    to: 'not_home'
    for: 00:03:00
  condition: []
  action:
    service: climate.set_hvac_mode
    target:
      entity_id: climate.kamer_alunya
    data:
      hvac_mode: auto
  mode: single

- alias: "♨️ >21 °C gevraagd in kamer Amilya = chauffage op automatisch"
  id: '95335e38-c593-48a6-b356-1be5f78db02c'
  description: ''
  trigger:
  - platform: numeric_state
    entity_id: climate.kamer_amilya
    attribute: temperature
    above: '21'
  condition: []
  action:
  - service: notify.bart_phone
    data:
      message: Kamer Amilya op {{state_attr('climate.kamer_amilya', 'temperature') }} gezet = herzet naar automatisch.
  - service: climate.set_hvac_mode
    target:
      entity_id: climate.kamer_amilya
    data:
      hvac_mode: auto      
  mode: single
  
- alias: "♨️ >20 °C gevraagd in kamer Amilya 's nachts = chauffage op automatisch"
  id: 'b5bc7134-9f34-455e-9f89-447ae445cce8'
  description: ''
  trigger:
  - platform: numeric_state
    entity_id: climate.kamer_amilya
    attribute: temperature
    above: '20'
  condition:
  - condition: time
    after: '23:00'
    before: '06:00'
  action:
  - service: notify.bart_phone
    data:
      message: Kamer Amilya op {{state_attr('climate.kamer_amilya', 'temperature') }} 's nachts gezet = herzet naar automatisch.  
  - service: climate.set_hvac_mode
    target:
      entity_id: climate.kamer_amilya
    data:
      hvac_mode: auto
  mode: single

- alias: ">20 °C gevraagd in kamer Amilya overdag = chauffage op 19"
  id: '434ae070-ac26-40a4-8700-7d5a86b7c2c9'
  description: ''
  trigger:
  - platform: numeric_state
    entity_id: climate.kamer_amilya
    attribute: temperature
    above: '20'
  condition:
  - condition: time
    after: '06:00'
    before: '23:00'
  action:
  - service: notify.bart_phone
    data:
      message: Kamer Amilya op 20° of meer gezet (overdag) = herzet naar 19°.
  - service: climate.set_temperature
    data:
      temperature: 19
    target:
      entity_id: climate.kamer_amilya
  mode: single

- alias: "♨️ Chauffage Alunya 's nachts op automatisch"
  id: '0c41db26-ed5a-46c8-b2f5-ba93514fb638'
  description: ''
  trigger:
  - minutes: /30
    platform: time_pattern
  condition:
  - condition: time
    after: '0:00'
    before: '6:00'
  - condition: state
    entity_id: climate.kamer_alunya
    state: "heat"
  action:
  - service: climate.set_hvac_mode
    target:
      entity_id: climate.kamer_alunya
    data:
      hvac_mode: auto
  mode: single
  
- alias: "♨️ Chauffage Amilya 's nachts op automatisch"
  id: 'a9ed4d73-ab63-48f1-a05b-e252d9d60694'
  description: ''
  trigger:
  - minutes: /30
    platform: time_pattern
  condition:
  - condition: time
    after: '0:00'
    before: '6:00'
  - condition: state
    entity_id: climate.kamer_amilya
    state: "heat"
  action:
  - service: climate.set_hvac_mode
    target:
      entity_id: climate.kamer_amilya
    data:
      hvac_mode: auto
  mode: single

# - alias: chauffage badkamer aan + raam open = chauffage uit
