############################ Table of Contents ############################ 
# 
#   Automations

automation:

- alias: Melding wanneer vaatwasser gedaan
  id: 'b781e2b9-6c6c-47e4-9a27-35477993e952'
  description: ''
  trigger:
  - platform: time
    at: input_datetime.elec_vaatwasser_end
  condition:
  condition:
    - condition: state
      entity_id: input_boolean.elec_vaatwasser_busy
      state: 'on'
  action:
    - service: notify.bart_phone
      data:
        message: boodschap
        title: De vaatwasser is klaar.
  mode: single
  
- alias: Melding wanneer wasmachine gedaan
  id: 'c3f49f52-23e5-4e00-b29d-88af3003ce9d'
  description: ''
  trigger:
  - platform: time
    at: input_datetime.elec_wasmachine_end
  condition:
  condition:
    - condition: state
      entity_id: input_boolean.elec_wasmachine_busy
      state: 'on'
  action:
    - service: notify.bart_phone
      data:
        message: boodschap
        title: De wasmachine is klaar.
  mode: single
  
- alias: Melding wanneer droger gedaan
  id: 'cb339c9a-a923-4676-a53b-afc1e8437ea5'
  description: ''
  trigger:
  - platform: time
    at: input_datetime.elec_droger_end
  condition:
  condition:
    - condition: state
      entity_id: input_boolean.elec_droger_busy
      state: 'on'
  action:
    - service: notify.bart_phone
      data:
        message: boodschap
        title: De droger is klaar.
  mode: single    