############################ Table of Contents ############################ 
# 
#   Automations
#     Vocht in huis >75%
#     Vocht master bedroom -> machine aan
#
############################ Automations ################################## 

# dauwpunt
# Hoger dan 26 °C	Ernstig hoog, zelfs dodelijk voor mensen met astma gerelateerde ziekten	65% en hoger
# 24–26 °C	Zeer ongemakkelijk, tamelijk benauwend	62%
# 21–24 °C	Erg vochtig, heel ongemakkelijk	52–60%
# 18–21 °C	Enigszins ongemakkelijk, voor de meeste mensen is de luchtvochtigheid aan de hoge kant	44–52%
# 16–18 °C	OK voor de meeste mensen, maar men merkt al dat de luchtvochtigheid aan de hoge kant is	37–46%
# 13–16 °C	Comfortabel	38–41%
# 10–12 °C	Zeer comfortabel	31–37%
# Lager dan 10 °C	Een beetje droog voor sommige mensen

automation:
- alias: "💧 Vocht in huis >75%"
  id: '466f577f-83c4-4954-b17e-335ad7fa83f6'
  description: ''
  trigger:
    - platform: numeric_state
      entity_id: sensor.avg_inside_humidity
      above: '75'
      for: '00:15'
  condition:
    - condition: state
      entity_id: person.bart
      state: home
    - condition: time
      after: '7:0:0'
      before: '23:00:00'
  action:
    - service: notify.bart_phone
      data:
        title: Vocht
        message: "Vocht % in huis is heel hoog: {{states('sensor.avg_inside_humidity')}}%."
  mode: single
  
- alias: "💧 vocht % master bedroom -> machine aan"
  id: '9309eba6-275f-4a93-953a-908b937358ec'
  description: ''
  trigger:
  - platform: time
    at: '20:30'
  condition:
  - condition: numeric_state
    entity_id: sensor.master_bedroom_humidity
    above: '75'
  - condition: numeric_state
    entity_id: sensor.humidity_leuven24_wunderground
    above: '75'
  action:
  - service: notify.bart_phone
    data:
      message: "Master bedroom vocht is {{states('sensor.master_bedroom_humidity')}}%. Zet eventueel machine aan."
      title: Zet ontvochtiger in master bedroom.
      data:
        color: blue
        channel: Vocht
        actions:
        - action: URI
          title: Meer info
          uri: /lovelace/humidity
  mode: single

- alias: 💧 vocht gram in badkamer >14 gram/m³
  id: 8358a61f-74f1-4045-ba75-563bbca3b4e3
  description: ''
  trigger:
  - platform: numeric_state
    entity_id: sensor.badkamer_thermal_absolutehumidity
    above: '14'
  condition: []
  action:
  - repeat:
      while:
      - condition: numeric_state
        entity_id: sensor.badkamer_thermal_absolutehumidity
        above: '14'
      sequence:
      - service: notify.bart_phone
        data:
          message: '{{states(''sensor.badkamer_thermal_absolutehumidity'')}} gram
            water /m³ en {{states(''sensor.badkamer_humidity'')}}% vocht.'
          title: Veel vocht in badkamer!
          data:
            color: blue
            tag: badkamer_vocht
      - delay:
          hours: 0
          minutes: 15
          seconds: 0
          milliseconds: 0
  - service: notify.bart_phone
    data:
      message: "clear_notification"
      data:
        tag: badkamer_vocht
  mode: single
  
- alias: 💧 vocht gram in master bedroom >80%
  id: 'e1a0cee2-ee78-4e66-a133-9ea28f3a4fb8'
  description: ''
  trigger:
  - platform: numeric_state
    entity_id: sensor.master_bedroom_humidity
    above: '80'
  condition: []
  action:
  - repeat:
      while:
      - condition: numeric_state
        entity_id: sensor.master_bedroom_humidity
        above: '80'
      sequence:
      - service: notify.bart_phone
        data:
          title: Veel vocht in master bedroom!
          message: '{{states(''sensor.master_bedroom_thermal_absolutehumidity'')}} gram
            water /m³ en {{states(''sensor.master_bedroom_humidity'')}}% vocht.'
          data:
            color: blue
            tag: master_bedroom_vocht
      - delay:
          hours: 1
          minutes: 0
          seconds: 0
          milliseconds: 0
  - service: notify.bart_phone
    data:
      message: "clear_notification"
      data:
        tag: master_bedroom_vocht
  mode: single