############################ Table of Contents ############################ 
# 
#   Automations
#     💡 Amilya niet thuis = licht uit
#     💡 Amilya licht badkamer brandt langer dan 20 minuten
#     💡 Alunya niet thuis = licht uit
#     💡 Alunya lichten uit om 1u en 2u 's nachts
#     💡 bij donker living bol inschakelen
#     💡 Donker, <20° buiten en thuis = licht aan
#     💡 Master bedroom deurswitch
#     💡 Licht in garage aan > 10 min
#     💡 TV aan + zon onder = TV strip aan
#     💡 TV uit = TV strip uit
#     💡 master bedroom TV aan 's avonds = gezellig licht

############################ Automations ################################## 

automation:

- alias: 💡 Amilya niet thuis = lichten uit
  id: 'c5fc-389d-42e8-8f3f-78f'
  description: ''
  trigger:
  - platform: state
    entity_id: device_tracker.amilya_iphone_xs
    to: not_home
    for: 00:03:00
    from: home
  condition: []
  action:
  - type: turn_off
    device_id: 7fa0163478cef7ca4d8f74d7d8f8872e
    entity_id: light.amilya_badkamer
    domain: light
  - type: turn_off
    device_id: 5849a609ec647763c122b1619fdcc430
    entity_id: light.amilya_plafond_1
    domain: light
  - type: turn_off
    device_id: d132ab8d29e675c160114d2470ce12e5
    entity_id: light.amilya_plafond_2
    domain: light
  - type: turn_off
    device_id: 31f28530e074ca664948b83668a55dfa
    entity_id: light.amilya_bol
    domain: light
  - type: turn_off
    device_id: c17c802d6eae726de2531355e36a0d5e
    entity_id: light.amilya_strip
  - type: turn_off
    device_id: c17c802d6eae726de2531355e36a0d5e
    entity_id: light.amilya_strip
    domain: light
  mode: single
  
- alias: 💡 Amilya licht badkamer brandt langer dan 20 minuten
  id: db73f94a-536a-4d6f-9f5b-ce2757587b20
  description: ''
  trigger:
  - platform: state
    entity_id: light.amilya_badkamer
    to: 'on'
    for:
      hours: 0
      minutes: 20
      seconds: 0
      milliseconds: 0
  condition: []
  action:
  - service: light.turn_off
    target:
      entity_id: light.amilya_badkamer
  mode: single

- alias: 💡 Alunya niet thuis = licht uit
  id: 'b31b70d7-e8c0-4bb8-8a45-335d57d427b8'
  description: ''
  trigger:
  - platform: state
    entity_id: device_tracker.alunya_samsung_galaxy_a71
    to: not_home
    for: 00:03:00
  condition: []
  action:
  - type: turn_off
    device_id: 698a7cf7cee6d32dda3a430591d0ebe9
    entity_id: light.alunya_bol
    domain: light
  - type: turn_off
    device_id: c79c606a18f7c9049409ee7a945f768c
    entity_id: light.alunya_staande_lamp
    domain: light
  - type: turn_off
    device_id: bc3bf3bec76c984ab510c820d37ea63b
    entity_id: light.alunya_wasbak
    domain: light
  mode: single

- alias: 💡 Alunya lichten uit om 1u, 2u, 3u en 4u 's nachts
  id: 'ee497cc7-cb83-4a8d-afd9-dedaf4fe56ff'
  description: ''
  trigger:
  - platform: time
    at: 01:00:00
  - platform: time
    at: 02:00:00
  - platform: time
    at: 03:00:00
  - platform: time
    at: 04:00:00
  condition: []
  action:
  - type: turn_off
    device_id: 698a7cf7cee6d32dda3a430591d0ebe9
    entity_id: light.alunya_bol
    domain: light
  - type: turn_off
    device_id: c79c606a18f7c9049409ee7a945f768c
    entity_id: light.alunya_staande_lamp
    domain: light
  - type: turn_off
    device_id: bc3bf3bec76c984ab510c820d37ea63b
    entity_id: light.alunya_wasbak
    domain: light
  mode: single

- alias: 💡 Donker, <20° buiten en thuis = licht aan
  id: '9652f025-25a5-4eb0-8eb4-6f61ecb57936'
  description: ''
  trigger:
  - platform: state
    entity_id: sun.sun
    to: below_horizon
  condition:
  - condition: state
    entity_id: person.madouce
    state: home
  - condition: numeric_state
    entity_id: sensor.temp_leuven24_wunderground
    below: '20'
  action:
  - type: turn_on
    device_id: a0297c6061546a2108b2d33e01ed449d
    entity_id: light.living_links_3
    domain: light
  mode: single

- alias: 💡 bij donker living bol inschakelen
  id: 'd754582e-1ba3-44f2-93ef-32a7f9bbc2af'
  description: ''
  trigger:
  - platform: sun
    event: sunset
  condition: []
  action:
  - type: turn_on
    device_id: 3623c76590024bf538fcc54a365fc8cc
    entity_id: light.living_bol
    domain: light
    brightness_pct: 10
    flash: long
  mode: single

- alias: 💡 Master bedroom deurswitch
  id: '0ca77314-116c-4d39-bf43-fd51e9771514'
  description: ''
  trigger:
  - device_id: 4247e8ef769909d83520323811fc6550
    domain: hue
    platform: device
    type: remote_button_short_release
    subtype: turn_on
  condition:
  - condition: sun
    after: sunset
  action:
  - service: light.turn_on
    target:
      entity_id:
      - light.master_bedroom_play_madouce
      - light.master_bedroom_play_bart
      - light.master_bedroom_staande_lamp
    data:
      brightness_pct: 75
  mode: single

- alias: 💡 Licht in garage aan > 10 min
  id: c3801d8a-dd6e-444e-9a25-0adc8c0655d8
  description: ''
  trigger:
  - platform: numeric_state
    entity_id: sensor.garage_sensor_light_level
    for:
      hours: 0
      minutes: 10
      seconds: 0
      milliseconds: 0
    above: '4'
  condition: []
  action:
  - service: notify.bart_phone
    data:
      message: Licht in garage brandt al langer dan 10 minuten.
      title: Licht in garage
  mode: single

- alias: 💡 TV aan + zon onder = TV strip aan
  id: 'decc48cf-f977-42e0-8d54-52cc3fad75d1'
  description: ''
  trigger:
  - platform: state
    entity_id: media_player.ue55ju7000
    from: 'off'
    to: 'on'
  condition:
  - condition: state
    entity_id: sun.sun
    state: below_horizon
  action:
  - type: turn_on
    device_id: d5ef9b4f569a408660e7e445331abfcc
    entity_id: light.tv_strip
    domain: light
    brightness_pct: 25
  mode: single

- alias: 💡 TV uit = TV strip uit
  id: 'dfbb4779-8083-49e3-9b83-b045c4db5d43'
  description: ''
  trigger:
  - platform: state
    entity_id: media_player.ue55ju7000
    from: 'on'
    to: 'off'
  condition: []
  action:
  - type: turn_off
    device_id: d5ef9b4f569a408660e7e445331abfcc
    entity_id: light.tv_strip
    domain: light
  mode: single
  
- alias: 💡 master bedroom TV aan 's avonds = gezellig licht
  id: 62b15358-7447-43f7-9c76-b2d72db61875
  description: ''
  trigger:
  - platform: state
    entity_id: media_player.master_bedroom_tv
    to: playing
  condition:
  - condition: time
    after: '22:00'
  action:
  - service: light.turn_on
    target:
      entity_id:
      - light.master_bedroom_play_bart
      - light.master_bedroom_play_madouce
      - light.master_bedroom_halve_bol
    data:
      color_name: darkorange
      brightness_pct: 30
  - service: light.turn_off
    target:
      entity_id: light.staande_lamp
  mode: single
