############################ Table of Contents ############################ 
# 
#   Automations
#     Amilya niet thuis = licht uit
#     Alunya niet thuis = licht uit
#     bij donker living bol inschakelen
#     Alunya bol uit om 1u en 2u 's nachts
#     Donker, <20° buiten en thuis = licht aan
# 
############################ Automations ################################## 

automation:
# Switch ON Ensuite fan at high humidity
# - id: ensuite_turn_on_fan_at_high_humidity
    
- id: "Amilya niet thuis = licht uit"
  alias: 💡 Amilya niet thuis = licht uit
  description: ''
  trigger:
  - platform: state
    entity_id: device_tracker.amilya_iphone_xs
    to: not_home
    for: 00:03:00
    from: home
  condition: []
  action:
  - type: turn_off
    device_id: 7fa0163478cef7ca4d8f74d7d8f8872e
    entity_id: light.amilya_badkamer
    domain: light
  - type: turn_off
    device_id: 5849a609ec647763c122b1619fdcc430
    entity_id: light.amilya_plafond_1
    domain: light
  - type: turn_off
    device_id: d132ab8d29e675c160114d2470ce12e5
    entity_id: light.amilya_plafond_2
    domain: light
  - type: turn_off
    device_id: 31f28530e074ca664948b83668a55dfa
    entity_id: light.amilya_bol
    domain: light
  - type: turn_off
    device_id: c17c802d6eae726de2531355e36a0d5e
    entity_id: light.amilya_strip
  - type: turn_off
    device_id: c17c802d6eae726de2531355e36a0d5e
    entity_id: light.amilya_strip
    domain: light
  mode: single
- id: "Alunya niet thuis = licht uit"
  alias: 💡Alunya niet thuis = licht uit
  description: ''
  trigger:
  - platform: state
    entity_id: device_tracker.alunya_samsung_galaxy_a71
    to: not_home
    for: 00:03:00
  condition: []
  action:
  - type: turn_off
    device_id: 698a7cf7cee6d32dda3a430591d0ebe9
    entity_id: light.alunya_bol
    domain: light
  - type: turn_off
    device_id: c79c606a18f7c9049409ee7a945f768c
    entity_id: light.alunya_staande_lamp
    domain: light
  - type: turn_off
    device_id: bc3bf3bec76c984ab510c820d37ea63b
    entity_id: light.alunya_wasbak
    domain: light
  mode: single
- id: "bij donker living bol inschakelen"
  alias: 💡bij donker living bol inschakelen
  description: ''
  trigger:
  - platform: sun
    event: sunset
  condition: []
  action:
  - type: turn_on
    device_id: 3623c76590024bf538fcc54a365fc8cc
    entity_id: light.living_bol
    domain: light
    brightness_pct: 10
    flash: long
  mode: single
- id: "Alunya bol uit om 1u en 2u 's nachts"
  alias: 💡 Alunya bol uit om 1u en 2u 's nachts
  description: ''
  trigger:
  - platform: time
    at: 01:00:00
  - platform: time
    at: 02:00:00
  condition: []
  action:
  - type: turn_off
    device_id: 698a7cf7cee6d32dda3a430591d0ebe9
    entity_id: light.alunya_bol
    domain: light
  mode: single
- id: "Donker, <20° buiten en thuis = licht aan"
  alias: Donker, <20° buiten en thuis = licht aan
  description: ''
  trigger:
  - platform: state
    entity_id: sun.sun
    to: below_horizon
  condition:
  - condition: state
    entity_id: person.madouce
    state: home
  - condition: numeric_state
    entity_id: sensor.temp_leuven24_wunderground
    below: '20'
  action:
  - type: turn_on
    device_id: a0297c6061546a2108b2d33e01ed449d
    entity_id: light.living_links_3
    domain: light
  mode: single

- id: "TV aan + zon onder = TV strip aan"
  alias: 📺 TV aan + zon onder = TV strip aan
  description: ''
  trigger:
  - platform: state
    entity_id: media_player.ue55ju7000
    from: 'off'
    to: 'on'
  condition:
  - condition: state
    entity_id: sun.sun
    state: below_horizon
  action:
  - type: turn_on
    device_id: d5ef9b4f569a408660e7e445331abfcc
    entity_id: light.tv_strip
    domain: light
    brightness_pct: 25
  mode: single

- id: "TV uit = TV strip uit"
  alias: 📺 TV uit = TV strip uit
  description: ''
  trigger:
  - platform: state
    entity_id: media_player.ue55ju7000
    from: 'on'
    to: 'off'
  condition: []
  action:
  - type: turn_off
    device_id: d5ef9b4f569a408660e7e445331abfcc
    entity_id: light.tv_strip
    domain: light
  mode: single
