automation:
- id: '1627754705422'
  alias: het regent
  description: ''
  trigger:
  - platform: numeric_state
    entity_id: sensor.precip_rate_leuven24_wunderground
    above: '0'
  condition: []
  action:
  - service: notify.bart_phone
    data:
      message: Het regent. Zijn de ramen dicht?
      title: Regen
      tag: regen
  - service: notify.madouce_phone
    data:
      message: Het regent. Zijn de ramen dicht?
      title: Regen
      tag: regen
  mode: single

- id: 'straks regen'
  alias: "Het gaat regenen over 15 minuten (en raam nog open ?) (Bart)"
  description: ''
  trigger:
  - platform: state
    entity_id: sensor.buienradar_precipitation_forecast_total
    from: '0'
  condition: []
  action:
  - service: notify.bart_phone
    data:
      message: Het gaat regenen over een kwartier. 
  mode: single

- id: '1627749113699'
  alias: Regen en raam open = melding
  description: ''
  trigger:
  - platform: numeric_state
    entity_id: sensor.precip_rate_leuven24_wunderground
    above: '0'
  condition:
  - condition: state
    entity_id: binary_sensor.kamer_amilya_window_sensor
    state: 'on'
  action:
  - service: notify.bart_phone
    data:
      message: Het regent en het raam van Amilya staat open.
      title: Het regent. Doe raam Amilya dicht aub.
  - service: notify.madouce_phone
    data:
      message: Het regent en het raam van Amilya staat open.
      title: Het regent. Doe raam Amilya dicht aub.
  mode: single
