############################ Table of Contents ############################ 
# 
#   Automations
#     Bart, Madouce en/of Alunya komt thuis (zone) = alarm uit
#     niemand thuis (enkel melding)
#     iemand thuis (enkel melding)
#     niemand thuis = alarm aanzetten
#     Iemand komt thuis (wifi) = alarm uitzetten
#     alarm ingeschakeld aan voordeur
#     alarm uitgeschakeld aan voordeur
#     alarm bij beweging
#     garagepoort staat lang open
#     beweging op oprit

############################ Automations ################################## 

automation:

- alias: 🚨 Bart, Madouce en/of Alunya komt thuis (zone) = alarm uit
  id: '8bc11499-60b0-4b90-9c5b-e36dcd5d03fc'
  description: ''
  trigger:
  - platform: state
    entity_id: person.bart
    to: 'home'
  - platform: state
    entity_id: person.madouce
    to: 'home'
  - platform: state
    entity_id: person.alunya
    to: 'home'
  condition:
  - condition: state
    entity_id: alarm_control_panel.home_alarm
    state: armed_away
  action:
  - device_id: !secret id_tel_bart
    domain: mobile_app
    type: notify
    title: ''
    message: '✅  Alarm is automatisch uitgeschakeld door thuiskomst.'
  - service: alarm_control_panel.alarm_disarm
    target:
      entity_id: alarm_control_panel.home_alarm
    data:
      code: !secret alarm_code
  mode: single

- alias: 🚨 niemand thuis (wifi) = alarm automatisch aanzetten
  id: '71de9fe1-32d9-4a62-ae3a-635d6103daac'
  description: ''
  trigger:
  - platform: state
    entity_id: group.gezin
    to: 'not_home'
    for: 00:05:00
  condition: []
  action:
  - service: alarm_control_panel.alarm_arm_away
    data:
      code: !secret alarm_code
    target:
      entity_id: alarm_control_panel.home_alarm
  - device_id: !secret id_tel_bart
    domain: mobile_app
    type: notify
    title: ''
    message: ⛔ Alarm is automatisch ingeschakeld wegens niemand thuis.
  mode: single

- alias: 🚨 Iemand komt thuis (wifi) = alarm automatisch uitzetten
  id: 'f17014e2-4cf5-43f0-90ae-be7d609f2a28'
  description: ''
  trigger:
  - platform: state
    entity_id: group.gezin
    to: 'home'
  condition:
  - condition: state
    entity_id: alarm_control_panel.home_alarm
    state: armed_away
  action:
  - service: alarm_control_panel.alarm_disarm
    target:
      entity_id: alarm_control_panel.home_alarm
  - device_id: !secret id_tel_bart
    domain: mobile_app
    type: notify
    title: ''
    message: '✅  Alarm is automatisch uitgeschakeld door thuiskomst.'
  mode: single

- alias: 🚨 alarm ingeschakeld aan voordeur
  id: '1acceb9a-ca45-49b3-ab22-166314aa9cf0'
  description: OK
  trigger:
  - platform: tag
    tag_id: !secret tag_voordeur_arm_alarm
  condition: []
  action:
  - service: notify.bart_phone
    data:
      message: ⛔ Alarm ingeschakeld aan voordeur.
      title: ''
      data:
        color: blue
        actions:
        - action: URI
          title: Meer info
          uri: /lovelace/humidity
  - service: alarm_control_panel.alarm_arm_away
    target:
      entity_id: alarm_control_panel.home_alarm
    data:
      code: !secret alarm_code
  - service: media_player.volume_set
    data:
      entity_id: media_player.living_speaker
      volume_level: 0.7
  - service: tts.google_say
    data:
      entity_id: media_player.living_speaker
      message: "Alarm ingeschakeld!
      {% if is_state('group.group.raam_sensoren', 'off') %} Alle ramen zijn dicht!
      {% else %} De volgende ramen staan nog open: {{ expand(states.binary_sensor.kamer_amilya_raam, states.binary_sensor.kamer_alunya_raam, states.binary_sensor.kamer_alunya_schuifraam, states.binary_sensor.badkamer_raam, states.binary_sensor.berging_raam, states.binary_sensor.keuken_raam, states.binary_sensor.living_oprit_raam, states.binary_sensor.living_tuin_raam, states.binary_sensor.master_bedroom_raam, states.binary_sensor.veranda_schuifraam) | selectattr('state','eq','on') | map(attribute='name')| list }}
      {% endif %}"
  - wait_template: ''
    timeout: 00:00:02
  - service: media_player.volume_set
    data:
      entity_id: media_player.living_speaker
      volume_level: 0.4
  mode: queued

- alias: 🚨 alarm uitgeschakeld aan voordeur
  id: 'dc004044-06a8-4ad2-acb8-cafe5f617d1f'
  description: OK
  trigger:
  - platform: tag
    tag_id: !secret tag_voordeur_disarm_alarm
  condition: []
  action:
  - device_id: !secret id_tel_bart
    domain: mobile_app
    type: notify
    title: ''
    message: ✅ Alarm uitgeschakeld aan voordeur.
  - service: alarm_control_panel.alarm_disarm
    data:
      code: !secret alarm_code
    target:
      entity_id: alarm_control_panel.home_alarm
  - service: media_player.volume_set
    data:
      entity_id: media_player.living_speaker
      volume_level: 0.8
  - service: tts.google_say
    data:
      entity_id: media_player.living_speaker
      message: Alarm uitgeschakeld!
  - delay: 00:00:10
  - service: media_player.volume_set
    data:
      entity_id: media_player.living_speaker
      volume_level: 0.4
  mode: single
  
- alias: 🚨 alarm bij beweging
  id: 'f4cc29aa-ef63-411b-a755-343f97a9b721'
  description: NOK
  trigger:
  - platform: state
    entity_id:
    # bewegingssensoren
    - binary_sensor.berging_sensor_motion
    - binary_sensor.garage_sensor_motion
    - binary_sensor.keldertrap_sensor_motion
    - binary_sensor.trap_boven_motion_motion
    - binary_sensor.toilet_motion_sensor_motion
    - binary_sensor.terras_motion_sensor
    # raam sensoren
    - binary_sensor.kamer_alunya_raam
    - binary_sensor.kamer_alunya_schuifraam
    - binary_sensor.kamer_amilya_raam
    - binary_sensor.badkamer_raam
    - binary_sensor.berging_raam
    - binary_sensor.keuken_raam
    - binary_sensor.living_oprit_raam
    - binary_sensor.living_tuin_raam
    - binary_sensor.master_bedroom_raam
    - binary_sensor.veranda_schuifraam
    - binary_sensor.voordeur
    from: 'off'
    to: 'on'
  condition:
  - condition: state
    entity_id: alarm_control_panel.home_alarm
    state: armed_away
  action:
  - service: input_text.set_value
    data_template:
      entity_id: input_text.trigger_source
      value: '{{ trigger.to_state.attributes.friendly_name }}'
  - service: alarm_control_panel.alarm_trigger
    entity_id: alarm_control_panel.home_alarm
  mode: single

- alias: 🚨 melding bij alarm trigger
  id: '5fef4d2e-d1e1-4247-9c1f-0cb97130c86e'
  description: NOK
  trigger:
  - platform: state
    entity_id: alarm_control_panel.home_alarm
    to: 'triggered'
  condition: []
  action:
  - service: notify.bart_phone
    data:
      message: TTS
      title: Alarm in Eikenboslaan!
      data:
        color: red
        actions:
        - action: URI
          title: Meer info
          uri: /lovelace/alarm
        vibrationPattern: 10, 10, 10, 10, 10, 10, 10
        channel: alarm
  - service: notify.bart_phone
    data:
      message: 'Alarm in Eikenbos: beweging aan {{ states(''input_text.trigger_source'')}}'
      title: '🚨 Alarm!'
      data:
        color: red
        channel: alarm
  - service: notify.madouce_phone
    data:
      message: 'Alarm in Eikenbos: beweging aan {{ states(''input_text.trigger_source'')}}'
      title: '🚨 Alarm!'
      data:
        color: red
        channel: alarm
  #  - service: media_player.volume_set
  #    data:
  #      entity_id: media_player.nestaudio3875
  #      volume_level: 0.8
  #  - service: media_player.play_media
  #    data:
  #      entity_id: media_player.living_speaker
  #      media_content_id: http://192.168.86.101:8123/local/siren.mp3
  #      media_content_type: music
  #  - service: media_player.play_media
  #    data:
  #      entity_id: media_player.nestaudio3875
  #      media_content_id: http://192.168.86.101:8123/local/siren.mp3
  #      media_content_type: music
  #  - service: media_player.volume_set
  #    data:
  #      entity_id: media_player.nestaudio3875
  #      volume_level: 0.8
  mode: queued

- alias: set_alarm_arm_away
  id: 'b2531e01-aa6d-4a32-b6d7-8627e1450c7e'
  trigger:
  - platform: event
    event_type: mobile_app_notification_action
    event_data:
      action: set_alarm_arm_away
  action:
  - service: alarm_control_panel.alarm_arm_away
    data:
      code: !secret alarm_code
    target:
      entity_id: alarm_control_panel.home_alarm
  mode: single
  
- alias: Garagepoort staat lang open
  id: '2afaab2f-0aee-4dea-a340-be690d593fca'
  description: ''
  trigger:
  - platform: state
    entity_id: cover.garagepoort
    from: 'closed'
    to: 'open'
    for: 00:05:00
  condition: []
  action:
  - repeat:
      while:
      - condition: state
        entity_id: cover.garagepoort
        state: 'open'
      sequence:
      - service: notify.bart_phone      
        data:
          title: "Garage staat al lang open."
          message: "Staat al {{((as_timestamp(now()) - as_timestamp(states.cover.garagepoort.last_changed)) / 60 )| int() }} minuten open."
          data:
            color: red
            tag: garage_staat_open
      - delay:
          minutes: 2
  - service: notify.bart_phone
    data:
      message: "Garage is nu terug dicht."
      data:
        tag: garage_staat_open
  mode: single

- alias: Voordeur staat lang open
  id: '76d0bc44-085e-4a6f-bb8d-22d46f5f2ad5'
  description: ''
  trigger:
  - platform: state
    entity_id: binary_sensor.voordeur
    from: 'off'
    to: 'on'
    for: 00:05:00
  condition: []
  action:
  - repeat:
      while:
      - condition: state
        entity_id: binary_sensor.voordeur
        state: 'on'
      sequence:
      - service: notify.bart_phone      
        data:
          title: "Voordeur al lang open"
          message: "Staat al {{((as_timestamp(now()) - as_timestamp(states.binary_sensor.voordeur.last_changed)) / 60 )| int() }} minuten open."
          data:
            color: red
            tag: voordeur_staat_open
      - delay:
          minutes: 2
  - service: notify.bart_phone
    data:
      message: "Voordeur is nu terug dicht."
      data:
        tag: voordeur_staat_open
  mode: single

- alias: 👀 beweging op oprit
  id: 'c9b40a57-f31d-424f-80fb-c2a8c25c4d21'
  description: Beweging op oprit = melding op living speaker
  trigger:
  - platform: state
    entity_id: binary_sensor.buitensensor_vooraan_motion
    from: 'off'
    to: 'on'
  condition: []
  action:
  - service: media_player.volume_set
    data:
      entity_id: media_player.living_speaker
      volume_level: 0.5
  - service: tts.google_say
    data:
      entity_id: media_player.living_speaker
      message: Beweging op oprit!
  - service: tts.google_say
    data:
      entity_id: media_player.veranda_speaker
      message: Beweging op oprit! 
  - wait_template: ''
    timeout: 00:00:07
  - service: camera.play_stream
    data:
      media_player: media_player.living_speaker
    target:
      entity_id: camera.netatmo_eikenbos_oprit
  - wait_template: ''
    timeout: 00:01:30
  - service: media_player.turn_off
    entity_id: media_player.living_speaker
  mode: single

- alias: 👀 beweging op terras = melding speaker
  id: '1317b64b-1a0a-4a6a-848d-e3feb029ab22'
  description: "Beweging op terras = melding op living & veranda speaker"
  trigger:
  - platform: state
    entity_id: binary_sensor.terras_motion
    from: 'off'
    to: 'on'
  condition: []
  action:
  - service: media_player.volume_set
    data:
      entity_id: media_player.living_speaker
      volume_level: 0.5
  - service: tts.google_say
    data:
      entity_id: media_player.living_speaker
      message: Beweging op terras!
  - service: tts.google_say
    data:
      entity_id: media_player.veranda_speaker
      message: Beweging op terras! 
  mode: single
  
- alias: 👀 beweging in tuin = melding smartphone
  id: '28641c60-8f5e-4856-96a9-e69ceb8c9cc8'
  description: ''
  trigger:
  - platform: state
    entity_id: binary_sensor.tuin_motion
    from: 'off'
    to: 'on'
  condition: []
  action:
  - service: notify.bart_phone
    data:
      title: Beweging in tuin! 
      message: "Beweging begon om {{ as_timestamp(now()) | timestamp_custom('%H:%M:%S') }}."
      data:
        color: red
        tag: beweging_in_tuin
  - repeat:
      while:
      - condition: state
        entity_id: binary_sensor.tuin_motion
        state: 'on'
      sequence:
      - delay:
          seconds: 15
      - service: notify.bart_phone      
        data:
          title: Beweging in tuin!
          message: "Beweging begon om {{ as_timestamp(now()) | timestamp_custom('%H:%M:%S') }} en duurt al {{((as_timestamp(now()) - as_timestamp(states.binary_sensor.tuin_motion.last_changed)) / 60 )| round(1) }} min."
          data:
            color: red
            tag: beweging_in_tuin
            alert_once: true
  - service: notify.bart_phone      
    data:
      title: "Geen beweging in tuin meer. ({{ as_timestamp(now()) | timestamp_custom('%H:%M:%S') }})"
      message: "Beweging begon om {{ as_timestamp(now()) | timestamp_custom('%H:%M:%S') }} en duurde {{((as_timestamp(now()) - as_timestamp(states.binary_sensor.tuin_motion.last_changed)) / 60 )| round(1) }} min."
      data:
        color: red
        tag: beweging_in_tuin
  mode: single

- alias: 👀 beweging op terras = melding smartphone
  id: '554afe6c-1cde-4bbd-93e2-dc4851424fc6'
  description: ''
  trigger:
  - platform: state
    entity_id: binary_sensor.terras_motion
    from: 'off'
    to: 'on'
  condition: []
  action:
  - service: notify.bart_phone
    data:
      title: Beweging op terras! 
      message: "Beweging begon om {{ as_timestamp(now()) | timestamp_custom('%H:%M:%S') }}"
      data:
        color: red
        tag: beweging_op_terras
  - repeat:
      while:
      - condition: state
        entity_id: binary_sensor.terras_motion
        state: 'on'
      sequence:
      - delay:
          seconds: 15
      - service: notify.bart_phone      
        data:
          title: Beweging op terras!
          message: "Beweging begon om {{ as_timestamp(now()) | timestamp_custom('%H:%M:%S') }} en duurt al {{((as_timestamp(now()) - as_timestamp(states.binary_sensor.terras_motion.last_changed)) / 60 )| round(1) }} min."
          data:
            color: red
            tag: beweging_op_terras
            alert_once: true
  - service: notify.bart_phone      
    data:
      title: "Geen beweging op terras meer. ({{ as_timestamp(now()) | timestamp_custom('%H:%M:%S') }})"
      message: "Beweging begon om {{ as_timestamp(now()) | timestamp_custom('%H:%M:%S') }} en duurde {{((as_timestamp(now()) - as_timestamp(states.binary_sensor.terras_motion.last_changed)) / 60 )| round(1) }} min."
      data:
        color: red
        tag: beweging_op_terras
  mode: single
