############################ Table of Contents ############################ 
# 
#   Automations
#     Bart, Madouce en/of Alunya komt thuis (zone) = alarm uit
#     niemand thuis (enkel melding)
#     iemand thuis (enkel melding)
#     niemand thuis = alarm aanzetten
#     Iemand komt thuis (wifi) = alarm uitzetten
#     alarm ingeschakeld aan voordeur
#     alarm uitgeschakeld aan voordeur
#     alarm bij beweging
#     garagepoort staat lang open
#     beweging op oprit

############################ Automations ################################## 

automation:
- id: "Bart, Madouce en/of Alunya komt thuis (zone) = alarm uit"
  alias: 🚨 Bart, Madouce en/of Alunya komt thuis (zone) = alarm uit
  description: ''
  trigger:
  - platform: state
    entity_id: person.bart
    to: home
  - platform: state
    entity_id: person.madouce
    to: home
  - platform: state
    entity_id: person.alunya
    to: home
  condition:
  - condition: state
    entity_id: alarm_control_panel.home_alarm
    state: armed
  action:
  - device_id: !secret id_tel_bart
    domain: mobile_app
    type: notify
    title: ''
    message: '✅  Alarm is automatisch uitgeschakeld door thuiskomst.'
  - service: alarm_control_panel.alarm_disarm
    target:
      entity_id: alarm_control_panel.home_alarm
    data:
      code: !secret alarm_code
  mode: single

- id: "niemand thuis (enkel melding)"
  alias: ✅ niemand thuis (enkel melding)
  description: ''
  trigger:
  - platform: state
    entity_id: group.group_gezin
    from: home
    to: not_home
    for: 00:04:00
  condition: []
  action:
  - service: notify.mobile_app_bart_s10
    data:
      title: Alarm inschakelen?
      message: Niemand thuis?
      data:
  # attention: these actions still need to be changed!
        actions:
        - action: open_garage
          title:  (niet doen) garage openen
        - action: open_voordeur
          title: Niets doen
  mode: single
  
- id: "iemand thuis (enkel melding)"
  alias: ✅ iemand thuis (enkel melding)
  description: ''
  trigger:
  - platform: state
    entity_id: group.group_gezin
    to: home
  condition: []
  action:
  - device_id: !secret id_tel_bart
    domain: mobile_app
    type: notify
    title: Home
    message: Bart, er is nu wel iemand thuis.
  mode: single
  
- id: "niemand thuis = alarm aanzetten"
  alias: 🚨 niemand thuis = alarm aanzetten
  description: ''
  trigger:
  - platform: state
    entity_id: group.group_gezin
    to: not_home
    for: 00:05:00
  condition: []
  action:
  - service: alarm_control_panel.alarm_arm_away
    data:
      code: !secret alarm_code
    target:
      entity_id: alarm_control_panel.home_alarm
  - device_id: !secret id_tel_bart
    domain: mobile_app
    type: notify
    title: ''
    message: ⛔ Alarm is automatisch ingeschakeld wegens niemand thuis.
  mode: single

- id: "Iemand komt thuis (wifi) = alarm uitzetten"
  alias: '🚨 Iemand komt thuis (wifi) = alarm uitzetten'
  description: ''
  trigger:
  - platform: state
    entity_id: group.group_gezin
    to: home
  condition:
  - condition: state
    entity_id: alarm_control_panel.home_alarm
    state: armed
  action:
  - service: alarm_control_panel.alarm_disarm
    target:
      entity_id: alarm_control_panel.home_alarm
    data:
      code: !secret alarm_code
  - service: notify.mobile_app_bart_s10
    title: ''
    message: '✅  Alarm is automatisch uitgeschakeld door thuiskomst.'
  mode: single

- id: "alarm ingeschakeld aan voordeur"
  alias: 🚨 alarm ingeschakeld aan voordeur
  description: OK
  trigger:
  - platform: tag
    tag_id: !secret tag_voordeur_arm_alarm
  condition: []
  action:
  - service: notify.mobile_app_bart_s10
    data:
      message: ⛔ Alarm ingeschakeld aan voordeur.
      title: ''
      data:
        color: blue
        actions:
        - action: URI
          title: Meer info
          uri: /lovelace/humidity
  - service: alarm_control_panel.alarm_arm_away
    target:
      entity_id: alarm_control_panel.home_alarm
    data:
      code: !secret alarm_code
  - service: media_player.volume_set
    data:
      entity_id: media_player.living_speaker
      volume_level: 0.7
  - service: tts.google_say
    data:
      entity_id: media_player.living_speaker
      message: "Alarm ingeschakeld!
      {% if is_state('group.group.raam_sensoren', 'off') %} Alle ramen zijn dicht!
      {% else %} De volgende ramen staan nog open: {{ expand(states.binary_sensor.kamer_amilya_raam_sensor, states.binary_sensor.kamer_alunya_raam_sensor, states.binary_sensor.kamer_alunya_schuifraam_sensor, states.binary_sensor.badkamer_raam_sensor, states.binary_sensor.berging_raam_sensor, states.binary_sensor.keuken_raam_sensor, states.binary_sensor.living_oprit_raam_sensor, states.binary_sensor.living_tuin_raam_sensor, states.binary_sensor.master_bedroom_raam_sensor, states.binary_sensor.veranda_schuifraam_sensor) | selectattr('state','eq','on') | map(attribute='name')| list }}
      {% endif %}"
  - wait_template: ''
    timeout: 00:00:02
  - service: media_player.volume_set
    data:
      entity_id: media_player.living_speaker
      volume_level: 0.4
  mode: queued

- id: "alarm uitgeschakeld aan voordeur"
  alias: 🚨 alarm uitgeschakeld aan voordeur
  description: OK
  trigger:
  - platform: tag
    tag_id: !secret tag_voordeur_disarm_alarm
  condition: []
  action:
  - device_id: !secret id_tel_bart
    domain: mobile_app
    type: notify
    title: ''
    message: ✅ Alarm uitgeschakeld aan voordeur.
  - service: alarm_control_panel.alarm_disarm
    data:
      code: !secret alarm_code
    target:
      entity_id: alarm_control_panel.home_alarm
  - service: media_player.volume_set
    data:
      entity_id: media_player.living_speaker
      volume_level: 0.8
  - service: tts.google_say
    data:
      entity_id: media_player.living_speaker
      message: Alarm uitgeschakeld!
  - delay: 00:00:10
  - service: media_player.volume_set
    data:
      entity_id: media_player.living_speaker
      volume_level: 0.4
  mode: single
  
- id: "alarm bij beweging"
  alias: 🚨 alarm bij beweging
  description: NOK
  trigger:
  - platform: state
    entity_id:
    # bewegingssensoren
    - binary_sensor.berging_sensor_motion
    - binary_sensor.garage_sensor_motion
    - binary_sensor.keldertrap_sensor_motion
    - binary_sensor.trap_boven_motion_motion
    - binary_sensor.toilet_motion_sensor_motion
    - binary_sensor.terras_motion_sensor
    # raam sensoren
    - binary_sensor.kamer_alunya_raam_sensor
    - binary_sensor.kamer_alunya_schuifraam_sensor
    - binary_sensor.kamer_amilya_raam_sensor
    - binary_sensor.badkamer_raam_sensor
    - binary_sensor.berging_raam_sensor
    - binary_sensor.keuken_raam_sensor
    - binary_sensor.living_oprit_raam_sensor
    - binary_sensor.living_tuin_raam_sensor
    - binary_sensor.master_bedroom_raam_sensor
    - binary_sensor.veranda_schuifraam_sensor
    from: 'off'
    to: 'on'
  condition:
  - condition: state
    entity_id: alarm_control_panel.home_alarm
    state: armed_away
  action:
  - service: input_text.set_value
    data_template:
      entity_id: input_text.trigger_source
      value: '{{ trigger.to_state.attributes.friendly_name }}'
  - service: alarm_control_panel.alarm_trigger
    entity_id: alarm_control_panel.home_alarm
  mode: single

- id: "melding bij alarm trigger"
  alias: 🚨 melding bij alarm trigger
  description: NOK
  trigger:
  - platform: state
    entity_id: alarm_control_panel.home_alarm
    to: triggered
  condition: []
  action:
  - service: notify.mobile_app_bart_s10
    data:
      message: TTS
      title: Alarm in Eikenboslaan!
      data:
        color: red
        actions:
        - action: URI
          title: Meer info
          uri: /lovelace/alarm
        vibrationPattern: 10, 10, 10, 10, 10, 10, 10
        channel: alarm
  - service: notify.mobile_app_bart_s10
    data:
      message: 'Alarm in Eikenbos: beweging aan {{ states(''input_text.trigger_source'')}}'
      title: '🚨 Alarm!'
      data:
        color: red
        channel: alarm
  - service: notify.mobile_app_madouce_s20
    data:
      message: 'Alarm in Eikenbos: beweging aan {{ states(''input_text.trigger_source'')}}'
      title: '🚨 Alarm!'
      data:
        color: red
        channel: alarm
 #  - service: media_player.volume_set
 #    data:
 #      entity_id: media_player.nestaudio3875
 #      volume_level: 0.8
 #  - service: media_player.play_media
 #    data:
 #      entity_id: media_player.living_speaker
 #      media_content_id: http://192.168.86.101:8123/local/siren.mp3
 #      media_content_type: music
 #  - service: media_player.play_media
 #    data:
 #      entity_id: media_player.nestaudio3875
 #      media_content_id: http://192.168.86.101:8123/local/siren.mp3
 #      media_content_type: music
 #  - service: media_player.volume_set
 #    data:
 #      entity_id: media_player.nestaudio3875
 #      volume_level: 0.8
  mode: queued

- id: "garagepoort staat al 5 minuten open"
  alias: Garagepoort staat al 5 minuten open
  description: ''
  trigger:
  - platform: state
    entity_id: binary_sensor.ty18857573dc4f22b78e02
    from: 'off'
    to: 'on'
    for: 00:05:00
  condition: []
  action:
  - service: notify.mobile_app_bart_s10
    data:
      title: Garagepoort
      message: Garagepoort staat al 5 minuten open.
  - service: notify.mobile_app_madouce_s20
    data:
      title: Garagepoort
      message: Garagepoort staat al 5 minuten open.
  mode: single

- id: "garagepoort staat al 10 minuten open"
  alias: Garagepoort staat al 10 minuten open
  description: ''
  trigger:
  - platform: state
    entity_id: binary_sensor.ty18857573dc4f22b78e02
    from: 'off'
    to: 'on'
    for: 00:10:00
  condition: []
  action:
  - service: notify.mobile_app_bart_s10
    data:
      title: Garagepoort
      message: Garagepoort staat al 10 minuten open.
  - service: notify.mobile_app_madouce_s20
    data:
      title: Garagepoort
      message: Garagepoort staat al 10 minuten open.
  mode: single


- id: '1523171664225'
  alias: 👀 beweging oprit
  description: Beweging op oprit = melding op living speaker
  trigger:
  - platform: state
    entity_id: binary_sensor.buitensensor_vooraan_motion
    from: 'off'
    to: 'on'
  condition:
  - condition: template
    value_template: '{{ as_timestamp(now()) - as_timestamp(states.automation.beweging_oprit.attributes.last_triggered)
      | int > 120 }}'
  action:
  - service: tts.google_say
    data:
      entity_id: media_player.living_speaker
      message: Beweging op oprit!
  - service: tts.google_say
    data:
      entity_id: media_player.veranda_speaker_2
      message: Beweging op oprit!
  - wait_template: ''
    timeout: 00:00:10
  - service: camera.play_stream
    data:
      media_player: media_player.living_speaker
    target:
      entity_id: camera.netatmo_eikenbos_oprit
  - wait_template: ''
    timeout: 00:01:30
  - service: media_player.turn_off
    entity_id: media_player.living_speaker
  mode: single
