############################ Table of Contents ############################ 
# 
#   Automations
#
#
#
#
########################################################################### 


automation:
- alias: 🚀 Pi processor temp >72 °C = melding
  id: '64c59baf-e8fb-4fc0-b789-cf74742e57e4'
  description: ''
  trigger:
  - platform: numeric_state
    entity_id: sensor.processor_temperature
    above: '72'
    for: 00:10
  condition: []
  action:
  - service: notify.bart_phone
    data:
      message: temperatuur Raspberry Pi CPU is %{{states('sensor.processor_temperature')}}%
      title: Raspberry PI
  mode: single
  
- alias: 🚀 CPU > 60% = melding
  id: 'db887805-238d-4fe2-8512-e10b918eefe3'
  description: ''
  trigger:
  - platform: numeric_state
    entity_id: sensor.processor_use_percent
    above: '60'
    for: 00:15
  condition: []
  action:
  - service: notify.bart_phone
    data:
      message: CPU van Raspberry Pi werkt aan {{states('sensor.processor_use_percent')}}%.
      title: Raspberry Pi
  mode: single

- alias: 🚀 system shutdown notification-
  id: 'f15aa89e-f40c-45ad-8c54-dfa8317a98d1'
  description: Send notification on Home Assistant stop
  trigger:
  - platform: homeassistant
    event: shutdown
  action:
  - service: notify.bart_phone
    data:
      message: Home Assistant wordt gestopt.
  mode: single

- alias: 🚀 system restart notification
  id: 'c7eacdc5-7bf3-4a6f-a4a4-03fb7e62262c'
  description: Send notification on Home Assistant start
  trigger:
  - platform: homeassistant
    event: start
  condition: []
  action:
  - service: notify.bart_phone
    data:
      message: Home Assistant is volledig gestart.
  mode: single

- alias: 🚀Low battery level detection & notification for all battery sensors
  id: '9e972067-200b-4b7c-9a33-4a1d79543085'
  description: ''
  use_blueprint:
    path: sbyx/low-battery-level-detection-notification-for-all-battery-sensors.yaml
    input:
      threshold: 10
      actions:
      - device_id: b5d28be91fff8c03aece377f73b28dd2
        domain: mobile_app
        type: notify
        title: Batterijen
        message: Batterijen laag van {{sensors}}
      day: 6
      time: '12:00:00'

- alias: 🚀 Database cleanen
  id: '9bda21a0-65f4-4c33-8c17-e12f4331522b'
  description: ''
  trigger:
  - platform: time
    at: 09:00
  condition: []
  action:
  - service: recorder.purge
    data:
      keep_days: 30
  mode: single

- alias: 🚀 Google servers onbereikbaar = melding internetprobleem
  id: 'ba3fab2f-867f-4e94-a699-9580bacd8f27'
  description: ''
  trigger:
  - platform: state
    entity_id: binary_sensor.google_server
    from: 'on'
    to: 'off'
  condition: []
  action:
  - service: notify.bart_phone
    data:
      title: Probleem met internettoegang thuis.
      message: Google servers konden niet worden bereikt.
  mode: single

- alias: 🚀 Google servers terug bereikbaar = melding sturen
  id: '0f7ada67-01bc-4603-8da3-124b26cf1e24'
  description: ''
  trigger:
  - platform: state
    entity_id: binary_sensor.google_server
    from: 'off'
    to: 'on'
  condition: []
  action:
  - service: notify.bart_phone
    data:
      title: Internettoegang thuis opnieuw OK.
      message: Google servers konden opnieuw worden bereikt.
  mode: single

- alias: 🚀Home Assistant update notification
  id: '3cc10db6-a3e7-4a90-b165-87a606e438cd'
  description: ''
  use_blueprint:
    path: Klumper/update_notification.yaml
    input:
      notification_message: Home Assistant {{ newest_version }} is available
      delay: 0
      updater: binary_sensor.updater
      notify_device: b5d28be91fff8c03aece377f73b28dd2
      is_ios: false
      notification_title: Upgrade time!

- alias: '⏱ toiletteller: beweging = + 1'
  id: toiletteller
  description: ''
  trigger:
  - platform: state
    entity_id: binary_sensor.toilet_motion_sensor_motion
    to: 'on'
  condition: []
  action:
  - service: counter.increment
    target:
      entity_id: counter.toilet_counter
  mode: single

- alias: '⏱ toiletteller: reset om middernacht'
  id: 'toiletteller: reset om middernacht'
  description: ''
  trigger:
  - platform: time
    at: 00:00:00
  condition: []
  action:
  - service: counter.reset
    target:
      entity_id: counter.toilet_counter
  mode: single
