############################ Table of Contents ############################ 
# 
#   Automations
#   🚀 Pi CPU temp >79 °C = melding
#   🚀 Pi CPU > 50% = melding
#   🚀 system shutdown notification
#   🚀 system restart notification
#   🚀 Low battery level detection & notification for all battery sensors
#   🚀 Database cleanen
#   🚀 Google servers onbereikbaar = melding internetprobleem
#   🚀 Google servers terug bereikbaar = melding sturen
#   🚀 Home Assistant update notification
#   ⏱ toiletteller: beweging = + 1'
#   ⏱ toiletteller: reset om middernacht'
########################################################################### 


automation:

- alias: 🚀 Pi CPU temp >70 °C = melding
  id: '64c59baf-e8fb-4fc0-b789-cf74742e57e4'
  description: ''
  trigger:
  - platform: numeric_state
    entity_id: sensor.processor_temperature
    above: '70'
    for: 00:10
  condition: []
  action:
  - service: notify.bart_phone
    data_template:
      title: Raspberry Pi CPU
      message: CPU van Raspberry Pi werkt aan {{states('sensor.processor_use_percent')}}% en temperatuur is {{states('sensor.processor_temperature')}}°C.
      data:
        color: red
        actions:
        - action: URI
          title: meer info
          uri: /eikenbos-dashboard/netwerk
  mode: single
  
- alias: 🚀 Pi CPU > 50% = melding
  id: 'db887805-238d-4fe2-8512-e10b918eefe3'
  description: ''
  trigger:
  - platform: numeric_state
    entity_id: sensor.processor_use_percent
    above: '50'
    for: 00:15
  condition: []
  action:
  - service: notify.bart_phone
    data_template:
      title: Raspberry Pi CPU
      message: CPU van Raspberry Pi werkt aan {{states('sensor.processor_use_percent')}}% en temperatuur is {{states('sensor.processor_temperature')}}°C.
      data:
        color: red
        actions:
        - action: URI
          title: meer info
          uri: /eikenbos-dashboard/netwerk
  mode: single

- alias: 🚀 HA stopt
  id: 'f15aa89e-f40c-45ad-8c54-dfa8317a98d1'
  description: ''
  trigger:
  - platform: homeassistant
    event: shutdown
  action:
  - service: notify.bart_phone
    data:
      message: Home Assistant wordt gestopt.
  mode: single

- alias: 🚀 HA is herstart
  id: 'c7eacdc5-7bf3-4a6f-a4a4-03fb7e62262c'
  description: ''
  trigger:
  - platform: homeassistant
    event: start
  condition: []
  action:
  - service: notify.bart_phone
    data:
      message: Home Assistant is volledig gestart.
  mode: single

- alias: 🚀 Melding lage batterij voor alle batterijsensoren
  id: '9e972067-200b-4b7c-9a33-4a1d79543085'
  description: ''
  use_blueprint:
    path: sbyx/low-battery-level-detection-notification-for-all-battery-sensors.yaml
    input:
      threshold: 10
      actions:
      - device_id: b5d28be91fff8c03aece377f73b28dd2
        domain: mobile_app
        type: notify
        title: Batterijen
        message: Batterijen laag van {{sensors}}
      day: 6
      time: '12:00:00'

- alias: 🚀 Database cleanen
  id: '9bda21a0-65f4-4c33-8c17-e12f4331522b'
  description: ''
  trigger:
  - platform: time
    at: 09:00
  condition: []
  action:
  - service: recorder.purge
    data:
      keep_days: 7
      repack: true  # if you do not repack, the database size will not reduce
  mode: single

- alias: 🚀 Google servers onbereikbaar = melding internetprobleem
  id: 'ba3fab2f-867f-4e94-a699-9580bacd8f27'
  description: ''
  trigger:
  - platform: state
    entity_id: binary_sensor.google_server
    from: 'on'
    to: 'off'
  condition: []
  action:
  - service: notify.bart_phone
    data:
      title: Probleem met internettoegang thuis.
      message: Google servers konden niet worden bereikt.
      data:
        color: red      
  mode: single

- alias: 🚀 Google servers terug bereikbaar = melding sturen
  id: '0f7ada67-01bc-4603-8da3-124b26cf1e24'
  description: ''
  trigger:
  - platform: state
    entity_id: binary_sensor.google_server
    from: 'off'
    to: 'on'
  condition: []
  action:
  - service: notify.bart_phone
    data:
      title: Internettoegang thuis opnieuw OK.
      message: Google servers konden opnieuw worden bereikt.
  mode: single

- alias: 🚀 Nieuwe versie Home Assistant beschikbaar
  id: 27f3b3f5-aad9-4aaf-a37b-461e1a856935
  description: ''
  trigger:
  - platform: state
    entity_id: binary_sensor.updater
    to: 'on'
  condition: []
  action:
  - service: notify.bart_phone
    data:
      title: Er is een update van Home Assistant beschikbaar.
      message: "Nieuwe versie: {{ state_attr('binary_sensor.updater', 'newest_version') }}"
  mode: single

- alias: '⏱ toiletteller: beweging = + 1'
  id: toiletteller
  description: ''
  trigger:
  - platform: state
    entity_id: binary_sensor.toilet_motion_sensor_motion
    to: 'on'
    for:
      hours: 0
      minutes: 0
      seconds: 30    
  condition: []
  action:
  - service: counter.increment
    target:
      entity_id: counter.toilet_counter
  - delay:
      hours: 0
      minutes: 2
      seconds: 0
      milliseconds: 0
  mode: single    

- alias: '⏱ toiletteller: reset om middernacht'
  id: 'toiletteller: reset om middernacht'
  description: ''
  trigger:
  - platform: time
    at: 00:00:00
  condition: []
  action:
  - service: counter.reset
    target:
      entity_id: counter.toilet_counter
  mode: single
