############################ Table of Contents ############################ 
# 
#   Automations
#     garagepoorttag binnen gescand door Bart
#     garagepoorttag binnen gescand door Madouce
#     garagepoorttag binnen gescand door Alunya
#     garagepoorttag buiten gescand door Madouce
#     garagepoorttag buiten gescand door Alunya
#     button nachtkastje Bart (single press)

############################ Automations ################################## 

automation:

##########################################################################
# binnen
##########################################################################

- alias: 🔐 garagepoorttag binnen gescand door Bart
  id: '67a89219-5e5a-4862-b4a2-55f6013be43e'
  description: ''
  trigger:
  - platform: tag
    tag_id: !secret id_tag_garagepoort_binnen
    device_id: !secret id_nfc_bart
  condition: []
  action:
  - service: cover.open_cover
    target:
      entity_id: cover.garagepoort
  - service: notify.bart_phone
    data:
      message: 'Bart scant tag garagepoort binnen.'
      title: 'Garagepoort'
      data:
        color: "#FFA500"
        channel: home_access
  mode: single
  
- alias: 🔐 garagepoorttag binnen gescand door Madouce
  id: '7c52e27f-3e9c-45a2-b434-e4bec52d9b32'
  description: ''
  trigger:
  - platform: tag
    tag_id: !secret id_tag_garagepoort_binnen
    device_id: !secret id_nfc_madouce
  condition: []
  action:
  - service: cover.open_cover
    target:
      entity_id: cover.garagepoort
  - service: notify.bart_phone
    data:
      message: 'Madouce scant tag garagepoort binnen.'
      title: 'Garagepoort'
      data:
        color: "#FFA500"
        channel: home_access
  mode: single
  
- alias: 🔐 garagepoorttag binnen gescand door Alunya
  id: 'c51e85a1-d8bd-4f82-a919-0138a1e68861'
  description: ''
  trigger:
  - platform: tag
    tag_id: !secret id_tag_garagepoort_binnen
    device_id: !secret id_nfc_alunya
  condition: []
  action:
  - service: cover.open_cover
    target:
      entity_id: cover.garagepoort
  - service: notify.bart_phone
    data:
      message: 'Alunya scant tag garagepoort binnen.'
      title: 'Garagepoort'
      data:
        color: "#FFA500"
        channel: home_access
  - service: notify.madouce_phone
    data:
      message: 'Alunya scant tag garagepoort binnen.'
      title: 'Garagepoort'
      data:
        color: "#FFA500"
        channel: home_access
  mode: single


##########################################################################
# buiten
##########################################################################

- alias: 🔐 garagepoorttag buiten gescand door Bart
  id: '15550e2d-9a16-4d69-9342-c753548c534b'
  description: ''
  trigger:
  - platform: tag
    tag_id: !secret id_tag_garagepoort_buiten
    device_id: !secret id_nfc_bart
  condition: []
  action:
  - service: tts.google_say
    data:
      entity_id: media_player.living_speaker
      message: Bart scant garagepoort.
  - service: cover.open_cover
    target:
      entity_id: cover.garagepoort
  - service: notify.bart_phone
    data:
      message: 'Bart scant garagepoorttag buiten.'
      title: 'Garagepoort'
      data:
        color: "#FFA500"
        channel: home_access
  - service: notify.madouce_phone
    data:
      message: 'Bart scant garagepoorttag buiten.'
      title: 'Garagepoort'
      data:
        color: "#FFA500"
        channel: home_access
  mode: single

- alias: 🔐 garagepoorttag buiten gescand door Madouce
  id: '43cd43bd-9577-4e30-b825-61ea11e9ee7c'
  description: ''
  trigger:
  - platform: tag
    tag_id: !secret id_tag_garagepoort_buiten
    device_id: !secret id_nfc_madouce
  condition: []
  action:
  - service: tts.google_say
    data:
      entity_id: media_player.living_speaker
      message: Madouce scant garagepoort.
  - service: cover.open_cover
    target:
      entity_id: cover.garagepoort
  - service: notify.bart_phone
    data:
      message: 'Madouce scant garagepoorttag buiten.'
      title: 'Garagepoort'
      data:
        color: "#FFA500"
        channel: home_access
  mode: single
  
- alias: 🔐 garagepoorttag buiten gescand door Alunya
  id: 'd8fb82a1-a0d5-4b2f-a5d1-cce5fe4cf004'
  description: ''
  trigger:
  - platform: tag
    tag_id: !secret id_tag_garagepoort_buiten
    device_id: !secret id_nfc_alunya
  condition: []
  action:
  - service: tts.google_say
    data:
      entity_id: media_player.living_speaker
      message: Alunya scant garagepoort.
  - service: cover.open_cover
    target:
      entity_id: cover.garagepoort
  - service: notify.bart_phone
    data:
      message: 'Alunya scant garagepoorttag buiten.'
      title: 'Garagepoort'
      data:
        color: "#FFA500"
        channel: home_access
  - service: notify.madouce_phone
    data:
      message: 'Alunya scant garagepoorttag buiten.'
      title: 'Garagepoort'
      data:
        color: "#FFA500"
        channel: home_access
  mode: single

