############################ Table of Contents ############################ 
# 
#   Automations
#     TBD
#     TBD


############################ Automations ################################## 

automation:
- id: '1622791895306'
  alias: 🔐 garagepoorttag binnen gescand door Bart
  description: ''
  trigger:
  - platform: tag
    tag_id: !secret id_tag_garagepoort_binnen
    device_id: !secret id_nfc_bart
  condition: []
  action:
  - scene: scene.v5bab2lu7dc9oexz
  - service: notify.mobile_app_bart_s10
    data:
      message: 'Bart scant tag garagepoort binnen.'
      title: 'Garagepoort'
      data:
        color: "#FFA500"
        channel: home_access
  mode: single
  
- id: '1622794616704'
  alias: 🔐 garagepoorttag binnen gescand door Madouce
  description: ''
  trigger:
  - platform: tag
    tag_id: !secret id_tag_garagepoort_binnen
    device_id: !secret id_nfc_madouce
  condition: []
  action:
  - scene: scene.v5bab2lu7dc9oexz
  - service: notify.mobile_app_bart_s10
    data:
      message: 'Madouce scant tag garagepoort binnen.'
      title: 'Garagepoort'
      data:
        color: "#FFA500"
        channel: home_access
  mode: single
  
- id: '1622794712207'
  alias: 🔐 garagepoorttag binnen gescand door Alunya
  description: ''
  trigger:
  - platform: tag
    tag_id: !secret id_tag_garagepoort_binnen
    device_id: !secret id_nfc_alunya
  condition: []
  action:
  - scene: scene.v5bab2lu7dc9oexz
  - service: notify.mobile_app_bart_s10
    data:
      message: 'Alunya scant tag garagepoort binnen.'
      title: 'Garagepoort'
      data:
        color: "#FFA500"
        channel: home_access
  - service: notify.mobile_app_madouce_s20
    data:
      message: 'Alunya scant tag garagepoort binnen.'
      title: 'Garagepoort'
      data:
        color: "#FFA500"
        channel: home_access
  mode: single
  
- id: '1621967805692'
  alias: 🔐 garagepoorttag buiten gescand door Bart
  description: ''
  trigger:
  - platform: tag
    tag_id: !secret id_tag_garagepoort_buiten
    device_id: 10cfa6b79c0abd76
  condition: []
  action:
  - service: tts.google_say
    data:
      entity_id: media_player.living_speaker
      message: Bart scant garagepoort.
  - scene: scene.v5bab2lu7dc9oexz
  - service: notify.mobile_app_bart_s10
    data:
      message: 'Bart scant garagepoorttag buiten.'
      title: 'Garagepoort'
      data:
        color: "#FFA500"
        channel: home_access
  - service: notify.mobile_app_madouce_s20
    data:
      message: 'Bart scant garagepoorttag buiten.'
      title: 'Garagepoort'
      data:
        color: "#FFA500"
        channel: home_access
  mode: single

- id: '1621966250598'
  alias: 🔐 garagepoorttag buiten gescand door Madouce
  description: ''
  trigger:
  - platform: tag
    tag_id: !secret id_tag_garagepoort_buiten
    device_id: !secret id_nfc_madouce
  condition: []
  action:
  - service: tts.google_say
    data:
      entity_id: media_player.living_speaker
      message: Madouce scant garagepoort.
  - scene: scene.v5bab2lu7dc9oexz
  - service: notify.mobile_app_bart_s10
    data:
      message: 'Madouce scant garagepoorttag buiten.'
      title: 'Garagepoort'
      data:
        color: "#FFA500"
        channel: home_access
  mode: single
  
- id: '1621967888435'
  alias: 🔐 garagepoorttag buiten gescand door Alunya
  description: ''
  trigger:
  - platform: tag
    tag_id: !secret id_tag_garagepoort_buiten
    device_id: !secret id_nfc_alunya
  condition: []
  action:
  - service: tts.google_say
    data:
      entity_id: media_player.living_speaker
      message: Alunya scant garagepoort.
  - scene: scene.v5bab2lu7dc9oexz
  - service: notify.mobile_app_bart_s10
    data:
      message: 'Alunya scant garagepoorttag buiten.'
      title: 'Garagepoort'
      data:
        color: "#FFA500"
        channel: home_access
  - service: notify.mobile_app_madouce_s20
    data:
      message: 'Alunya scant garagepoorttag buiten.'
      title: 'Garagepoort'
      data:
        color: "#FFA500"
        channel: home_access
  mode: single