############################ Table of Contents ############################ 
# 
#   Automations
#     garagepoorttag binnen gescand door Bart
#     garagepoorttag binnen gescand door Madouce
#     garagepoorttag binnen gescand door Alunya
#     garagepoorttag buiten gescand door Madouce
#     garagepoorttag buiten gescand door Alunya
#     button nachtkastje Bart (single press)

############################ Automations ################################## 

automation:
- alias: 🔐 garagepoorttag binnen gescand door Bart
  id: '67a89219-5e5a-4862-b4a2-55f6013be43e'
  description: ''
  trigger:
  - platform: tag
    tag_id: !secret id_tag_garagepoort_binnen
    device_id: !secret id_nfc_bart
  condition: []
  action:
  - service: cover.open_cover
    target:
      entity_id: cover.garagepoort_door
  - service: notify.bart_phone
    data:
      message: 'Bart scant tag garagepoort binnen.'
      title: 'Garagepoort'
      data:
        color: "#FFA500"
        channel: home_access
  mode: single
  
- alias: 🔐 garagepoorttag binnen gescand door Madouce
  id: '7c52e27f-3e9c-45a2-b434-e4bec52d9b32'
  description: ''
  trigger:
  - platform: tag
    tag_id: !secret id_tag_garagepoort_binnen
    device_id: !secret id_nfc_madouce
  condition: []
  action:
  - service: cover.open_cover
    target:
      entity_id: cover.garagepoort_door
  - service: notify.bart_phone
    data:
      message: 'Madouce scant tag garagepoort binnen.'
      title: 'Garagepoort'
      data:
        color: "#FFA500"
        channel: home_access
  mode: single
  
- alias: 🔐 garagepoorttag binnen gescand door Alunya
  id: 'c51e85a1-d8bd-4f82-a919-0138a1e68861'
  description: ''
  trigger:
  - platform: tag
    tag_id: !secret id_tag_garagepoort_binnen
    device_id: !secret id_nfc_alunya
  condition: []
  action:
  - service: cover.open_cover
    target:
      entity_id: cover.garagepoort_door
  - service: notify.bart_phone
    data:
      message: 'Alunya scant tag garagepoort binnen.'
      title: 'Garagepoort'
      data:
        color: "#FFA500"
        channel: home_access
  - service: notify.madouce_phone
    data:
      message: 'Alunya scant tag garagepoort binnen.'
      title: 'Garagepoort'
      data:
        color: "#FFA500"
        channel: home_access
  mode: single
  
- alias: 🔐 garagepoorttag buiten gescand door Bart
  id: '15550e2d-9a16-4d69-9342-c753548c534b'
  description: ''
  trigger:
  - platform: tag
    tag_id: !secret id_tag_garagepoort_buiten
    device_id: scene.garagepoort_open
  condition: []
  action:
  - service: tts.google_say
    data:
      entity_id: media_player.living_speaker
      message: Bart scant garagepoort.
  - service: cover.open_cover
    target:
      entity_id: cover.garagepoort_door
  - service: notify.bart_phone
    data:
      message: 'Bart scant garagepoorttag buiten.'
      title: 'Garagepoort'
      data:
        color: "#FFA500"
        channel: home_access
  - service: notify.madouce_phone
    data:
      message: 'Bart scant garagepoorttag buiten.'
      title: 'Garagepoort'
      data:
        color: "#FFA500"
        channel: home_access
  mode: single

- alias: 🔐 garagepoorttag buiten gescand door Madouce
  id: '43cd43bd-9577-4e30-b825-61ea11e9ee7c'
  description: ''
  trigger:
  - platform: tag
    tag_id: !secret id_tag_garagepoort_buiten
    device_id: !secret id_nfc_madouce
  condition: []
  action:
  - service: tts.google_say
    data:
      entity_id: media_player.living_speaker
      message: Madouce scant garagepoort.
  - service: cover.open_cover
    target:
      entity_id: cover.garagepoort_door
  - service: notify.bart_phone
    data:
      message: 'Madouce scant garagepoorttag buiten.'
      title: 'Garagepoort'
      data:
        color: "#FFA500"
        channel: home_access
  mode: single
  
- alias: 🔐 garagepoorttag buiten gescand door Alunya
  id: 'd8fb82a1-a0d5-4b2f-a5d1-cce5fe4cf004'
  description: ''
  trigger:
  - platform: tag
    tag_id: !secret id_tag_garagepoort_buiten
    device_id: !secret id_nfc_alunya
  condition: []
  action:
  - service: tts.google_say
    data:
      entity_id: media_player.living_speaker
      message: Alunya scant garagepoort.
  - service: cover.open_cover
    target:
      entity_id: cover.garagepoort_door
  - service: notify.bart_phone
    data:
      message: 'Alunya scant garagepoorttag buiten.'
      title: 'Garagepoort'
      data:
        color: "#FFA500"
        channel: home_access
  - service: notify.madouce_phone
    data:
      message: 'Alunya scant garagepoorttag buiten.'
      title: 'Garagepoort'
      data:
        color: "#FFA500"
        channel: home_access
  mode: single
  
- alias: tag nachtkastje Bart
  id: '2daac4a9-ac7c-4cbd-a52d-03ed47da044b'
  description: ''
  trigger:
    - platform: tag
      tag_id: df93d9d5-f6c6-4705-902a-b7e5d9dfbb77
  condition: []
  action:
    - service: tts.google_say
      data:
        entity_id: media_player.master_bedroom_speaker
        cache: false
        message: >-
          Het is nu {{ as_timestamp(now()) |timestamp_custom('%H') }} uur {{
          as_timestamp(now()) |timestamp_custom('%M') }}. Buiten is het
          {{states('sensor.temp_leuven24_wunderground')}} graden.
    - delay:
        seconds: 8
    - service: tts.google_say
      data:
        entity_id: media_player.master_bedroom_speaker
        message: >-
          Nog {{states('sensor.anniversary_huwelijk_madouce_bart')}} dagen voor
          jullie huwelijk. {{("Het begint nu echt wel te korten!", "Dat is eigenlijk niet zo lang meer!", "Proficiat alvast!", "Heb je de ringen al?", "Het kostuum mag nu toch gaan komen.", "Spannend hé?", "Ik kijk er zelf ook al naar uit!"
              )|random }}
    - delay:
        seconds: 10
    - service: tts.google_say
      data:
        entity_id: media_player.master_bedroom_speaker
        message: >-
          {% if is_state('lock.audi_e_tron_sportback_55_door_lock_2', 'unlocked')
          %} De auto is niet op slot. {% else %} De auto is op slot. {% endif %}
    - delay:
        seconds: 2
    - service: tts.google_say
      data:
        entity_id: media_player.master_bedroom_speaker
        message: >-
          De auto is
          {{states('sensor.audi_e_tron_sportback_55_state_of_charge')}}% geladen
          {% if is_state('sensor.audi_e_tron_sportback_55_plug_state',
          'connected') %} en de laadkabel is verbonden. {%else%} maar de laadkabel
          is niet verbonden. {% endif %}
    - delay:
        seconds: 7
    - service: tts.google_say
      data:
        entity_id: media_player.master_bedroom_speaker
        cache: false
        message: >-
          {% if is_state('lock.voordeur', 'unlocked') %} De voordeur is niet op
          slot. {% else %} De voordeur is op slot. {% endif %}
    - delay:
        seconds: 3
    - service: tts.google_say
      data:
        entity_id: media_player.master_bedroom_speaker
        cache: false
        message: >-
          {% if is_state('group.alle_raam_sensoren', 'off') %} Alle ramen zijn
          dicht! {% else %} De volgende ramen staan nog open:
          {{expand(states.binary_sensor.kamer_amilya_raam,
          states.binary_sensor.kamer_alunya_raam,
          states.binary_sensor.kamer_alunya_schuifraam,
          states.binary_sensor.badkamer_raam_kantel,
          states.binary_sensor.badkamer_raam_wijd,
          states.binary_sensor.berging_raam,
          states.binary_sensor.keuken_raam,
          states.binary_sensor.living_oprit_raam,
          states.binary_sensor.living_tuin_raam,
          states.binary_sensor.master_bedroom_raam_kantel,
          states.binary_sensor.master_bedroom_raam_wijd,
          states.binary_sensor.veranda_schuifraam)
          |selectattr('state','eq','on') | map(attribute='name')| list }} {% endif
          %}
  mode: single
