############################ Table of Contents ############################ 
# 
#   Automations
#     garagepoorttag binnen gescand door Bart
#     garagepoorttag binnen gescand door Madouce
#     garagepoorttag binnen gescand door Alunya
#     garagepoorttag buiten gescand door Madouce
#     garagepoorttag buiten gescand door Alunya
#     Tag gescand controle voor nacht

############################ Automations ################################## 

automation:
- alias: 🔐 garagepoorttag binnen gescand door Bart
  id: '67a89219-5e5a-4862-b4a2-55f6013be43e'
  description: ''
  trigger:
  - platform: tag
    tag_id: !secret id_tag_garagepoort_binnen
    device_id: !secret id_nfc_bart
  condition: []
  action:
  - scene: scene.garagepoort_open
  - service: notify.bart_phone
    data:
      message: 'Bart scant tag garagepoort binnen.'
      title: 'Garagepoort'
      data:
        color: "#FFA500"
        channel: home_access
  mode: single
  
- alias: 🔐 garagepoorttag binnen gescand door Madouce
  id: '7c52e27f-3e9c-45a2-b434-e4bec52d9b32'
  description: ''
  trigger:
  - platform: tag
    tag_id: !secret id_tag_garagepoort_binnen
    device_id: !secret id_nfc_madouce
  condition: []
  action:
  - scene: scene.garagepoort_open
  - service: notify.bart_phone
    data:
      message: 'Madouce scant tag garagepoort binnen.'
      title: 'Garagepoort'
      data:
        color: "#FFA500"
        channel: home_access
  mode: single
  
- alias: 🔐 garagepoorttag binnen gescand door Alunya
  id: 'c51e85a1-d8bd-4f82-a919-0138a1e68861'
  description: ''
  trigger:
  - platform: tag
    tag_id: !secret id_tag_garagepoort_binnen
    device_id: !secret id_nfc_alunya
  condition: []
  action:
  - scene: scene.garagepoort_open
  - service: notify.bart_phone
    data:
      message: 'Alunya scant tag garagepoort binnen.'
      title: 'Garagepoort'
      data:
        color: "#FFA500"
        channel: home_access
  - service: notify.madouce_phone
    data:
      message: 'Alunya scant tag garagepoort binnen.'
      title: 'Garagepoort'
      data:
        color: "#FFA500"
        channel: home_access
  mode: single
  
- alias: 🔐 garagepoorttag buiten gescand door Bart
  id: '15550e2d-9a16-4d69-9342-c753548c534b'
  description: ''
  trigger:
  - platform: tag
    tag_id: !secret id_tag_garagepoort_buiten
    device_id: scene.garagepoort_open
  condition: []
  action:
  - service: tts.google_say
    data:
      entity_id: media_player.living_speaker
      message: Bart scant garagepoort.
  - scene: scene.v5bab2lu7dc9oexz
  - service: notify.bart_phone
    data:
      message: 'Bart scant garagepoorttag buiten.'
      title: 'Garagepoort'
      data:
        color: "#FFA500"
        channel: home_access
  - service: notify.madouce_phone
    data:
      message: 'Bart scant garagepoorttag buiten.'
      title: 'Garagepoort'
      data:
        color: "#FFA500"
        channel: home_access
  mode: single

- alias: 🔐 garagepoorttag buiten gescand door Madouce
  id: '43cd43bd-9577-4e30-b825-61ea11e9ee7c'
  description: ''
  trigger:
  - platform: tag
    tag_id: !secret id_tag_garagepoort_buiten
    device_id: !secret id_nfc_madouce
  condition: []
  action:
  - service: tts.google_say
    data:
      entity_id: media_player.living_speaker
      message: Madouce scant garagepoort.
  - scene: scene.garagepoort_open
  - service: notify.bart_phone
    data:
      message: 'Madouce scant garagepoorttag buiten.'
      title: 'Garagepoort'
      data:
        color: "#FFA500"
        channel: home_access
  mode: single
  
- alias: 🔐 garagepoorttag buiten gescand door Alunya
  id: 'd8fb82a1-a0d5-4b2f-a5d1-cce5fe4cf004'
  description: ''
  trigger:
  - platform: tag
    tag_id: !secret id_tag_garagepoort_buiten
    device_id: !secret id_nfc_alunya
  condition: []
  action:
  - service: tts.google_say
    data:
      entity_id: media_player.living_speaker
      message: Alunya scant garagepoort.
  - scene: scene.garagepoort_open
  - service: notify.bart_phone
    data:
      message: 'Alunya scant garagepoorttag buiten.'
      title: 'Garagepoort'
      data:
        color: "#FFA500"
        channel: home_access
  - service: notify.madouce_phone
    data:
      message: 'Alunya scant garagepoorttag buiten.'
      title: 'Garagepoort'
      data:
        color: "#FFA500"
        channel: home_access
  mode: single
  
- alias: Tag gescand controle voor nacht
  id: '2484b046-5083-487b-b5e5-d040d486cf09'
  description: ''
  trigger:
  - platform: tag
    tag_id: df93d9d5-f6c6-4705-902a-b7e5d9dfbb77
  condition: []
  action:
  - service: tts.google_say
    data:
      entity_id: media_player.nestaudio3875
      message: "{% if is_state('lock.audi_e_tron_sportback_55_door_lock_2', 'unlocked') %} De auto is niet op slot. {% else %} De auto is op slot. {% endif %}"
  - wait_template: ''
    timeout: 00:00:05
 #- wait_template: "{{ is_state('media_player.nestaudio3875','idle') }}"
  - service: tts.google_say
    data:
      entity_id: media_player.nestaudio3875
      message: "De auto is {{states('sensor.audi_e_tron_sportback_55_state_of_charge')}}% geladen {% if is_state('sensor.audi_e_tron_sportback_55_plug_state', 'connected') %} en de laadkabel is verbonden. {%else%} maar de laadkabel is niet verbonden. {% endif %}"
  - wait_template: ''
    timeout: 00:00:06
  - service: tts.google_say
    data:
      entity_id: media_player.nestaudio3875
      message: "{% if is_state('lock.voordeur', 'unlocked') %} De voordeur is niet op slot. {% else %} De voordeur is op slot. {% endif %}"
  - wait_template: ''
    timeout: 00:00:03
  - service: tts.google_say
    data:
      entity_id: media_player.nestaudio3875
      message: '{% if is_state(''group.group.raam_sensoren'', ''off'')
        %} Alle ramen zijn dicht! {% else %} De volgende ramen staan nog open: {{
        expand(states.binary_sensor.kamer_amilya_raam_sensor, states.binary_sensor.kamer_alunya_raam_sensor,
        states.binary_sensor.kamer_alunya_schuifraam_sensor, states.binary_sensor.badkamer_raam_sensor,
        states.binary_sensor.berging_raam_sensor, states.binary_sensor.keuken_raam_sensor,
        states.binary_sensor.living_oprit_raam_sensor, states.binary_sensor.living_tuin_raam_sensor,
        states.binary_sensor.master_bedroom_raam_sensor, states.binary_sensor.veranda_schuifraam_sensor)
        | selectattr(''state'',''eq'',''on'') | map(attribute=''name'')| list }} {%
        endif %}'
  mode: single
