############################ Table of Contents ############################ 
# 

automation:
- alias: te warm in kamer Amilya - open raam (Bart)
  id: 'ae5bbb04-af4b-42e2-ba7a-5d57a411c6bc'
  description: ''
  trigger:
  - platform: time_pattern
    minutes: /60
  condition:
  - condition: state
    entity_id: binary_sensor.kamer_amilya_raam_sensor
    state: 'off'
  - condition: template
    value_template: "{{ states('sensor.kamer_amilya_temperature') | float > 23 }}"
  - condition: template
    value_template: "{{ states('sensor.kamer_amilya_temperature') > states('sensor.temp_leuven24_wunderground') }}"
  - condition: zone
    entity_id: person.bart
    zone: zone.home
  - condition: time
    after: '7:0:0'
    before: '23:00:00'
  action:
  - service: notify.bart_phone
    data:
      message: "Temperatuur in kamer Amilya is {{states('sensor.kamer_amilya_temperature')}}째C. Buiten {{states('sensor.temp_leuven24_wunderground')}}째C."
      title: Open het raam van Amilya!
      data:
        color: blue
        channel: Temperatuur
        timeout: 3600
        tag: temp_amilya
        actions:
        - action: URI
          title: meer info
          uri: /lovelace/temp_detail
  mode: single
  
- alias: te warm in kamer Amilya - open raam (Madouce)
  id: '5f334c36-306e-4ab5-84c3-ba771b739748'
  description: ''
  trigger:
  - platform: time_pattern
    minutes: /60
  condition:
  - condition: state
    entity_id: binary_sensor.kamer_amilya_raam_sensor
    state: 'off'
  - condition: template
    value_template: "{{ states('sensor.kamer_amilya_temperature') | float > 23 }}"
  - condition: template
    value_template: "{{ states('sensor.kamer_amilya_temperature') > states('sensor.temp_leuven24_wunderground') }}"
  - condition: zone
    entity_id: person.madouce
    zone: zone.home
  - condition: time
    after: '7:0:0'
    before: '23:00:00'
  action:
  - service: notify.madouce_phone
    data:
      message: "Temperatuur in kamer Amilya is {{states('sensor.kamer_amilya_temperature')}}째C. Buiten {{states('sensor.temp_leuven24_wunderground')}}째C."
      title: Open het raam van Amilya!
      data:
        color: blue
        channel: Temperatuur
        timeout: 3600
        tag: temp_amilya
        actions:
        - action: URI
          title: meer info
          uri: /lovelace/temp_detail
  mode: single
    