############################ Table of Contents ############################ 
# 
########################################################################### 

automation:

- alias: te warm in kamer Amilya - open raam (Bart)
  id: 'ae5bbb04-af4b-42e2-ba7a-5d57a411c6bc'
  description: ''
  trigger:
  - platform: time_pattern
    hours: /1
  condition:
  - condition: state
    entity_id: binary_sensor.kamer_amilya_raam
    state: 'off'
  - condition: template
    value_template: "{{ states('sensor.kamer_amilya_temperature') | float > 23 }}"
  - condition: template
    value_template: "{{ states('sensor.kamer_amilya_temperature') > states('sensor.temp_leuven24_wunderground') }}"
  - condition: zone
    entity_id: person.bart
    zone: zone.home
  - condition: time
    after: '07:00'
    before: '23:00'
  action:
  - service: notify.bart_phone
    data:
      message: "Temperatuur in kamer Amilya is {{states('sensor.kamer_amilya_temperature')}}째C. Buiten {{states('sensor.temp_leuven24_wunderground')}}째C."
      title: Open het raam van Amilya!
      data:
        color: blue
        channel: Temperatuur
        timeout: 3600
        tag: temp_amilya
        actions:
        - action: URI
          title: meer info
          uri: /lovelace/temp_detail
  mode: single
  
- alias: te warm in kamer Amilya - open raam (Madouce)
  id: '5f334c36-306e-4ab5-84c3-ba771b739748'
  description: ''
  trigger:
  - platform: time_pattern
    hours: /1
  condition:
  - condition: state
    entity_id: binary_sensor.kamer_amilya_raam
    state: 'off'
  - condition: template
    value_template: "{{ states('sensor.kamer_amilya_temperature') | float > 23 }}"
  - condition: template
    value_template: "{{ states('sensor.kamer_amilya_temperature') > states('sensor.temp_leuven24_wunderground') }}"
  - condition: zone
    entity_id: person.madouce
    zone: zone.home
  - condition: time
    after: '07:00:00'
    before: '23:00:00'
  action:
  - service: notify.madouce_phone
    data:
      message: "Temperatuur in kamer Amilya is {{states('sensor.kamer_amilya_temperature')}}째C. Buiten {{states('sensor.temp_leuven24_wunderground')}}째C."
      title: Open het raam van Amilya!
      data:
        color: blue
        channel: Temperatuur
        timeout: 3600
        tag: temp_amilya
        actions:
        - action: URI
          title: meer info
          uri: /lovelace/temp_detail
  mode: single


  id: '1783207d-8943-4734-b76a-9a8a613e5b5d'
  description: ''
  trigger:
  - platform: template
    value_template: '{{ states(''sensor.master_bedroom_temperature'') | float < 21 }}'
  condition: []
  action:
  - service: fan.turn_off
    target:
      entity_id: fan.xiaomi_smart_fan_3c
  mode: single

- alias: temperatuur in huis stijgt snel = melding
  id: '8d121e36-fd46-4a2e-b6ad-e6d15442f352'
  description: ''
  trigger:
    - platform: state
      entity_id:
        - group.home_temp_rising
      to: 'on'
  condition: []
  action:
    - service: notify.bart_phone
      data:
        title: Temperatuur in huis begint snel te stijgen.
        message: >
          Temperatuur stijgt in: {{expand(states.group.home_temp_rising) |
          selectattr('state','eq','on') | map(attribute='name') | list | join(',
          ') }}<br> {% if is_state('group.alle_raam_sensoren', 'off') %} Gelukkig
          zijn alle ramen dicht! {% else %}
          {{expand(states.group.alle_raam_sensoren) |selectattr('state','eq','on')
          | list | length }} open ramen: 
          {{expand(states.group.alle_raam_sensoren) |
          selectattr('state','eq','on') | map(attribute='name') | list | join(',
          ') }} {% endif %}
    - service: notify.madouce_phone
      data:
        title: Temperatuur in huis begint snel te stijgen.
        message: >
          Temperatuur stijgt in: {{expand(states.group.home_temp_rising) |
          selectattr('state','eq','on') | map(attribute='name') | list | join(',
          ') }}<br> {% if is_state('group.alle_raam_sensoren', 'off') %} Gelukkig
          zijn alle ramen dicht! {% else %}
          {{expand(states.group.alle_raam_sensoren) |selectattr('state','eq','on')
          | list | length }} open ramen: 
          {{expand(states.group.alle_raam_sensoren) |
          selectattr('state','eq','on') | map(attribute='name') | list | join(',
          ') }} {% endif %}
  mode: single

- alias: buiten kouder geworden dan in living = melding
  id: '5ab391c1-772d-44c0-adeb-cbf62f1cbf20'
  description: ''
  trigger:
  - platform: template
    value_template: "{{outdoor}} < {{indoor}}"
  condition:
  - condition: state
    entity_id: group.living_ramen
    state: "off"
  action:
  - service: input_boolean.turn_on
    target:
      entity_id: input_boolean.living_raam_moet_open
  - service: input_boolean.turn_off
    target:
      entity_id: input_boolean.living_raam_moet_dicht
  - service: notify.bart_phone
    data:
      title: Ramen in living mogen open
      message: Buiten wordt het nu koeler ({{outdoor}}) dan binnen ({{indoor}}).
      data:
        color: green
        channel: ramen
        timeout: 3600
        tag: window_living
  - service: notify.madouce_phone
    data:
      title: Ramen in living mogen open
      message: Buiten wordt het nu koeler ({{outdoor}}) dan binnen ({{ indoor }}).
      data:
        color: green
        channel: ramen
        timeout: 3600
        tag: window_living
  variables:
    outdoor: "{{ states('sensor.temp_leuven24_wunderground') |float }}"
    indoor: "{{ states('sensor.living_temperature')| float }}"         

- alias: buiten kouder geworden dan in veranda = melding
  id: 'bdb9a781-02a1-429a-a4dd-d9bdcdd79807'
  description: ''
  trigger:
  - platform: template
    value_template: "{{outdoor}} < {{indoor}}"
  condition:
  - condition: state
    entity_id: binary_sensor.veranda_schuifraam
    state: "off"
  action:
    - service: input_boolean.turn_on
      target:
        entity_id: input_boolean.veranda_raam_moet_open
    - service: input_boolean.turn_off
      target:
        entity_id: input_boolean.veranda_raam_moet_dicht
    - service: notify.bart_phone
      data:
        title: Raam in veranda mag open
        message: Buiten wordt het nu koeler ({{outdoor}}) dan binnen ({{indoor}}).
        data:
          color: green
          channel: ramen
          timeout: 3600
          tag: window_veranda          
    - service: notify.madouce_phone
      data:
        title: Raam in veranda mag open
        message: >
          Buiten wordt het nu koeler ({{outdoor}}) dan binnen ({{indoor}}).
        data:
          color: green
          channel: ramen
          timeout: 3600
          tag: window_veranda          
  variables:
    outdoor: "{{ states('sensor.temp_leuven24_wunderground') |float }}"
    indoor: "{{ states('sensor.veranda_temperature') |float }}"           

- alias: buiten kouder geworden dan in kamer Amilya = melding
  id: 'ab17e743-817e-4649-a2a4-d222131f0f44'
  description: ''
  trigger:
  - platform: template
    value_template: "{{outdoor}} < {{indoor}}"
  condition:
  - condition: state
    entity_id: binary_sensor.kamer_amilya_raam
    state: "off"
  action:
    - service: input_boolean.turn_on
      target:
        entity_id: input_boolean.kamer_amilya_raam_moet_open
    - service: input_boolean.turn_off
      target:
        entity_id: input_boolean.kamer_amilya_raam_moet_dicht
    - service: notify.bart_phone
      data:
        title: Raam Amilya mag open
        message: Buiten wordt het nu koeler ({{outdoor}}) dan binnen ({{indoor}}).
        data:
          color: green
          channel: ramen
          timeout: 3600
          tag: window_amilya          
    - service: notify.madouce_phone
      data:
        title: Raam Amilya mag open
        message: >
          Buiten wordt het nu koeler ({{outdoor}}) dan binnen ({{indoor}}).
        data:
          color: green
          channel: ramen
          timeout: 3600
          tag: window_amilya          
  variables:
    outdoor: "{{ states('sensor.temp_leuven24_wunderground') |float }}"
    indoor: "{{ states('sensor.kamer_amilya_temperature') |float }}"           

- alias: buiten kouder geworden dan in kamer Alunya = melding
  id: '6ac20eb1-35ef-4811-8396-84f98646f425'
  description: ''
  trigger:
  - platform: template
    value_template: "{{outdoor}} < {{indoor}}"
  condition:
  - condition: state
    entity_id: group.kamer_alunya_ramen
    state: "off"
  action:
    - service: input_boolean.turn_on
      target:
        entity_id: input_boolean.kamer_alunya_raam_moet_open
    - service: input_boolean.turn_off
      target:
        entity_id: input_boolean.kamer_alunya_raam_moet_dicht
    - service: notify.bart_phone
      data:
        title: Raam Alunya mag open
        message: Buiten wordt het nu koeler ({{outdoor}}) dan binnen ({{indoor}}).
        data:
          color: green
          channel: ramen
          timeout: 3600
          tag: window_alunya          
    - service: notify.madouce_phone
      data:
        title: Raam Alunya mag open
        message: Buiten wordt het nu koeler ({{outdoor}}) dan binnen ({{indoor}}).
        data:
          color: green
          channel: ramen
          timeout: 3600
          tag: window_alunya          
  variables:
    outdoor: "{{ states('sensor.temp_leuven24_wunderground') |float }}"
    indoor: "{{ states('sensor.kamer_alunya_temperature') |float }}"          

- alias: buiten kouder geworden dan in master bedroom = melding
  id: '695898c2-c66e-4d93-9598-ff3337f00e05'
  description: ''
  trigger:
  - platform: template
    value_template: "{{outdoor}} < {{indoor}}"
  condition:
  - condition: state
    entity_id: binary_sensor.master_bedroom_raam_kantel
    state: "off"
  action:
    - service: input_boolean.turn_on
      target:
        entity_id: input_boolean.master_bedroom_raam_moet_open
    - service: input_boolean.turn_off
      target:
        entity_id: input_boolean.master_bedroom_raam_moet_dicht
    - service: notify.bart_phone
      data:
        title: Raam in master bedroom mag open
        message: Buiten wordt het nu koeler ({{outdoor}}) dan binnen ({{indoor}}).
        data:
          color: green
          channel: ramen
          timeout: 3600
          tag: window_master_bedroom
    - service: notify.madouce_phone
      data:
        title: Raam in master bedroom mag open
        message: Buiten wordt het nu koeler ({{outdoor}}) dan binnen ({{indoor}}).
        data:
          color: green
          channel: ramen
          timeout: 3600
          tag: window_master_bedroom          
  variables:
    outdoor: "{{ states('sensor.temp_leuven24_wunderground') |float }}"
    indoor: "{{ states('sensor.master_bedroom_temperature') |float }}"