############################ Table of Contents ############################ 
# 
########################################################################### 

automation:

- alias: 'fan: slaapkamer >21° = ventilator aan'
  id: '88271d4a-b388-4cae-8886-ed4c85529d9e'
  description: ''
  trigger:
  - platform: template
    value_template: '{{ states(''sensor.master_bedroom_temperature'') | float > 21
      }}'
  condition:
  - condition: time
    after: '22:30:00'
    before: '08:00:00'
  - condition: state
    entity_id: person.bart
    state: home
  action:
  - service: fan.turn_on
    target:
      entity_id: fan.xiaomi_smart_fan_3c
    data:
      percentage: 15
  mode: single

- alias: 'fan: slaapkamer <21° = ventilator uit'
  id: '1783207d-8943-4734-b76a-9a8a613e5b5d'
  description: ''
  trigger:
  - platform: template
    value_template: '{{ states(''sensor.master_bedroom_temperature'') | float < 21 }}'
  condition: []
  action:
  - service: fan.turn_off
    target:
      entity_id: fan.xiaomi_smart_fan_3c
  mode: single

  id: '695898c2-c66e-4d93-9598-ff3337f00e05'
  description: ''
  trigger:
  - platform: template
    value_template: "{{outdoor}} < {{indoor}}"
  condition:
  - condition: state
    entity_id: binary_sensor.master_bedroom_raam_kantel
    state: "off"
  action:
    - service: input_boolean.turn_on
      target:
        entity_id: input_boolean.master_bedroom_raam_moet_open
    - service: input_boolean.turn_off
      target:
        entity_id: input_boolean.master_bedroom_raam_moet_dicht
    - service: notify.bart_phone
      data:
        title: Raam in master bedroom mag open
        message: Buiten wordt het nu koeler ({{outdoor}}) dan binnen ({{indoor}}).
        data:
          color: green
          channel: ramen
          timeout: 3600
          tag: window_master_bedroom
    - service: notify.madouce_phone
      data:
        title: Raam in master bedroom mag open
        message: Buiten wordt het nu koeler ({{outdoor}}) dan binnen ({{indoor}}).
        data:
          color: green
          channel: ramen
          timeout: 3600
          tag: window_master_bedroom          
  variables:
    outdoor: "{{ states('sensor.temp_leuven24_wunderground') |float }}"
    indoor: "{{ states('sensor.master_bedroom_temperature') |float }}"