############################ Table of Contents ############################ 
#
#     Open windows notifications
#     Open windows clear notifications
#
###########################################################################

automation:

###################################
# Open windows: notifications
###################################

- id: 'ramen -  open raam living room (Bart en Madouce)'
  alias: 🪟 ramen -  open raam living room (Bart en Madouce)
  description: ''
  trigger:
  - platform: time_pattern
    minutes: /15
  condition:
  - condition: state
    entity_id: input_boolean.living_room_raam_moet_open
    state: 'on'
  - condition: and
    conditions:    
    - condition: state
      entity_id: binary_sensor.keuken_raam_sensor
      state: 'off'
    - condition: state
      entity_id: binary_sensor.living_room_oprit_raam_sensor
      state: 'off'
    - condition: state
      entity_id: binary_sensor.living_room_tuin_raam_sensor
      state: 'off'            
  - condition: state
    entity_id: input_boolean.living_room_window_pause
    state: 'off'
  action:
  - service: script.notify_bart_windows
    data_template:
      message: "Vocht living: {{states('sensor.gram_water_living_room')}} g/m³. Buiten: {{states('sensor.gram_water_outside')}} g/m³.<br>Temp living: {{states('sensor.living_room_temperature')}} °C. Buiten: {{states('sensor.temp_leuven24_wunderground')}} °C."
      title: "Open het raam van de living/keuken!"
      tag: "window_living_room"
      action_window_pause: "living_room_window_pause"
      reason: "{% if (states('sensor.gram_water_living_room_diff_outside') | float >= 0.5 %} Te vochtig binnen. {% endif %}"
  - service: script.notify_madouce_windows
    data_template:
      message: "Vocht living: {{states('sensor.gram_water_living_room')}} g/m³. Buiten: {{states('sensor.gram_water_outside')}} g/m³.<br>Temp living: {{states('sensor.living_room_temperature')}} °C. Buiten: {{states('sensor.temp_leuven24_wunderground')}} °C."
      title: "Open het raam van de living/keuken!"
      tag: "window_living_room"
      action_window_pause: "living_room_window_pause"
      reason: "{% if (states('sensor.gram_water_living_room_diff_outside') | float >= 0.5 %} Te vochtig binnen. {% endif %}"
  mode: single

- id: 'ramen -  open raam kamer Amilya (Bart en Madouce)'
  alias: 🪟 ramen -  open raam kamer Amilya (Bart en Madouce)
  description: ''
  trigger:
  - platform: time_pattern
    minutes: /15
  condition:
  - condition: state
    entity_id: input_boolean.kamer_amilya_raam_moet_open
    state: 'on'
  - condition: state
    entity_id: binary_sensor.kamer_amilya_raam_sensor
    state: 'off'
  - condition: state
    entity_id: input_boolean.kamer_amilya_window_pause
    state: 'off'
  - condition: zone
    entity_id: person.bart
    zone: zone.home
  action:
  - service: script.notify_bart_windows
    data_template:
      message: "Vocht kamer Amilya: {{states('sensor.gram_water_kamer_amilya')}} g/m³. Buiten: {{states('sensor.gram_water_outside')}} g/m³.<br>Temp kamer Amilya: {{states('sensor.kamer_amilya_temperature')}} °C. Buiten: {{states('sensor.temp_leuven24_wunderground')}} °C."
      title: "Open het raam van Amilya!"
      tag: "window_kamer_amilya"
      action_window_pause: "kamer_amilya_window_pause"
      reason: "{% if (states('sensor.gram_water_kamer_amilya_diff_outside') | float >= 0.5 %} Te vochtig binnen. {% endif %}"
  - service: script.notify_madouce_windows
    data_template:
      message: "Vocht kamer Amilya: {{states('sensor.gram_water_kamer_amilya')}} g/m³. Buiten: {{states('sensor.gram_water_outside')}} g/m³.<br>Temp kamer Amilya: {{states('sensor.kamer_amilya_temperature')}} °C. Buiten: {{states('sensor.temp_leuven24_wunderground')}} °C."
      title: "Open het raam van Amilya!"
      tag: "window_kamer_amilya"
      action_window_pause: "kamer_amilya_window_pause"
      reason: "{% if (states('sensor.gram_water_kamer_amilya_diff_outside') | float >= 0.5 %} Te vochtig binnen. {% endif %}"
  mode: single

- id: 'ramen -  open raam veranda (Bart en Madouce)'
  alias: 🪟 ramen -  open raam veranda (Bart en Madouce)
  description: ''
  trigger:
  - platform: time_pattern
    minutes: /15
  condition:
  - condition: state
    entity_id: input_boolean.veranda_schuifraam_moet_open
    state: 'on'
  - condition: state
    entity_id: binary_sensor.veranda_schuifraam_sensor
    state: 'off'
  - condition: state
    entity_id: input_boolean.veranda_window_pause
    state: 'off'
  action:
  - service: script.notify_bart_windows
    data_template:
      message: "Vocht veranda {{states('sensor.gram_water_veranda')}} g/m³. Buiten: {{states('sensor.gram_water_outside')}} g/m³.<br>Temp veranda: {{states('sensor.veranda_temperature')}} °C. Buiten: {{states('sensor.temp_leuven24_wunderground')}} °C."
      title: "Open het raam van de veranda!"
      tag: "window_veranda"
      action_window_pause: "veranda_window_pause"
      reason: "{% if (states('sensor.gram_water_veranda_diff_outside') | float >= 0.5 %} Te vochtig binnen. {% endif %}"
  - service: script.notify_madouce_windows
    data_template:
      message: "Vocht veranda {{states('sensor.gram_water_veranda')}} g/m³. Buiten: {{states('sensor.gram_water_outside')}} g/m³.<br>Temp veranda: {{states('sensor.veranda_temperature')}} °C. Buiten: {{states('sensor.temp_leuven24_wunderground')}} °C."
      title: "Open het raam van de veranda!"
      tag: "window_veranda"
      action_window_pause: "veranda_window_pause"
      reason: "{% if (states('sensor.gram_water_veranda_diff_outside') | float >= 0.5 %} Te vochtig binnen. {% endif %}"
  mode: single

- id: 'ramen -  open raam berging (Bart en Madouce)'
  alias: 🪟 ramen -  open raam berging (Bart en Madouce)
  description: ''
  trigger:
  - platform: time_pattern
    minutes: /15
  condition:
  - condition: state
    entity_id: input_boolean.berging_raam_moet_open
    state: 'on'
  - condition: state
    entity_id: binary_sensor.berging_raam_sensor
    state: 'off'
  - condition: state
    entity_id: input_boolean.berging_window_pause
    state: 'off'    
  action:
  - service: script.notify_bart_windows
    data_template:
      message: "Vocht berging {{states('sensor.gram_water_berging')}} g/m³. Buiten: {{states('sensor.gram_water_outside')}} g/m³.<br>Temp berging: {{states('sensor.berging_temperature')}} °C. Buiten: {{states('sensor.temp_leuven24_wunderground')}} °C."
      title: "Open het raam van de berging!"
      tag: "window_berging"
      action_window_pause: "berging_window_pause"
      reason: "{% if (states('sensor.gram_water_berging_diff_outside') | float >= 0.5 %} Te vochtig binnen. {% endif %}"
  - service: script.notify_madouce_windows
    data_template:
      message: "Vocht berging {{states('sensor.gram_water_berging')}} g/m³. Buiten: {{states('sensor.gram_water_outside')}} g/m³.<br>Temp berging: {{states('sensor.berging_temperature')}} °C. Buiten: {{states('sensor.temp_leuven24_wunderground')}} °C."
      title: "Open het raam van de berging!"
      tag: "window_berging"
      action_window_pause: "berging_window_pause"
      reason: "{% if (states('sensor.gram_water_berging_diff_outside') | float >= 0.5 %} Te vochtig binnen. {% endif %}"
  mode: single


- id: 'ramen -  open raam badkamer (Bart en Madouce)'
  alias: 🪟 ramen -  open raam badkamer (Bart en Madouce)
  description: ''
  trigger:
  - platform: time_pattern
    minutes: /15
  condition:
  - condition: state
    entity_id: input_boolean.badkamer_raam_moet_open
    state: 'on'
  - condition: state
    entity_id: binary_sensor.badkamer_raam_sensor
    state: 'off'
  - condition: state
    entity_id: input_boolean.badkamer_window_pause
    state: 'off'
  action:
  - service: script.notify_bart_windows
    data_template:
      message: "Vocht badkamer: {{states('sensor.gram_water_badkamer')}} g/m³. Buiten: {{states('sensor.gram_water_outside')}} g/m³.<br>Temp badkamer: {{states('sensor.badkamer_temperature')}} °C. Buiten: {{states('sensor.temp_leuven24_wunderground')}} °C."
      title: "Open het raam van de badkamer!"
      tag: "window_badkamer"
      action_window_pause: "badkamer_window_pause"
      reason: "{% if (states('sensor.gram_water_badkamer_diff_outside') | float >= 0.5 %} Te vochtig binnen. {% endif %}"
  - service: script.notify_madouce_windows
    data_template:
      message: "Vocht badkamer: {{states('sensor.gram_water_badkamer')}} g/m³. Buiten: {{states('sensor.gram_water_outside')}} g/m³.<br>Temp badkamer: {{states('sensor.badkamer_temperature')}} °C. Buiten: {{states('sensor.temp_leuven24_wunderground')}} °C."
      title: "Open het raam van de badkamer!"
      tag: "window_badkamer"
      action_window_pause: "badkamer_window_pause"
      reason: "{% if (states('sensor.gram_water_badkamer_diff_outside') | float >= 0.5 %} Te vochtig binnen. {% endif %}"
  mode: single

- id: 'ramen -  open raam kamer Alunya (Bart en Madouce)'
  alias: 🪟 ramen -  open raam kamer Alunya (Bart en Madouce)
  description: ''
  trigger:
  - platform: time_pattern
    minutes: /15
  condition:
  - condition: state
    entity_id: input_boolean.kamer_alunya_raam_moet_open
    state: 'on'
  - condition: and
    conditions:    
    - condition: state
      entity_id: binary_sensor.kamer_alunya_raam_sensor
      state: 'off'
    - condition: state
      entity_id: binary_sensor.kamer_alunya_schuifraam_sensor
      state: 'off'      
  - condition: state
    entity_id: input_boolean.kamer_alunya_window_pause
    state: 'off'
  action:
  - service: script.notify_bart_windows
    data_template:
      message: "Vocht kamer Alunya: {{states('sensor.gram_water_kamer_alunya')}} g/m³. Buiten: {{states('sensor.gram_water_outside')}} g/m³.<br>Temp kamer Alunya: {{states('sensor.kamer_alunya_temperature')}} °C. Buiten: {{states('sensor.temp_leuven24_wunderground')}} °C."
      title: "Open het raam van Alunya!"
      tag: "window_kamer_alunya"
      action_window_pause: "kamer_alunya_window_pause"
      reason: "{% if (states('sensor.gram_water_kamer_alunya_diff_outside') | float >= 0.5 %} Te vochtig binnen. {% endif %}"
  - service: script.notify_madouce_windows
    data_template:
      message: "Vocht kamer Alunya: {{states('sensor.gram_water_kamer_alunya')}} g/m³. Buiten: {{states('sensor.gram_water_outside')}} g/m³.<br>Temp kamer Alunya: {{states('sensor.kamer_alunya_temperature')}} °C. Buiten: {{states('sensor.temp_leuven24_wunderground')}} °C."
      title: "Open het raam van Alunya!"
      tag: "window_kamer_alunya"
      action_window_pause: "kamer_alunya_window_pause"
      reason: "{% if (states('sensor.gram_water_kamer_alunya_diff_outside') | float >= 0.5 %} Te vochtig binnen. {% endif %}"
  mode: single

- id: 'ramen -  open raam master bedroom (Bart en Madouce)'
  alias: 🪟 ramen -  open raam master bedroom (Bart en Madouce)
  description: ''
  trigger:
  - platform: time_pattern
    minutes: /15
  condition:
  - condition: state
    entity_id: input_boolean.master_bedroom_raam_moet_open
    state: 'on'
  - condition: state
    entity_id: binary_sensor.master_bedroom_raam_sensor
    state: 'off'
  - condition: state
    entity_id: input_boolean.master_bedroom_window_pause
    state: 'off'
  action:
  - service: script.notify_bart_windows
    data_template:
      message: "Vocht master bedroom: {{states('sensor.gram_water_master_bedroom')}} g/m³. Buiten: {{states('sensor.gram_water_outside')}} g/m³.<br>Temp master bedroom: {{states('sensor.master_bedroom_temperature')}} °C. Buiten: {{states('sensor.temp_leuven24_wunderground')}} °C."
      title: Open het raam van de master bedroom!
      tag: "window_master_bedroom"
      action_window_pause: "master_bedroom_window_pause"
      reason: "{% if (states('sensor.gram_water_master_bedroom_diff_outside') | float >= 0.5 %} Te vochtig binnen. {% endif %}"
  - service: script.notify_madouce_windows
    data_template:
      message: "Vocht master bedroom: {{states('sensor.gram_water_master_bedroom')}} g/m³. Buiten: {{states('sensor.gram_water_outside')}} g/m³.<br>Temp master bedroom: {{states('sensor.master_bedroom_temperature')}} °C. Buiten: {{states('sensor.temp_leuven24_wunderground')}} °C."
      title: Open het raam van de master bedroom!
      tag: "window_master_bedroom"
      action_window_pause: "master_bedroom_window_pause"
      reason: "{% if (states('sensor.gram_water_master_bedroom_diff_outside') | float >= 0.5 %} Te vochtig binnen. {% endif %}"
  mode: single


############################################
# Clear notifications when window is opened
############################################

- id: 'ramen -  open raam living room - clear notification (Bart en Madouce)'
  alias: 🪟 ramen -  open raam living room - clear notification (Bart en Madouce)
  description: ''
  trigger:
    - platform: state
      entity_id: binary_sensor.keuken_raam_sensor
#     from: 'off'
      to: 'on'
    - platform: state
      entity_id: binary_sensor.living_room_oprit_raam_sensor
#     from: 'off'
      to: 'on'
    - platform: state
      entity_id: binary_sensor.living_room_tuin_raam_sensor
#     from: 'off'
      to: 'on'
    - platform: state
      entity_id: input_boolean.living_room_window_pause
      to: 'on'            
  condition:
  - condition: state
    entity_id: input_boolean.living_room_raam_moet_open
    state: 'on'
  - condition: time
    after: '7:0:0'
    before: '23:30:00'
  action:
  - service: notify.bart_phone
    data:
      message: "clear_notification"
      data:
        tag: window_living_room
  - service: notify.madouce_phone
    data:
      message: "clear_notification"
      data:
        tag: window_living_room
  mode: single

- id: 'ramen -  open raam kamer Amilya - clear notification (Bart en Madouce)'
  alias: 🪟 ramen -  open raam kamer Amilya - clear notification (Bart en Madouce)
  description: ''
  trigger:
    - platform: state
      entity_id: binary_sensor.kamer_amilya_raam_sensor
      from: 'off'
      to: 'on'
    - platform: state
      entity_id: input_boolean.kamer_amilya_window_pause
      to: 'on'                  
  condition:
  - condition: state
    entity_id: input_boolean.kamer_amilya_raam_moet_open
    state: 'on'
  - condition: time
    after: '7:0:0'
    before: '23:30:00'
  action:
  - service: notify.bart_phone
    data:
      message: "clear_notification"
      data:
        tag: window_kamer_amilya
  - service: notify.madouce_phone
    data:
      message: "clear_notification"
      data:
        tag: window_kamer_amilya
  mode: single

- id: 'ramen -  open raam veranda - clear notification (Bart en Madouce)'
  alias: 🪟 ramen -  open raam veranda - clear notification (Bart en Madouce)
  description: ''
  trigger:
    - platform: state
      entity_id: binary_sensor.veranda_schuifraam_sensor
      from: 'off'
      to: 'on'
    - platform: state
      entity_id: input_boolean.veranda_window_pause
      to: 'on'                        
  condition:
  - condition: state
    entity_id: input_boolean.veranda_schuifraam_moet_open
    state: 'on'
  - condition: time
    after: '7:0:0'
    before: '23:30:00'
  action:
  - service: notify.bart_phone
    data:
      message: "clear_notification"
      data:
        tag: window_veranda
  - service: notify.madouce_phone
    data:
      message: "clear_notification"
      data:
        tag: window_veranda
  mode: single

- id: 'ramen -  open raam berging  - clear notification (Bart en Madouce)'
  alias: 🪟 ramen -  open raam berging - clear notification (Bart en Madouce)
  description: ''
  trigger:
    - platform: state
      entity_id: binary_sensor.berging_raam_sensor
      from: 'off'
      to: 'on'
    - platform: state
      entity_id: input_boolean.berging_window_pause
      to: 'on'      
  condition:
  - condition: state
    entity_id: input_boolean.berging_raam_moet_open
    state: 'on'
  - condition: time
    after: '7:0:0'
    before: '23:30:00'
  action:
  - service: notify.bart_phone
    data:
      message: "clear_notification"
      data:
        tag: window_berging
  - service: notify.madouce_phone
    data:
      message: "clear_notification"
      data:
        tag: window_berging
  mode: single

- id: 'ramen -  open raam badkamer - clear notification (Bart en Madouce)'
  alias: 🪟 ramen -  open raam badkamer - clear notification (Bart en Madouce)
  description: ''
  trigger:
    - platform: state
      entity_id: binary_sensor.badkamer_raam_sensor
      from: 'off'
      to: 'on'
    - platform: state
      entity_id: input_boolean.badkamer_window_pause
      to: 'on'                              
  condition:
  - condition: state
    entity_id: input_boolean.badkamer_raam_moet_open
    state: 'on'
  - condition: time
    after: '7:0:0'
    before: '23:30:00'
  action:
  - service: notify.bart_phone
    data:
      message: "clear_notification"
      data:
        tag: window_badkamer
  - service: notify.madouce_phone
    data:
      message: "clear_notification"
      data:
        tag: window_badkamer
  mode: single

- id: 'ramen -  open raam kamer Alunya - clear notification (Bart en Madouce)'
  alias: 🪟 ramen -  open raam kamer Alunya - clear notification (Bart en Madouce)
  description: ''
  trigger:
    - platform: state
      entity_id: binary_sensor.kamer_alunya_raam_sensor
#     from: 'off'
      to: 'on'
    - platform: state
      entity_id: binary_sensor.kamer_alunya_schuifraam_sensor
#     from: 'off'
      to: 'on'
    - platform: state
      entity_id: input_boolean.kamer_alunya_window_pause
      to: 'on'                                    
  condition:
  - condition: state
    entity_id: input_boolean.kamer_alunya_raam_moet_open
    state: 'on'
  - condition: time
    after: '7:0:0'
    before: '23:30:00'
  action:
  - service: notify.bart_phone
    data:
      message: "clear_notification"
      data:
        tag: window_kamer_alunya
  - service: notify.madouce_phone
    data:
      message: "clear_notification"
      data:
        tag: window_kamer_alunya
  mode: single

- id: 'ramen -  open raam master bedroom  - clear notification (Bart en Madouce)'
  alias: 🪟 ramen -  open raam master bedroom - clear notification (Bart en Madouce)
  description: ''
  trigger:
    - platform: state
      entity_id: binary_sensor.master_bedroom_raam_sensor
      from: 'off'
      to: 'on'
    - platform: state
      entity_id: input_boolean.master_bedroom_window_pause
      to: 'on'                                    
  condition:
  - condition: state
    entity_id: input_boolean.master_bedroom_raam_moet_open
    state: 'on'
  - condition: time
    after: '7:0:0'
    before: '23:30:00'
  action:
  - service: notify.bart_phone
    data:
      message: "clear_notification"
      data:
        tag: window_master_bedroom
  - service: notify.madouce_phone
    data:
      message: "clear_notification"
      data:
        tag: window_master_bedroom
  mode: single