############################ Table of Contents ############################ 
#
#  check to CLOSE windows
#   🪟 ramen - check living (moet dicht)
#   🪟 ramen - check kamer Amilya (moet dicht)
#   🪟 ramen - check veranda (moet dicht)
#   🪟 ramen - check berging (moet dicht)
#   🪟 ramen - check badkamer (moet dicht)
#   🪟 ramen - check gang (moet dicht)
#   🪟 ramen - check kamer Alunya (moet dicht)
#   🪟 ramen - check master bedroom (moet dicht)
#
###########################################################################

#    De laagste temperatuur morgen (dus de volgende nacht) =
#    value_template: "{{ state_attr('weather.eikenbos', 'forecast')[0].templow }}"

# gekopieerd naar automations.yml en was ok

automation:

- alias: 🪟 ramen - check living (moet dicht)
  id: 'a53a248b-91d0-4700-b42d-60c3f2497ae1'
  description: ''
  trigger:
  - platform: state
    entity_id: sensor.gram_water_outside
  - platform: state
    entity_id: sensor.temp_leuven24_wunderground
  - platform: state
    entity_id: sensor.gram_water_living
  condition:
  - condition: template
    value_template: >
      {{trigger.to_state is not none and
        trigger.from_state is not none and
        trigger.to_state.state != trigger.from_state.state}}
  - condition: or
    conditions:    
    - condition: numeric_state
      entity_id: sensor.living_temperature
      below: '17'            
    - condition: numeric_state
      entity_id: sensor.living_heating
      above: '0'
    - condition: template
      value_template: "{{ (states('sensor.temp_leuven24_wunderground') | float) < 15 }}"
    - condition: template
      value_template: "{{ states('sensor.gram_water_living_diff_outside') | float < 0.5 }}"
 #    - condition: and      
 #      conditions:
 #        - condition: time
 #          after: '22:00'
 #        - condition: template
 #          value_template: "{{ (state_attr('weather.eikenbos', 'forecast')[0].templow) >= 14 }}"
  action:
  - service: input_boolean.turn_on
    target:
      entity_id: input_boolean.living_raam_moet_dicht
  - service: input_boolean.turn_off
    target:
      entity_id: input_boolean.living_raam_moet_open      
  mode: restart

- alias: 🪟 ramen - check kamer Amilya (moet dicht)
  id: '7c37f7aa-e787-4dd7-a843-bb37f23273f1'
  description: ''
  trigger:
  - platform: state
    entity_id: sensor.gram_water_outside
  - platform: state
    entity_id: sensor.temp_leuven24_wunderground    
  - platform: state
    entity_id: sensor.gram_water_kamer_amilya
  condition:
  - condition: template
    value_template: >
      {{trigger.to_state is not none and
        trigger.from_state is not none and
        trigger.to_state.state != trigger.from_state.state}}
  - condition: or
    conditions:
    - condition: numeric_state
      entity_id: sensor.kamer_amilya_temperature
      below: '17'            
    - condition: numeric_state
      entity_id: sensor.kamer_amilya_heating
      above: '0'
    - condition: template
      value_template: "{{ (states('sensor.temp_leuven24_wunderground') | float) < 15 }}"
    - condition: template
      value_template: "{{ states('sensor.gram_water_kamer_amilya_diff_outside') | float < 0.5 }}"             
  action:
  - service: input_boolean.turn_on
    target:
      entity_id: input_boolean.kamer_amilya_raam_moet_dicht
  - service: input_boolean.turn_off
    target:
      entity_id: input_boolean.kamer_amilya_raam_moet_open
  mode: restart

- alias: 🪟 ramen - check veranda (moet dicht)
  id: 'c1dba9cc-cff2-4c67-a8b9-62173ac2b993'
  description: ''
  trigger:
  - platform: state
    entity_id: sensor.gram_water_outside
  - platform: state
    entity_id: sensor.temp_leuven24_wunderground    
  - platform: state
    entity_id: sensor.gram_water_veranda    
  condition:
  - condition: template
    value_template: >
      {{trigger.to_state is not none and
        trigger.from_state is not none and
        trigger.to_state.state != trigger.from_state.state}}
  - condition: or
    conditions:
    - condition: numeric_state
      entity_id: sensor.veranda_temperature
      below: '17'            
    - condition: numeric_state
      entity_id: sensor.veranda_heating
      above: '0'
    - condition: template
      value_template: "{{ (states('sensor.temp_leuven24_wunderground') | float) < 16 }}"
    - condition: template
      value_template: "{{ states('sensor.gram_water_veranda_diff_outside') | float < 0.5 }}"             
  action:
  - service: input_boolean.turn_on
    target:
      entity_id: input_boolean.veranda_schuifraam_moet_dicht
  - service: input_boolean.turn_off
    target:
      entity_id: input_boolean.veranda_schuifraam_moet_open
  mode: restart

- alias: 🪟 ramen - check berging (moet dicht)
  id: '890e3208-5bfd-453c-b784-fcbd09f3db98'
  description: ''
  trigger:
  - platform: state
    entity_id: sensor.gram_water_outside
  - platform: state
    entity_id: sensor.temp_leuven24_wunderground    
  - platform: state
    entity_id: sensor.gram_water_berging  
  condition:
  - condition: template
    value_template: >
      {{trigger.to_state is not none and
        trigger.from_state is not none and
        trigger.to_state.state != trigger.from_state.state}}
  - condition: or
    conditions:
    - condition: numeric_state
      entity_id: sensor.berging_temperature
      below: '17'            
    - condition: numeric_state
      entity_id: sensor.berging_heating
      above: '0'
    - condition: template
      value_template: "{{ (states('sensor.temp_leuven24_wunderground') | float) < 16 }}"
    - condition: template
      value_template: "{{ states('sensor.gram_water_berging_diff_outside') | float < 0.5 }}"             
  action:
  - service: input_boolean.turn_on
    target:
      entity_id: input_boolean.berging_raam_moet_dicht
  - service: input_boolean.turn_off
    target:
      entity_id: input_boolean.berging_raam_moet_open
  mode: restart

- alias: 🪟 ramen - check badkamer (moet dicht)
  id: '2d5600a4-1dac-429b-8663-b954d4002a62'
  description: ''
  trigger:
  - platform: state
    entity_id: sensor.gram_water_outside
  - platform: state
    entity_id: sensor.temp_leuven24_wunderground
  - platform: state
    entity_id: sensor.gram_water_badkamer    
  condition:
  - condition: template
    value_template: >
      {{trigger.to_state is not none and
        trigger.from_state is not none and
        trigger.to_state.state != trigger.from_state.state}}
  - condition: or
    conditions:
    - condition: numeric_state
      entity_id: sensor.badkamer_temperature
      below: '16'            
    - condition: numeric_state
      entity_id: sensor.badkamer_heating
      above: '0'
    - condition: template
      value_template: "{{ (states('sensor.temp_leuven24_wunderground') | float) < 10 }}"
    - condition: template
      value_template: "{{ states('sensor.gram_water_badkamer_diff_outside') | float < 0.5 }}"             
  action:
  - service: input_boolean.turn_on
    target:
      entity_id: input_boolean.badkamer_raam_moet_dicht
  - service: input_boolean.turn_off
    target:
      entity_id: input_boolean.badkamer_raam_moet_open
  mode: restart

- alias: 🪟 ramen - check gang (moet dicht)
  id: '7f47085a-c4b8-4129-a83d-0710297bf8aa'
  description: ''
  trigger:
  - platform: state
    entity_id: sensor.gram_water_outside
  - platform: state
    entity_id: sensor.temp_leuven24_wunderground
  - platform: state
    entity_id: sensor.gram_water_gang   
  condition:
  - condition: template
    value_template: >
      {{trigger.to_state is not none and
        trigger.from_state is not none and
        trigger.to_state.state != trigger.from_state.state}}
  - condition: or
    conditions:
    - condition: numeric_state
      entity_id: sensor.gang_temperature
      below: '17'            
    - condition: numeric_state
      entity_id: sensor.gang_heating
      above: '0'
    - condition: template
      value_template: "{{ (states('sensor.temp_leuven24_wunderground') | float) < 16 }}"    
    - condition: template
      value_template: "{{ states('sensor.gram_water_gang_diff_outside') | float < 0.5 }}"  
  action:
  - service: input_boolean.turn_on
    target:
      entity_id: input_boolean.gang_raam_moet_dicht
  - service: input_boolean.turn_off
    target:
      entity_id: input_boolean.gang_raam_moet_open
  mode: restart

- alias: 🪟 ramen - check kamer Alunya (moet dicht)
  id: '1037bc55-e21a-4003-ac9c-e9722cbed3ed'
  description: ''
  trigger:
  - platform: state
    entity_id: sensor.gram_water_outside
  - platform: state
    entity_id: sensor.temp_leuven24_wunderground
  - platform: state
    entity_id: sensor.gram_water_kamer_alunya    
  condition:
  - condition: template
    value_template: >
      {{trigger.to_state is not none and
        trigger.from_state is not none and
        trigger.to_state.state != trigger.from_state.state}}
  - condition: or
    conditions:
    - condition: numeric_state
      entity_id: sensor.kamer_alunya_temperature
      below: '17'            
    - condition: numeric_state
      entity_id: sensor.kamer_alunya_heating
      above: '0'
    - condition: template
      value_template: "{{ (states('sensor.temp_leuven24_wunderground') | float) < 15 }}"        
    - condition: template
      value_template: "{{ states('sensor.gram_water_kamer_alunya_diff_outside') | float < 0.5 }}"
  action:
  - service: input_boolean.turn_on
    target:
      entity_id: input_boolean.kamer_alunya_raam_moet_dicht
  - service: input_boolean.turn_off
    target:
      entity_id: input_boolean.kamer_alunya_raam_moet_open
  mode: restart

- alias: 🪟 ramen - check master bedroom (moet dicht)
  id: 'e2e581a2-52be-4625-aed3-619da8328767'
  description: ''
  trigger:
  - platform: state
    entity_id: sensor.gram_water_outside
  - platform: state
    entity_id: sensor.temp_leuven24_wunderground
  - platform: state
    entity_id: sensor.gram_water_master_bedroom    
  condition:
  - condition: template
    value_template: >
      {{trigger.to_state is not none and
        trigger.from_state is not none and
        trigger.to_state.state != trigger.from_state.state}}
  - condition: or
    conditions:
    - condition: numeric_state
      entity_id: sensor.master_bedroom_temperature
      below: '14.5'            
    - condition: numeric_state
      entity_id: sensor.master_bedroom_heating
      above: '0'
    - condition: template
      value_template: "{{ states('sensor.temp_leuven24_wunderground') | float < 12 }}"
    - condition: template
      value_template: "{{ states('sensor.gram_water_master_bedroom_diff_outside') | float < 0.5 }}"             
  action:
  - service: input_boolean.turn_on
    target:
      entity_id: input_boolean.master_bedroom_raam_moet_dicht
  - service: input_boolean.turn_off
    target:
      entity_id: input_boolean.master_bedroom_raam_moet_open
  mode: restart


