############################ Table of Contents ############################ 
#
#  Actions to pause window notifications
# 
###########################################################################

automation:

- id: 'living_room_window_pause'
  alias: "living_room_window_pause"
  trigger:
  - platform: event
    event_type: mobile_app_notification_action
    event_data:
      action: living_room_window_pause
  action:
  - service: input_boolean.turn_on
    target:
      entity_id: input_boolean.living_room_window_pause  

- id: 'kamer_amilya_window_pause'
  alias: "kamer_amilya_window_pause"
  trigger:
  - platform: event
    event_type: mobile_app_notification_action
    event_data:
      action: kamer_amilya_window_pause
  action:
  - service: input_boolean.turn_on
    target:
      entity_id: input_boolean.kamer_amilya_window_pause  

- id: 'veranda_window_pause'
  alias: "veranda_window_pause"
  trigger:
  - platform: event
    event_type: mobile_app_notification_action
    event_data:
      action: veranda_window_pause
  action:
  - service: input_boolean.turn_on
    target:
      entity_id: input_boolean.veranda_window_pause  

- id: 'badkamer_window_pause'
  alias: "badkamer_window_pause"
  trigger:
  - platform: event
    event_type: mobile_app_notification_action
    event_data:
      action: badkamer_window_pause
  action:
  - service: input_boolean.turn_on
    target:
      entity_id: input_boolean.badkamer_window_pause  

- id: 'berging_window_pause'
  alias: "berging_window_pause"
  trigger:
  - platform: event
    event_type: mobile_app_notification_action
    event_data:
      action: berging_window_pause
  action:
  - service: input_boolean.turn_on
    target:
      entity_id: input_boolean.berging_window_pause  

- id: 'kamer_alunya_window_pause'
  alias: "kamer_alunya_window_pause"
  trigger:
  - platform: event
    event_type: mobile_app_notification_action
    event_data:
      action: kamer_alunya_window_pause
  action:
  - service: input_boolean.turn_on
    target:
      entity_id: input_boolean.kamer_alunya_window_pause  

- id: 'master_bedroom_window_pause'
  alias: " master_bedroom_window_pause"
  trigger:
  - platform: event
    event_type: mobile_app_notification_action
    event_data:
      action: master_bedroom_window_pause
  action:
  - service: input_boolean.turn_on
    target:
      entity_id: input_boolean.master_bedroom_window_pause  

#######################################
###  reset pauze toggles after 2 hours
#######################################

- id: "zet pauze toggle living room naar OFF na 2 uren"  
  alias: " zet pauze toggle living room naar OFF na 2 uren"
  description: 'zet pauze toggle living room naar OFF na 2 uren'
  mode: single
  trigger:
    - platform: state
      entity_id: input_boolean.living_room_window_pause
      to: 'on'
  condition: []
  action:
    - wait_template: '2:00:00'
    - service: input_boolean.turn_off
      target:
        entity_id: input_boolean.living_room_window_pause

- id: "zet pauze toggle kamer Amilya naar OFF na 2 uren"
  alias: " zet pauze toggle kamer Amilya naar OFF na 2 uren"
  description: 'zet pauze toggle kamer Amilya naar OFF na 2 uren'
  mode: single
  trigger:
    - platform: state
      entity_id: input_boolean.kamer_amilya_window_pause
      to: 'on'
  condition: []
  action:
    - wait_template: '2:00:00'
    - service: input_boolean.turn_off
      target:
        entity_id: input_boolean.kamer_amilya_window_pause

- id: "zet pauze toggle veranda naar OFF na 2 uren"
  alias: " zet pauze toggle veranda naar OFF na 2 uren"
  description: 'zet pauze toggle veranda naar OFF na 2 uren'
  mode: single
  trigger:
    - platform: state
      entity_id: input_boolean.veranda_window_pause
      to: 'on'
  condition: []
  action:
    - wait_template: '2:00:00'
    - service: input_boolean.turn_off
      target:
        entity_id: input_boolean.veranda_window_pause

- id: "zet pauze toggle berging naar OFF na 2 uren"
  alias: " zet pauze toggle berging naar OFF na 2 uren"
  description: 'zet pauze toggle berging naar OFF na 2 uren'
  mode: single
  trigger:
    - platform: state
      entity_id: input_boolean.berging_window_pause
      to: 'on'
  condition: []
  action:
    - wait_template: '2:00:00'
    - service: input_boolean.turn_off
      target:
        entity_id: input_boolean.berging_window_pause

- id: "zet pauze toggle badkamer naar OFF na 2 uren"
  alias: " zet pauze toggle badkamer naar OFF na 2 uren"
  description: 'zet pauze toggle badkamer naar OFF na 2 uren'
  mode: single
  trigger:
    - platform: state
      entity_id: input_boolean.badkamer_window_pause
      to: 'on'
  condition: []
  action:
    - wait_template: '2:00:00'
    - service: input_boolean.turn_off
      target:
        entity_id: input_boolean.badkamer_window_pause

        
- id: "zet pauze toggle kamer Alunya naar OFF na 2 uren"
  alias: " zet pauze toggle kamer Alunya naar OFF na 2 uren"
  description: 'zet pauze toggle kamer Alunya naar OFF na 2 uren'
  mode: single
  trigger:
    - platform: state
      entity_id: input_boolean.kamer_alunya_window_pause
      to: 'on'
  condition: []
  action:
    - wait_template: '2:00:00'
    - service: input_boolean.turn_off
      target:
        entity_id: input_boolean.kamer_alunya_window_pause

- id: "zet pauze toggle master bedroom naar OFF na 2 uren"
  alias: " zet pauze toggle master bedroom naar OFF na 2 uren"
  description: 'zet pauze toggle master bedroom naar OFF na 2 uren'
  mode: single
  trigger:
    - platform: state
      entity_id: input_boolean.master_bedroom_window_pause
      to: 'on'
  condition: []
  action:
    - wait_template: '2:00:00'
    - service: input_boolean.turn_off
      target:
        entity_id: input_boolean.master_bedroom_window_pause


#######################################
###  reset pauze toggles after 2 hours
#######################################


- id: "middernacht = reset schakelaars"
  alias: " middernacht = reset schakelaars"
  description: reset booleans voor openzetten ramen ivm vocht
  trigger:
    - platform: time
      at: '00:00'
  condition: []
  action:
    - service: input_boolean.turn_off
      target:
        entity_id:
          - input_boolean.living_room_window_pause
          - input_boolean.kamer_amilya_window_pause
          - input_boolean.veranda_window_pause
          - input_boolean.berging_window_pause
          - input_boolean.badkamer_window_pause
          - input_boolean.kamer_alunya_window_pause
          - input_boolean.master_bedroom_window_pause
  mode: single
