automation:

############################ Table of Contents ############################ 
#
###########################################################################

- alias: 🪟 Raam open = verwarming uit
  id: '6c852b1f-e1fe-413d-9447-49bc4e9e30ed'
  description: ''
  trigger:
  - platform: state
    entity_id: group.living_ramen
    to: 'on'
    id: living
    for:
      hours: 0
      minutes: 0
      seconds: 30
      milliseconds: 0
  - platform: state
    entity_id: binary_sensor.kamer_amilya_raam
    to: 'on'
    id: kamer_amilya
    for:
      hours: 0
      minutes: 0
      seconds: 30
      milliseconds: 0
  - platform: state
    entity_id: binary_sensor.veranda_schuifraam
    to: 'on'
    id: veranda
    for:
      hours: 0
      minutes: 0
      seconds: 30
      milliseconds: 0
  - platform: state
    entity_id: binary_sensor.berging_raam
    to: 'on'
    id: berging
    for:
      hours: 0
      minutes: 0
      seconds: 30
      milliseconds: 0
  - platform: state
    entity_id: binary_sensor.badkamer_raam_kantel
    to: 'on'
    id: badkamer
    for:
      hours: 0
      minutes: 0
      seconds: 30
      milliseconds: 0
  - platform: state
    entity_id: binary_sensor.badkamer_raam_wijd
    to: 'on'
    id: badkamer
    for:
      hours: 0
      minutes: 0
      seconds: 30
      milliseconds: 0
  - platform: state
    entity_id: group.kamer_alunya_ramen
    to: 'on'
    id: kamer_alunya
    for:
      hours: 0
      minutes: 0
      seconds: 30
      milliseconds: 0
  - platform: state
    entity_id: binary_sensor.master_bedroom_raam_kantel
    id: master_bedroom
    to: 'on'
    for:
      hours: 0
      minutes: 0
      seconds: 30
      milliseconds: 0
  - platform: state
    entity_id: binary_sensor.master_bedroom_raam_wijd
    id: master_bedroom
    to: 'on'
    for:
      hours: 0
      minutes: 0
      seconds: 30
      milliseconds: 0
  condition: []
  action:
  - choose:
    - conditions:
      - condition: trigger
        id: living
      sequence:
      - service: climate.set_hvac_mode
        target:
          entity_id: climate.living
        data:
          hvac_mode: 'off'
    - conditions:
      - condition: trigger
        id: kamer_amilya
      sequence:
      - service: climate.set_hvac_mode
        target:
          entity_id: climate.kamer_amilya
        data:
          hvac_mode: 'off'
    - conditions:
      - condition: trigger
        id: veranda
      sequence:
      - service: climate.set_hvac_mode
        target:
          entity_id: climate.veranda
        data:
          hvac_mode: 'off'
      - service: climate.set_hvac_mode
        target:
          entity_id: climate.gang
        data:
          hvac_mode: 'off'
    - conditions:
      - condition: trigger
        id: berging
      sequence:
      - service: climate.set_hvac_mode
        target:
          entity_id: climate.berging
        data:
          hvac_mode: 'off'
    - conditions:
      - condition: trigger
        id: badkamer
      sequence:
      - service: climate.set_hvac_mode
        target:
          entity_id: climate.badkamer
        data:
          hvac_mode: 'off'
    - conditions:
      - condition: trigger
        id: kamer_alunya
      sequence:
      - service: climate.set_hvac_mode
        target:
          entity_id: climate.kamer_alunya
        data:
          hvac_mode: 'off'
    - conditions:
      - condition: trigger
        id: master_bedroom
      sequence:
      - service: climate.set_hvac_mode
        target:
          entity_id: climate.master_bedroom
        data:
          hvac_mode: 'off'
  mode: parallel

- alias: 🪟 Raam dicht = verwarming automatisch
  id: 'bc2f6955-e69a-44fc-a5f4-eb6ef94e036d'
  description: ''
  trigger:
  - platform: state
    entity_id: group.living_ramen
    to: 'off'
    id: living
    for:
      hours: 0
      minutes: 5
      seconds: 0
      milliseconds: 0
  - platform: state
    entity_id: binary_sensor.kamer_amilya_raam
    to: 'off'
    id: kamer_amilya
    for:
      hours: 0
      minutes: 5
      seconds: 0
      milliseconds: 0
  - platform: state
    entity_id: binary_sensor.veranda_schuifraam
    to: 'off'
    id: veranda
    for:
      hours: 0
      minutes: 5
      seconds: 0
      milliseconds: 0
  - platform: state
    entity_id: binary_sensor.berging_raam
    to: 'off'
    id: berging
    for:
      hours: 0
      minutes: 5
      seconds: 0
      milliseconds: 0
  - platform: state
    entity_id: binary_sensor.badkamer_raam_kantel
    to: 'off'
    id: badkamer
    for:
      hours: 0
      minutes: 5
      seconds: 0
      milliseconds: 0
  - platform: state
    entity_id: binary_sensor.badkamer_raam_wijd
    to: 'off'
    id: badkamer
    for:
      hours: 0
      minutes: 5
      seconds: 0
      milliseconds: 0
  - platform: state
    entity_id: group.kamer_alunya_ramen
    to: 'off'
    id: kamer_alunya
    for:
      hours: 0
      minutes: 5
      seconds: 0
      milliseconds: 0
  - platform: state
    entity_id: binary_sensor.master_bedroom_raam_kantel
    id: master_bedroom
    to: 'off'
    for:
      hours: 0
      minutes: 5
      seconds: 0
      milliseconds: 0
  - platform: state
    entity_id: binary_sensor.master_bedroom_raam_wijd
    id: master_bedroom
    to: 'off'
    for:
      hours: 0
      minutes: 5
      seconds: 0
      milliseconds: 0
  condition: []
  action:
  - choose:
    - conditions:
        - condition: and
          conditions:
            - condition: trigger
              id: living
            - condition: state
              entity_id: group.living_ramen
              state: 'off'
      sequence:
      - service: climate.set_hvac_mode
        target:
          entity_id: climate.living
        data:
          hvac_mode: auto
    - conditions:
        - condition: and
          conditions:
            - condition: trigger
              id: kamer_amilya
            - condition: state
              entity_id: binary_sensor.kamer_amilya_raam
              state: 'off'
      sequence:
      - service: climate.set_hvac_mode
        target:
          entity_id: climate.kamer_amilya
        data:
          hvac_mode: auto
    - conditions:
        - condition: and
          conditions:
            - condition: trigger
              id: veranda
            - condition: state
              entity_id: binary_sensor.veranda_schuifraam
              state: 'off'
      sequence:
      - service: climate.set_hvac_mode
        target:
          entity_id: climate.veranda
        data:
          hvac_mode: auto
      - service: climate.set_hvac_mode
        target:
          entity_id: climate.gang
        data:
          hvac_mode: auto          
    - conditions:
        - condition: and
          conditions:
            - condition: trigger
              id: berging
            - condition: state
              entity_id: binary_sensor.berging_raam
              state: 'off'
      sequence:
      - service: climate.set_hvac_mode
        target:
          entity_id: climate.berging
        data:
          hvac_mode: auto
      - service: climate.set_hvac_mode
        target:
          entity_id: climate.gang
        data:
          hvac_mode: auto
    - conditions:
        - condition: and
          conditions:
            - condition: trigger
              id: badkamer
            - condition: state
              entity_id: binary_sensor.badkamer_raam_kantel
              state: 'off'
      sequence:
      - service: climate.set_hvac_mode
        target:
          entity_id: climate.badkamer
        data:
          hvac_mode: auto
    - conditions:
        - condition: and
          conditions:
            - condition: trigger
              id: kamer_alunya
            - condition: state
              entity_id: group.kamer_alunya_ramen
              state: 'off'
      sequence:
      - service: climate.set_hvac_mode
        target:
          entity_id: climate.kamer_alunya
        data:
          hvac_mode: auto
    - conditions:
        - condition: and
          conditions:
            - condition: trigger
              id: master_bedroom
            - condition: state
              entity_id: binary_sensor.master_bedroom_raam_kantel
              state: 'off'
      sequence:
      - service: climate.set_hvac_mode
        target:
          entity_id: climate.master_bedroom
        data:
          hvac_mode: auto
  mode: parallel
  max: 10

- alias: 🪟 Verwarming aan en raam open = verwarming uit
  id: '82a6a600-8657-457a-b45a-7fead7073079'
  # Het Tado tijdschema doet de chauffage aan gaan ook al heeft HA de chauffage uitgezet
  description: ''
  trigger:
  - platform: state
    entity_id: sensor.living_heating
    to: 'on'
    id: living
  - platform: state
    entity_id: sensor.kamer_amilya_heating
    to: 'on'
    id: kamer_amilya
  - platform: state
    entity_id: sensor.veranda_heating
    to: 'on'
    id: veranda
  - platform: state
    entity_id: sensor.berging_heating
    to: 'on'
    id: berging
  - platform: state
    entity_id: sensor.badkamer_heating
    to: 'on'
    id: badkamer
  - platform: state
    entity_id: sensor.kamer_alunya_heating
    to: 'on'
    id: kamer_alunya
  - platform: state
    entity_id: sensor.master_bedroom_heating
    id: master_bedroom
    to: 'on'
  condition: []
  action:
  - choose:
    - conditions:
        - condition: and
          conditions:
            - condition: trigger
              id: living
            - condition: state
              entity_id: group.living_ramen
              state: 'on'
      sequence:
      - service: climate.set_hvac_mode
        target:
          entity_id: climate.living
        data:
          hvac_mode: 'off'
    - conditions:
        - condition: and
          conditions:
            - condition: trigger
              id: kamer_amilya
            - condition: state
              entity_id: binary_sensor.kamer_amilya_raam
              state: 'on'
      sequence:
      - service: climate.set_hvac_mode
        target:
          entity_id: climate.kamer_amilya
        data:
          hvac_mode: 'off'
    - conditions:
        - condition: and
          conditions:
            - condition: trigger
              id: veranda
            - condition: state
              entity_id: binary_sensor.veranda_schuifraam
              state: 'on'
      sequence:
      - service: climate.set_hvac_mode
        target:
          entity_id: climate.veranda
        data:
          hvac_mode: 'off'
      - service: climate.set_hvac_mode
        target:
          entity_id: climate.gang
        data:
          hvac_mode: 'off'          
    - conditions:
        - condition: and
          conditions:
            - condition: trigger
              id: berging
            - condition: state
              entity_id: binary_sensor.berging_raam
              state: 'on'
      sequence:
      - service: climate.set_hvac_mode
        target:
          entity_id: climate.berging
        data:
          hvac_mode: 'off'
      - service: climate.set_hvac_mode
        target:
          entity_id: climate.gang
        data:
          hvac_mode: auto
    - conditions:
        - condition: and
          conditions:
            - condition: trigger
              id: badkamer
            - condition: state
              entity_id: binary_sensor.badkamer_raam_kantel
              state: 'on'
      sequence:
      - service: climate.set_hvac_mode
        target:
          entity_id: climate.badkamer
        data:
          hvac_mode: 'off'
    - conditions:
        - condition: and
          conditions:
            - condition: trigger
              id: kamer_alunya
            - condition: state
              entity_id: group.kamer_alunya_ramen
              state: 'on'
      sequence:
      - service: climate.set_hvac_mode
        target:
          entity_id: climate.kamer_alunya
        data:
          hvac_mode: 'off'
    - conditions:
        - condition: and
          conditions:
            - condition: trigger
              id: master_bedroom
            - condition: state
              entity_id: binary_sensor.master_bedroom_raam_kantel
              state: 'on'
      sequence:
      - service: climate.set_hvac_mode
        target:
          entity_id: climate.master_bedroom
        data:
          hvac_mode: 'off'
  mode: parallel
  max: 10
