automation:

############################ Table of Contents ############################ 
#
###########################################################################

- alias: Raam open = verwarming uit
  id: '6c852b1f-e1fe-413d-9447-49bc4e9e30ed'
  description: ''
  trigger:
  - platform: state
    entity_id: group.living_room_ramen
    to: 'on'
    id: living_room
    for:
      hours: 0
      minutes: 0
      seconds: 30
      milliseconds: 0
  - platform: state
    entity_id: binary_sensor.kamer_amilya_raam
    to: 'on'
    id: kamer_amilya
    for:
      hours: 0
      minutes: 0
      seconds: 30
      milliseconds: 0
  - platform: state
    entity_id: binary_sensor.veranda_schuifraam
    to: 'on'
    id: veranda
    for:
      hours: 0
      minutes: 0
      seconds: 30
      milliseconds: 0
  - platform: state
    entity_id: binary_sensor.berging_raam
    to: 'on'
    id: berging
    for:
      hours: 0
      minutes: 0
      seconds: 30
      milliseconds: 0
  - platform: state
    entity_id: binary_sensor.badkamer_raam_kantel
    to: 'on'
    id: badkamer
    for:
      hours: 0
      minutes: 0
      seconds: 30
      milliseconds: 0
  - platform: state
    entity_id: group.kamer_alunya_ramen
    to: 'on'
    id: kamer_alunya
    for:
      hours: 0
      minutes: 0
      seconds: 30
      milliseconds: 0
  - platform: state
    entity_id: binary_sensor.master_bedroom_raam_kantel
    id: master_bedroom
    to: 'on'
    for:
      hours: 0
      minutes: 0
      seconds: 30
      milliseconds: 0
  condition: []
  action:
  - choose:
    - conditions:
      - condition: trigger
        id: living_room
      sequence:
      - service: climate.set_hvac_mode
        target:
          entity_id: climate.living_room
        data:
          hvac_mode: 'off'
    - conditions:
      - condition: trigger
        id: veranda
      sequence:
      - service: climate.set_hvac_mode
        target:
          entity_id: climate.veranda
        data:
          hvac_mode: 'off'
    - conditions:
      - condition: trigger
        id: berging
      sequence:
      - service: climate.set_hvac_mode
        target:
          entity_id: climate.berging
        data:
          hvac_mode: 'off'
    - conditions:
      - condition: trigger
        id: badkamer
      sequence:
      - service: climate.set_hvac_mode
        target:
          entity_id: climate.badkamer
        data:
          hvac_mode: 'off'
    - conditions:
      - condition: trigger
        id: kamer_alunya
      sequence:
      - service: climate.set_hvac_mode
        target:
          entity_id: climate.kamer_alunya
        data:
          hvac_mode: 'off'
    - conditions:
      - condition: trigger
        id: master_bedroom
      sequence:
      - service: climate.set_hvac_mode
        target:
          entity_id: climate.master_bedroom
        data:
          hvac_mode: 'off'
  mode: parallel

- alias: Raam dicht = verwarming automatisch
  id: 'bc2f6955-e69a-44fc-a5f4-eb6ef94e036d'
  description: ''
  trigger:
  - platform: state
    entity_id: group.living_room_ramen
    to: 'off'
    id: living_room
    for:
      hours: 0
      minutes: 5
      seconds: 0
      milliseconds: 0
  - platform: state
    entity_id: binary_sensor.kamer_amilya_raam
    to: 'off'
    id: kamer_amilya
    for:
      hours: 0
      minutes: 5
      seconds: 0
      milliseconds: 0
  - platform: state
    entity_id: binary_sensor.veranda_schuifraam
    to: 'off'
    id: veranda
    for:
      hours: 0
      minutes: 5
      seconds: 0
      milliseconds: 0
  - platform: state
    entity_id: binary_sensor.berging_raam
    to: 'off'
    id: berging
    for:
      hours: 0
      minutes: 5
      seconds: 0
      milliseconds: 0
  - platform: state
    entity_id: binary_sensor.badkamer_raam_kantel
    to: 'off'
    id: badkamer
    for:
      hours: 0
      minutes: 5
      seconds: 0
      milliseconds: 0
  - platform: state
    entity_id: group.kamer_alunya_ramen
    to: 'off'
    id: kamer_alunya
    for:
      hours: 0
      minutes: 5
      seconds: 0
      milliseconds: 0
  - platform: state
    entity_id: binary_sensor.master_bedroom_raam_kantel
    id: master_bedroom
    to: 'off'
    for:
      hours: 0
      minutes: 5
      seconds: 0
      milliseconds: 0
  condition: []
  action:
  - choose:
    - conditions:
      - condition: trigger
        id: living_room
      sequence:
      - service: climate.set_hvac_mode
        target:
          entity_id: climate.living_room
        data:
          hvac_mode: auto
    - conditions:
      - condition: trigger
        id: veranda
      sequence:
      - service: climate.set_hvac_mode
        target:
          entity_id: climate.veranda
        data:
          hvac_mode: auto
    - conditions:
      - condition: trigger
        id: berging
      sequence:
      - service: climate.set_hvac_mode
        target:
          entity_id: climate.berging
        data:
          hvac_mode: auto
    - conditions:
      - condition: trigger
        id: badkamer
      sequence:
      - service: climate.set_hvac_mode
        target:
          entity_id: climate.badkamer
        data:
          hvac_mode: auto
    - conditions:
      - condition: trigger
        id: kamer_alunya
      sequence:
      - service: climate.set_hvac_mode
        target:
          entity_id: climate.kamer_alunya
        data:
          hvac_mode: auto
    - conditions:
      - condition: trigger
        id: master_bedroom
      sequence:
      - service: climate.set_hvac_mode
        target:
          entity_id: climate.master_bedroom
        data:
          hvac_mode: auto
  mode: parallel
  max: 10
