automation:

###################################
# Close windows notifications
# Close windows clear notifications
###################################

#####################################
# Close windows: send notifications
#####################################

- id: 'ramen - sluit raam living room (Bart en Madouce)'
  alias: 🪟 ramen - sluit raam living room (Bart en Madouce)
  description: ''
  trigger:
  - platform: time_pattern
    minutes: /15
  condition:
  - condition: state
    entity_id: input_boolean.living_room_raam_moet_dicht
    state: 'on'
  - condition: or
    conditions:    
    - condition: state
      entity_id: binary_sensor.keuken_raam_sensor
      state: 'on'
    - condition: state
      entity_id: binary_sensor.living_room_oprit_raam_sensor
      state: 'on'
    - condition: state
      entity_id: binary_sensor.living_room_tuin_raam_sensor
      state: 'on'
  - condition: state
    entity_id: input_boolean.living_room_window_pause
    state: 'off'
  action:
  - service: script.notify_bart_windows
    data_template:
      message: "Vocht living: {{states('sensor.gram_water_living_room')}} g/m³. Buiten: {{states('sensor.gram_water_outside')}} g/m³.<br>Temp living: {{states('sensor.living_room_temperature')}} °C. Buiten: {{states('sensor.temp_leuven24_wunderground')}} °C."
      title: "Sluit het raam van de living/keuken!"
      tag: "window_living_room"
      action_window_pause: "living_room_window_pause"
  - service: script.notify_madouce_windows
    data_template:
      message: "Vocht living: {{states('sensor.gram_water_living_room')}} g/m³. Buiten: {{states('sensor.gram_water_outside')}} g/m³.<br>Temp living: {{states('sensor.living_room_temperature')}} °C. Buiten: {{states('sensor.temp_leuven24_wunderground')}} °C."
      title: "Sluit het raam van de living/keuken!"
      tag: "window_living_room"
      action_window_pause: "living_room_window_pause"
  mode: single

- id: 'ramen - sluit raam Amilya (Bart en Madouce)'
  alias: '🪟 ramen - sluit raam Amilya (Bart en Madouce)'
  description: ''
  trigger:
  - platform: time_pattern
    minutes: /15
  condition:
  - condition: state
    entity_id: input_boolean.kamer_amilya_raam_moet_dicht
    state: 'on'
  - condition: or
    conditions:    
    - condition: state
      entity_id: binary_sensor.kamer_amilya_raam_sensor
      state: 'on'
    - condition: state
      entity_id: input_boolean.kamer_amylia_window_pause
      state: 'off'
  action:
  - service: script.notify_bart_windows
    data_template:
      message: "Vocht kamer Amilya: {{states('sensor.gram_water_kamer_amilya')}} g/m³. Buiten: {{states('sensor.gram_water_outside')}} g/m³.<br>Temp kamer Amilya: {{states('sensor.kamer_amilya_temperature')}} °C. Buiten: {{states('sensor.temp_leuven24_wunderground')}} °C."
      title: "Sluit het raam van Amilya!"
      tag: "window_kamer_amilya"
      action_window_pause: "kamer_amilya_window_pause"
  - service: script.notify_madouce_windows
    data_template:
      message: "Vocht kamer Amilya: {{states('sensor.gram_water_kamer_amilya')}} g/m³. Buiten: {{states('sensor.gram_water_outside')}} g/m³.<br>Temp kamer Amilya: {{states('sensor.kamer_amilya_temperature')}} °C. Buiten: {{states('sensor.temp_leuven24_wunderground')}} °C."
      title: "Sluit het raam van Amilya!"
      tag: "window_kamer_amilya"
      action_window_pause: "kamer_amilya_window_pause"
  mode: single

- id: 'ramen - sluit raam veranda (Bart en Madouce)'
  alias: 🪟 ramen - sluit raam veranda (Bart en Madouce)
  description: ''
  trigger:
  - platform: time_pattern
    minutes: /15
  condition:
  - condition: state
    entity_id: input_boolean.veranda_schuifraam_moet_dicht
    state: 'on'
  - condition: state
    entity_id: binary_sensor.veranda_schuifraam_sensor
    state: 'on'
  - condition: state
    entity_id: input_boolean.veranda_window_pause
    state: 'off'    
  action:
  - service: script.notify_bart_windows
    data_template:
      message: "Vocht veranda: {{states('sensor.gram_water_veranda')}} g/m³. Buiten: {{states('sensor.gram_water_outside')}} g/m³.<br>Temp veranda: {{states('sensor.veranda_temperature')}} °C. Buiten: {{states('sensor.temp_leuven24_wunderground')}} °C."
      title: "Sluit het raam van veranda!"
      tag: "window_veranda"
      action_window_pause: "veranda_window_pause"
  - service: script.notify_madouce_windows
    data_template:
      message: "Vocht veranda: {{states('sensor.gram_water_veranda')}} g/m³. Buiten: {{states('sensor.gram_water_outside')}} g/m³.<br>Temp veranda: {{states('sensor.veranda_temperature')}} °C. Buiten: {{states('sensor.temp_leuven24_wunderground')}} °C."
      title: "Sluit het raam van veranda!"
      tag: "window_veranda"
      action_window_pause: "veranda_window_pause"
  mode: single

- id: 'ramen - sluit raam berging (Bart en Madouce)'
  alias: 🪟 ramen - sluit raam berging (Bart en Madouce)
  description: ''
  trigger:
  - platform: time_pattern
    minutes: /15
  condition:
  - condition: state
    entity_id: input_boolean.berging_raam_moet_dicht
    state: 'on'
  - condition: state
    entity_id: binary_sensor.berging_raam_sensor
    state: 'on'
  - condition: state
    entity_id: input_boolean.berging_window_pause
    state: 'off'
  action:
  - service: script.notify_bart_windows
    data_template:
      message: "Vocht berging: {{states('sensor.gram_water_berging')}} g/m³. Buiten: {{states('sensor.gram_water_outside')}} g/m³.<br>Temp berging: {{states('sensor.berging_temperature')}} °C. Buiten: {{states('sensor.temp_leuven24_wunderground')}} °C."
      title: "Sluit het raam van de berging!"
      tag: "window_berging"
      action_window_pause: "berging_window_pause"
  - service: script.notify_madouce_windows
    data_template:
      message: "Vocht berging: {{states('sensor.gram_water_berging')}} g/m³. Buiten: {{states('sensor.gram_water_outside')}} g/m³.<br>Temp berging: {{states('sensor.berging_temperature')}} °C. Buiten: {{states('sensor.temp_leuven24_wunderground')}} °C."
      title: "Sluit het raam van de berging!"
      tag: "window_berging"
      action_window_pause: "berging_window_pause"
  mode: single

- id: 'ramen - sluit raam badkamer (Bart en Madouce)'
  alias: 🪟 ramen - sluit raam badkamer (Bart en Madouce)
  description: ''
  trigger:
  - platform: time_pattern
    minutes: /15
  condition:
  - condition: state
    entity_id: input_boolean.badkamer_raam_moet_dicht
    state: 'on'
  - condition: state
    entity_id: binary_sensor.badkamer_raam_sensor
    state: 'on'
  - condition: state
    entity_id: input_boolean.badkamer_window_pause
    state: 'off'
  action:
  - service: script.notify_bart_windows
    data_template:
      message: "Vocht badkamer: {{states('sensor.gram_water_badkamer')}} g/m³. Buiten: {{states('sensor.gram_water_outside')}} g/m³.<br>Temp badkamer: {{states('sensor.badkamer_temperature')}} °C. Buiten: {{states('sensor.temp_leuven24_wunderground')}} °C."
      title: "Sluit het raam van de badkamer!"
      tag: "window_badkamer"
      action_window_pause: "badkamer_window_pause"
  - service: script.notify_madouce_windows
    data_template:
      message: "Vocht badkamer: {{states('sensor.gram_water_badkamer')}} g/m³. Buiten: {{states('sensor.gram_water_outside')}} g/m³.<br>Temp badkamer: {{states('sensor.badkamer_temperature')}} °C. Buiten: {{states('sensor.temp_leuven24_wunderground')}} °C."
      title: "Sluit het raam van de badkamer!"
      tag: "window_badkamer"
      action_window_pause: "badkamer_window_pause"
  mode: single

- id: 'ramen - sluit raam Alunya (Bart en Madouce)'
  alias: '🪟 ramen - sluit raam Alunya (Bart en Madouce)'
  description: ''
  trigger:
  - platform: time_pattern
    minutes: /15
  condition:
  - condition: state
    entity_id: input_boolean.kamer_alunya_raam_moet_dicht
    state: 'on'
  - condition: or
    conditions:    
    - condition: state
      entity_id: binary_sensor.kamer_alunya_raam_sensor
      state: 'on'
    - condition: state
      entity_id: binary_sensor.kamer_alunya_schuifraam_sensor
      state: 'on'
  - condition: state
    entity_id: input_boolean.kamer_alunya_window_pause
    state: 'off'
  action:
  - service: script.notify_bart_windows
    data_template:
      message: "Vocht kamer Alunya: {{states('sensor.gram_water_kamer_alunya')}} g/m³. Buiten: {{states('sensor.gram_water_outside')}} g/m³.<br>Temp kamer Alunya: {{states('sensor.kamer_alunya_temperature')}} °C. Buiten: {{states('sensor.temp_leuven24_wunderground')}} °C."
      title: "Sluit het raam van Alunya!"
      tag: "window_kamer_alunya"
      action_window_pause: "kamer_alunya_window_pause"
  - service: script.notify_madouce_windows
    data_template:
      message: "Vocht kamer Alunya: {{states('sensor.gram_water_kamer_alunya')}} g/m³. Buiten: {{states('sensor.gram_water_outside')}} g/m³.<br>Temp kamer Alunya: {{states('sensor.kamer_alunya_temperature')}} °C. Buiten: {{states('sensor.temp_leuven24_wunderground')}} °C."
      title: "Sluit het raam van Alunya!"
      tag: "window_kamer_alunya"
      action_window_pause: "kamer_alunya_window_pause"
  mode: single

- id: 'ramen - sluit raam master bedroom (Bart en Madouce)'
  alias: '🪟 ramen - sluit raam master bedroom (Bart en Madouce)'
  description: ''
  trigger:
  - platform: time_pattern
    minutes: /15
  condition:
  - condition: state
    entity_id: input_boolean.master_bedroom_raam_moet_dicht
    state: 'on'
  - condition: state
    entity_id: binary_sensor.master_bedroom_raam_sensor
    state: 'on'
  - condition: state
    entity_id: input_boolean.master_bedroom_window_pause
    state: 'off'    
  action:
  - service: script.notify_bart_windows
    data_template:
      message: "Vocht master bedroom: {{states('sensor.gram_water_master_bedroom')}} g/m³. Buiten: {{states('sensor.gram_water_outside')}} g/m³.<br>Temp master bedroom: {{states('sensor.master_bedroom_temperature')}} °C. Buiten: {{states('sensor.temp_leuven24_wunderground')}} °C."
      title: "Sluit master bedroom raam!"
      tag: "window_master_bedroom"
      action_window_pause: "master_bedroom_window_pause"
  - service: script.notify_madouce_windows
    data_template:
      message: "Vocht master bedroom: {{states('sensor.gram_water_master_bedroom')}} g/m³. Buiten: {{states('sensor.gram_water_outside')}} g/m³.<br>Temp master bedroom: {{states('sensor.master_bedroom_temperature')}} °C. Buiten: {{states('sensor.temp_leuven24_wunderground')}} °C."
      title: "Sluit master bedroom raam!"
      tag: "window_master_bedroom"
      action_window_pause: "master_bedroom_window_pause"
  mode: single


############################################
# Clear notifications when window is closed
############################################

- id: 'ramen - sluit raam living room - clear notification (Bart en Madouce)'
  alias: 🪟 ramen - sluit raam living room - clear notification (Bart en Madouce)
  description: ''
  trigger:
    - platform: state
      entity_id: binary_sensor.keuken_raam_sensor
      from: 'on'
      to: 'off'
    - platform: state
      entity_id: binary_sensor.living_room_oprit_raam_sensor
      from: 'on'
      to: 'off'
    - platform: state
      entity_id: binary_sensor.living_room_tuin_raam_sensor
      from: 'on'
      to: 'off'
  condition:
  - condition: state
    entity_id: input_boolean.living_room_raam_moet_dicht
    state: 'on'
  - condition: time
    after: '7:0:0'
    before: '23:30:00'
  action:
  - service: notify.bart_phone
    data:
      message: "clear_notification"
      data:
        tag: window_living_room
  - service: notify.madouce_phone
    data:
      message: "clear_notification"
      data:
        tag: window_living_room
  mode: single


- id: 'ramen - sluit raam veranda - clear notification (Bart en Madouce)'
  alias: 🪟 ramen - sluit raam veranda - clear notification (Bart en Madouce)
  description: ''
  trigger:
    - platform: state
      entity_id: binary_sensor.veranda_schuifraam_sensor
      from: 'on'
      to: 'off'
  condition:
  - condition: state
    entity_id: input_boolean.veranda_schuifraam_moet_dicht
    state: 'on'
  - condition: time
    after: '7:0:0'
    before: '23:30:00'
  action:
  - service: notify.bart_phone
    data:
      message: "clear_notification"
      data:
        tag: window_veranda
  - service: notify.bart_phone
    data:
      message: "clear_notification"
      data:
        tag: window_berging        
  mode: single

- id: 'ramen - sluit raam berging  - clear notification (Bart en Madouce)'
  alias: 🪟 ramen - sluit raam berging - clear notification (Bart en Madouce)
  description: ''
  trigger:
    - platform: state
      entity_id: binary_sensor.berging_raam_sensor
      from: 'on'
      to: 'off'
  condition:
  - condition: state
    entity_id: input_boolean.berging_raam_moet_dicht
    state: 'on'
  - condition: time
    after: '7:0:0'
    before: '23:30:00'
  action:
  - service: notify.bart_phone
    data:
      message: "clear_notification"
      data:
        tag: window_berging
  - service: notify.madouce_phone
    data:
      message: "clear_notification"
      data:
        tag: window_berging
  mode: single


######################
### nog aan te passen hieronder
#######################

- id: 'ramen - sluit raam badkamer  - clear notification (Bart en Madouce)'
  alias: 🪟 ramen - sluit raam badkamer - clear notification (Bart en Madouce)
  description: ''
  trigger:
    - platform: state
      entity_id: binary_sensor.badkamer_raam_sensor
      from: 'on'
      to: 'off'
  condition:
  - condition: state
    entity_id: input_boolean.badkamer_raam_moet_dicht
    state: 'on'
  - condition: time
    after: '7:0:0'
    before: '23:30:00'
  action:
  - service: notify.bart_phone
    data:
      message: "clear_notification"
      data:
        tag: window_badkamer
  - service: notify.madouce_phone
    data:
      message: "clear_notification"
      data:
        tag: window_badkamer
  mode: single

- id: 'ramen - sluit raam kamer Alunya - clear notification (Bart en Madouce)'
  alias: 🪟 ramen - sluit raam kamer Alunya - clear notification (Bart en Madouce)
  description: ''
  trigger:
    - platform: state
      entity_id: binary_sensor.kamer_alunya_raam_sensor
#     from: 'on'
      to: 'off'
    - platform: state
      entity_id: binary_sensor.kamer_alunya_schuifraam_sensor
#     from: 'on'
      to: 'off'
  condition:
  - condition: state
    entity_id: input_boolean.kamer_alunya_raam_moet_dicht
    state: 'on'
  - condition: time
    after: '7:0:0'
    before: '23:30:00'
  action:
  - service: notify.bart_phone
    data:
      message: "clear_notification"
      data:
        tag: window_kamer_alunya
  - service: notify.madouce_phone
    data:
      message: "clear_notification"
      data:
        tag: window_kamer_alunya
  mode: single

- id: 'ramen - sluit raam master bedroom  - clear notification (Bart en Madouce)'
  alias: 🪟 ramen - sluit raam master bedroom - clear notification (Bart en Madouce)
  description: ''
  trigger:
    - platform: state
      entity_id: binary_sensor.master_bedroom_raam_sensor
      from: 'on'
      to: 'off'
  condition:
  - condition: state
    entity_id: input_boolean.master_bedroom_raam_moet_dicht
    state: 'on'
  - condition: time
    after: '7:0:0'
    before: '23:30:00'
  action:
  - service: notify.bart_phone
    data:
      message: "clear_notification"
      data:
        tag: window_master_bedroom
  - service: notify.madouce_phone
    data:
      message: "clear_notification"
      data:
        tag: window_master_bedroom
  mode: single