############################ Table of Contents ############################ 
#
#   Close windows notifications
#   🪟 ramen - sluit raam living (Bart en Madouce)
#   🪟 ramen - sluit raam kamer Amilya (Bart en Madouce)
#   🪟 ramen - sluit raam veranda (Bart en Madouce)
#   🪟 ramen - sluit raam berging (Bart en Madouce)
#   🪟 ramen - sluit raam badkamer (Bart en Madouce)
#   🪟 ramen - sluit raam kamer Alunya (Bart en Madouce)
#   🪟 ramen - sluit raam master bedroom (Bart en Madouce)
#
#   Close windows clear notifications
#   🪟 ramen - sluit raam living - clear notification (Bart en Madouce)
#   🪟 ramen - sluit raam kamer Amilya - clear notification (Bart en Madouce)
#   🪟 ramen - sluit raam veranda - clear notification (Bart en Madouce)
#   🪟 ramen - sluit raam berging - clear notification (Bart en Madouce)
#   🪟 ramen - sluit raam badkamer - clear notification (Bart en Madouce)
#   🪟 ramen - sluit raam kamer Alunya - clear notification (Bart en Madouce)
#   🪟 ramen - sluit raam master bedroom - clear notification (Bart en Madouce)
# 
#############################################################################

automation:

############################################
# Close windows: send notifications
############################################

- alias: 🪟 ramen - sluit raam living (Bart en Madouce)
  id: 'cec1c79b-5c6a-46a3-a3c7-5f981f7e18b3'
  description: ''
  trigger:
  - platform: time_pattern
    minutes: /15
  condition:
  - condition: state
    entity_id: input_boolean.living_raam_moet_dicht
    state: 'on'
  - condition: or
    conditions:    
    - condition: state
      entity_id: binary_sensor.keuken_raam
      state: 'on'
    - condition: state
      entity_id: binary_sensor.living_oprit_raam
      state: 'on'
    - condition: state
      entity_id: binary_sensor.living_tuin_raam
      state: 'on'
  - condition: state
    entity_id: input_boolean.living_window_pause
    state: 'off'
  action:
  - service: script.notify_bart_windows
    data_template:
      title: '{{title}}'
      message: '{{message}}'
      tag: '{{tag}}'
      action_window_pause: '{{action_window_pause}}' 
      reason: '{{reason}}'
  - service: script.notify_madouce_windows
    data_template:
      title: '{{title}}'
      message: '{{message}}'
      tag: '{{tag}}'
      action_window_pause: '{{action_window_pause}}' 
      reason: '{{reason}}'
  variables:
    message: "Vocht living: {{states('sensor.gram_water_living')}} g/m³. Buiten: {{states('sensor.gram_water_outside')}} g/m³.<br>Temp living: {{states('sensor.living_temperature')}} °C. Buiten: {{states('sensor.temp_leuven24_wunderground')}} °C."
    title: "Sluit raam van living/keuken!"
    tag: "window_living"
    action_window_pause: "living_window_pause"
    reason: "{% if (states('sensor.temp_leuven24_wunderground') | float) < 16 %} Te koud buiten. {% endif %}"  
  mode: single

- alias: 🪟 ramen - sluit raam kamer Amilya (Bart en Madouce)
  id: '47662219-10c5-4e7f-b319-e181eab91282'
  description: ''
  trigger:
  - platform: time_pattern
    minutes: /15
  condition:
  - condition: state
    entity_id: input_boolean.kamer_amilya_raam_moet_dicht
    state: 'on'
  - condition: state
    entity_id: binary_sensor.kamer_amilya_raam
    state: 'on'
  - condition: state
    entity_id: input_boolean.kamer_amilya_window_pause
    state: 'off'
  action:
  - service: script.notify_bart_windows
    data_template:
      title: '{{title}}'
      message: '{{message}}'
      tag: '{{tag}}'
      action_window_pause: '{{action_window_pause}}' 
      reason: '{{reason}}'
  - service: script.notify_madouce_windows
    data_template:
      title: '{{title}}'
      message: '{{message}}'
      tag: '{{tag}}'
      action_window_pause: '{{action_window_pause}}' 
      reason: '{{reason}}'
  variables:
    message: "Vocht kamer Amilya: {{states('sensor.gram_water_kamer_amilya')}} g/m³. Buiten: {{states('sensor.gram_water_outside')}} g/m³.<br>Temp kamer Amilya: {{states('sensor.kamer_amilya_temperature')}} °C. Buiten: {{states('sensor.temp_leuven24_wunderground')}} °C."
    title: "Sluit het raam van Amilya!"
    tag: "window_kamer_amilya"
    action_window_pause: "kamer_amilya_window_pause"
    reason: "{% if (states('sensor.temp_leuven24_wunderground') | float) < 16 %} Te koud buiten. {% endif %}"  
  mode: single

- alias: 🪟 ramen - sluit raam veranda (Bart en Madouce)
  id: '4c471c95-d235-4d41-bd08-490de91230df'
  description: ''
  trigger:
  - platform: time_pattern
    minutes: /15
  condition:
  - condition: state
    entity_id: input_boolean.veranda_schuifraam_moet_dicht
    state: 'on'
  - condition: state
    entity_id: binary_sensor.veranda_schuifraam
    state: 'on'
  - condition: state
    entity_id: input_boolean.veranda_window_pause
    state: 'off'    
  action:
  - service: script.notify_bart_windows
    data_template:
      title: '{{title}}'
      message: '{{message}}'
      tag: '{{tag}}'
      action_window_pause: '{{action_window_pause}}' 
      reason: '{{reason}}'
  - service: script.notify_madouce_windows
    data_template:
      title: '{{title}}'
      message: '{{message}}'
      tag: '{{tag}}'
      action_window_pause: '{{action_window_pause}}' 
      reason: '{{reason}}'
  variables:
    message: "Vocht veranda: {{states('sensor.gram_water_veranda')}} g/m³. Buiten: {{states('sensor.gram_water_outside')}} g/m³.<br>Vocht veranda: {{states('sensor.veranda_humidity')}} %. Buiten: {{states('sensor.humidity_leuven24_wunderground')}} %.<br>Temp veranda: {{states('sensor.veranda_temperature')}} °C. Buiten: {{states('sensor.temp_leuven24_wunderground')}} °C."
    title: "Sluit het raam van de veranda!"
    tag: "window_veranda"
    action_window_pause: "veranda_window_pause"
    reason: "{% if (states('sensor.temp_leuven24_wunderground') | float) < 16 %} Te koud buiten. {% endif %}"  
  mode: single

- alias: 🪟 ramen - sluit raam berging (Bart en Madouce)
  id: 'b82e4252-8dae-4a6e-9a48-8ace11815aa1'
  description: ''
  trigger:
  - platform: time_pattern
    minutes: /15
  condition:
  - condition: state
    entity_id: input_boolean.berging_raam_moet_dicht
    state: 'on'
  - condition: state
    entity_id: binary_sensor.berging_raam
    state: 'on'
  - condition: state
    entity_id: input_boolean.berging_window_pause
    state: 'off'
  action:
  - service: script.notify_bart_windows
    data_template:
      title: '{{title}}'
      message: '{{message}}'
      tag: '{{tag}}'
      action_window_pause: '{{action_window_pause}}' 
      reason: '{{reason}}'
  - service: script.notify_madouce_windows
    data_template:
      title: '{{title}}'
      message: '{{message}}'
      tag: '{{tag}}'
      action_window_pause: '{{action_window_pause}}' 
      reason: '{{reason}}'
  variables:
    message: "Vocht berging: {{states('sensor.gram_water_berging')}} g/m³. Buiten: {{states('sensor.gram_water_outside')}} g/m³.<br>Temp berging: {{states('sensor.berging_temperature')}} °C. Buiten: {{states('sensor.temp_leuven24_wunderground')}} °C."
    title: "Sluit het raam van de berging!"
    tag: "window_berging"
    action_window_pause: "berging_window_pause"
    reason: "{% if (states('sensor.temp_leuven24_wunderground') | float) < 16 %} Te koud buiten. {% endif %}"
  mode: single

- alias: 🪟 ramen - sluit raam badkamer (Bart en Madouce)
  id: 'b99dc88d-4bd9-486e-9a87-48bd09bcbd71'
  description: ''
  trigger:
  - platform: time_pattern
    minutes: /15
  condition:
  - condition: state
    entity_id: input_boolean.badkamer_raam_moet_dicht
    state: 'on'
  - condition: state
    entity_id: binary_sensor.badkamer_raam_kantel
    state: 'on'
  - condition: state
    entity_id: input_boolean.badkamer_window_pause
    state: 'off'
  action:
  - service: script.notify_bart_windows
    data_template:
      title: '{{title}}'
      message: '{{message}}'
      tag: '{{tag}}'
      action_window_pause: '{{action_window_pause}}' 
      reason: '{{reason}}'
  - service: script.notify_madouce_windows
    data_template:
      title: '{{title}}'
      message: '{{message}}'
      tag: '{{tag}}'
      action_window_pause: '{{action_window_pause}}' 
      reason: '{{reason}}'
  variables:
    title: "Sluit badkamer raam ({{states('sensor.badkamer_raam')}})!"    
    message: "Sinds openen raam: {{ ((states('sensor.badkamer_humidity') | float) - ((states('input_number.badkamer_initial_humidity_percentage') | float))) | round(1)}}%.<br> Vocht  badkamer: {{states('sensor.gram_water_badkamer')}} g/m³. Buiten: {{states('sensor.gram_water_outside')}} g/m³.<br>Vocht badkamer: {{states('sensor.badkamer_humidity')}} %. Buiten: {{states('sensor.humidity_leuven24_wunderground')}} %.<br>Temp badkamer: {{states('sensor.badkamer_temperature')}} °C. Buiten: {{states('sensor.temp_leuven24_wunderground')}} °C."
    tag: "window_badkamer"
    action_window_pause: "badkamer_window_pause"
    reason: "{% if states('sensor.badkamer_temperature') | float < 14 %} Wordt te koud binnen. 
      {% elif states('sensor.temp_leuven24_wunderground') | float < 10 %} Wordt te koud buiten.
      {% elif states('sensor.gram_water_badkamer_diff_outside') | float < 0.5 %} Te vochtig buiten.
      {% endif %}"
  mode: single

- alias: 🪟 ramen - sluit raam kamer Alunya (Bart en Madouce en Alunya)
  id: '2cc50202-cd87-49d9-ad25-21627a175597'
  description: ''
  trigger:
  - platform: time_pattern
    minutes: /15
  condition:
  - condition: state
    entity_id: input_boolean.kamer_alunya_raam_moet_dicht
    state: 'on'
  - condition: or
    conditions:    
    - condition: state
      entity_id: binary_sensor.kamer_alunya_raam
      state: 'on'
    - condition: state
      entity_id: binary_sensor.kamer_alunya_schuifraam
      state: 'on'
  - condition: state
    entity_id: input_boolean.kamer_alunya_window_pause
    state: 'off'
  action:
  - service: script.notify_bart_windows
    data_template:
      title: '{{title}}'
      message: '{{message}}'
      tag: '{{tag}}'
      action_window_pause: '{{action_window_pause}}' 
      reason: '{{reason}}'
  - service: script.notify_madouce_windows
    data_template:
      title: '{{title}}'
      message: '{{message}}'
      tag: '{{tag}}'
      action_window_pause: '{{action_window_pause}}' 
      reason: '{{reason}}'
  variables:
      message: "Vocht kamer Alunya: {{states('sensor.gram_water_kamer_alunya')}} g/m³. Buiten: {{states('sensor.gram_water_outside')}} g/m³.<br>Vocht kamer Alunya: {{states('sensor.kamer_alunya_humidity')}} %. Buiten: {{states('sensor.humidity_leuven24_wunderground')}} %.<br>Temp kamer Alunya: {{states('sensor.kamer_alunya_temperature')}} °C. Buiten: {{states('sensor.temp_leuven24_wunderground')}} °C."
      title: "Sluit het raam van Alunya!"
      tag: "window_kamer_alunya"
      action_window_pause: "kamer_alunya_window_pause"
      reason: "{% if (states('sensor.temp_leuven24_wunderground') | float) < 15 %} Te koud buiten. {% endif %}"  
  mode: single

- alias: 🪟 ramen - sluit raam master bedroom (Bart en Madouce)
  id: '851234af-52eb-4109-a2f0-415c410ce596'
  description: ''
  trigger:
  - platform: time_pattern
    minutes: /15
  condition:
  - condition: state
    entity_id: input_boolean.master_bedroom_raam_moet_dicht
    state: 'on'
  - condition: state
    entity_id: binary_sensor.master_bedroom_raam_kantel
    state: 'on'
  - condition: state
    entity_id: input_boolean.master_bedroom_window_pause
    state: 'off'    
  action:
  - service: script.notify_bart_windows
    data_template:
      title: '{{title}}'
      message: '{{message}}'
      tag: '{{tag}}'
      action_window_pause: '{{action_window_pause}}' 
      reason: '{{reason}}'
  - service: script.notify_madouce_windows
    data_template:
      title: '{{title}}'
      message: '{{message}}'
      tag: '{{tag}}'
      action_window_pause: '{{action_window_pause}}' 
      reason: '{{reason}}'
  variables:
    title: "Sluit master bedroom raam ({{states('sensor.master_bedroom_raam')}})!"
    message: "Vocht sinds openen raam: {{ ((states('sensor.master_bedroom_humidity') | float) - ((states('input_number.master_bedroom_initial_humidity_percentage') | float))) | round(1)}}% verschil.<br> Vocht master bedroom: {{states('sensor.gram_water_master_bedroom')}} g/m³. Buiten: {{states('sensor.gram_water_outside')}} g/m³.<br>Vocht master bedroom: {{states('sensor.master_bedroom_humidity')}} %. Buiten: {{states('sensor.humidity_leuven24_wunderground')}} %.<br>Temp master bedroom: {{states('sensor.master_bedroom_temperature')}} °C. Buiten: {{states('sensor.temp_leuven24_wunderground')}} °C."
    tag: "window_master_bedroom"
    action_window_pause: "master_bedroom_window_pause"
    reason: "{% if states('sensor.master_bedroom_temperature') | float < 14 %} Wordt te koud binnen. 
      {% elif states('sensor.temp_leuven24_wunderground') | float < 10 %} Wordt te koud buiten.
      {% endif %}"      
  mode: single


############################################
# Clear notifications when window is closed
############################################

- alias: 🪟 ramen - sluit raam living - clear notification (Bart en Madouce)
  id: '14873cee-f737-4de1-9f0c-7e3ee45cea02'
  description: ''
  trigger:
  - platform: state
    entity_id: binary_sensor.keuken_raam
    from: 'on'
    to: 'off'
  - platform: state
    entity_id: binary_sensor.living_oprit_raam
    from: 'on'
    to: 'off'
  - platform: state
    entity_id: binary_sensor.living_tuin_raam
    from: 'on'
    to: 'off'
  - platform: state
    entity_id: input_boolean.living_window_pause
    from: 'off'
    to: 'on'
  condition:
  - condition: state
    entity_id: input_boolean.living_raam_moet_dicht
    state: 'on'
  action:
  - service: notify.bart_phone
    data:
      message: "clear_notification"
      data:
        tag: window_living
  - service: notify.madouce_phone
    data:
      message: "clear_notification"
      data:
        tag: window_living
  mode: single

- alias: 🪟 ramen - sluit raam kamer Amilya - clear notification (Bart en Madouce)
  id: '641488e0-5315-4a14-98c1-91a58c2541f3'
  description: ''
  trigger:
  - platform: state
    entity_id: binary_sensor.kamer_amilya_raam
    from: 'on'
    to: 'off'
  - platform: state
    entity_id: binary_sensor.kamer_amilya_schuifraam
    from: 'on'
    to: 'off'
  - platform: state
    entity_id: input_boolean.kamer_amilya_window_pause
    from: 'off'
    to: 'on'    
  condition:
  - condition: state
    entity_id: input_boolean.kamer_amilya_raam_moet_dicht
    state: 'on'
  action:
  - service: notify.bart_phone
    data:
      message: "clear_notification"
      data:
        tag: window_kamer_amilya
  - service: notify.madouce_phone
    data:
      message: "clear_notification"
      data:
        tag: window_kamer_amilya
  mode: single

- alias: 🪟 ramen - sluit raam veranda - clear notification (Bart en Madouce)
  id: '2edf5074-c13e-41c1-be2e-056f14dc22bc' 
  description: ''
  trigger:
  - platform: state
    entity_id: binary_sensor.veranda_schuifraam
    from: 'on'
    to: 'off'
  - platform: state
    entity_id: input_boolean.veranda_window_pause
    from: 'off'
    to: 'on'
  condition:
  - condition: state
    entity_id: input_boolean.veranda_schuifraam_moet_dicht
    state: 'on'
  action:
  - service: notify.bart_phone
    data:
      message: "clear_notification"
      data:
        tag: window_veranda
  - service: notify.bart_phone
    data:
      message: "clear_notification"
      data:
        tag: window_berging        
  mode: single

- alias: 🪟 ramen - sluit raam berging - clear notification (Bart en Madouce)
  id: 'ac82b1aa-20a8-4b50-b528-d3565aaac616'
  description: ''
  trigger:
  - platform: state
    entity_id: binary_sensor.berging_raam
    from: 'on'
    to: 'off'
  - platform: state
    entity_id: input_boolean.berging_window_pause
    from: 'off'
    to: 'on'
  condition:
  - condition: state
    entity_id: input_boolean.berging_raam_moet_dicht
    state: 'on'
  action:
  - service: notify.bart_phone
    data:
      message: "clear_notification"
      data:
        tag: window_berging
  - service: notify.madouce_phone
    data:
      message: "clear_notification"
      data:
        tag: window_berging
  mode: single

- alias: 🪟 ramen - sluit raam badkamer - clear notification (Bart en Madouce)
  id: '8b2d90de-b450-4150-a9f3-0851eb39c3a6'
  description: ''
  trigger:
  - platform: state
    entity_id: binary_sensor.badkamer_raam_kantel
    from: 'on'
    to: 'off'
  - platform: state
    entity_id: input_boolean.badkamer_window_pause
    from: 'off'
    to: 'on'    
  condition:
  - condition: state
    entity_id: input_boolean.badkamer_raam_moet_dicht
    state: 'on'
  action:
  - service: notify.bart_phone
    data:
      message: "clear_notification"
      data:
        tag: window_badkamer
  - service: notify.madouce_phone
    data:
      message: "clear_notification"
      data:
        tag: window_badkamer
  mode: single

- alias: 🪟 ramen - sluit raam kamer Alunya - clear notification (Bart en Madouce)
  id: '301ebb17-90c6-4d29-a5f4-5a4a3e757bb8'
  description: ''
  trigger:
  - platform: state
    entity_id: binary_sensor.kamer_alunya_raam
    from: 'on'
    to: 'off'
  - platform: state
    entity_id: binary_sensor.kamer_alunya_schuifraam
    from: 'on'
    to: 'off'
  - platform: state
    entity_id: input_boolean.kamer_alunya_window_pause
    from: 'off'
    to: 'on'    
  condition:
  - condition: state
    entity_id: input_boolean.kamer_alunya_raam_moet_dicht
    state: 'on'
  action:
  - service: notify.bart_phone
    data:
      message: "clear_notification"
      data:
        tag: window_kamer_alunya
  - service: notify.madouce_phone
    data:
      message: "clear_notification"
      data:
        tag: window_kamer_alunya
  mode: single

- alias: 🪟 ramen - sluit raam master bedroom - clear notification (Bart en Madouce)
  id: 'ce55bb82-1faf-4867-84ee-e0bf45b5b4cc'
  description: ''
  trigger:
  - platform: state
    entity_id: binary_sensor.master_bedroom_raam_kantel
    to: 'off'
  - platform: state
    entity_id: input_boolean.master_bedroom_window_pause
    from: 'off'
    to: 'on'    
  condition:
  - condition: state
    entity_id: input_boolean.master_bedroom_raam_moet_dicht
    state: 'on'
  action:
  - service: notify.bart_phone
    data:
      message: "clear_notification"
      data:
        tag: window_master_bedroom
  - service: notify.madouce_phone
    data:
      message: "clear_notification"
      data:
        tag: window_master_bedroom
  mode: single