############################ Table of Contents ############################ 
#
#   Open windows notifications
#   🪟 ramen - open raam living (Bart en Madouce)
#   🪟 ramen - open raam kamer Amilya (Bart en Madouce)
#   🪟 ramen - open raam veranda (Bart en Madouce)
#   🪟 ramen - open raam berging (Bart en Madouce)
#   🪟 ramen - open raam badkamer (Bart en Madouce)
#   🪟 ramen - open raam kamer Alunya (Bart en Madouce)
#   🪟 ramen - open raam master bedroom (Bart en Madouce)
#
#   Open windows clear notifications
#   🪟 ramen - open raam living - clear notification (Bart en Madouce)
#   🪟 ramen - open raam kamer Amilya - clear notification (Bart en Madouce)
#   🪟 ramen - open raam veranda - clear notification (Bart en Madouce)
#   🪟 ramen - open raam berging - clear notification (Bart en Madouce)
#   🪟 ramen - open raam badkamer - clear notification (Bart en Madouce)
#   🪟 ramen - open raam kamer Alunya - clear notification (Bart en Madouce)
#   🪟 ramen - open raam master bedroom - clear notification (Bart en Madouce)
#
###########################################################################

automation:

############################################
# Open windows: notifications
############################################

- alias: 🪟 ramen - open raam living (Bart en Madouce)
  id: '095d6529-f4e6-44df-b25d-2548de7f5958'
  description: ''
  trigger:
  - platform: time_pattern
    minutes: /15
  condition:
  - condition: state
    entity_id: input_boolean.living_raam_moet_open
    state: 'on'
  - condition: state
    entity_id: binary_sensor.keuken_raam
    state: 'off'
  - condition: state
    entity_id: binary_sensor.living_oprit_raam
    state: 'off'
  - condition: state
    entity_id: binary_sensor.living_tuin_raam
    state: 'off'
  - condition: state
    entity_id: input_boolean.living_window_pause
    state: 'off'
  action:
  - service: script.notify_bart_windows
    data_template:
      title: '{{title}}'
      message: '{{message}}'
      tag: '{{tag}}'
      action_window_pause: '{{action_window_pause}}' 
      reason: '{{reason}}'
  - service: script.notify_madouce_windows
    data_template:  
      title: '{{title}}'
      message: '{{message}}'
      tag: '{{tag}}'
      action_window_pause: '{{action_window_pause}}' 
      reason: '{{reason}}'
  variables:
    message: "Vocht living: {{states('sensor.gram_water_living')}} g/m³. Buiten: {{states('sensor.gram_water_outside')}} g/m³.<br>Vocht living: {{states('sensor.living_humidity')}} %. Buiten: {{states('sensor.humidity_leuven24_wunderground')}} %.<br>Temp living: {{states('sensor.living_temperature')}} °C. Buiten: {{states('sensor.temp_leuven24_wunderground')}} °C."
    title: "Open het raam van de living/keuken!"
    tag: "window_living"
    action_window_pause: "living_window_pause"
    reason: "{% if (states('sensor.gram_water_living_diff_outside') | float) >= 0.5 %} Te vochtig binnen. {% endif %}"
  mode: single

- alias: 🪟 ramen - open raam kamer Amilya (Bart en Madouce)
  id: '5e940ddb-56ad-4f8a-b9c5-4fd24b0138c2'
  description: ''
  trigger:
  - platform: time_pattern
    minutes: /15
  condition:
  - condition: state
    entity_id: input_boolean.kamer_amilya_raam_moet_open
    state: 'on'
  - condition: state
    entity_id: binary_sensor.kamer_amilya_raam
    state: 'off'
  - condition: state
    entity_id: input_boolean.kamer_amilya_window_pause
    state: 'off'
  - condition: zone
    entity_id: person.bart
    zone: zone.home
  action:
  - service: script.notify_bart_windows
    data_template:
      title: '{{title}}'
      message: '{{message}}'
      tag: '{{tag}}'
      action_window_pause: '{{action_window_pause}}' 
      reason: '{{reason}}'
  - service: script.notify_madouce_windows
    data_template:  
      title: '{{title}}'
      message: '{{message}}'
      tag: '{{tag}}'
      action_window_pause: '{{action_window_pause}}' 
      reason: '{{reason}}'
  variables:
    message: "Vocht kamer Amilya: {{states('sensor.gram_water_kamer_amilya')}} g/m³. Buiten: {{states('sensor.gram_water_outside')}} g/m³.<br>Temp kamer Amilya: {{states('sensor.kamer_amilya_temperature')}} °C. Buiten: {{states('sensor.temp_leuven24_wunderground')}} °C."
    title: "Open het raam van Amilya!"
    tag: "window_kamer_amilya"
    action_window_pause: "kamer_amilya_window_pause"
    reason: "{% if (states('sensor.gram_water_kamer_amilya_diff_outside') | float) >= 0.5 %} Te vochtig binnen. {% endif %}"
  mode: single

- alias: 🪟 ramen - open raam veranda (Bart en Madouce)
  id: '16b26e4a-ba87-4a26-a72d-310f70e4e5b2'
  description: ''
  trigger:
  - platform: time_pattern
    minutes: /15
  condition:
  - condition: state
    entity_id: input_boolean.veranda_schuifraam_moet_open
    state: 'on'
  - condition: state
    entity_id: binary_sensor.veranda_schuifraam
    state: 'off'
  - condition: state
    entity_id: input_boolean.veranda_window_pause
    state: 'off'
  action:
  - service: script.notify_bart_windows
    data_template:
      title: '{{title}}'
      message: '{{message}}'
      tag: '{{tag}}'
      action_window_pause: '{{action_window_pause}}' 
      reason: '{{reason}}'
  - service: script.notify_madouce_windows
    data_template:  
      title: '{{title}}'
      message: '{{message}}'
      tag: '{{tag}}'
      action_window_pause: '{{action_window_pause}}' 
      reason: '{{reason}}'
  variables:
    message: "Vocht veranda {{states('sensor.gram_water_veranda')}} g/m³. Buiten: {{states('sensor.gram_water_outside')}} g/m³.<br>Temp veranda: {{states('sensor.veranda_temperature')}} °C. Buiten: {{states('sensor.temp_leuven24_wunderground')}} °C."
    title: "Open het raam van de veranda!"
    tag: "window_veranda"
    action_window_pause: "veranda_window_pause"
    reason: "{% if (states('sensor.gram_water_veranda_diff_outside') | float) >= 0.5 %} Te vochtig binnen. {% endif %}"
  mode: single

- alias: 🪟 ramen - open raam berging (Bart en Madouce)
  id: '58397619-e77f-44d8-9e1a-fb0a9e6eae22'
  description: ''
  trigger:
  - platform: time_pattern
    minutes: /15
  condition:
  - condition: state
    entity_id: input_boolean.berging_raam_moet_open
    state: 'on'
  - condition: state
    entity_id: binary_sensor.berging_raam
    state: 'off'
  - condition: state
    entity_id: input_boolean.berging_window_pause
    state: 'off'
  action:
  - service: script.notify_bart_windows
    data_template:
      title: '{{title}}'
      message: '{{message}}'
      tag: '{{tag}}'
      action_window_pause: '{{action_window_pause}}' 
      reason: '{{reason}}'
  - service: script.notify_madouce_windows
    data_template:  
      title: '{{title}}'
      message: '{{message}}'
      tag: '{{tag}}'
      action_window_pause: '{{action_window_pause}}' 
      reason: '{{reason}}'
  variables:
    message: "Vocht berging {{states('sensor.gram_water_berging')}} g/m³. Buiten: {{states('sensor.gram_water_outside')}} g/m³.<br>Temp berging: {{states('sensor.berging_temperature')}} °C. Buiten: {{states('sensor.temp_leuven24_wunderground')}} °C."
    title: "Open het raam van de berging!"
    tag: "window_berging"
    action_window_pause: "berging_window_pause"
    reason: "{% if (states('sensor.gram_water_berging_diff_outside') | float) >= 0.5 %} Te vochtig binnen. {% endif %}"
  mode: single

- alias: 🪟 ramen - open raam badkamer (Bart en Madouce)
  id: '4739d887-11b6-49c9-8086-6c4bd142b6b0'
  description: ''
  trigger:
  - platform: time_pattern
    minutes: /15
  condition:
  - condition: state
    entity_id: input_boolean.badkamer_raam_moet_open
    state: 'on'
  - condition: state
    entity_id: binary_sensor.badkamer_raam_kantel
    state: 'off'
  - condition: state
    entity_id: input_boolean.badkamer_window_pause
    state: 'off'
  action:
  - service: script.notify_bart_windows
    data_template:
      title: '{{title}}'
      message: '{{message}}'
      tag: '{{tag}}'
      action_window_pause: '{{action_window_pause}}' 
      reason: '{{reason}}'
  - service: script.notify_madouce_windows
    data_template:  
      title: '{{title}}'
      message: '{{message}}'
      tag: '{{tag}}'
      action_window_pause: '{{action_window_pause}}' 
      reason: '{{reason}}'
  variables:  
    message: "Vocht  badkamer: {{states('sensor.gram_water_badkamer')}} g/m³. Buiten: {{states('sensor.gram_water_outside')}} g/m³.<br>Vocht badkamer: {{states('sensor.badkamer_humidity')}} %. Buiten: {{states('sensor.humidity_leuven24_wunderground')}} %.<br>Temp badkamer: {{states('sensor.badkamer_temperature')}} °C. Buiten: {{states('sensor.temp_leuven24_wunderground')}} °C."
    title: "Open het raam van de badkamer!"
    tag: "window_badkamer"
    action_window_pause: "badkamer_window_pause"
    reason: "{% if (states('sensor.gram_water_badkamer_diff_outside') | float) >= 0.5 %} Te vochtig binnen. {{states('sensor.badkamer_humidity')}} % {% endif %}"
  mode: single

- alias: 🪟 ramen - open raam kamer Alunya (Bart en Madouce)
  id: '73c4f6ed-f3ff-4180-86b8-bebb95b89b6d'
  description: ''
  trigger:
  - platform: time_pattern
    minutes: /15
  condition:
  - condition: state
    entity_id: input_boolean.kamer_alunya_raam_moet_open
    state: 'on'
  - condition: state
    entity_id: binary_sensor.kamer_alunya_raam
    state: 'off'
  - condition: state
    entity_id: binary_sensor.kamer_alunya_schuifraam
    state: 'off'  
  - condition: state
    entity_id: input_boolean.kamer_alunya_window_pause
    state: 'off'
  action:
  - service: script.notify_bart_windows
    data_template:
      title: '{{title}}'
      message: '{{message}}'
      tag: '{{tag}}'
      action_window_pause: '{{action_window_pause}}' 
      reason: '{{reason}}'
  - service: script.notify_madouce_windows
    data_template:  
      title: '{{title}}'
      message: '{{message}}'
      tag: '{{tag}}'
      action_window_pause: '{{action_window_pause}}' 
      reason: '{{reason}}'
  variables:  
    message: "Vocht kamer Alunya: {{states('sensor.gram_water_kamer_alunya')}} g/m³. Buiten: {{states('sensor.gram_water_outside')}} g/m³.<br>Temp kamer Alunya: {{states('sensor.kamer_alunya_temperature')}} °C. Buiten: {{states('sensor.temp_leuven24_wunderground')}} °C."
    title: "Open het raam van Alunya!"
    tag: "window_kamer_alunya"
    action_window_pause: "kamer_alunya_window_pause"
    reason: "{% if (states('sensor.gram_water_kamer_alunya_diff_outside') | float) >= 0.5 %} Te vochtig binnen. {% endif %}"
  mode: single

- alias: 🪟 ramen - open raam master bedroom (Bart en Madouce)
  id: '64c1f037-4152-4380-b341-9aef8df8fcf0'
  description: ''
  trigger:
  - platform: time_pattern
    minutes: /15
  condition:
  - condition: state
    entity_id: input_boolean.master_bedroom_raam_moet_open
    state: 'on'
  - condition: state
    entity_id: binary_sensor.master_bedroom_raam_kantel
    state: 'off'
  - condition: state
    entity_id: input_boolean.master_bedroom_window_pause
    state: 'off'
  action:
  - service: script.notify_bart_windows
    data_template:
      title: '{{title}}'
      message: '{{message}}'
      tag: '{{tag}}'
      action_window_pause: '{{action_window_pause}}' 
      reason: '{{reason}}'
  - service: script.notify_madouce_windows
    data_template:  
      title: '{{title}}'
      message: '{{message}}'
      tag: '{{tag}}'
      action_window_pause: '{{action_window_pause}}' 
      reason: '{{reason}}'
  variables:
      message: "Vocht master bedroom: {{states('sensor.gram_water_master_bedroom')}} g/m³. Buiten: {{states('sensor.gram_water_outside')}} g/m³.<br>Vocht master bedroom: {{states('sensor.master_bedroom_humidity')}} %. Buiten: {{states('sensor.humidity_leuven24_wunderground')}} %.<br>Temp master bedroom: {{states('sensor.master_bedroom_temperature')}} °C. Buiten: {{states('sensor.temp_leuven24_wunderground')}} °C."
      title: "Open het raam van de master bedroom!"
      tag: "window_master_bedroom"
      action_window_pause: "master_bedroom_window_pause"
      reason: "{% if (states('sensor.gram_water_master_bedroom_diff_outside') | float) >= 0.5 %} Te vochtig binnen: {{states('sensor.master_bedroom_humidity')}} % {% endif %}"
  mode: single

- alias: 🪟 ramen - open raam badkamer (melding op speaker)
  id: '86ec8dc8-381e-460a-af44-3afe02f69147'
  description: ''
  trigger:
  - platform: state
    entity_id: input_boolean.badkamer_raam_moet_open
    to: 'on'
  condition:
  - condition: state
    entity_id: binary_sensor.badkamer_raam_kantel
    state: 'off'
  - condition: state
    entity_id: light.badkamer_douche
    state: 'on'
  action:
  - service: tts.cloud_say
    data:
      entity_id: media_player.badkamer_speaker
      message: "Het raam mag open. Er is {{states('sensor.badkamer_humidity')}}% vocht."
  mode: single


############################################
# Clear notifications when window is opened
############################################

- alias: 🪟 ramen - open raam living - clear notification (Bart en Madouce)
  id: 'cd3425f6-6c8b-4e1b-93dc-1721d6db07ee'
  description: ''
  trigger:
  - platform: state
    entity_id: binary_sensor.keuken_raam
    from: 'off'
    to: 'on'
  - platform: state
    entity_id: binary_sensor.living_oprit_raam
    from: 'off'
    to: 'on'
  - platform: state
    entity_id: binary_sensor.living_tuin_raam
    from: 'off'
    to: 'on'
  - platform: state
    entity_id: input_boolean.living_window_pause
    to: 'on'
  condition:
  - condition: state
    entity_id: input_boolean.living_raam_moet_open
    state: 'on'
  action:
  - service: notify.bart_phone
    data:
      message: "clear_notification"
      data:
        tag: window_living
  - service: notify.madouce_phone
    data:
      message: "clear_notification"
      data:
        tag: window_living
  mode: single

- alias: 🪟 ramen - open raam kamer Amilya - clear notification (Bart en Madouce)
  id: '4f5f9a4c-76b7-4336-af97-cc93eab67acd'
  description: ''
  trigger:
  - platform: state
    entity_id: binary_sensor.kamer_amilya_raam
    from: 'off'
    to: 'on'
  - platform: state
    entity_id: input_boolean.kamer_amilya_window_pause
    to: 'on'
  condition:
  - condition: state
    entity_id: input_boolean.kamer_amilya_raam_moet_open
    state: 'on'
  action:
  - service: notify.bart_phone
    data:
      message: "clear_notification"
      data:
        tag: window_kamer_amilya
  - service: notify.madouce_phone
    data:
      message: "clear_notification"
      data:
        tag: window_kamer_amilya
  mode: single

- alias: 🪟 ramen - open raam veranda - clear notification (Bart en Madouce)
  id: '09a07555-51ac-4ce2-b365-fbbd81b55298'
  description: ''
  trigger:
  - platform: state
    entity_id: binary_sensor.veranda_schuifraam
    from: 'off'
    to: 'on'
  - platform: state
    entity_id: input_boolean.veranda_window_pause
    to: 'on'
  condition:
  - condition: state
    entity_id: input_boolean.veranda_schuifraam_moet_open
    state: 'on'
  action:
  - service: notify.bart_phone
    data:
      message: "clear_notification"
      data:
        tag: window_veranda
  - service: notify.madouce_phone
    data:
      message: "clear_notification"
      data:
        tag: window_veranda
  mode: single

- alias: 🪟 ramen - open raam berging - clear notification (Bart en Madouce)
  id: '133107e0-eaad-4ddf-9645-df489dc212c7'
  description: ''
  trigger:
  - platform: state
    entity_id: binary_sensor.berging_raam
    from: 'off'
    to: 'on'
  - platform: state
    entity_id: input_boolean.berging_window_pause
    to: 'on'
  condition:
  - condition: state
    entity_id: input_boolean.berging_raam_moet_open
    state: 'on'
  action:
  - service: notify.bart_phone
    data:
      message: "clear_notification"
      data:
        tag: window_berging
  - service: notify.madouce_phone
    data:
      message: "clear_notification"
      data:
        tag: window_berging
  mode: single

- alias: 🪟 ramen - open raam badkamer - clear notification (Bart en Madouce)
  id: '27f63745-eb58-410d-b416-b7e6ccb7387c'
  description: ''
  trigger:
  - platform: state
    entity_id: binary_sensor.badkamer_raam_kantel
    from: 'off'
    to: 'on'
  - platform: state
    entity_id: input_boolean.badkamer_window_pause
    to: 'on'
  condition:
  - condition: state
    entity_id: input_boolean.badkamer_raam_moet_open
    state: 'on'
  action:
  - service: notify.bart_phone
    data:
      message: "clear_notification"
      data:
        tag: window_badkamer
  - service: notify.madouce_phone
    data:
      message: "clear_notification"
      data:
        tag: window_badkamer
  mode: single

- alias: 🪟 ramen - open raam kamer Alunya - clear notification (Bart en Madouce)
  id: 'bd75a6c7-039b-4e5d-8c84-12459bfab11a'
  description: ''
  trigger:
  - platform: state
    entity_id: binary_sensor.kamer_alunya_raam
    from: 'off'
    to: 'on'
  - platform: state
    entity_id: binary_sensor.kamer_alunya_schuifraam
    from: 'off'
    to: 'on'
  - platform: state
    entity_id: input_boolean.kamer_alunya_window_pause
    to: 'on'
  condition:
  - condition: state
    entity_id: input_boolean.kamer_alunya_raam_moet_open
    state: 'on'
  action:
  - service: notify.bart_phone
    data:
      message: "clear_notification"
      data:
        tag: window_kamer_alunya
  - service: notify.madouce_phone
    data:
      message: "clear_notification"
      data:
        tag: window_kamer_alunya
  mode: single

- alias: 🪟 ramen - open raam master bedroom - clear notification (Bart en Madouce)
  id: '55bd62eb-9d04-44a0-b008-6ccb53531c29'
  description: ''
  trigger:
  - platform: state
    entity_id: binary_sensor.master_bedroom_raam_kantel
    from: 'off'
    to: 'on'
  - platform: state
    entity_id: input_boolean.master_bedroom_window_pause
    to: 'on'
  condition:
  - condition: state
    entity_id: input_boolean.master_bedroom_raam_moet_open
    state: 'on'
  action:
  - service: notify.bart_phone
    data:
      message: "clear_notification"
      data:
        tag: window_master_bedroom
  - service: notify.madouce_phone
    data:
      message: "clear_notification"
      data:
        tag: window_master_bedroom
  mode: single